### ISSUE TITLE
invalid relocation for non-allocated sections: R_X86_64_GOTPC64

### ISSUE THREAD

**Issue by faern** [rui314/mold#1003]
I'm trying to switch over to `mold` for linking our Rust projects at https://github.com/mullvad/mullvadvpn-app/. But I get the following error when building Rust binaries that pull in our static library archive for `libnftnl`:

```
  = note: mold: fatal: /home/faern/src/mullvadvpn-app/dist-assets/binaries/x86_64-unknown-linux-gnu/libnftnl.a(utils.o):(.debug_info): invalid relocation for non-allocated sections: R_X86_64_GOTPC64
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can avoid the error and link fine if I rebuild `libnftnl.a` with either gcc or clang directly on my Fedora development machine (gcc 12.2.1 and clang 14.0.5) or with clang in our Debian 10 based build container (clang version 7.0.1-8+deb10u2). However, building `libnftnl.a` with gcc in the Debian 10 build container (gcc version 8.3.0)) is what triggers the error above.

Is the only recommended solution simply to use clang / upgrade the build environment, or is this issue fixable in `mold` in some way that allows us to continue building with gcc on Debian 10? I would prefer to not have to change compiler just for this, if possible.

[Here is the `Makefile` used for building `libnftnl`](https://github.com/mullvad/mullvadvpn-app-binaries/blob/29a4c7205e78c651fcd1b8c3a55181c0d86a50d3/Makefile#L168-L179). And [here is the container definition](https://github.com/mullvad/mullvadvpn-app-binaries/blob/29a4c7205e78c651fcd1b8c3a55181c0d86a50d3/Dockerfile).

Thank you for an amazingly fast linker <3

**Comment by rui314** [comment]
Thank you for your report! This should be fixed in mold. I'll make a change to support that relocation type.

**Comment by rui314** [comment]
On second thought, it is odd that a debug section contains a PC-relative relocation because the notion of PC-relative doesn't make sense for non-memory-mapped section. Can you upload your `/home/faern/src/mullvadvpn-app/dist-assets/binaries/x86_64-unknown-linux-gnu/libnftnl.a` so that I can take a look into it? It is likely a compiler bug that happens to work with GNU ld.

**Comment by faern** [comment]
Absolutely. The version checked in to our repository has this issue. It's very old and built in Debian 9, but gives the same error. It's available [here](https://github.com/mullvad/mullvadvpn-app-binaries/raw/main/x86_64-unknown-linux-gnu/libnftnl.a).

But I'll also upload a freshly built one that has the same issue but built on a newer build container (Debian 10). For comparison I'll also upload this one built in the same container from the exact same Makefile and source code, but with clang:

* [libnftnl.a-gcc-broken.zip](https://github.com/rui314/mold/files/10868330/libnftnl.a-gcc-broken.zip).  
* [libnftnl.a-clang-working.zip](https://github.com/rui314/mold/files/10868354/libnftnl.a-clang-working.zip)

**Comment by rui314** [comment]
Can you also run the final link command with `-Wl,--repro`? If that flag is given, mold creates a tar file containing all input files with which it is very easy to re-run the same command with the same output. Please share that file with me.

**Comment by faern** [comment]
Github will only allow me to upload 25 MiB files, and this repro tar achive is 1.3 GiB (~150MiB when compressed).... And I can't push it to a temporary git branch either because there files can only be 100 MiB... I'll sort this out somehow.

**Comment by faern** [comment]
Here we go! The extra layer of zip is just because that's the only format Github allowed :sweat_smile: 

[mullvad_daemon-96dd93fc4006358c.repro.tar.xz.zip](https://drive.google.com/file/d/1XgO9dD2OTzfRyZ7mY0VWcUd6d0QAr_X1/view?usp=share_link)

**Comment by rui314** [comment]
This is apparently a bug of an old version of GCC. According to its `.comment` section, `utils.o` was built by GCC 6.3.0. Are you sure you are using that old compiler? It was released in 2016.

**Comment by faern** [comment]
The build I uploaded the repro from is indeed very old. We have not had any reason to rebuild `libnftnl` for a couple of years since we have had no need to upgrade it. But if we were to rebuild it today we would use our Debian 10 build images (the oldest distro our software supports, so we want to link to the oldest supported glibc), and Debian 10 currently has gcc 8.3.0 and there I see the same error message.

I can create a new repro build with the 8.3.0 build if you think that makes a difference. But it would be awesome if mold would support the newest GCC supported by Debian 10 (it's still supported, albeit in LTS now)

**Comment by rui314** [comment]
Does the above change work for you?

**Comment by faern** [comment]
Interesting. This actually solves it for that specific version of `libnftnl.a`. However, when I re-build it with gcc 8.3.0 in Debian 10 I hit the same error again.. Was the fix too specific to 6.3.0?

Here is my repro for the failing build using `libnftnl.a` built by gcc 8.3.0 and with `mold` built from commit 77c479513939aa3638450cc512a1fb2e177b1559:

[mullvad_daemon-4eecad6dfc3f04fb.repro-gcc8.3.0.tar.xz](https://drive.google.com/file/d/1xOTJSzyY-lTvZWH_QR-erwUl4ugSxwqB/view?usp=share_link)


Thank you so much for paying attention to this gcc issue :)

**Comment by rui314** [comment]
Can you paste the new error message? It should be different from the previous one.

**Comment by faern** [comment]
```
  = note: mold: fatal: /home/faern/src/mullvadvpn-app/dist-assets/binaries/x86_64-unknown-linux-gnu/libnftnl.a(utils.o):(.debug_info): invalid relocation for non-allocated sections: R_X86_64_GOTOFF64
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rui314** [comment]
Should be fixed in the above change.

**Comment by faern** [comment]
This works! Thank you so much!
