### ISSUE TITLE
Is mold linker true drop in replacement for bsd ld ?

### ISSUE THREAD

**Issue by steviekm3** [rui314/mold#1005]
Hi there, I am looking to make effort to try mold out.  Currently though I’m on redhat 7 using gcc10 and binutils 2.36-EL7.

I managed to get gold linker to work with just minor change to add flag —disable-new-dtags 

tried to get lld 14 to work and got it to link but the binaries apps crashed.  

Should I just upgrade whole os to new distro or should I make attempt to get mold to work?  Basically am asking if there are any show stoppers with trying it out.  Normally I would just try it but am in closed network so I have to get sys admins to download it and any dependencies and do not want to ask them unless am pretty sure it will work.

many thanks

**Comment by rui314** [comment]
It depends, as there's no true drop-in replacement anywhere. That being said, as long as you are not building a program that needs linker script (which is rare unless you are doing kernel/embedded programming), mold should work just fine.
