### ISSUE TITLE
Linking error with relocation R_X86_64_TPOFF32 and R_386_TLS_LE

### ISSUE THREAD

**Issue by ms178** [rui314/mold#1007]
Trying to compile [libjpeg-turbo-git](https://github.com/ms178/archpkgbuilds/blob/main/packages/libjpeg-turbo-git/PKGBUILD) with flto and mold-git (ad26944) leads to a lot of the following linker errors:

```
mold: error: /tmp/lto-llvm-551a39.o:(.text.tjEncodeYUV3): relocation R_X86_64_TPOFF32 against `errStr` can not be used when making a shared object; recompile with -fPIC
mold: error: /tmp/lto-llvm-f09303.o:(.text.jsimd_idct_2x2): relocation R_386_TLS_LE against `simd_support` can not be used when making a shared object; recompile with -fPIC)
```

Compiling with -fPIC however succeeds. But it also used to work without explicitly adding -fPIC.

**Comment by rui314** [comment]
These error messages are real; these types of relocations cannot be used when creating a shared library. We recently added more rigorous error checks. Before that, mold silently created broken binaries.

When you create a shared library, you want to always compile object files with `-fPIC`.
