### ISSUE TITLE
Dwarf Error with gcc 4.8.5 (centos7)

### ISSUE THREAD

**Issue by feizhengfeng** [rui314/mold#1012]
I encountered the issue on cento7 with gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
Newer gcc works fine.

```
a.c:
#include <stdio.h>
int main() {
    return printf("hello\n");
}

b.c:
//empty

gcc -g -c a.c
gcc -g -c b.c
gcc a.o b.o -B<path to mold>
gdb ./a.out

Reading symbols from ./a.out...
Dwarf Error: DW_FORM_strp used without .debug_str section [in module a.out]
```

**Comment by feizhengfeng** [comment]
[mold_issue.tar.gz](https://github.com/rui314/mold/files/10950523/mold_issue.tar.gz)

**Comment by rui314** [comment]
Can you run the linker with `-Wl,--repro` (https://github.com/rui314/mold/blob/main/docs/mold.md#auto:~:text=as%2Dneeded.-,%2D%2Drepro,-%3A%20Archive%20input%20files) and share the generated tar file with me?

**Comment by feizhengfeng** [comment]
[a.out.repro.tar.gz](https://github.com/rui314/mold/files/10957412/a.out.repro.tar.gz)
