### ISSUE TITLE
mold produces a program with undefined behaviour

### ISSUE THREAD

**Issue by JohannesBeck** [rui314/mold#1014]
Compiling the following program results in undefined behaviour when using the mold linker combined with g++ (ubuntu 20.04: `g++-9 -B/usr/local/libexec/mold -fopenmp main.cpp`):
```
#include <mutex>
#include <set>

int main()
{
    std::set<int> global_set;
    std::mutex m;

#pragma omp parallel for
    for (int i = 0; i < 100000000; ++i)
    {
        std::lock_guard<std::mutex> l(m);

        std::set<int> local_set;
        local_set.insert(i);
        global_set = local_set;
    }
}
```
The expected result would be that it just works. The error I get are different, e.g.:
```
munmap_chunk(): invalid pointer
Segmentation fault (core dumped)
```

If clang is used as a compiler or ld as a linker, it works.

This zip archive contains a Dockerfile and the source code from above to reproduce:
[files.zip](https://github.com/rui314/mold/files/10960992/files.zip)

**Comment by rui314** [comment]
It looks like a name resolution issue of mold. I'll fix it.

**Comment by JohannesBeck** [comment]
Thanks a lot for fixing this so quickly.
