### ISSUE TITLE
Does not include linked library without -Wl, --no-as-needed

### ISSUE THREAD

**Issue by vchernin** [rui314/mold#1017]
When linking with [gsl](https://www.gnu.org/software/gsl/doc/html/intro.html), [gsl cblas](https://www.gnu.org/software/gsl/doc/html/cblas.html) is also necessary. However, mold does not include the `libgslcblas.so.0` shared library in the outputted elf file as expected, resulting in a failure when running the program. 

This can be workarounded by using `-Wl,--no-as-needed`, which isn't needed with the default gcc linker.

Using this file as `example.c`:
```c
#include <stdio.h>
#include <gsl/gsl_sf_bessel.h>

int
main (void)
{
  double x = 5.0;
  double y = gsl_sf_bessel_J0 (x);
  printf ("J0(%g) = %.18e\n", x, y);
  return 0;
}
```

```bash
# this doesn't work, results in ./example: symbol lookup error: /usr/lib/libgsl.so.27: undefined symbol: cblas_ctrmv
gcc example.c -fuse-ld=mold -Wl,--as-needed -lgsl -lgslcblas -o example
./example
# works, due to -Wl,--no-as-needed
gcc example.c -fuse-ld=mold -Wl,--no-as-needed -lgsl -lgslcblas -o example
./example
```
The above examples both work when not setting `-fuse-ld=mold`.

Tested with
arch linux
gcc `12.2.1`
mold `1.10.1`

**Comment by rui314** [comment]
Can you check out git head and try again to see if it is still a problem?

**Comment by vchernin** [comment]
Thanks, as of 325d12d1694f9b257d7225a5f0e3c17a23818367 I can't reproduce this, so closing.
