### ISSUE TITLE
Segfault while generating x86 shared library, while static linking libc++

### ISSUE THREAD

**Issue by hehaoqian** [rui314/mold#1019]
mold linker segmentation faults when linking x86 shared library,
while static linking libc++

Using LD in binutils 2.32, or llvm lld linker works fine

The linking command is similar to
```
clang++ -fPIC -stdlib=libc++ -fuse-ld=mold -static-libstdc++ -Xlinker --exclude-libs -Xlinker ALL -shared  -o test.so    -Wl,--whole-archive  AAA.a  -Wl,--no-whole-archive  BBB.a
```

The bug can be workaround by linking libc++ first
```
clang++ -fPIC -stdlib=libc++ -fuse-ld=mold -Bstatic -lc++ -lc++abi -Bdynamic -static-libstdc++ -Xlinker --exclude-libs -Xlinker ALL -shared  -o test.so    -Wl,--whole-archive  AAA.a  -Wl,--no-whole-archive  BBB.a
```

Version:
mold: 1.10.1
clang & libc++ : 12.0.0

Below are the reproducible tar bar generated by `-Wl,--repro`

[test.so.repro1.zip](https://github.com/rui314/mold/files/11007356/test.so.repro1.zip)
[test.so.repro2.zip](https://github.com/rui314/mold/files/11007357/test.so.repro2.zip)

The tar bar after xz compressed is 31MB,
the maximum single file allowed to be uploaded by Github is 25MB,
so I have split the tar bar into 2 files, 
and rename the file suffix to workaround Github file suffix restriction

You can get the original tar bar by
```
cat test.so.repro1.zip test.so.repro2.zip > test.so.repro.tar.xz
tar -xvf test.so.repro.tar.xz
```

**Comment by rui314** [comment]
Your program contains an ODR violation.

Both `llvm-project/llvm/tools/hbdk/hbtl/3rdparty/oneDNN/src/common/CMakeFiles/dnnl_common.dir/verbose.cpp.o` and `swwork/hbcc/commontools/clang-llvm/clang-llvm-12.0.0/lib/libc++.a(ios.instantiations.cpp.o)` contains a definition of `vtable for std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >` (in the mangled form, `_ZTVNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE`), but their definitions are different.

The definition in `ios.instantiations.cpp.o` has more symbols than that in `verbose.cpp.o`. mold picks up the definition in `verbose.cpp.o`. References to the extra symbols in `ios.instantiation.cpp.o` causes this error.

I'll fix the segmentation fault issue and turn it into an error message.

You want to recompile `ios.instantiations.cpp.o` with a compiler that is ABI-compatible with your compiler.

**Comment by hehaoqian** [comment]
That would be strange, since libc++.a is bootstrapped with the same compiler (clang12),
I'll upgrade the compiler to clang 15.0.7 and try again.
Not sure why ld and LLD works fine, may be because they do not check ODR?

**Comment by rui314** [comment]
I don't exactly know why other linkers don't report errors, but I guess if they pick up the definition in `ios.instantiations.cpp.o`, they would fail to find an error. But that's not a good thing; it's more like a situation in which compiler doesn't report an error to a syntactically wrong code.

It looks like your `verbose.cpp.o` is compiled with an older version of GCC. You can verify that by extracting the `.o` file from `.a` using `ar` and then print out its `.comment` section with `readelf -p .comment verbose.cpp.o`. Maybe that version of GCC is not compatible with Clang 15.

**Comment by hehaoqian** [comment]
Thanks. It looks that libc++.a is not correctly bootstrapped, 
which is compiled by gcc 7.4.0, instead of clang 12.0.0.
I think a correctly configured clang installation should fix the problem.
Note that I compiled clang myself.
