### ISSUE TITLE
Can't build frawk

### ISSUE THREAD

**Issue by roland-5** [rui314/mold#1021]
I wanted to update [frawk](https://crates.io/crates/frawk) crate via `cargo +nightly install frawk` from `frawk 0.4.7` to `frawk 0.4.8` but compilation fails with [this error](https://gist.github.com/roland-5/624c88ee4dc0d3808ec4cdd39b9298e7).

Readelf for 0.4.7 version:
```
readelf -p .comment ~/.cargo/bin/frawk
String dump of section '.comment':
  [     0]  GCC: (GNU) 12.2.0
  [    12]  clang version 15.0.0
  [    27]  mold 1.10.1 (040180f933d33fa246f9d2961c2d6e8b74241463; compatible with GNU ld)
  [    77]  GCC: (GNU) 12.2.1 20230201
```

cat ~/.cargo/config.toml
```
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=mold"]

[profile.release]
lto = "thin"

[registries.crates-io]
protocol = "sparse"
```

clang -v
```
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/12.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

mold -V
```
mold 1.10.1 (040180f933d33fa246f9d2961c2d6e8b74241463; compatible with GNU ld)
  Supported emulations:
   elf_x86_64
   elf_i386
   aarch64linux
   armelf_linux_eabi
   elf64lriscv
   elf64briscv
   elf32lriscv
   elf32briscv
   elf32ppc
   elf64ppc
   elf64lppc
   elf64_s390
   elf64_sparc
   m68kelf
   shlelf_linux
   elf64alpha
```

Distribution - Arch Linux

**Comment by rui314** [comment]
mold 1.11.0 is the latest version. Can you try again with the latest version?

**Comment by ishitatsuyuki** [comment]
Installs fine here with the config you provided — `mold 1.11.0 (36fc0655489eb96e1be15b03b3f5e227cd97a22e; compatible with GNU ld)`, Ubuntu 22.04 with LLVM 14.

Maybe check:
- If it compiles without mold
- Whether you have multiple installation of LLVM in your system (and the build script might be confusing the link paths)

**Comment by roland-5** [comment]
Damn, it's not `mold` but llvm/clang problem. I'm sorry about this.
