### ISSUE TITLE
[RFC] Automatically load lto plugin if required

### ISSUE THREAD

**Issue by Keruspe** [rui314/mold#1022]
Background story: I recently switched my system linker from lld to mold. Most of the things are going smoothly (apart from glibc configure script but that's for another day). I build everything with clang and ThinLTO enabled (apart from a couple of cherry-picked stuff that are known to fail with lto and/or clang).

While most of the things on my system build fine with mold, there's a recurring pattern in the failing ones. Some build system somehow don't pass the CFLAGS and/or LDFLAGS correctly (I guess) to specific commands and `-flto=thin` gets missing in some linker invocations (from what I understood). Here is a sample output of this failure while building e.g. sqlite:

```
mold: fatal: .libs/sqlite3.o: don't know how to handle this LTO object file because no -plugin option was given. Please make sure you added -flto not only for creating object files but also for creating the final executable.
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

The proper fix will be to fix all affected packages as much as possible in the end, this issue is just here to discuss the drawbacks that would come with automatic loading of the plugin

While the proper fix in the end is definitely to fix these as much as possible

**Comment by Keruspe** [comment]
Right, since mold isn't called directly but through cc, it's cc's job to do that, makes sense thanks!

**Comment by rui314** [comment]
If you file a feature request to gcc, please copy-n-paste a link here for tracking.
