### ISSUE TITLE
libstdc++ not found when compiling Rust

### ISSUE THREAD

**Issue by michaelsproul** [rui314/mold#1025]
Recently my `mold` & Rust setup stopped being able to link binaries and started producing this error:

> note: mold: fatal: library not found: stdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm not sure whether this error started occurring after a mold update, a Rust update, or something else.

I've managed to get `mold` working again by changing my Cargo config to use GCC rather than Clang:

```toml
[build]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```

This was the only configuration that I could get to work. I've created a repo with the 3 other variations of configuration that I tried which _do not_ work here: https://github.com/michaelsproul/mold-stdcpp.

This could be a Rust bug, as I update Rust much more frequently than I update mold, although older Rust versions (1.65.0) do not seem to resolve the issue. I guess it could also be a change to how `clang` works on my system, as I found that `clang` without `mold` also fails unless prompted with the path to `libstdc++.so.6` via `-L /lib/x86_64-linux-gnu/`.

### Software Versions

```
$ mold --version
mold 1.11.0 (cca255e6be069cdbc135c83fd16036d86b98b85e; compatible with GNU ld)
```

```
$ rustc --version --verbose
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

```
$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by rui314** [comment]
Let's see if this is clang's problem or not. If you use LLVM lld instead (by passing `link-arg=-fuse-ld=lld`) along with clang, does it wokr?

**Comment by michaelsproul** [comment]
Still fails with `lld`, so I guess it's a Clang/Rust issue

**Comment by rui314** [comment]
Yup, I guess so. You may want to report it to Clang. Since this is not specific to mold, I'll close this bug.

**Comment by ethercflow** [comment]
Hi @michaelsproul , I met this issue too,  do you have a solution now?

**Comment by michaelsproul** [comment]
@ethercflow The workaround is in my OP (use GCC)

**Comment by ethercflow** [comment]
> @ethercflow The workaround is in my OP (use GCC)

@michaelsproul Get it, thanks! :)
