### ISSUE TITLE
Mold generates corrupted executable with no-pie option

### ISSUE THREAD

**Issue by sillycross** [rui314/mold#1028]
I have been using `mold` for my project and it has been working great!
However, I ran into a weird issue today, and eventually I tracked down the bug to be a `mold` bug, which I report here.

Minimal repro:
```c++
#include <bits/stdc++.h>
#include <dlfcn.h>
int main()
{
    printf("0x%llx\n", (unsigned long long)memcpy);
    void* res = dlsym(RTLD_DEFAULT, "memcpy");  // crash if the program is compiled using mold as linker
    printf("dlsym: 0x%llx\n", (unsigned long long)res);
    return 0;
}
```
The program clearly has no undefined behavior. However, when compiled with `clang` using `mold` as linker:
```bash
clang++ zz3.cpp -fno-pie -no-pie -ldl
./a.out
```
I get a crash:
```
0x2017b0
Segmentation fault (core dumped)
```
When compiled with `clang` using default `ld` linker, the program runs without problem:
```
0x401040
dlsym: 0x401040
```

It seems like the executable generated by mold has a corrupted symbol table, which causes `dlsym` to crash.

(By the way, if you remove the first `printf` in the code, the executable also runs fine, further confirming that this is a `mold` bug.)

I am using latest mold:
```bash
mold -v
mold 1.11.0 (cca255e6be069cdbc135c83fd16036d86b98b85e; compatible with GNU ld)
```

Is there any chance this bug could be fixed? 
Thanks!

**Comment by ishitatsuyuki** [comment]
Taking a look.

**Comment by rui314** [comment]
Actually I'm working on it now. It looks like it's a bug related to GNU IFUNC.

**Comment by ishitatsuyuki** [comment]
Yeah, definitely IFUNC related. I'll leave it to you then, as I'm not super familiar with IFUNCs.

**Comment by sillycross** [comment]
Thanks for the quick fix! Is there any chance you could publish a new release so I could use it? 
Thanks again!

**Comment by rui314** [comment]
This change is probably too small to make another release solely for this, so please apply your local patch until we make a new release.
