### ISSUE TITLE
riscv64 - many test failed

### ISSUE THREAD

**Issue by sajcho** [rui314/mold#1035]
Hi.
Machine: cat /sys/firmware/devicetree/base/model
StarFive VisionFive V2
gcc 13.0.1
binutils 2.40
glibc 2.37
gcc -dumpmachine -> riscv64-unknown-linux-gnu

Compile mold use:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSATALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=c++ .. -> OK
[buildlog.txt](https://github.com/rui314/mold/files/11301408/buildlog.txt)

$ ./mold --version
mold 1.11.0 (dce8ebe5265b615f35999272d3dc666b1c246ff4; compatible with GNU ld)

$ readelf -p .comment mold

String dump of section '.comment':
  [     0]  GCC: (SAUX-RISCV64) 13.0.1 20230409 (experimental)

$ ldd mold
	linux-vdso.so.1 (0x0000003f9e1b3000)
	libz.so.1 => /lib/libz.so.1 (0x0000003f9e18f000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x0000003f9e0d3000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x0000003f9dd94000)
	libatomic.so.1 => /usr/lib/libatomic.so.1 (0x0000003f9dd8c000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000003f9db7e000)
	libm.so.6 => /lib/libm.so.6 (0x0000003f9db05000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000003f9dae8000)
	libc.so.6 => /lib/libc.so.6 (0x0000003f9d988000)
	/lib/ld-linux-riscv64-lp64d.so.1 (0x0000003f9e1b4000)

ctest -> many test failed
[LastTest.log.txt](https://github.com/rui314/mold/files/11301419/LastTest.log.txt)
[LastTestsDisabled.log.txt](https://github.com/rui314/mold/files/11301420/LastTestsDisabled.log.txt)
[LastTestsFailed.log.txt](https://github.com/rui314/mold/files/11301421/LastTestsFailed.log.txt)

Same configuration on x86_64, arm64 - mold works fine

**Comment by rui314** [comment]
`mold` failed to find `libc.so` probably because the path to the directory containing `libc.so` was not passed as an argument for `-l`. It's `cc`'s job to pass the required path to `ld`. Your `cc` may not have been configured properly.

**Comment by sajcho** [comment]
Interesting that other apps work fine.
I will look for a solution. Thank you for the explanation.
I'm closing it for now.
