### ISSUE TITLE
mold links more libraries than necessary with `--as-needed`

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1036]
Consider following chain of dependencies (`libbar`<-`libfoo`<-`libtest`):

`libbar` is standalone and has no dependencies:
```sh
$ gcc -fuse-ld=mold -o libbar.so -shared -x c - <<EOF                           
void bar() { }                    
EOF
```

`libfoo` needs `libbar`:
```sh
$ gcc -fuse-ld=mold -o libfoo.so -shared -x c - -Wl,--as-needed -L. -lbar <<EOF 
void bar();void foo() { bar(); } 
EOF
$ readelf -a libfoo.so|grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libbar.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]
```

`libtest` needs `libfoo` but has no direct dependency on `libbar`:
```sh
$ gcc -fuse-ld=mold -o libtest.so -shared -x c - -Wl,--as-needed -L. -lfoo -lbar <<EOF         
void foo();void test() { foo(); }
EOF
```

Result for `mold 1.11.0`:
```sh
$ readelf -a libtest.so|grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libfoo.so]
 0x0000000000000001 (NEEDED)             Shared library: [libbar.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]
```

Result for both `bfd` and `lld`:
```
$ readelf -a libtest.so|grep NEEDED                                                  
 0x0000000000000001 (NEEDED)             Shared library: [libfoo.so]
```

Since `libtest` does not have dependencies on `libbar` and `libfoo` requires `libbar` already I consider `bfd` and `lld` output to be correct.

**Comment by rui314** [comment]
Right, mold behaves exactly as you explained in this bug. It's not exactly the same as GNU ld, but in practice it didn't seem to cause any practical issues, so I settled with it. Is it causing an issue on your side?

**Comment by jpalus** [comment]
Consider ABI change in `libbar.so` and subsequent `SONAME` change to reflect that. Now not only `libfoo.so` needs to be rebuilt against new `libbar.so` but also `libtest.so`. My primary use of `mold` is for packages building at linux distribution and that makes it enough of a reason to stop using it. Comparing to `bfd` and `lld` it results in many more packages needing rebuild when `SONAME` changes, users need to download more packages on upgrade and it's much harder to keep certain version of a program relying only on ABI stable libraries since some other libraries creep in during linking. In some way that makes `mold` slower than `bfd` and `lld`.

`mold` is of course free to choose semantics for its `--as-needed` flag so feel free to close it as not an issue. However if `--as-needed` filters only libraries that are not used by anything, so appear on command line somewhat by accident, then I'd say it's usefulness is very limited.

**Comment by firasuke** [comment]
I was going to open a new issue with regards to a similar behavior when using `mold` as it adds `libgcc_s.so.1` as a needed library to almost all executables when in fact they are not needed (example software [attr](https://savannah.nongnu.org/projects/attr)).

**Comment by rui314** [comment]
Yeah, sorry for the trouble. Let me take a look. It's a bit risky to change this fundamental behavior at this point, but it's indeed an unnecessary churn compared to GNU ld.

**Comment by justanotheranonymoususer** [comment]
I have the same problem, which makes Mold not practical in many cases as @jpalus explained, please consider fixing it
