### ISSUE TITLE
Cannot configure cargo to use mold as linker

### ISSUE THREAD

**Issue by FilipAndersson245** [rui314/mold#1037]
I am trying to configure the rust config.toml to use mold as the default linker, but I face some errors that I think is wierd.

this is my `config.toml`
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=/home/odin/.linker/mold/bin/mold"]
```

using the latest mold release this is the output

<details><summary>Details</summary>
<p>

error: could not compile `serde_derive` (build script) due to previous error
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/odin/.cargo/bin:/home/odin/.pyenv/plugins/pyenv-virtualenv/shims:/home/odin/.pyenv/shims:/home/odin/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/lib/mpv.install/tools:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Users/odin/.cargo/bin:/mnt/c/Users/odin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/odin/AppData/Roaming/npm:/mnt/c/Users/odin/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/odin/AppData/Local/Programs/oh-my-posh/bin:/mnt/c/Users/odin/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe:/mnt/c/Users/odin/.dotnet/tools:/snap/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcaYSesO/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcaYSesO/symbols.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.0.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.1.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.10.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.11.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.12.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.13.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.14.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.15.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.2.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.3.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.4.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.5.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.6.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.7.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.8.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.9.rcgu.o" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.1b4o2llml6q3bvys.rcgu.rmeta" "/tmp/cargo-installlCjVVt/release/deps/time_macros-20a77f2a1a8242ba.3ojbr7tkzk5d4y7m.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installlCjVVt/release/deps" "-L" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installlCjVVt/release/deps/libtime_core-668f8003283b9341.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-17c4e69028abe652.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-efba0938fd8201db.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5a365829e69d2a98.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-fd705a60736c3357.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-c0ff7ddb2987d8da.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-c459f8b0a64f04e1.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c2d64f918d4b26ad.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d22c51811a78dc80.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-bf5c8066ec73f833.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-c6524d8077d4ee9d.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-45ff23c614a38f1d.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-6b9410c3805b4c08.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6deb8c633abe47e3.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-63b99e7722b1dcf3.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0b7d1529f62927c0.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8307745cd9fd5b28.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c2c050aec00eb6da.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-35b8a4bd2de4e62e.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installlCjVVt/release/deps/libtime_macros-20a77f2a1a8242ba.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs" "-fuse-ld=/home/odin/.linker/mold/bin/mold"
  = note: cc: error: unrecognized command-line option '-fuse-ld=/home/odin/.linker/mold/bin/mold'

</p>
</details> 

I tested to install clang-15 but then i get this error instead if I specify it as this

```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang-15"
rustflags = ["-C", "link-arg=-fuse-ld=/home/odin/.linker/mold/bin/mold"]
```

i get this error
<details><summary>Details</summary>
<p>

error: could not compile `typenum` (build script) due to previous error
error: linking with `clang-15` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/odin/.cargo/bin:/home/odin/.pyenv/plugins/pyenv-virtualenv/shims:/home/odin/.pyenv/shims:/home/odin/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/lib/mpv.install/tools:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Users/odin/.cargo/bin:/mnt/c/Users/odin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/odin/AppData/Roaming/npm:/mnt/c/Users/odin/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/odin/AppData/Local/Programs/oh-my-posh/bin:/mnt/c/Users/odin/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe:/mnt/c/Users/odin/.dotnet/tools:/snap/bin" VSLANG="1033" "clang-15" "-Wl,--version-script=/tmp/rustcV6pXZn/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcV6pXZn/symbols.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.0.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.1.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.10.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.11.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.12.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.13.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.14.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.15.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.2.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.3.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.4.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.5.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.6.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.7.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.8.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.time_macros.198bef6de87c94e2-cgu.9.rcgu.o" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.1b4o2llml6q3bvys.rcgu.rmeta" "/tmp/cargo-installoREbgp/release/deps/time_macros-20a77f2a1a8242ba.3ojbr7tkzk5d4y7m.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installoREbgp/release/deps" "-L" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installoREbgp/release/deps/libtime_core-668f8003283b9341.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-17c4e69028abe652.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-efba0938fd8201db.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5a365829e69d2a98.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-fd705a60736c3357.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-c0ff7ddb2987d8da.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-c459f8b0a64f04e1.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c2d64f918d4b26ad.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d22c51811a78dc80.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-bf5c8066ec73f833.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-c6524d8077d4ee9d.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-45ff23c614a38f1d.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-6b9410c3805b4c08.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6deb8c633abe47e3.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-63b99e7722b1dcf3.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0b7d1529f62927c0.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8307745cd9fd5b28.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c2c050aec00eb6da.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-35b8a4bd2de4e62e.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/odin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installoREbgp/release/deps/libtime_macros-20a77f2a1a8242ba.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs" "-fuse-ld=/home/odin/.linker/mold/bin/mold"
  = note: clang: error: unable to execute command: posix_spawn failed: Exec format error
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

</p>
</details> 

anyone that can point me to what im doing wrong? or if there is a problem with mold?

**Comment by Paulo-21** [comment]
First of all can you test with a stable version of rust if it's work ?

For the first try, when you compile it with cc, i know that gcc have to be recent enought to support some command options to use mold, which version of gcc did you use ?

**Comment by rui314** [comment]
What is the output of `ls -l /home/odin/.linker/mold/bin/mold`?

**Comment by FilipAndersson245** [comment]
> ls -l /home/odin/.linker/mold/bin/mold

-rwxr-xr-x 1 odin odin 22394984 Mar 16 07:15 /home/odin/.linker/mold/bin/mold


> First of all can you test with a stable version of rust if it's work ?
> 
> For the first try, when you compile it with cc, i know that gcc have to be recent enought to support some command options to use mold, which version of gcc did you use ?

`gcc --version` gives me this `gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`

**Comment by ishitatsuyuki** [comment]
A few compilers have deprecated the use of `-fuse-ld=absolute-path`. You should use `--ld-path=absolute-path` instead.

**Comment by FilipAndersson245** [comment]
> A few compilers have deprecated the use of `-fuse-ld=absolute-path`. You should use `--ld-path=absolute-path` instead.

changing the `config.toml` to this
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "-ld-path=/home/odin/.linker/mold/bin/mold"]
```
produces this error
<details><summary>Details</summary>
<p>

error: failed to compile `starship v1.14.2`, intermediate artifacts can be found at `/tmp/cargo-installxeJIBs`

Caused by:
  failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C -ld-path=/home/odin/.linker/mold/bin/mold --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: unknown codegen option: `-ld-path`

</p>
</details>

**Comment by ishitatsuyuki** [comment]
You didn't pass `link-arg=` though?

**Comment by FilipAndersson245** [comment]
> You didn't pass `link-arg=` though?

like this?
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-ld-path=/home/odin/.linker/mold/bin/mold"]
```
<details><summary>Details</summary>
<p>
 then i get this error
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/odin/.cargo/bin:/home/odin/.pyenv/plugins/pyenv-virtualenv/shims:/home/odin/.pyenv/shims:/home/odin/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/snap/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcNlI8gj/list" "-m64" "/tmp/rustcNlI8gj/symbols.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.0.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.1.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.10.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.11.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.12.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.13.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.14.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.15.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.2.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.3.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.4.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.5.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.6.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.7.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.8.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.time_macros.a575c406-cgu.9.rcgu.o" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.3dfzs4rzo29c6pie.rcgu.rmeta" "/tmp/cargo-installjX0FsG/release/deps/time_macros-a3b1019170681d76.hdei81xvkrx4etr.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installjX0FsG/release/deps" "-L" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installjX0FsG/release/deps/libtime_core-1eb7ef5697eb1322.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-3627dfecd49b0535.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-89bc084783fdc439.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8bee4b287d4367c1.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-d61707aed80694c0.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-d85366256f22345b.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-96069b86b8a8cae9.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-d19d53abf68dfa6c.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-787cbccd19d64ac6.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-b3837a36b830e0d0.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-e3deb0e7e3f04966.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-dabbb79c9815def4.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-305b01f34c9409f2.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-f833521df6074e73.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-9ac333113350d171.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-1c126114322d0eee.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-bad9164fdeeecf92.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-f9374b1e480fa681.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-207f06e41d9603af.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-7e2768e66e984e85.rlib" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-957b4aff41f8cd46.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/odin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installjX0FsG/release/deps/libtime_macros-a3b1019170681d76.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs" "-ld-path=/home/odin/.linker/mold/bin/mold"
  = note: /usr/bin/ld: cannot find -ld-path=/home/odin/.linker/mold/bin/mold: No such file or directory
          collect2: error: ld returned 1 exit status
</p>
</details>

**Comment by FilipAndersson245** [comment]
I realised i had the wrong linux version of mold, not the x86_64 version, i will retry to see if the config listed here will fix it then.

**Comment by cdown** [comment]
For what it's worth, just specifying `mold` works for me with GCC 13.1.1, which makes sense since this specifies the linker family rather than a path, as I understand it.

```
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```

**Comment by ishitatsuyuki** [comment]
> But this still requires me to install clang-15 in addition to mold and the rust toolchain, as not specifying clang-15 breaks the compilation.

This is more or less working as intended. Rust links LLVM bitcode for ThinLTO, and for that you either need to use LLD (built-in LLVM IR support) or clang with LLVM LTO gold plugin. Even the latter is kind of a hack since Rust ships its own copy of LLVM and version mismatch can cause incompatibility.
