### ISSUE TITLE
mold: fatal: unknown command line option: -EB collect2: error: ld returned 1 exit status Finished

### ISSUE THREAD

**Issue by alphaonex86** [rui314/mold#1046]
Hi,
On MIPS big endiant, softfloat float Gentoo Linux I have this bug:
mold: fatal: unknown command line option: -EB
collect2: error: ld returned 1 exit status
Finished

**Comment by rui314** [comment]
MIPS is not supported. I wanted to support that target, but the MIPS processor-specific ABI is too different from other psABIs and therefore hard to support. So it is unlikely that mold will support it.

**Comment by rui314** [comment]
I closed the issue since MIPS is not supported.
