### ISSUE TITLE
tbb doesn't build under cmake < 3.14

### ISSUE THREAD

**Issue by mqudsi** [rui314/mold#105]
Trying to build mold with CMake versions less than 3.14 gives the error below. I believe [the fix described here](https://github.com/oneapi-src/oneTBB/issues/297#issuecomment-878408577) should work.

CMake 3.10 is the latest available for Ubuntu 18.04 LTS. I know you target Ubuntu 20.04 - you don't necessarily need to do anything about this, but I figured at least having this documented as a closed issue would help anyone running into it in the future. Install Kitware's cmake ppa and upgrading to CMake 3.21 fixed it for me.

```
mkdir -p out/tbb
(cd out/tbb; cmake -DBUILD_SHARED_LIBS=OFF -DTBB_TEST=OFF -DCMAKE_CXX_FLAGS=-D__TBB_DYNAMIC_LOAD_ENABLED=0 ../../tbb)
CMake Warning at CMakeLists.txt:109 (message):
  You are building oneTBB as a static library.  This is highly discouraged
  and such configuration is not supported.  Consider building a dynamic
  library to avoid unforeseen issues.


-- Checking for one of the modules 'hwloc'
CMake Error at cmake/utils.cmake:39 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "tbb".
Call Stack (most recent call first):
  src/tbb/CMakeLists.txt:114 (tbb_install_target)


CMake Error at cmake/utils.cmake:39 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "tbbmalloc".
Call Stack (most recent call first):
  src/tbbmalloc/CMakeLists.txt:94 (tbb_install_target)


CMake Error at cmake/utils.cmake:39 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "tbbmalloc_proxy".
Call Stack (most recent call first):
  src/tbbmalloc_proxy/CMakeLists.txt:85 (tbb_install_target)


-- HWLOC target HWLOC::hwloc_1_11 doesn't exist. The tbbbind target cannot be created
-- HWLOC target HWLOC::hwloc_2 doesn't exist. The tbbbind_2_0 target cannot be created
-- HWLOC target HWLOC::hwloc_2_4 doesn't exist. The tbbbind_2_4 target cannot be created
-- Configuring incomplete, errors occurred!
See also "/home/mqudsi/mold/out/tbb/CMakeFiles/CMakeOutput.log".
See also "/home/mqudsi/mold/out/tbb/CMakeFiles/CMakeError.log".
Makefile:81: recipe for target 'out/tbb/libs/libtbb.a' failed
make: *** [out/tbb/libs/libtbb.a] Error 1
```

**Comment by rui314** [comment]
Thank you for the report. I think we should at least print out a friendly error message than this one.

BTW, is there a C++ compiler/C++ standard library that supports C++20 available for Ubuntu 18.04? I guess the answer is yes, because otherwise you wouldn't be able to build mold on Ubuntu 18.04, but I wonder how you install it.

**Comment by mqudsi** [comment]
I'm assuming that you have tbb upstreamed as-is (i.e. no different than if it were a submodule, except easier to use)? Since you don't (yet) use CMake the only alternative to patching tbb's CMake files would be, e.g., to add a `.begin` section to the `Makefile` to validate the CMake version.

---

Regarding the C++ compiler - it's actually really easy to get gcc/g++ 10 or 11 on Ubuntu 18.04 as Canonical backports the toolchains so it's as easy as adding (this ppa)[https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test] then `apt install g++-11`. You can do the same with clang 12/13/14 by adding [the llvm ppa](https://apt.llvm.org/) instead. They're proper backports, so you don't have to mess with libc version conflicts like you would if you tried to install out of `debian-unstable` or whatever.

**Comment by rui314** [comment]
I applied a few local patches to tbb already, so it is fine to apply another one. I'll fix it by tweaking the cmakefile of tbb.
