### ISSUE TITLE
Incorrect `symtab` entry

### ISSUE THREAD

**Issue by mkornaukhov03** [rui314/mold#1061]
**How to reproduce:**
I had gcc 8.3.0, but I suppose that it's reproducible on newer versions of it;
mold 1.11.0 (d4d93d7fb), but I suppose that it's reproducible on newer versions of it.
Let's generate an `.o` file with a lot of sections. For example, 
```python
def generate_file(file_id):
    ITER_CNT = 1000
    s = "#include <iostream>\n"
    
    for iter_id in range(0, ITER_CNT):
        s += 'int uninit_{}_{};\n'.format(file_id, iter_id)
        s += 'int zeroed_{}_{} = 0;\n'.format(file_id, iter_id)
        s += 'int init_{}_{} = {};\n'.format(file_id, iter_id, iter_id + file_id)
        s += 'static int static_{}_{} = {};\n'.format(file_id, iter_id, iter_id + file_id)
        s += 'int foo_{}_{}(){{ std::cout << {}; return {}; }}\n'.format(file_id, iter_id, iter_id + file_id, iter_id + file_id);
    return s;

if __name__ == "__main__":
    FILE_CNT = 50
    for file_id in range(0, FILE_CNT):
        with open('cpp/file{}.cpp'.format(file_id), 'w') as f:
            f.write(generate_file(file_id))
```
Then, let's compile each `.cpp` file with generating an extra section per data/function definition(`/home/mkornaukhov/mold` contains symlink `ld -> /usr/bin/mold`):
```bash
#!/bin/bash

for file in *.cpp; do
  g++ "$file" -B/home/mkornaukhov/mold  -ffunction-sections -fdata-sections -c -o "$file".o &
done
```
And then, let's collect all `.o` files in single `.o` file:
```bash
g++ -B/home/mkornaukhov/mold file*.o -r -nostdlib -ffunction-sections -fdata-sections -o total.o
```
After that, let's try to compile an executable:
```bash
g++ -B/home/mkornaukhov/mold total.o -o total.out
```
**There's error:**
```
mold: fatal: total.o: common local symbol?
collect2: error: ld returned 1 exit status

```
Meanwhile `ld` and `lld` handle it and fail when they cannot find `main` function.

**I did some research:**
Let's look at symbol table:
```
$ readelf -s total.o | grep " COM"
 65522: 0000000000000000     0 SECTION LOCAL  DEFAULT  COM 
131058: 0000000000000000     0 SECTION LOCAL  DEFAULT  COM 
196594: 0000000000000000     0 SECTION LOCAL  DEFAULT  COM 
262130: 0000000000000000     0 SECTION LOCAL  DEFAULT  COM

```
Mold creates entries of type `SECTION` with `LOCAL` binding and `st_shndx` equal to 65522 (= 0xfff2 = `COM`).
It's interesting that each entry of this pattern is equal to 0xfff2(=65522) modulo 0x10000(=65536).

Let's look at section header table:
```
$ readelf -S total.o | head -n1
There are 300118 section headers, starting at offset 0x1af5548
$ readelf -S total.o | grep "\[65522\]"
  [65522] .data._ZL13static PROGBITS         0000000000000000  002ed964
```
I found out that in case of sections number is greater (or equal) than 65522 (reserved index for `SHN_COMMON`) mold creates incorrect entries in symbol table, mentioned above.

**Comment by irdkwmnsb** [comment]
It looks like because there are just too many section header tables that the index to the entry in the section header is so big it overlaps with the reserved header indices when writing the section table. As per [linux elf format manpages](https://man7.org/linux/man-pages/man5/elf.5.html#:~:text=A%20section%20header%20table%20index%20is%20a%20subscript%20into%20this%20array.%0A%20%20%20%20%20%20%20Some%20section%20header%20table%20indices%20are%20reserved%3A%20the%20initial%20entry%0A%20%20%20%20%20%20%20and%20the%20indices%20between%20SHN_LORESERVE%20and%20SHN_HIRESERVE)
Maybe mold can add a check to not put symbols at those indices?

**Comment by rui314** [comment]
Thank you for your report. I will fix the issue.
