### ISSUE TITLE
Question about windows

### ISSUE THREAD

**Issue by Milo123459** [rui314/mold#1069]
In the new release, it was said that the attempt to monetise mold didn't work, and thus, sold should stop. Does this mean #190 can be reopened?

**Comment by rui314** [comment]
First of all, we won't sunset the sold linker. Speaking of Windows support, I suspect Microsoft is already working on their own version of faster linker, and if that's the case, no third-party linker can compete with it. Linux has mold/lld, macOS now has ld-prime (Apple's new faster default linker). It is hard to imagine that Microsoft is not doing anything against them. So I don't want to risk wasting my time to work on a non-competitive product.

**Comment by subsoap** [comment]
Have you tried applying for more grants?

**Comment by RivenSkaye** [comment]
Not sure if I should be asking here or if it's better to respond to an existing (or open a new) issue on the sold repo, but might I ask to reconsider the stance on linking PE executables? Besides some lesser-known OSes, m/sold support for PE binaries would also be amazing for cross toolchains and MingW-W64 environments (MSYS2, Cygwin) where MSVC is not an option and MS isn't likely to deliver any alternatives

**Comment by rui314** [comment]
I don't have a plan to work on a PE linker for the reason I described above. If you want a PE linker that works for cross toolchains, you may want to try LLVM lld, which I originally wrote before.
