### ISSUE TITLE
Segfault on aarch64 when running an application with main() in shared library

### ISSUE THREAD

**Issue by dmellosanjay** [rui314/mold#1074]
My unit tests linked with Catch and GoogleTest are failing to run on `aarch64` but work fine on `x86_64`. This seems identical to this [issue](https://sourceware.org/bugzilla/show_bug.cgi?id=23870) reported in `gold`.

### Minimal code example (same as in the linked ticket):

```
$ cat main.c 
#include <stdio.h>
extern int foo(int, int);

int main()
{
  printf("%d\n", foo(1, 3));
  return 0;
}
```

```
$ cat foo.c 
int __attribute__ ((noinline)) foo(int x, int y)
{
  return x & y;
}
```

Compile main into a shared object first, before creating the executables with `lld` and `mold`.
```
clang-14 -o main.o -c main.c
clang-14 -shared -o libmain.so main.o
clang-14 -o foo.o -c foo.c
clang-14 -shared -o libmain.so main.o
clang-14 -fuse-ld=mold -o mold_test.out -lmain -L$PWD -Wl,-v,-rpath=$PWD foo.o
clang-14 -fuse-ld=lld -o lld_test.out -lmain -L$PWD -Wl,-v,-rpath=$PWD foo.o
```

Result of running the `mold` linked executable:
```
 ./mold_test.out 
Segmentation fault (core dumped)
```

Result of running the `lld` linked executable:
```
./lld_test.out 
1
```

### Setup
```
# mold --version
mold 2.0.0 (de991b519a4b2ec90121323dab84b221080a6220; compatible with GNU ld)

# clang --version
clang version 14.0.6


```

**Comment by rui314** [comment]
I couldn't reproduce the issue in my Ubuntu 22.04 ARM64 docker container.

Can you re-run the last link command with `-Wl,--repro`? I.e.

```
clang-14 -fuse-ld=mold -o mold_test.out -lmain -L$PWD -Wl,-v,-rpath=$PWD foo.o -Wl,--repro
```

And then upload the generated `mold_test.out.repro.tar`.

**Comment by dmellosanjay** [comment]
Had to zip the tar file to upload. 

[mold_test.out.repro.tgz](https://github.com/rui314/mold/files/12224738/mold_test.out.repro.tgz)


Forgot to mention I'm testing on a Ubuntu 18.04 arm64 container. Thanks for looking into this!

**Comment by rui314** [comment]
Let me know if the above fix will work for you.

**Comment by dmellosanjay** [comment]
Works! 🙏
