### ISSUE TITLE
Undefined reference to symbol in the COMMON section

### ISSUE THREAD

**Issue by carlosgalvezp** [rui314/mold#1075]
Hi,

We are trying to switch to mold (2.0.0 release) from LLD, but we are getting a linker error. We are using the libxml2 library, which defines a global variable `xmlLastError` ([source](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/globals.c#L365)). The linker error looks as follows:

```
mold: error: undefined symbol: xmlLastError
>>> referenced by globals.c
>>>               path/to/libxml2/globals.pic.o:(__xmlLastError)
collect2: error: ld returned 1 exit status
```

Inspecting `globals.pic.o`, I can see that the symbol exists in the COMMON section, not the BSS section:
```
$ nm path/to/libxml2/globals.pic.o | grep LastError
000000000000059b T __xmlLastError
0000000000000058 C xmlLastError
```

Do you have any idea why this could be happening? Thanks!

**Comment by carlosgalvezp** [comment]
Update: the problem is solved by passing `-fno-common` to our compiler (GCC 9). More modern compilers have that option as default. I suppose it doesn't make sense for a "modern" linker like mold to support this "legacy" use case, feel free to close the ticket if you don't think it's worth spending time on it :)

**Comment by rui314** [comment]
This is a difficult case. Currently, mold does not pull out an object file from an archive file for a common symbol. We used to pull out object files for common symbols, but that caused a link failure for some programs, so the current behavior was chosen. I don't think we can make it work for all programs, so I don't think we can change the behavior.
