### ISSUE TITLE
powerpc64le-execute-only fails likely since 2.1.0 release

### ISSUE THREAD

**Issue by marxin** [rui314/mold#1087]
Since the release I see the following happening on `ppc64le-linux-gnu` machine:

```
[  651s]  58/281 Test  #63: powerpc64le-execute-only ...................***Failed    0.17 sec
[  651s] ++ dirname /home/abuild/rpmbuild/BUILD/mold-2.1.0/test/elf/execute-only.sh
[  651s] + . /home/abuild/rpmbuild/BUILD/mold-2.1.0/test/elf/common.inc
[  651s] ++ export LC_ALL=C
[  651s] ++ LC_ALL=C
[  651s] ++++ uname -m
[  651s] +++ canonical_name ppc64le
[  651s] +++ case $1 in
[  651s] +++ echo ppc64le
[  651s] ++ HOST=ppc64le
[  651s] ++ '[' '' = '' ']'
[  651s] ++ MACHINE=ppc64le
[  651s] ++ TESTDIR=out/test/elf/ppc64le
[  651s] ++ CC=cc
[  651s] ++ CXX=c++
[  651s] ++ GCC=gcc
[  651s] ++ GXX=g++
[  651s] ++ OBJDUMP=objdump
[  651s] ++ OBJCOPY=objcopy
[  651s] ++ STRIP=strip
[  651s] ++ QEMU=
[  651s] ++ trap 'on_error $LINENO' ERR
[  651s] ++ trap on_exit EXIT
[  651s] +++ basename /home/abuild/rpmbuild/BUILD/mold-2.1.0/test/elf/execute-only.sh .sh
[  651s] ++ testname=execute-only
[  651s] ++ echo -n 'Testing execute-only ... '
[  651s] Testing execute-only ... ++ t=out/test/elf/ppc64le/execute-only
[  651s] ++ mkdir -p out/test/elf/ppc64le/execute-only
[  651s] + '[' ppc64le = sparc64 ']'
[  651s] + '[' ppc64le = ppc64 ']'
[  651s] + cat
[  651s] + cc -o out/test/elf/ppc64le/execute-only/a.o -c -xc -
[  651s] + cc -B. -o out/test/elf/ppc64le/execute-only/exe out/test/elf/ppc64le/execute-only/a.o -Wl,--execute-only
[  651s] + out/test/elf/ppc64le/execute-only/exe
[  651s] + grep -q 'Hello world'
[  651s] ++ on_error 18
[  651s] ++ code=1
[  651s] ++ echo 'command failed: 18: grep -q '\''Hello world'\'''
[  651s] command failed: 18: grep -q 'Hello world'
```

**Comment by rui314** [comment]
It passes on my Qemu environment. Can you upload your `out/test/elf/ppc64le/execute-only/exe`?

**Comment by marxin** [comment]
Sure: 
[ppc64-execute-only.gz](https://github.com/rui314/mold/files/12368944/ppc64-execute-only.gz)

**Comment by marxin** [comment]
Rui, can you please analyze the binary? Does it help the provided binary?

**Comment by sicherha** [comment]
This issue is also reproducible on Fedora: https://download.copr.fedorainfracloud.org/results/sicherha/mold/fedora-rawhide-ppc64le/06316963-mold/builder-live.log.gz

**Comment by rui314** [comment]
@marxin That test passes on Ubuntu 22.04 on Qemu as well as on gcc120.fsffrance.org. So I suspect that it fails only on specific OSes or CPU. What are your hardware?

**Comment by marxin** [comment]
Dunno as I've left SUSE company. However, I bet it's somehow related to Linux version, where in my case,  a pretty new kernel is used (`Linux version 6.4.11-1-default`). Btw. how can I test running `ppc64le` tests in qemu on `x86_64`? I can try that on my recent Linux kernel x86_64 machine.

**Comment by sicherha** [comment]
Interestingly, the issue doesn't seem to be 100 % reproducible. Compare two Copr builds of the exact same mold version:
* Friday: https://copr.fedorainfracloud.org/coprs/sicherha/mold/build/6316963/ - test fails for some ppc64le builds
* Today: https://copr.fedorainfracloud.org/coprs/sicherha/mold/build/6321422/ - test fails for all ppc64le builds

**Comment by marxin** [comment]
My `gdb` session tells:
```
[ 1191s] + gdb -batch -x /tmp/x build/out/test/elf/ppc64le/execute-only/exe
[ 1191s] [Thread debugging using libthread_db enabled]
[ 1191s] Using host libthread_db library "/lib64/libthread_db.so.1".
[ 1191s] 
[ 1191s] Program received signal SIGSEGV, Segmentation fault.
[ 1191s] 0x0000000100010580 in __glink_PLTresolve ()
[ 1191s] #0  0x0000000100010580 in __glink_PLTresolve ()
[ 1191s] #1  0x0000000000000000 in ?? ()
```

**Comment by rui314** [comment]
@marxin Thank you for the trace! Now it is clear what is wrong. We read data in .plt in the PLT header. I'll replace that code.

**Comment by sicherha** [comment]
Confirmed fixed in Fedora. Thanks!
