### ISSUE TITLE
Drop OpenSSL dependency in favor of another smaller hashing library (for example blake3) ?

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [rui314/mold#1088]
Hi,

I was wondering, would it make sense to drop the mandatory openssl dependency in favor of a library specialized in hashing and easier to embed as a third party dependency ? Typically I know ccache uses the blake3 library for all computation of digests (which apparently you use for two things: build id computation and identical code folding). For both these use cases, I doubt you actually care about the actual hash algorithm, just about the fact that the result is rather "unique" for a given output. And it seems you care about having vectorized implementation for different architectures so it's fast, and ideally parallelizable. https://github.com/BLAKE3-team/BLAKE3 matches these requirements and is a smaller dependency than OpenSSL's libcrypto, plus it comes with CMake integration so you could ship it as part of your sources.

So would it make sense to use Blake3 in mold instead of OpenSSL's librcrypto ?

Cheers,
Romain

**Comment by Alcaro** [comment]
BLAKE3 was tried a while ago. https://github.com/rui314/mold/issues/246#issuecomment-1010996838

But it may be worthwhile to redo that comparison, it could've improved since then.

**Comment by rui314** [comment]
It may actually be worth trying blake3 given the following hash speed difference. Let me try that.

```
ruiu@blue:~/mold/build$ ls -lh mold
-rwxrwxr-x 1 ruiu ruiu 465M Aug 16 10:27 mold

ruiu@blue:~/mold/build$ time sha256sum mold
9a100d617607d744881530c97ebb93cd53950650450c4494e5c585c4a30fec70  mold

real    0m1.607s
user    0m1.542s
sys     0m0.064s

ruiu@blue:~/mold/build$ time b3sum --num-threads 1 mold
d6948d1945f3236f41f23d25941fe7ffa697320f03a9f01142b43b60e1f288b6  mold

real    0m0.189s
user    0m0.137s
sys     0m0.052s
```

**Comment by rui314** [comment]
BLAKE3 is indeed a bit faster than SHA256, so let's switch to that hash function.
