### ISSUE TITLE
`CREATE_LINK` in `file` is not in CMake 3.13

### ISSUE THREAD

**Issue by david-perez** [rui314/mold#1091]
`CMakeLists.txt` contains:

https://github.com/rui314/mold/blob/83fe073e970ea32a91f7b940cfd74b4f0a91c40e/CMakeLists.txt#L467-L467

`CREATE_LINK` was [added to `file` in CMake 3.14](https://cmake.org/cmake/help/latest/command/file.html#create-link). However, `mold` only requires CMake 3.13:

https://github.com/rui314/mold/blob/83fe073e970ea32a91f7b940cfd74b4f0a91c40e/CMakeLists.txt#L46-L46

Can something else be used instead of `CREATE_LINK`? I have CMake 3.13 in my system, and everything works fine except for this small thing:

```
[100%] Built target mold
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib64/mold/mold-wrapper.so
-- Installing: /usr/local/bin/mold
-- Installing: /usr/local/share/man/man1/mold.1
-- Installing: /usr/local/share/doc/mold/LICENSE
-- Installing symlink: /usr/local/libexec/mold/ld -> ../../bin/mold
CMake Error at cmake_install.cmake:92 (file):
  file does not recognize sub-command CREATE_LINK
```

**Comment by rui314** [comment]
I think we should just bump the required CMake version to 3.14. Did you install cmake by hand? If not, what is your distro?

**Comment by david-perez** [comment]
This is on [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/), installed via `sudo yum install cmake3`. Latest version in the Amazon Linux 2 repositories is 3.13.1.

**Comment by rui314** [comment]
It is unfortunate to hear that cmake on Amazon Linux 2 is a bit too old, but I think it is best to bump the required cmake version. Users can always install a pre-built binary if they can't built mold on their local machines.
