### ISSUE TITLE
Benign warning spam? symbol type mismatch STT_OBJECT / STT_FUNC

### ISSUE THREAD

**Issue by milianw** [rui314/mold#1093]
Hey there,

many thanks for mold, much appreciated! In a project that I'm working on we leverage [libvolk](https://github.com/zeux/volk) for vulkan, but mold keeps triggering these warnings which seem to be benign (at least, I cannot spot any apparent issues):

```
mold: warning: symbol type mismatch: vkCmdExecuteCommands
>>> defined in lib/libvolk.a(volk.c.o) as STT_OBJECT
>>> defined in /lib/libvulkan.so as STT_FUNC
```

This repeats for all other symbols in vok/libvulkan. Is this a real bug in libvolk, or could this warning be silenced as it's benign?

**Comment by rui314** [comment]
That warning seems real. I think you have a non-function definition (i.e. a global variable) of `vkCmdExecuteCommands` in your program which conflicts with the one in `libvulkan.so`. If someone tries to call `vkCmdExecuteCommands`, your program will very likely to just crash. Even if you do not explicitly call that function from your program, if `libvulkan.so` indirectly calls that function within the library, your "object" will be called instead as a function.

Where did you define that symbol in your program?

**Comment by milianw** [comment]
the warnings come from external libs that are not under my control, i.e.:

https://github.com/zeux/volk/blob/master/volk.h#L962C1-L962C54

anyhow, thanks for your input - if you are saying this is wrong on the ELF lib level, then I'll take it up with the volk authors.

Cheers, keep up the great work

**Comment by milianw** [comment]
ah, it seems that this is an issue in the volk cmake setup, which was fixed recently: https://github.com/zeux/volk/issues/134

sorry for the noise
