### ISSUE TITLE
mold rebuilds from scratch if cmake is executed again

### ISSUE THREAD

**Issue by dmikushin** [rui314/mold#1094]
As of `v2.1.0`, I've noticed if I run CMake again after successful build of mold, mold is getting rebuilt from scratch without a reason. According to the `ninja -d explain`, this behavior is caused by regeneration of *.cc files in the elf/ directory. Those files are configure-time generated, and are re-generated unconditionally upon the CMake execution. Therefore, their timestamp is renewed, and existing object files are considered dirty. I haven't looked into the details, but this should be a misuse of CMake. In CMake, the generated files should be created conditionally, only if their dependencies have changed.

**Comment by rui314** [comment]
Thanks! Fixed in the above commit.
