### ISSUE TITLE
Partial linking generate object file with empty SHT_GROUP section

### ISSUE THREAD

**Issue by hehaoqian** [rui314/mold#1096]
Version: mold 2.1.0

---

Issues:
1. It seems `--repro` does nothing  (no output reproducible tar), if used with partial linking (`-r` option), 
so I create `repro.tar.gz` by hand. 
`tar -xvf` then `make` to reproduce.

2. `mold`  generates some empty `SHT_GROUP` section in `output.o`, when partial linking (`-r` option)

```
mold -o output.o -r --whole-archive libstdc++.a Context.cpp.o --no-whole-archive --repro
```

The linking is okay.

Then I call
```
objcopy --localize-hidden output.o
```

It gives the following error:
`objcopy: output.o: SHT_GROUP section [index 23216] has no SHF_GROUP sections`

objcopy version: binutils 2.32

lld (llvm 15.0.7) do not have such problem

---

[repro.tar.gz](https://github.com/rui314/mold/files/12476123/repro.tar.gz)
sha256sum: 4bf77b841cedbfaadd3c58d92d6fa082fd45aa244acfb71e0b992760eddcc9c2

**Comment by rui314** [comment]
Can you try again with the above commit?
