### ISSUE TITLE
riscv64-riscv64_attributes (Failed)

### ISSUE THREAD

**Issue by andreas-schwab** [rui314/mold#1097]
1/289 Test   #1: riscv64-riscv64_attributes .............***Failed    0.48 sec
++ dirname /home/abuild/rpmbuild/BUILD/mold-2.1.0.69.g7f8872b/test/elf/riscv64_attributes.sh
+ . /home/abuild/rpmbuild/BUILD/mold-2.1.0.69.g7f8872b/test/elf/common.inc
++ export LC_ALL=C
++ LC_ALL=C
++++ uname -m
+++ canonical_name riscv64
+++ case $1 in
+++ echo riscv64
++ HOST=riscv64
++ '[' '' = '' ']'
++ MACHINE=riscv64
++ TESTDIR=out/test/elf/riscv64
++ CC=cc
++ CXX=c++
++ GCC=gcc
++ GXX=g++
++ OBJDUMP=objdump
++ OBJCOPY=objcopy
++ STRIP=strip
++ QEMU=
++ trap 'on_error $LINENO' ERR
++ trap on_exit EXIT
+++ basename /home/abuild/rpmbuild/BUILD/mold-2.1.0.69.g7f8872b/test/elf/riscv64_attributes.sh .sh
++ testname=riscv64_attributes
++ echo -n 'Testing riscv64_attributes ... '
Testing riscv64_attributes ... ++ t=out/test/elf/riscv64/riscv64_attributes
++ mkdir -p out/test/elf/riscv64/riscv64_attributes
+ cc -march=rv64imafd_xfoo1p5 -o out/test/elf/riscv64/riscv64_attributes/a.o -c -xc -
+ cat
cc: error: '-march=rv64imafd_xfoo1p5': extension 'xfoo' starts with 'x' but is unsupported non-standard extension
++ on_error 4
++ code=1
++ echo 'command failed: 4: $CC -march=rv64imafd_xfoo1p5 -o $t/a.o -c -xc -'
command failed: 4: $CC -march=rv64imafd_xfoo1p5 -o $t/a.o -c -xc -
++ trap - EXIT
++ exit 1

**Comment by andreas-schwab** [comment]
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=c283c4774d1

**Comment by rui314** [comment]
Ah, thanks! I'll fix it shortly.
