### ISSUE TITLE
Differing behaviour using version script from gold/ld  

### ISSUE THREAD

**Issue by eds-collabora** [rui314/mold#1098]
If our version script looks something like:

```
{
   local:
      extern "C++" {
        foo*;
     };
};
```

then the symbols matching `foo*` will be flagged as global not local.  Neither `ld` nor `gold` behave this way.

There is a workaround, in that mold **will** accept the following:

```
{
   local:
      extern "C++" {
           local:
               foo*;
      };
};
```

This restores the `local` target scope inside the `extern` block. However, both `ld` and `gold` reject this as invalid syntax, which means it cannot be used for those linkers

The actual root problem in the code seems to be in `read_version_script_commands()` in `elf/linker-script.cc`. It parses labels and stores the target scope (`local`, `global`) in the `is_global` variable. However, when it enters an `extern` block, it recurses and the value of `is_global` is not available in the recursion (`is_global` becomes `true` again at the top of the function).

I could submit a patch if that's helpful.

**Comment by rui314** [comment]
Thank you for your report! It should be fixed in the above commit.
