### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by xyproto** [rui314/mold#11]
Please consider adding a git tag per release (and also adding a license).

It makes `mold` easier to package for Linux distros, Homebrew and other systems.

Thanks!

**Comment by tesuji** [comment]
Per https://github.com/rui314/mold/issues/8#issuecomment-778651932, the author said it is too early to create a package.
Especially when there are no license/copyright for this repo.

**Comment by xyproto** [comment]
That is true. Release tags would still be nice, though.

**Comment by rui314** [comment]
I added a license file and tagged as v0.1.
