### ISSUE TITLE
Mold generates larger debug infos than lld

### ISSUE THREAD

**Issue by moncefmechri** [rui314/mold#1100]
While comparing mold 2.1.0 to lld 14, I noticed that the debug infos produced by mold are significantly larger than what lld produces.

The application under test is a large, statically-linked C++20 Linux x86_64 binary, built in release mode on Ubuntu 20.04 using GCC 12.

The debug sections are compressed by passing `-gz` to the compiler.

Here are the results. Notice in particular that the `.gdb_index` generated by mold is over **100x** larger than the one produced by `lld`

lld:

```
SECTION          SIZE (b)
---------------  ---------
.debug_info      514714231 (63.07%)
.debug_abbrev      3840000 (0.47%)
.debug_loclists   74777630 (9.16%)
.debug_aranges      626108 (0.08%)
.debug_rnglists   13484946 (1.65%)
.debug_line       30180711 (3.70%)
.debug_str        86775023 (10.63%)
.debug_line_str      59922 (0.01%)
.gdb_index         2145784 (0.26%)

 Total Size: 726604355  (89.03%)
 Total File Size: 816139152
```

mold:

```
SECTION          SIZE (b)
---------------  ---------
.gdb_index       280081460 (25.15%)
.debug_abbrev      3842598 (0.35%)
.debug_aranges      626800 (0.06%)
.debug_info      513466412 (46.11%)
.debug_line       30232554 (2.71%)
.debug_line_str      59056 (0.01%)
.debug_loclists   74780671 (6.71%)
.debug_rnglists   13486318 (1.21%)
.debug_str       104153467 (9.35%)

 Total Size: 1020729336  (91.66%)
 Total File Size: 1113657664
```

After decompressing the debug sections with `objcopy --decompress-debug-sections MyBinary`, I get:

lld:

```
SECTION          SIZE (b)
---------------  ----------
.debug_info      1081745293 (52.25%)
.debug_abbrev      11197596 (0.54%)
.debug_loclists   264351592 (12.77%)
.debug_aranges      3011696 (0.15%)
.debug_rnglists    42006176 (2.03%)
.debug_line       116304261 (5.62%)
.debug_str        460377259 (22.24%)
.debug_line_str      260600 (0.01%)
.gdb_index          2145784 (0.10%)

 Total Size: 1981400257  (95.71%)
 Total File Size: 2070220800
```

mold:

```
.gdb_index        280081460 (11.92%)
.debug_abbrev      11197596 (0.48%)
.debug_aranges      3011696 (0.13%)
.debug_info      1081745293 (46.02%)
.debug_line       116304261 (4.95%)
.debug_line_str      260603 (0.01%)
.debug_loclists   264351592 (11.25%)
.debug_rnglists    42006176 (1.79%)
.debug_str        460377259 (19.59%)

 Total Size: 2259335936  (96.12%)
 Total File Size: 2350458384
```

**Comment by moncefmechri** [comment]
Digging a bit more into this, it looks like the `.gdb_index` generated by `mold` contains far more address entries in the address area than what's generated by lld:

lld:

`Address area offset = 0x5548, has 105788 entries`

mold:

`Address area offset = 0x5548, has 14002975 entries`


By diff-ing the `gdb_index` generated by lld and mold, I noticed **a lot** of empty address entries in the `.gdb_index` generated by the latter. For example:

```
    Low/High address = [0x1208a90, 0x1208a90) (Size: 0x0), CU id = 35
    Low/High address = [0x1208a90, 0x1208a90) (Size: 0x0), CU id = 35
    Low/High address = [0x1208a90, 0x1208a90) (Size: 0x0), CU id = 35
    Low/High address = [0x1208a90, 0x1208a90) (Size: 0x0), CU id = 35
```

There are a total of 14002969 such empty entries, which almost perfectly accounts for the difference in number of entries between mold and lld.

**Comment by moncefmechri** [comment]
I also noticed that the binary generated by mold takes significantly longer to be loaded by GDB. The following results were collected by running `time gdb -ex "quit" ./MyBinary`, using GDB 11.2

lld:

```
real    0m5.136s
user    0m6.978s
sys     0m0.516s
```

mold:

```
real    0m12.683s
user    0m14.157s
sys     0m1.163s
```

I would not be surprised if the slow down is caused by the issue reported here.

**Comment by ishitatsuyuki** [comment]
It looks like these are padding entries inserted by us due to the overconservative size estimate:
https://github.com/rui314/mold/blob/22443b149076111b662bb8a7e658af475d7a28a3/elf/dwarf.cc#L261C1-L279
I'll check why are we overestimating and see if it can be fixed without regressing performance.

**Comment by moncefmechri** [comment]
> It looks like these are padding entries inserted by us due to the overconservative size estimate: https://github.com/rui314/mold/blob/22443b149076111b662bb8a7e658af475d7a28a3/elf/dwarf.cc#L261C1-L279 I'll check why are we overestimating and see if it can be fixed without regressing performance.

Awesome! Please let me know if you would like me to try a patch.

**Comment by rui314** [comment]
a396fa400fb8aa5ecc766d83bb8ab0a646e295dd should fix the issue. Can you test it?
