### ISSUE TITLE
-Wl,--defsym=__ImageBase=0x0 either not working as expected or producing bad results

### ISSUE THREAD

**Issue by medhefgo** [rui314/mold#1106]
```
extern char __ImageBase[];
int main(void) {
        __builtin_printf("ImageBase: %p\n", &__ImageBase);
}
```

With `-static-pie` or `-pie`:
```
$ gcc -o test test.c -static-pie -Wl,--defsym=__ImageBase=0x0 -fuse-ld=bfd && ./test
ImageBase: 0x7f5c2ce27000
$ gcc -o test test.c -static-pie -Wl,--defsym=__ImageBase=0x0 -fuse-ld=lld && ./test
ImageBase: 0x7fd1ae701000
$ gcc -o test test.c -pie -Wl,--defsym=__ImageBase=0x0 -fuse-ld=gold && ./test
ImageBase: 0x555a619a2000
$ gcc -o test test.c -static-pie -Wl,--defsym=__ImageBase=0x0 -fuse-ld=mold && ./test
mold: error: /tmp/cc6mkihJ.o:(.text): R_X86_64_PC32 relocation at offset 0x7 against symbol `__ImageBase' can not be used; recompile with -fno-PIC
collect2: error: ld returned 1 exit status
```

With `-fPIC`:
```
$ gcc -o test test.c -fPIC -Wl,--defsym=__ImageBase=0x0 -fuse-ld=bfd && ./test
ImageBase: 0x55f5eeb5e000
$ gcc -o test test.c -fPIC -Wl,--defsym=__ImageBase=0x0 -fuse-ld=gold && ./test
ImageBase: 0x55b1687af000
$ gcc -o test test.c -fPIC -Wl,--defsym=__ImageBase=0x0 -fuse-ld=lld && ./test
ImageBase: (nil)
$ gcc -o test test.c -fPIC -Wl,--defsym=__ImageBase=0x0 -fuse-ld=mold && ./test
ImageBase: (nil)
```

**Comment by rui314** [comment]
Using PC-relative relocation (`R_X86_64_32`) to refer to an absolute symbol works only for non-PIC executable. So the mold's is the most honest result, as it reported an error. GNU ld and lld silently create a binary that doesn't work as intended.

You want to compile your executable with `-fno-PIC` and link with `-no-pie`, or compile with `-fPIC` and link with `-pie`. Compiling with `-fno-PIC ` and linking with `-pie` doesn't work.

**Comment by Alcaro** [comment]
That depends on what the intention is.

If the intention is a symbol that's a NULL pointer, then it does indeed not work as intended. But why would you do that instead of just typing NULL in your source code?

If the intention is a symbol that points to the ELF headers, at address 0 relative to the program start, then bfd and lld are doing exactly that (though I agree the command line syntax is strange and misleading).

Judging by the variable name, it's the latter.

**Comment by rui314** [comment]
If you want to define a symbol relative to the beginning of the ELF header, you should pass `--defsym=foo=__ehdr_start+0xabcd`

**Comment by medhefgo** [comment]
> If the intention is a symbol that's a NULL pointer, then it does indeed not work as intended. But why would you do that instead of just typing NULL in your source code?

Is that supposed to be some lame attempt at a joke at my expense? Not everyone understands how linking works, you know.

> If the intention is a symbol that points to the ELF headers, at address 0 relative to the program start, then bfd and lld are doing exactly that (though I agree the command line syntax is strange and misleading).

This is trying to get at the image base/load address. From what I can tell, it gets me the same thing as `__ImageBase = .` at the start of a `-dT` linker script. There is `__executable_start` already provided by the linker, but I suspect it's not exactly the same (if `-Ttext-segment` were used).

@rui314 Either way, I merely saw a surprising (to me) behavior difference I thought should be reported. I you don't like this kind of report I am happy to keep potential bugs to myself in the future.

Ultimately, I don't think I will be needing this in the end anyways as it won't be pointing to the right thing after the elf2efi conversion. (Unless it can be made to point in front of the ELF image/have a negative offset?)

**Comment by medhefgo** [comment]
> Using PC-relative relocation (`R_X86_64_32`) to refer to an absolute symbol works only for non-PIC executable. So the mold's is the most honest result, as it reported an error. GNU ld and lld silently create a binary that doesn't work as intended.
> 
> You want to compile your executable with `-fno-PIC` and link with `-no-pie`, or compile with `-fPIC` and link with `-pie`. Compiling with `-fno-PIC ` and linking with `-pie` doesn't work.

We instruct meson to pass pic/pie to compilation, this is merely an oversight on the test case.

If I use `--section-order` to define `__ImageBase` mold does not complain, but the binary will crash with `-static-pie`. Now I am really confused, I expected the behavior to be the same, or is this making a relative symbol? Is there a way to create a relative symbol with `--defsym`?
```
$ gcc -o test test.c -fPIE -pie -fuse-ld=mold -Wl,--section-order='=0x0 !__ImageBase PHDR TEXT DATA BSS RODATA' && ./test
ImageBase: 0x558015174000
$ gcc -o test test.c -fPIE -static-pie -fuse-ld=mold -Wl,--section-order='=0x0 !__ImageBase PHDR TEXT DATA BSS RODATA' && ./test
Segmentation fault (core dumped)
```

> Can you explain a little bit more about what are you trying to achieve with the `--defsym` option? I can give you a better answer if I understand the intention of the option.

I am trying to get the ELF to PE conversion going by using ELF load segments only as you suggested. And during runtime I may need to have access to the loaded image PE headers.
This was rather easy to do with linker scripts by putting `__ImageBase = .` at the top and would give me instant access to the PE headers (other sections were moved out of the way by the same linker script).

The idea behind the defsym was to get at the image base/load address of the loaded ELF image, which would then allow me to find the PE headers from the elf2efi conversion at a fixed negative offset.
I am also toying with the idea of using `-Ttext-segment=` to move the load segments out of the way so that the symbol can point directly at the PE headers. Assuming it does what I think it does.

Final image layout with defsym:
```
… | PE headers | … | ELF LOAD segment 0 | …
                   ^ load_segments[0].p_vaddr == __ImageBase == __executable_start == 0
  ^ __ImageBase - pe_header_offset
```

Or, if `-Ttext-segment=pe_header_offset` works as I think it does:
```
… | PE headers | … | ELF LOAD segment 0 | …
                   ^ load_segments[0].p_vaddr == __executable_start == pe_header_offset
  ^ __ImageBase == 0
```

Ultimately, I can do without defining `__ImageBase` as I can just ask the firmware to tell me where we were loaded at. It's just nice if we can get it directly from the linker as it should know this.
