### ISSUE TITLE
`mold` fails to build `glibc` on `aarch64` with `mathvec`

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1115]
`glibc 2.38` added support for `mathvec` on `aarch64` but it requires `PCS support` in order to enable it. `mold 2.2.0` seems to lack it though and `configure` fails if `mold` is used. I'm not really sure what `PCS` is but here's what `glibc` [does](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/aarch64/configure.ac;h=27874eceb44911e4f5751ca870d37198f37a9869;hb=36f2487f13e3540be9ee0fb51876b1da72176d3f#l69):
```console
$ cat <<EOF | gcc -nostdlib -nostartfiles -shared -fPIC -x assembler - -o test.so
.global foo
.type foo, %function
.variant_pcs foo
foo:
        ret
.global bar
.type bar, %function
bar:
        b foo
EOF
```
Compared to `bfd`, `mold` lacks following entry in `readelf -dW test.so`:
```
 0x0000000070000005 (AARCH64_VARIANT_PCS) 0x0
```

**Comment by rui314** [comment]
Thank you for reporting! I implemented it in the above commit.
