### ISSUE TITLE
armhf/armv7 failure with latest release

### ISSUE THREAD

**Issue by bl4ckb0ne** [rui314/mold#1116]
Hello there,

We upgraded the Alpinelinux package to the latest release, and the CI is failing on both armhf and armv7.

armhf [1]
```
The following tests FAILED:
	234 - arm-tlsdesc-local-dynamic (Failed)
	236 - arm-tlsdesc (Failed)
```

armv7 [2]
```
The following tests FAILED:
	  4 - arm-arm_tlsdesc (Failed)
	234 - arm-tlsdesc-local-dynamic (Failed)
	236 - arm-tlsdesc (Failed)
```

[1]: https://gitlab.alpinelinux.org/Celeste/aports/-/jobs/1124524/artifacts/raw/logs/build-mold.log
[2]: https://gitlab.alpinelinux.org/Celeste/aports/-/jobs/1124523/artifacts/raw/logs/build-mold.log

**Comment by rui314** [comment]
If you have an access to the build directory, can you pack the entire build directory as a tar or zip file and share it with me?

**Comment by bl4ckb0ne** [comment]
Havent found a way to grab it from the CI, I'll see what I can do

**Comment by bl4ckb0ne** [comment]
Here's the link for [armv7](https://files.catbox.moe/wvpx9o.zip) and [armhf](https://files.catbox.moe/h1edqk.zip), both are about ~55MB, but I can trim it down if you know what you need/want.

**Comment by rui314** [comment]
Thank you for sharing files! However, these files don't seem to contain artifacts created by tests. Do you mind if I ask you to pack everything including ones generated by `ctest`?

**Comment by bl4ckb0ne** [comment]
There you go, [armv7](https://files.catbox.moe/pnonxc.gz) and [armhf](https://files.catbox.moe/bd3c1w.gz)

**Comment by rui314** [comment]
Can you try again with the above change?

**Comment by bl4ckb0ne** [comment]
The change above is ICE'ing llvm on both armhf and armv7

[armhf](https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1133465#L927)
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Running pass 'Function Pass Manager' on module 'CMakeFiles/mold.dir/elf/passes.cc.SPARC64.cc.o'.
1.	Running pass 'Live DEBUG_VALUE analysis' on function '@_ZN4mold3elf25create_synthetic_sectionsINS0_7SPARC64EEEvRNS0_7ContextIT_EE'
clang-16: error: unable to execute command: Segmentation fault (core dumped)
clang-16: error: linker command failed due to signal (use -v to see invocation)
```

[armv7](https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1133464#L927)
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Running pass 'Function Pass Manager' on module 'CMakeFiles/mold.dir/elf/output-chunks.cc.PPC32.cc.o'.
1.	Running pass 'Live DEBUG_VALUE analysis' on function '@_ZZN4mold3elf14EhFrameSectionINS0_5PPC32EE8copy_bufERNS0_7ContextIS2_EEENKUlPNS0_10ObjectFileIS2_EEE_clES9_'
clang-16: error: unable to execute command: Segmentation fault (core dumped)
clang-16: error: linker command failed due to signal (use -v to see invocation)
ninja: subcommand failed
```

I'll edit this post with the build folder soon.

**Comment by rui314** [comment]
It looks like that test doesn't test even with GNU ld, so the TLSDESC implementation on ARM32 musl is just broken. I'll disable that test on that particular target and roll back my previous change.

**Comment by rui314** [comment]
Filed a bug report to musl: https://www.openwall.com/lists/musl/2023/10/06/1

**Comment by bl4ckb0ne** [comment]
Thanks you for reporting it. I applied part of the fix from https://github.com/rui314/mold/commit/cf11efb1471fca0d51fe788682f2404a115f47c7 to the Alpine package but still got some CI issue, I'll sort it out late.

Thank you for your time.
