### ISSUE TITLE
symbol referring .eh_frame is not supported for clang_rt.crtbegin-x86_64.o

### ISSUE THREAD

**Issue by kmatheussen** [rui314/mold#112]
Thanks for your work! My project uses a few seconds to link so it would be great to reduce linking time.

However I get this error when trying to use mold:

```mold: symbol referring .eh_frame is not supported: __EH_FRAME_LIST__ /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/clang_rt.crtbegin-x86_64.o```

Here's my arguments: ``` --rtlib=compiler-rt -lgcc_s -fuse-ld=/home/kjetil/mold/mold```

If I remove the `--rtlib=compiler-rt` argument I get a lot of these errors:

```
mold: undefined symbol: /tmp/radium_objects/velocities.o: __muloti4
```

Any tip? A newer version of llvm perhaps? (I'm currently using clang/llvm provided by ubuntu 20)
(I could also change the code so that it doesn't need the __muloti4 instructions but I rather not want to do that.)

**Comment by kmatheussen** [comment]
I found a workaround. There's an implementation of __muloti4 at https://reviews.llvm.org/D49828 I can use in debug mode. I guess that's an okay solution. The function is not very complicated.

And now my linking time was reduced from 8 seconds to 2 second!

I don't know if this is a limitation or bug in mold, so I leave it up to you to close the issue.

**Comment by rui314** [comment]
I made a change for you at 771fc02b6d491f8732e2c99a5dfcfa1155f83772. Could you check it out and try again?

**Comment by kmatheussen** [comment]
Yes, it works. Thanks!

**Comment by rui314** [comment]
Thank you for testing! By the way, what is your CPU, and what linker were you using before mold? 8 seconds to 2 seconds is a good improvement, but it could be 10x if your machine has lots of cores.

**Comment by kmatheussen** [comment]
I'm using a slow computer with only two cores, i5-3360M CPU @ 2.80GHz

Seems like clang was using bfd before by default, not even gold or lld, which are both much faster. In fact, on my computer, lld is even faster than mold.

Here's some benchmark data for linking https://github.com/kmatheussen/radium in debug mode:

```
lld:
0m1,149s
0m1,142s
0m1,140s


mold:
0m1,309s
0m1,297s
0m1,281s

gold:
0m3,072s
0m3,019s
0m3,122s


bfd:
0m7,627s
0m7,650s
0m7,568s
```

**Comment by kmatheussen** [comment]
`--preload` beats them all though:

```
0m0,051s
0m0,088s
0m0,054s
```

Extremely impressive!

**Comment by rui314** [comment]
With two cores, it's no surprise that lld outperforms mold. When I was writing multithreaded code, I oftentimes had to make a choice between multithreaded code with higher overhead (faster on multicore) and single-threaded code with lower overhead (faster on single core). I always choose the former for mold, so it's fast on a machine with lots of cores, but not so much if it doesn't that much cores. But still, mold isn't that slow compared to lld on a 2-core machine, though.

As for `--preload`, I believe you are measuring a wrong part of the process. The first invocation of the linker with `--preload` finishes very quickly, as it spawns a daemon and immediately exit. You should measure the second invocation of the linker without `--preload`.

**Comment by kmatheussen** [comment]
Yes you're right. I misunderstood how ```--preload``` works. For some reason I thought it created a binary in a special format that mold could reuse the next time it was launched. 

But are you supposed to start a ```--preload``` daemon every time, or should it be enough to start it just once? Because if I start it just one time, the daemon is stopped the next time mold is started without ```--preload```, so it seems like I have to restart it every time. In fact, the daemon is even defuncted after running without ```---preload```:
```
ps -Af|grep -i mold
kjetil    178836       1 26 11:51 ?        00:00:04 [mold] <defunct>
```
...which makes me believe something went wrong.

I also don't see any improvement in execution speed for the second run.

**Comment by rui314** [comment]
The daemon is designed to be used only once. So you need to invoke it every time just before you use the linker. Here is the expected use case of the feature: a user modifies their Makefile so that the linker is invoked twice, once before the compilation step runs and once after that. So, it's not a handy feature. It needs a build system's support.

**Comment by kmatheussen** [comment]
Got it, thanks! I've changed my build to run prelink before doing anything else and I do see a small speedup now:

```
With prelink:
0m1,175s
0m1,177s
0m1,171s
0m1,177s

Without prelink:
0m1,439s
0m1,268s
0m1,294s
0m1,272s
```

**Comment by kmatheussen** [comment]
Also note that most of my object files are placed on a ```tmpfs``` filesystem, including the produced executable, so this build should not be very i/o bounded, which perhaps lowers the advantage of using ```--prelink```.
