### ISSUE TITLE
Mold ignores archive redefinition with `--whole-archive`

### ISSUE THREAD

**Issue by nuudlman** [rui314/mold#1120]
I'm investigating a linker issue for StreamFX (https://github.com/Xaymar/obs-StreamFX/tree/54b6df0fd0864f9a996d4887dea73e541bd3a9a1).

There error there boils down to this:
```
c++ -shared -o StreamFX.so -Wl,--push-state,--whole-archive StreamFX_Core.a <many other archives> -Wl,--pop-state <system libs> -Wl,--push-state,--whole-archive StreamFX_Core.a -Wl,--pop-state
```
This causes BFD and LLD to fail with symbol redefinition errors. Mold is perfectly happy and completes successfully.

Is this intended behavior with mold?

Repro file: https://files.catbox.moe/pucmt3.xz

**Comment by rui314** [comment]
Thank you for your report! We should report a duplicate error for that case indeed. The above commit should fix the issue.
