### ISSUE TITLE
segfault when linking openjdk11 for ARM 32-bit

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1132]
`mold 2.3.0` crashes when linking `libjvm.so` from openjdk11 (ARM 32-bit). Tried to narrow down problematic object files but without much success. Note that issue possibly depends on specific object files order -- it reproduces with `@objfiles.txt` but does not with `*.o` so ie:
```
$ g++ -Wl,-fuse-ld=mold -shared -Wl,-soname=libjvm.so -o libjvm.so @objfiles.txt
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
```
http://jpalus.fastmail.com/mold/openjdk11-arm/objs.tar.xz
http://jpalus.fastmail.com/mold/openjdk11-arm/objfiles.txt

**Comment by rui314** [comment]
Thank you for your report. I confirmed the issue. I'll fix it and make a new release as 2.3.1.
