### ISSUE TITLE
Mold blocks some instruction sets when `-fcf-protection` is enabled?

### ISSUE THREAD

**Issue by HanabishiRecca** [rui314/mold#1133]
Looks like mold blocks generation of some instruction sets when `-fcf-protection` is enabled for almost every app I tested.

The easiest way to reproduce the problem: try to build [`btop`](https://github.com/aristocratos/btop), it uses `-fcf-protection` by default and has a convinient output during compilation. Simply run `make` in the source dir, output is `./bin/btop`.

Compare the output of `ld` and `mold`. Immediately you will see that the size of the binary is different.

---

To analyze it deeper, I use [`elfx86exts`](https://github.com/pkgw/elfx86exts) tool.

Using default GCC `ld`, the file size is 1.5 MiB (1555560 bytes) and the tool output:
```
$ elfx86exts ./bin/btop
File format and CPU architecture: Elf, X86_64
MODE64 (call)
CMOV (cmova)
SSE2 (movq)
SSE1 (movaps)
BMI (tzcnt)
Instruction set extensions used: BMI, CMOV, MODE64, SSE1, SSE2
CPU Generation: Haswell
```

Now using `mold` (`LDFLAGS='-fuse-ld=mold' make`), the file size is 1.6 MiB (1648104 bytes) and the tool output:
```
$ elfx86exts ./bin/btop
File format and CPU architecture: Elf, X86_64
MODE64 (push)
Instruction set extensions used: MODE64
CPU Generation: Intel Core
```
You can see effectively no instruction sets are used.

---

I don't know why and how it happens, noticed this behavior accidently.

OS: Arch Linux
GCC: 13.2.1

**Comment by HanabishiRecca** [comment]
Actually I was wrong. There is no direct correlation with build flags. And this behavior persists between compilers and even different languages.

Same thing happens even with Rust binaries linked with mold. Now I am started to think it is not a mold's fault.

My guess: mold somehow plays around with the data and `elfx86exts` is simply unable to read it. And size difference is just a coincedence.

**Comment by rui314** [comment]
mold might be at fault. What is your distro and compiler?

**Comment by rui314** [comment]
Well, the linker synthesizes some information that will be interpreted by the dynamic loader, and the dynamic loader might behave differently if some information is lacking. But I'll close it again.

**Comment by HanabishiRecca** [comment]
Sorry for bumping this again, but I think I figured out why disassembly fails. Despite it being a disassembly tool's fault, mold indeed have a specific behavior.

Inspecting dumps I found that it produces "junk" empty spaces between functions/symbols.

`objdump` shows them as `...`

```
   360e0:	f3 0f 1e fa          	endbr64
   360e4:	e9 67 ff ff ff       	jmp    36050 <_start+0x60>
   360e9:	00 00                	add    %al,(%rax)
   360eb:	00 00                	add    %al,(%rax)
   360ed:	00 00                	add    %al,(%rax)
	...

00000000000360f0 <atexit>:
   360f0:	f3 0f 1e fa          	endbr64
   360f4:	48 8b 15 ed 86 10 00 	mov    0x1086ed(%rip),%rdx        # 13e7e8 <__dso_handle>
   360fb:	31 f6                	xor    %esi,%esi
   360fd:	ff 25 65 75 10 00    	jmp    *0x107565(%rip)        # 13d668 <__cxa_atexit@GLIBC_2.2.5>
	...

0000000000036110 <_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev>:
   36110:	f3 0f 1e fa          	endbr64
```

These are effectively zero-filled spaces. In fact `360e9`, `360eb`, `360ed` are also zeroes, misinterpreted as instructions for some reason.

Using another disassembly tool (Cutter)

```
entry.init0();
0x000360e0      endbr64
0x000360e4      jmp     0x36050
0x000360e9      add     byte [rax], al
0x000360eb      add     byte [rax], al
0x000360ed      add     byte [rax], al
0x000360ef      add     bl, dh
int atexit(void *function);
0x000360f0      endbr64
0x000360f4      mov     rdx, qword __dso_handle ; 0x13e7e8
0x000360fb      xor     esi, esi
0x000360fd      jmp     qword __cxa_atexit$got ; 0x13d668
0x00036103      add     byte [rax], al
0x00036105      add     byte [rax], al
0x00036107      add     byte [rax], al
0x00036109      add     byte [rax], al
0x0003610b      add     byte [rax], al
0x0003610d      add     byte [rax], al
0x0003610f      add     bl, dh
  ;-- std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string():
```

This tool does not skip them, all that `add byte [rax], al` are zeroes, wrongly interpreted as instructions.

---

Well, what's the deal with it you may ask. Answer: I don't know, not an expert in this topic, can't judge is that bad or not.
The only thing I can say is **`ld` doesn't do that**. 🙂

**Comment by rui314** [comment]
That's not a bug. That's just garbage between functions. Usually the beginning of a function is aligned to a 16 byte boundary, but not all function ends at a 16 byte boundary. Therefore, there's usually a few bytes unused area at the end of each function. GNU ld seems to fill such area with a NOP while mold don't do anything (i.e. leaving it as zeros). Disassemblers should still be able to disassmeble it because each function's start is pointed to by an entry in the symbol table.

**Comment by HanabishiRecca** [comment]
Yes, I know this is not a bug.
I don't see free areas in binaries produced by ld though. It seems to pack functions tighter overall (and that's why binaries produced by mold is slightly larger, I guess this is a tradeoff for speed).

Not sure about filling with NOPs though. But I heard that filling empty space with INT3 (`0xCC`) may be a good idea for security. Because in case of code execution accidently hitting a place where it should not be, program will crash.

> Disassemblers should still be able to disassmeble it because each function's start is pointed to by an entry in the symbol table.

Not really, symbols are usually stripped for release / during packaging, and `.text` effectively turns into a one continious chunk of code.

**Comment by HanabishiRecca** [comment]
Thank you very much btw. Our discussion pointed me to a right direction and I managed to develop a fix for the tool! 🤗
