### ISSUE TITLE
Compiling mold: can't find <zstd.h> or -lzstd

### ISSUE THREAD

**Issue by absolutelynothinghere** [rui314/mold#1138]
I'm compiling mold on linux with clang and during compilation it can't find ZSTD.
My workaround was manually building ZSTD in `third-party/zstd/build/cmake` then running

```sh
LDFLAGS=-L$PWD/third-party/zstd/build/cmake/lib cmake -DCMAKE_CXX_COMPILER=c++ -DCMAKE_CXX_FLAGS=-I$PWD/third-party/zstd/lib .
cmake --build .
```

Mold version is 2.3.0

**Comment by rui314** [comment]
What is your distro?

**Comment by absolutelynothinghere** [comment]
Void Linux

**Comment by rui314** [comment]
I tried to build mold on `ghcr.io/void-linux/void-glibc` and `ghcr.io/void-linux/void-musl` docker images, and it built fine. Please provide more information so that I can reproduce your issue.

**Comment by absolutelynothinghere** [comment]
I created the [chroot](https://pastebin.com/5TKeTM3P) but was not able to reproduce the issue, so I'm closing this for now.

If I ever manage to reproduce the issue again I'll reply here. Thank you for your time and sorry for the inconvenience.
