### ISSUE TITLE
valgrind fails on assertion after loading debuginfo file

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1139]
Tried to run `Waybar` today with valgrind's `callgrind` but it failed:
```
valgrind: m_debuginfo/readelf.c:3394 (vgModuleLocal_read_elf_debug): Assertion 'di->rodata_size == a_shdr.sh_size' failed.
```
`Waybar` was built for `aarch64/linux` with `-g2` and linked with `mold 2.3.1`. debuginfo file is separate but it appears `callgrind` does not like something about it. If needed I can provide both binary and debuginfo file. If linking is done with `bfd` it works fine.

**Comment by jpalus** [comment]
Simple reproducer:
```sh
g++ -x c++ -g2 -fuse-ld=mold -o test - <<EOF
#include <iostream>

int main() {
  std::cout << "hello world" << std::endl;
}
EOF
eu-strip -f test.di test
valgrind -v --tool=callgrind ./test
```
Output:
```console
...
--413198--   Considering /home/users/builder/test.di ..
--413198--   .. CRC is valid

valgrind: m_debuginfo/readelf.c:3394 (vgModuleLocal_read_elf_debug): Assertion 'di->rodata_size == a_shdr.sh_size' failed.
...
```
Works fine with both `bfd` and `lld`.

**Comment by jpalus** [comment]
As a matter of fact it's an issue with any valgrind tool so not callgrind specific. memcheck fails as well.

**Comment by rui314** [comment]
It looks like the latest release of Valgrind contains a change to improve compatibility with mold. I haven't tried, but is this related to that?

https://valgrind.org/docs/manual/dist.news.html

**Comment by jpalus** [comment]
Actually it's with latest version and it seems it might be regression in 3.22.0. Just checked 3.21.0 and it works fine. Let me raise a ticket in valgrind bugtracker as well.

**Comment by jpalus** [comment]
Raised https://bugs.kde.org/show_bug.cgi?id=476548

**Comment by rui314** [comment]
Thank you for doing that!

**Comment by jpalus** [comment]
valgrind issue after all which is now fixed upstream.
