### ISSUE TITLE
Firefox segfaults on launch

### ISSUE THREAD

**Issue by dylanaraps** [rui314/mold#114]
The last good commit (which produces a working Firefox) is https://github.com/rui314/mold/commit/b99626fbf2c22e1024996646cb87cfdab5cfe667. All subsequent commits (that I have tried) produce a Firefox binary which segfaults on startup. It seems as though https://github.com/rui314/mold/commit/475a250ad499982b79d887937ea9298faf6cc10e is the cause though I have no proof to back this up. I will be going through commit by commit to see exactly where the issue is introduced. This will take me some time as it's 3+ hours per build.

**Comment by dylanaraps** [comment]
I will be trying with 0.9.4 next (3 commits ahead). Let me know if there is any information I can provide also.

**Comment by dylanaraps** [comment]
OK. 0.9.4 produces a segfaulting binary.

One of these two commits introduces the issue(?):

- https://github.com/rui314/mold/commit/06b11da76da50ff0ff3e4de387474d7f9ef17cb1
- https://github.com/rui314/mold/commit/475a250ad499982b79d887937ea9298faf6cc10e

**Comment by rui314** [comment]
Thank you for reporting! It is very likely to be caused by https://github.com/rui314/mold/commit/475a250ad499982b79d887937ea9298faf6cc10e. How did you build Firefox? Are you building a release binary or a debug?

**Comment by dylanaraps** [comment]
I built a release binary.

Build instructions: https://github.com/kisslinux/repo/blob/master/testing/firefox/build
CFLAGS/CXXFLAGS: `-O3 -march=native -pipe`

**Comment by rui314** [comment]
Thank you for sharing the build instruction. I succeeded to reproduce the issue. Investigating...

**Comment by rui314** [comment]
This comment states that Firefox uses a linker "loophole" that it will promote weak undef symbols to dynamic symbols even if `-z defs` is given when building a .so file. This loophole is exactly what I wanted to plug as I thought it was more like a bug than a feature. But it looks like I can't do that. I have to make mold compatible with mozilla.

https://hg.mozilla.org/mozilla-central/file/tip/mfbt/Types.h#l91

**Comment by rui314** [comment]
I believe I managed to fix this. Could you verify if you have time?

**Comment by dylanaraps** [comment]
Yes. I will verify now and let you know in 2-3 hours.

**Comment by dylanaraps** [comment]
Works, thanks. :)
