### ISSUE TITLE
2 tests fail on x86 32-bit in mold 2.3.2

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1140]
Running mold 2.3.2 tests when targeting i686 results in failures:
```
The following tests FAILED:
	81 - i686-global-offset-table (Failed)
	142 - i686-nocopyreloc (Failed)
```
It appears to be mismatch between test which expects `MACHINE` to be `i386` for all `i?86` HOSTS ie:
https://github.com/rui314/mold/blob/edc2f852a1f893be2cb824a6832d0f48d4680910/test/elf/global-offset-table.sh#L23-L27
and `cmake` which sets `HOST` to `i686`
https://github.com/rui314/mold/blob/edc2f852a1f893be2cb824a6832d0f48d4680910/test/elf/CMakeLists.txt#L3
and does not go through `canonical_name` in `common.inc` when `TRIPLE` is empty:
https://github.com/rui314/mold/blob/edc2f852a1f893be2cb824a6832d0f48d4680910/test/elf/common.inc#L6-L23

**Comment by rui314** [comment]
Does the above change fix the issue?

**Comment by jpalus** [comment]
It depends :) Was the intent to execute majority of tests on i686 through `qemu-i386`?
https://github.com/rui314/mold/commit/0f78fa9c4380725112013ab553d761b2cff6cfde#diff-2d799e2a6eec713212b1b644783018d36eb018d27e5465e9938e132bef0580d8R64-R66

**Comment by rui314** [comment]
Ah, that should be fixed by now.
