### ISSUE TITLE
Publish SHA256 checksums in releases

### ISSUE THREAD

**Issue by JonahPlusPlus** [rui314/mold#1146]
## Problem
I am creating a Dockerfile that downloads and installs mold from a release URL. I would like to also download the SHA256 checksums to verify that the archives I download are correct.

## Solution
I think the first thing to do would to create a GitHub action to build the archives and create the SHA256 checksums and export it to a file along the releases. This is probably enough to verify that there isn't any corruption, but I think it should go a step further and PGP sign the checksums. NodeJS does this and you can [see the result](https://nodejs.org/dist/v20.8.0/SHASUMS256.txt.asc).

How it would work is the release GitHub action would sign the checksum file using `gpg` and a private key stored as a secret. The primary public key would be displayed in the README.md and subkeys could be stored on [keys.openpgp.org](https://keys.openpgp.org) (NodeJS does the [same](https://github.com/nodejs/node#release-keys)).

This setup would result in a few files `SHA256SUMS.txt`, `SHA256SUMS.txt.asc`, and `SHA256SUMS.txt.sig`. These files could be used in a couple ways:
1. Users could just download `SHA256SUMS.txt.asc` and decode `SHA256SUMS.txt` from it.
2. Users could download both `SHA256SUMS.txt` and `SHA256SUMS.txt.sig` and verify the file.

**Comment by JonahPlusPlus** [comment]
I can look into making a PR for this, but I would need the project maintainer to add the secrets to the repo settings.

**Comment by rui314** [comment]
Gzip checks file integrity with CRC-32, and HTTPS ensures that a file has been downloaded from the real github.com. So, I don't see much value in publishing SHA256 checksums separately. What specific threat or failure mode are you aiming to guard against?

**Comment by JonahPlusPlus** [comment]
The real threat would be if GitHub were to become compromised and the release files were to become modified. (On that note, I suppose keeping the secret on GitHub would also be a bad idea, maybe it could be automated as a Git hook?)

Is there a real threat? No, the chances of GitHub becoming compromised and being used to attack individual projects is extremely small. Still, eliminating the slightest possibility of attack and keeping the attack surface as small as possible is ideal. It's probably overkill, but I would rather be safe than sorry. If this turns out to be too much, I guess I can go without it.

**Comment by rui314** [comment]
That's probably overkill. The real threat would be if I were a rogue developer and planted malicious code in the binary distribution files. That likelihood would be thousands of times greater than the chance of GitHub being compromised. Therefore, I think publishing SHA256 hashes wouldn't significantly reduce the risk as long as I'm involved in the process.

One thing I've been eager to do is make the build processes for release binaries reproducible, allowing users like you to verify that the release binaries were built from the corresponding source files. This wouldn’t entirely prevent the situation where I might be a rogue developer, as I could modify the source code to insert malicious code. However, doing this without leaving a trace would be much more difficult than doing the same with release binaries. I'll try to do that instead.

**Comment by JonahPlusPlus** [comment]
Huh, could you elaborate on that? I imagine that would mean storing the settings for the build environment either in the form of heavy documentation or a Docker image. Then I would build and archive the binaries, and store the checksums for my images to verify against. I suppose that would be even more secure, since it eliminates the need for trust entirely.

**Comment by rui314** [comment]
Well, if you use the SHA checksums I provide to verify binaries that I uploaded, you need to trust that I didn't insert malicious code into the binaries. So, if you don't trust me, verifying the checksums doesn't make sense. And if you do trust me, why bother verifying the checksums, given that only I can upload binaries to the release page?

If you do not trust me and you assess all source files yourself, you still wouldn't be sure if the binaries provided on the release pages contain malicious code, because they are binary blobs. For that situation, a reproducible build would be very helpful.

Anyways, let me take a look into it.
