### ISSUE TITLE
Some errors emit when i wanta change the ld of gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu to mold

### ISSUE THREAD

**Issue by playboy0007** [rui314/mold#1149]
When compiler wanta make ".so", this error emit.

![20231116-112529](https://github.com/rui314/mold/assets/36851506/c906022a-38cd-4444-a7a6-29009d44b662)

**Comment by rui314** [comment]
It says that `recompile with -fPIC`, so please compile your object files with the `-fPIC` compiler option.

**Comment by playboy0007** [comment]
Thanks a lots of you.
