### ISSUE TITLE
AppleClang 12.0.0 (latest) doesn't support `-std=c++20`

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [rui314/mold#115]
Trying to build the latest version of mold on macOS (to use for cross-compilation) but the build errors out because the latest version of AppleClang (which seems to be the preferred compiler based on the Makefile? And is the preferred compiler on macOS anyway) does not support `-std=c++20`.

It might be worth falling back to `-std=c++2a` on Darwin targets until Apple updates their modified clang, at least as a default.

I'm using trunk at the current head (1cb750a649aa94d111680241b53c915178bb15ff)

**Comment by rui314** [comment]
I have an Intel Mac. It looks like my clang version is newer than yours, and it does supports `-std=c++20`.

```
ruiu:~$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
```

Could you run software updates and try again?

**Comment by Th3T3chn0G1t** [comment]
I seem to be at latest for XCode? But IG if Apple dropped support for further updates to Intel macs then there's no point in supporting it at trunk for you ;p - I can just modify the makefile myself

**Comment by rui314** [comment]
So I guess you are not just using the latest version of clang on your mac? Did you update your Xcode to the latest version?

**Comment by Th3T3chn0G1t** [comment]
I am, apple just doesnt seem to provide later XCode versions to intel macs, or at least to and of the ones I have access to (I think the latest one I tested was a 2017 model?)

**Comment by rui314** [comment]
I'm using an Intel Mac (Macbook Pro 2018), and my clang's version of the latest Xcode is 12.0.5. It is hard to imagine that Intel Mac 2017 can't get the same version as mine. Maybe you need to update your macOS and then Xcode?

**Comment by Th3T3chn0G1t** [comment]
Its on Big Sur so it should be fine right? afaik the next release is still in beta. Weirdly the latest llvm cask on homebrew only offers me clang 12.0.1

**Comment by Th3T3chn0G1t** [comment]
Just to update - HB now has 13.0.0 so its all good
