### ISSUE TITLE
Error emit when I change the ld of gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu to mold

### ISSUE THREAD

**Issue by playboy0007** [rui314/mold#1150]
![20231116-112529](https://github.com/rui314/mold/assets/36851506/0f730d2d-6579-4df5-b7af-65adba9f8e56)

**Comment by rui314** [comment]
As I responded in the another issue, you need to compile with -fPIC.

**Comment by playboy0007** [comment]
Thanks a lots of you.
