### ISSUE TITLE
x86_64-run failure

### ISSUE THREAD

**Issue by andreas-schwab** [rui314/mold#1153]
+ LD_PRELOAD=/home/abuild/rpmbuild/BUILD/mold-2.3.3.34.gb3984c9/build/mold-wrapper.so
++ pwd
+ MOLD_PATH=/home/abuild/rpmbuild/BUILD/mold-2.3.3.34.gb3984c9/build/mold
+ gcc -o out/test/elf/x86_64/run/exe out/test/elf/x86_64/run/a.o -B/usr/bin
+ readelf -p .comment out/test/elf/x86_64/run/exe
+ grep -q '[ms]old' out/test/elf/x86_64/run/log
++ on_error 21
++ code=1
++ echo 'command failed: 21: grep -q '\''[ms]old'\'' $t/log'
command failed: 21: grep -q '[ms]old' $t/log

The compiler never actually calls mold:

$ MOLD_WRAPPER_DEBUG=1 LD_PRELOAD=/home/abuild/rpmbuild/BUILD/mold-2.3.3.34.gb3984c9/build/mold-wrapper.so gcc -o out/test/elf/x86_64/run/exe out/test/elf/x86_64/run/a.o -B/usr/bin 
mold-wrapper.so: posix_spawn /usr/lib64/gcc/x86_64-suse-linux/14/collect2

**Comment by andreas-schwab** [comment]
With gcc 13, mold-wrapper sees the call to the linker:

$ MOLD_WRAPPER_DEBUG=1 LD_PRELOAD=/home/abuild/rpmbuild/BUILD/mold-2.3.3.34.gb3984c9/build/mold-wrapper.so gcc -o out/test/elf/x86_64/run/exe out/test/elf/x86_64/run/a.o -B/usr/bin
mold-wrapper.so: execve /usr/lib64/gcc/x86_64-suse-linux/13/collect2
mold-wrapper.so: execvpe /usr/bin/ld
MOLD_PATH is not set
collect2: error: ld returned 1 exit status

**Comment by rui314** [comment]
Fixed by https://github.com/rui314/mold/pull/1154
