### ISSUE TITLE
Question: shall I use sold/mold in performance-sensitive production environment?

### ISSUE THREAD

**Issue by PureWhiteWu** [rui314/mold#1155]
Hi, I'm not familiar with various kind of linkers, I just heard about that sold (and mold) are much more faster in link time comparing with other linkers, which can greatly improve develop and debug experience. And I'm thinking about whether to buy sold commercial version.

But I wonder if I can also use sold/mold in production environment instead of lld? Is sold/mold only aims to improve the link performance instead of the final binary runtime performance? Is there any performance benchmark about the final binary?

For short, should I use sold/mold only during debug or I can also use it in production environment?

Thanks very much!

**Comment by rui314** [comment]
In general, linker doesn't affect the linked program's performance, so no need to worry about.

**Comment by PureWhiteWu** [comment]
Hello, thanks for your reply!
I'm not quite sure, but I suppose LTO may affect the program's performance?

**Comment by rui314** [comment]
mold supports LTO.

**Comment by PureWhiteWu** [comment]
Thanks very much!
