### ISSUE TITLE
Qt 6 symbol mismatch

### ISSUE THREAD

**Issue by HanabishiRecca** [rui314/mold#1158]
Qt 6.6.1 linked with mold make apps crash. Earlier versions were fine.

A particular error may vary, but it is about symbols not found, like
```
qbittorrent-nox: symbol lookup error: qbittorrent-nox: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6
```

It is a bit tricky to reproduce though.
Basically an app crashes if it is built against Qt linked with ld, but you trying to run it with Qt linked by mold.

I.e. I assume Qt 6.6.1 has symbols mismatch between ld and mold.

---

Arch Linux / mold 2.3.3

**Comment by rui314** [comment]
Thank you for reporting. I succeeded to reproduce the issue. Let me take a look.

**Comment by HanabishiRecca** [comment]
Yes, seems to be fixed. 👍
I'll report back in case of anomalies.

**Comment by ishitatsuyuki** [comment]
Looks like they turned that thing into a wildcard in 6.7.0-beta1 and this no longer works again.

https://github.com/qt/qtbase/commit/93233516957f71054c42ba843cdd57216834acd7

You can build 6.7.0-beta1 of https://github.com/qt/qtbase and inspect the symbol list.

BFD gives: `_ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate@@Qt_6`
mold gives: `_ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate@@Qt_6_PRIVATE_API`

**Comment by HanabishiRecca** [comment]
And this happens again in 6.6.2 🙃

**Comment by rui314** [comment]
Are you still using `qbittorrent-nox` as a test program? Did it work with Qt 6.6.1 but broke with 6.6.2?

**Comment by ishitatsuyuki** [comment]
I believe it's the same commit above cherry-picked into the 6.6 branch. @HanabishiRecca, are you using mold `main`?

**Comment by HanabishiRecca** [comment]
> Are you still using `qbittorrent-nox` as a test program? Did it work with Qt 6.6.1 but broke with 6.6.2?

Yes.

> I believe it's the same commit above cherry-picked into the 6.6 branch. @HanabishiRecca, are you using mold `main`?

No, I tested on the release. If that's the same already fixed thing, very well then.

At least now you are aware that it also affects stable 6.6 and we need fixes to be released soon.

**Comment by thesamesam** [comment]
Could you make a new release please, or should I cherry-pick this fix on top of 2.4.0 for Gentoo?

**Comment by rui314** [comment]
I'll make another release, but please wait for a few weeks. I'm fixing other issues now. If you are in hurry, you may want to build mold yourself or download the most recent binary from GitHub Actions (https://github.com/rui314/mold/actions/runs/7856596446).

**Comment by thesamesam** [comment]
I was just looking for consent to backport it, in case you thought it was unsafe to do so. Is it fine?

**Comment by rui314** [comment]
It's probably a bit too risky to just cherry pick. Version script has caused very subtle issues before (this is one of them), so it needs rigorous testing. I usually build all Gentoo packages with mold before making a release. Until doing it, I'm not 100% sure if this would be fine at the moment.

**Comment by thesamesam** [comment]
OK, thanks!
