### ISSUE TITLE
mold working but only with -fPIC

### ISSUE THREAD

**Issue by cruisercoder** [rui314/mold#116]
Mold on RHEL devtools-9 works but only when add -fPIC to specify position independent code.  Is there a way around having to add -fPIC?

**Comment by rui314** [comment]
Could you copy-paste the error message if you get one? I need to know why it is failing.

**Comment by cruisercoder** [comment]
Here's one of the errors: they are all similar.  It looks like it's all related to std library linkage. 

mold: obj/util/string/test_source/StringTest.o:(.rodata.cst8): R_X86_64_64 relocation against symbol `vtable for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >' can not be used; recompile with -fPIC

**Comment by rui314** [comment]
Let me reproduce the issue using Docker. What is the RHEL version? Is that CentOS or something?

**Comment by cruisercoder** [comment]
CentOS Linux release 7.8.2003 (Core).  Options: -O3 -msse3 -mavx2

**Comment by rui314** [comment]
I set up a Docker environment with CentOS 7, installed devtoolset-9 into it and tried to compile a "hello world" program using gcc and mold. It looks like it's working as shown below.

```
[root@a3480d2365e7 tmp]# cat hello.c
#include <stdio.h>
int main() { printf("Hello world\n"); }
[root@a3480d2365e7 tmp]# /mold/mold -run cc -o hello hello.c -fno-PIC
[root@a3480d2365e7 tmp]# ./hello
Hello world
```

To further investigate your issue, I think I need a program that cannot be built in your env that I can build locally.

**Comment by cruisercoder** [comment]
It looks like it was stale libraries on our side.  Thanks for checking this.

**Comment by cruisercoder** [comment]
Issue is still present.  Gathering more information...

**Comment by cruisercoder** [comment]
Here's a program that should reproduce:

`
echo -e '#include <iostream>\nclass Stream : public std::ostream { public: Stream() {} };\nint main(int argc, char* argv[]) { Stream stream; }' > hello.cc
scl enable devtoolset-9 -- g++ -Bmold -o hello hello.cc -fno-PIC
`

Error:

mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `typeinfo for std::ostream' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `std::basic_ostream<char, std::char_traits<char> >::~basic_ostream()' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `std::basic_ostream<char, std::char_traits<char> >::~basic_ostream()' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `typeinfo for std::ostream' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `virtual thunk to std::basic_ostream<char, std::char_traits<char> >::~basic_ostream()' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTC6Stream0_So): R_X86_64_64 relocation against symbol `virtual thunk to std::basic_ostream<char, std::char_traits<char> >::~basic_ostream()' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTI6Stream): R_X86_64_64 relocation against symbol `vtable for __cxxabiv1::__si_class_type_info' can not be used; recompile with -fPIC
mold: /tmp/cczoeY7K.o:(.rodata._ZTI6Stream): R_X86_64_64 relocation against symbol `typeinfo for std::ostream' can not be used; recompile with -fPIC
collect2: error: ld returned 1 exit status

**Comment by brenoguim** [comment]
I can also see this issue, but I hit that trying to link mold with mold. I changed the makefile of mold to add -Bpath/to/another/mold and saw the same types of error messages.

**Comment by rui314** [comment]
Thank you for the update! With that instruction, I could reproduce the issue, and it indeed looks like a bug in mold. I'll commit a fix soon.

**Comment by rui314** [comment]
I believe the previous change fixed the issue. Can you please confirm?

**Comment by cruisercoder** [comment]
Looks good to me.  Thanks!
