### ISSUE TITLE
do applications with LLVM's polly flag and thilto, and linked with mold still segfault?

### ISSUE THREAD

**Issue by formula-spectre** [rui314/mold#1164]
pretty much the title. I stumbled across this a long while ago, maybe 2 years? have there been progress ever since? iirc mold couldn't handle thinlto IR or something else about it, so it lead to broken final binaries. is it fixed now?

**Comment by rui314** [comment]
What is polly flag? We need a small reproducer to demonstrate the issue.

**Comment by formula-spectre** [comment]
https://polly.llvm.org/

**Comment by formula-spectre** [comment]
but don't focus on polly because i think the problem was thinlto IR

**Comment by rui314** [comment]
At least I can build a trivial "Hello world" program using clang+thinlto+mold.

**Comment by formula-spectre** [comment]
trivial, but i'm talking full blown day-to-day use applications, iirc the one crashing was either `zpool` or `telegram-desktop`

**Comment by formula-spectre** [comment]
i mean, since i'm knee deep I can try again and tell you what segfaults, since i have the power of zfs, if this can help the project i'm more than willing to break my stuff!

**Comment by rui314** [comment]
I want something like "I build this program with the following build options and then the output failed due to the following error" so that I can try the same thing myself to reproduce the issue. Do you mind if you provide me the information?

**Comment by formula-spectre** [comment]
uh, sorry but since this happened a long time ago I can't really.. but I will do this:
I will close this issue, make frequent snapshots and then start to build with thinlto and mold, and as soon as something sefgaults I'll open an issue, with detailed instructions of my CFLAGS, what I did, what happened, stack trace and so on..  
deal?

**Comment by rui314** [comment]
Yes, please reopen when you succeed to reproduce the issue.

**Comment by formula-spectre** [comment]
gotcha!

**Comment by formula-spectre** [comment]
just to be clear before I jump in the abyss: mold **does** support thinlto/thinlto's IR code right?

**Comment by rui314** [comment]
It does.

**Comment by formula-spectre** [comment]
hey sorry if I keep coming back to this issue, I don't want to open a new one because i think it's not needed;  but can you explain this:
`mold: error: /var/tmp/portage/sys-devel/clang-17.0.6/temp/lto-llvm-190bdc.o:(.text.startup): R_X86_64_PC32 relocation at offset 0x401 against symbol `clang::format::BreakableBlockComment::ContentIndentingJavadocAnnotations' can not be used; recompile with -fPIC`
this happened when I tried to compile clang-17 with mold as a linker, and it spat this for a bunch of lines; I fixed by simply adding `-fPIC` to my `CFLAGS`, but i'm curious; why? whatdoes Position Independent code has to do siwth lto and symbols of `.o` files?
