### ISSUE TITLE
-Bsymbolic-non-weak-functions not a valid flag in mold

### ISSUE THREAD

**Issue by needlesslygrim** [rui314/mold#1178]
```
mold: fatal: unknown command line option: -Bsymbolic-non-weak-functions
```

This flag doesn't seem to be supported in Mold, but [is in `lld`](https://reviews.llvm.org/D102570). Is it unsupported on purpose?

**Comment by rui314** [comment]
It's now supported. 7d17aa83ebeabeea1626fd21d94774993b5692b3
