### ISSUE TITLE
mold refused to link GP-setup code for RISC-V

### ISSUE THREAD

**Issue by piggynl** [rui314/mold#1182]
### Description

While building musl for riscv64 with mold as linker, mold refused to link the GP-setup code.

### A minimal reproduce

This assembly snippet is created from [`arch/riscv64/crt_arch.h`](https://git.musl-libc.org/cgit/musl/tree/arch/riscv64/crt_arch.h?h=v1.2.4&id=f5f55d6589940fd2c2188d76686efe3a530e64e0), which is included by [`ldso/dlstart.c`](https://git.musl-libc.org/cgit/musl/tree/ldso/dlstart.c?h=v1.2.4&id=f5f55d6589940fd2c2188d76686efe3a530e64e0). Save this snippet as `dlstart.s`.

```asm
.section .sdata,"aw"

.text
.global _dlstart
.type _dlstart,%function
_dlstart:
.weak __global_pointer$
.hidden __global_pointer$
.option push
.option norelax
        lla     gp, __global_pointer$
.option pop
        mv      a0, sp
.weak _DYNAMIC
.hidden _DYNAMIC
        lla     a1, _DYNAMIC
        andi    sp, sp, -16
        tail    _dlstart_c

.type _dlstart_c,%function
_dlstart_c:
        # The actual code here does not matter.
        ret
```

Then compile and link.

```
$ clang --target=riscv64 -march=rv64g dlstart.s -c -o dlstart.o
$ ld.lld -e _dlstart -shared dlstart.o -o fake_libc.so # no error
$ mold -shared -e _dlstart dlstart.o -o fake_libc.so
mold: error: dlstart.o:(.text): R_RISCV_PCREL_HI20 relocation at offset 0x0 against symbol `__global_pointer$' can not be used; recompile with -fno-PIC
```

Note that the GP-setup code in `_dlstart` do follows [the recommended way to initialize the gp register in RISC-V ELF specification](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/v1.0/riscv-elf.adoc#user-content-gp-relax), and the PIC option for compiler doesn't affect the content of `dlstart.o`.

### More information

With `git bisect` I found mold refuses to link such input after 5fb6091fb7242a5654729cb52295324166d693dc.

**Comment by rui314** [comment]
Thank you for your report. Maybe we should just revert the commit that broke your test case.
