### ISSUE TITLE
LDPT_REGISTER_CLAIM_FILE_HOOK_V2 missing from LTO support

### ISSUE THREAD

**Issue by tob2** [rui314/mold#1188]
To fix an issue with LTO used for offload support with GCC, a new enum was added: LDPT_REGISTER_CLAIM_FILE_HOOK_V2

The change is that the hook function now also passes a boolean whether the symbol was only found or is actually used.

For offloading w/o host LTO, it happened that the linker sent a file from an .a file to the lto wrapper of the compiler, in which offloading code was, but then didn't link that file on the host as the symbol was unused. But as being passed to the wrapper, the offloading code was produced, causing both pointless offload code and worse a mismatch in the number of entries of a var/func array between host vs. offload side.

Solution was as mentioned above to add a boolean argument.

A description can be found at
https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=b21318bd2c29fcca8f99c1de7facdaa5cb2e66e2

For GCC, see also the related problem report in GCC: https://gcc.gnu.org/PR109128 with example and commits on the compiler side.

Direct link to the GCC+Binutils patch submission and commits inside that GCC issue:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109128#c7

**Comment by tob2** [comment]
* The following is needed on the **header side. — The additional 'int' argument is a boolean ('known_used').
* TODO:  the actual implementation in `elf/lto-unix.cc`

```diff
--- a/elf/lto.h
+++ b/elf/lto.h
@@ -49,2 +49,3 @@ enum PluginTag {
   LDPT_GET_API_VERSION,
+  LDPT_REGISTER_CLAIM_FILE_HOOK_V2
 };
@@ -159,2 +160,3 @@ typedef PluginStatus OnloadFn(PluginTagValue *tv);
 typedef PluginStatus ClaimFileHandler(const PluginInputFile *, int *);
+typedef PluginStatus ClaimFileHandlerV2(const PluginInputFile *, int *, int);
 typedef PluginStatus AllSymbolsReadHandler();
```

**Comment by rui314** [comment]
Turns out that we don't need this function to support GCC offloading.
