### ISSUE TITLE
Update the performance comparison in the README, and include the GNU ld (BFD) linker

### ISSUE THREAD

**Issue by dralley** [rui314/mold#1189]
There has been a lot of performance work done on GNU ld over the past year, with the result that the very newest versions (2.41+) are quite a bit faster than GNU gold and competitive with (though still not as fast as) single-threaded `mold`.  Obviously it still loses by a significant margin to multi-threaded `mold`.

https://www.youtube.com/watch?v=h5pXt_YCwkU

Given GNU `gold`'s relative lack of maintenance and the fact that ld.bfd is the default linker on most Linux distributions, it probably makes sense to swap the `gold` comparison with GNU ld, or at least include the latter as well.

Note: The only mainstream-ish distro that currently has ld 2.41 are Arch and Debian Testing, so it might make sense to wait a few months until Fedora 40 and Ubuntu 24.04 also make it available.

**Comment by rui314** [comment]
That makes sense. I'm also genuinely curious how much faster GNU ld is now. Let me re-run benchmarks.

**Comment by rui314** [comment]
I built GNU ld from source and ran a few benchmarks with it, along with mold, lld and gold. In my test environment, GNU ld is still consistently slower than gold, though I believe the gap between GNU ld and GNU gold has narrowed down quite a bit indeed. GNU ld couldn't build a Chromium binary. You can see the raw output of the benchmarks here: https://gist.github.com/rui314/85c9951bca8f51be90b5f8e84f65d895

**Comment by gruenich** [comment]
This issue can be closed, as the README.md is accordingly updated?

**Comment by dralley** [comment]
Yup
