### ISSUE TITLE
Ignored flag -m is not ignored

### ISSUE THREAD

**Issue by Diegovsky** [rui314/mold#119]
mold 0.9.6 (e942f5e28e7cbc22ba5d3486e108661ef6ceb19a; compatible with GNU ld and GNU gold)

I tried compiling some rust code using mold and I get an error saying `mold: unknown -m argument: 64`. Upon some investigation, mold's `--help` option says (emphasis mine):
```
...
  -m EMULATION                Ignored
...
```

However it seems the flag is not being ignored. On #113 it was said mold does not support wasm, that being checked by the `-m` flag. I think this might be a problem in the help page because the flag is indeed used.

**Comment by rui314** [comment]
`-m`'s argument is usually something like `elf_x86_64` or `elf_i386`, so if just `64` is passed as an argument for `-m`, something must be wrong. What program are you trying to build?

**Comment by Diegovsky** [comment]
Just a personal rust project. I haven't configured anything besides setting the linker to mold. I'll try it again just to make sure.
