### ISSUE TITLE
ENOMEM after trying to mmap several exabytes of memory

### ISSUE THREAD

**Issue by crosdahl** [rui314/mold#1195]
Passing a relocatable build with `gcc -g3` crashes due to a bogus mmap call, minimal example:
crt.c:
```
/* Empty file, content doesn't seem to matter. */
```

build steps:
```
gcc -o crt crt.c -g3 -fuse-ld=mold -r
gcc -nostdlib -fuse-ld=mold -L. -l:crt
```

The second command fails due to being unable to allocate memory. stracing it  with
`strace -f gcc -nostdlib -fuse-ld=mold -L. -l:crt 2>&1 | grep ENOMEM` shows:
`[pid 22571] mmap(NULL, 360287970189658312, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = -1 ENOMEM (Cannot allocate memory)`.

It only crashes with `gcc -g3` (tried version 13.2.1 and current trunk),  using `clang` or `-g` compiles sucessfully.

**Comment by rui314** [comment]
I couldn't reproduce the issue in my environment. Can you upload your `crt.o` and `crt`?

**Comment by crosdahl** [comment]
[bug.zip](https://github.com/rui314/mold/files/14322605/bug.zip)

**Comment by rui314** [comment]
Should be fixed in the above commit.
