### ISSUE TITLE
On riscv64 mold seems to incorrectly interpret symbolic link /lib64/lp64d -> .

### ISSUE THREAD

**Issue by rwmjones** [rui314/mold#1197]
`mold 2.4.0`

One of the tests fails with:

```
++ mkdir -p out/test/elf/riscv64/repro
+ cat
+ cc -c -o out/test/elf/riscv64/repro/a.o -xc -
+ rm -rf out/test/elf/riscv64/repro/exe.repro out/test/elf/riscv64/repro/exe.repro.tar
+ cc -B. -o out/test/elf/riscv64/repro/exe out/test/elf/riscv64/repro/a.o
+ '[' -f out/test/elf/riscv64/repro/exe.repro.tar ']'
+ cc -B. -o out/test/elf/riscv64/repro/exe out/test/elf/riscv64/repro/a.o -Wl,-repro
mold: fatal: cannot open /lib64/lib64/lp64d/crt1.o: No such file or directory
collect2: error: ld returned 1 exit status
```

`/lib64/lib64/...` is an invalid path (the correct path should be `/lib64/lp64d/crt1.o`.

Looking at the build output, it seems to get confused over our symbolic link from `/lib64/lp64d -> .` (note: not a recursive link):
```
$ ls -l /lib64/lp64d
lrwxrwxrwx 1 root root 1 Jan 16 00:00 /lib64/lp64d -> .
```

The build system of mold is complicated to say the least, so I'm just going to tar up the whole thing and put it here for examination: 
http://oirase.annexia.org/tmp/mold-failure.tar.xz
(I deleted some binary files over 10M in size otherwise the whole tarball would have been many gigabytes in size)

Based on similar issues we've had, you might need to use `realpath` when manipulating paths that can contain symlinks (rather than string manipulation).

**Comment by rwmjones** [comment]
@davidlt

**Comment by rwmjones** [comment]
Build log: http://fedora.riscv.rocks/kojifiles/work/tasks/5948/1585948/build.log

**Comment by rui314** [comment]
Can you try again with the above commit?

**Comment by rwmjones** [comment]
> Can you try again with the above commit?

Yes that has fixed it, thanks.
