### ISSUE TITLE
Error running Mold-compiled project on ppc64le

### ISSUE THREAD

**Issue by rjzak** [rui314/mold#1203]
I compiled [VirusTotal/c-vtapi](https://github.com/VirusTotal/c-vtapi) with `mold -run make -j60`. The compilation went fine.

I then compiled [VirusTotal/qt-virustotal-uploader](https://github.com/VirusTotal/qt-virustotal-uploader) with the same mold command, and it went fine.

But trying to run `VirusTotalUploader`, it fails: `VirusTotalUploader: symbol lookup error: /usr/local/lib/libcvtapi.so.1: undefined symbol: _restgpr0_31`. Re-compiling just `c-vtapi` with the default linker allowed `VirusTotalUploader` to run fine.

A simple Google [search](https://www.google.com/search?client=firefox-b-1-e&q=_restgpr0_31) shows powerpc-related results, like [saving registers](https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#SAVEREG), leading me to think it's a powerpc64le thing.

This is with version 6d8e6afbf208e4aedda88fc44c9755e997f8ac91, Debian 12.5.

**Comment by rui314** [comment]
Please try again with the above commit.

**Comment by rjzak** [comment]
Works! Thank you.
