### ISSUE TITLE
`using mold with cargo not working anymore`

### ISSUE THREAD

**Issue by overtube** [rui314/mold#1214]
**RUSTC WIKI SECTION**
`linker-flavor`
This flag controls the linker flavor used by rustc. If a linker is given with the `-C linker flag`, then the linker flavor is inferred from the value provided. If no linker is given then the linker flavor is used to determine the linker to use. Every rustc target defaults to some linker flavor. Valid options are:

```
em: use Emscripten emcc.
gcc: use the cc executable, which is typically gcc or clang on many systems.
ld: use the ld executable.
msvc: use the link.exe executable from Microsoft Visual Studio MSVC.
wasm-ld: use the wasm-ld executable, a port of LLVM lld for WebAssembly.
ld64.lld: use the LLVM lld executable with the -flavor darwin flag for Apple's ld.
ld.lld: use the LLVM lld executable with the -flavor gnu flag for GNU binutils' ld.
lld-link: use the LLVM lld executable with the -flavor link flag for Microsoft's link.exe.
```

**Comment by overtube** [comment]
**:)** nothing terrible, is just feedback about some strange behavior of crab compiler.
passing `-C -fuse-ld=mold` flag for using that linker to `makepkg.conf` and his not seen at verbosive output, but before **rustc** some update, that can worked fine and seen in verbosive mode when execute `cargo build` so maybe need 
also create issue on crabs compiler maybe.

**Comment by overtube** [comment]
`https://github.com/rust-lang/rust/issues/119332`

**Comment by overtube** [comment]
**also** `-C link-arg=-fuse-ld=mold` can't work too
`https://github.com/rust-lang/rust/issues/119332`

**Comment by overtube** [comment]
:) nothing terrible, is just feedback about some strange behavior of crab compiler.
passing -C -fuse-ld=mold flag for using that linker to makepkg.conf and his not seen at verbosive output, but before rustc some update, that can worked fine and seen in verbosive mode when execute cargo build so maybe need
also create issue on crabs compiler maybe. 
But already created : 
**also** -C `link-arg=-fuse-ld=mold` can't work too
`https://github.com/rust-lang/rust/issues/119332`

**Comment by bluss** [comment]
Your bug report is not very clear, but here's an example of a working configuration for using mold with cargo: (~/.cargo/config.toml)

```toml
[target.x86_64-unknown-linux-gnu]
linker = "gcc-12"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```

You'll need to set `linker` to some compiler command that will accept the flag set in rustflags. As noted many other places, gcc wants just "mold" and not a full path for -fuse-ld

Or is there something wrong when using this configuration?

**Comment by overtube** [comment]
bluss: thank you
