### ISSUE TITLE
Concurrent map size is not large enough in gdb-index.cc

### ISSUE THREAD

**Issue by tupos** [rui314/mold#1219]
Hello,

during linking of our libraries we face an issue with the size of the ConcurrentMap here https://github.com/rui314/mold/blob/main/elf/gdb-index.cc#L679
```
ConcurrentMap<MapValue> map(estimator.get_cardinality() * 3 / 2);
```
and segfault in release build. When I recompiled into the debug build I saw assertion failure on the map size.
When I increased a factor 3/2 to 4/2=2 the crash and assertion do not trigger anymore.

Therefore I guess that the map size is not enough for our binaries.

Could you please have a look what is the best solution for the problem?

Thanks.

**Comment by rui314** [comment]
Can you try again with the latest release? We fixed the issue in the latest release.

**Comment by tupos** [comment]
Hello, yes indeed with the 2.30 it does not crash. I guess it is due to c60d1d0.

I think than the issue can be closed.

Thanks for the quick reply.
