### ISSUE TITLE
mold 2.30.0 test failure on alpinelinux

### ISSUE THREAD

**Issue by bl4ckb0ne** [rui314/mold#1221]
The CI pipeline for the 2.30.0 upgrade is failing for several arch: x86_64, riscv64 and ppcle64. 

Here are the failing tests:

ppcle64:

```
        70 - ppc64le-execute-only (Failed)
```

ricv64:

```
        106 - riscv64-ifunc-address-equality-exported (Failed)
	107 - riscv64-ifunc-address-equality (Failed)
	108 - riscv64-ifunc-alias (Failed)
	109 - riscv64-ifunc-dlopen (Failed)
	110 - riscv64-ifunc-dso (Failed)
	111 - riscv64-ifunc-dynamic (Failed)
	113 - riscv64-ifunc-funcptr (Failed)
	114 - riscv64-ifunc-noplt (Failed)
	115 - riscv64-ifunc-static-pie (Failed)
	116 - riscv64-ifunc-static (Failed)
```

x86_64:

```
         14 - x86_64-x86_64_init-array-readonly (Failed)
```

Let me know what do you need from the CI to help you with these issues.

**Comment by rui314** [comment]
I couldn't reproduce the issue with alpine:latest Docker image. How did you test it?

**Comment by bl4ckb0ne** [comment]
On the gitlab.alpinelinux.org CI [1]

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62444

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/pipelines/220087

**Comment by bl4ckb0ne** [comment]
x86_64 is green, seems to be a fluke, but riscv64 and ppcle64 are still there.

**Comment by bl4ckb0ne** [comment]
@rui314 thanks for the patch. The `riscv64` build is green but the issue for `ppcle64` persists.
