### ISSUE TITLE
linux/ppc64el: fails to build LLVM with `./elf/thunks.cc:257: void mold::elf::OutputSection<E>::create_range_extension_thunks(mold::elf::Context<E>&) [with E = mold::elf::PPC64V2]: Assertion `thunk->size() < max_thunk_size' failed.`

### ISSUE THREAD

**Issue by sylvestre** [rui314/mold#1224]
using mold:
2.4.1+dfsg-1  (i will try with 2.30 but i don't see any potential fix in the release notes))

Full log:
https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-18&arch=ppc64el&ver=1%3A18.1.2-1&stamp=1710939656&raw=0

**Comment by rui314** [comment]
Just to confirm: I can reproduce the issue if I build Clang with mold on ppc64le, right?

**Comment by sylvestre** [comment]
I also see it on arm64:
https://llvm-jenkins.debian.net/job/llvm-toolchain-18-binaries/architecture=arm64,distribution=unstable,label=arm64/73/console

**Comment by rui314** [comment]
It is not easy to reproduce the issue for me because it involves lots of Debian-specific toolings. Could you reproduce the issue just by building LLVM from source without using Debian-specific tools?

**Comment by sylvestre** [comment]
Just running the cmake will all the arg should be good but I will try to make a test case. Any recommendation on what to do next?
Thanks

**Comment by rui314** [comment]
I fired up debian:unstable docker image, installed build-deps for clang-18, installed mold, checked out the llvm repo from github, and then copy-and-pasted the cmake command line, but it built just fine. So I think there's a hidden condition to reproduce the issue. Ideally, I want to know a procedure to reproduce the issue with the docker image.

**Comment by jcelerier** [comment]
I'm seeing the same thing on fedora 40 aarch64 (asahi linux)

**Comment by rui314** [comment]
I need a reproducer to debug it. Is your program open-source?

**Comment by jcelerier** [comment]
Here's a small reproducer:
    
[data.zip](https://github.com/rui314/mold/files/15450594/data.zip)

 ld.mold -EL --hash-style=gnu --build-id --eh-frame-hdr -m aarch64linux -shared obj.o lib.a

**Comment by rui314** [comment]
Please try again with git head.
