### ISSUE TITLE
make install does not install libblake3.so

### ISSUE THREAD

**Issue by fefe17** [rui314/mold#1238]
This is the current git built on Linux in a fresh build dir.

After the make install, I get a mold binary that does not run, because libblake3.so.0 can't be found by the dynamic linker.
In the mold build tree, I can see

build/third-party/blake3/c/libblake3.pc
build/third-party/blake3/c/libblake3.so.1.4.1
build/third-party/blake3/c/libblake3.so.0
build/third-party/blake3/c/libblake3.so

But apparently make install forgets to actually install it.
I ran cmake with -DBUILD_SHARED_LIBS=ON and -DCMAKE_BUILD_TYPE=release as that is my system-wide cmake default.

**Comment by rui314** [comment]
Thank you for your report. The issue should be resolved by the above commit.
