### ISSUE TITLE
not able to compile in windows .

### ISSUE THREAD

**Issue by Abhinavpatel00** [rui314/mold#1241]
can someone please tell how to compile mold on windows i tried using clang as it is given in cmake that msvc doesnt compile it but it is not working 

![image](https://github.com/rui314/mold/assets/121427766/8e4c2599-fad9-42fb-86bf-bd140aa10442)

**Comment by rui314** [comment]
We have a Windows buildbot hosted on GitHub Actions, so you may want to take a look at it as to how it is compiled. However, even if you successfully build mold on Windows, you can't build Windows programs using mold. Only you can do instead is to cross-build Linux binaries on Windows. I'm not sure if that's you really want.

**Comment by Abhinavpatel00** [comment]
why its so hard even for a awesome project like mold to work on windows

**Comment by rui314** [comment]
Because the file format is fundamentally different.
