### ISSUE TITLE
--wrap support for MacOS

### ISSUE THREAD

**Issue by MageSlayer** [rui314/mold#1243]
Hi

Looks like --wrap support for MacOS is missing.
It seems it should easy to match ELF support here.

I'd like to know, if it's something that would be accepted as PR?

**Comment by Alcaro** [comment]
Last time I checked, LD_PRELOAD was not functional on mac, and I couldn't find any working replacement.

If one has been added since I last looked (about six years ago), or you can find something I couldn't, that sounds welcome.

**Comment by MageSlayer** [comment]
Hm.
Looks like MacOS support already gone.
Should be moved to sold as I guess?
https://github.com/bluewhalesystems/sold/issues/50

Sorry for noise.

**Comment by rui314** [comment]
Yes but no. We are no longer developing the linker for the Apple platforms.
