### ISSUE TITLE
Is -z x86-64-vX supported?

### ISSUE THREAD

**Issue by jfikar** [rui314/mold#1263]
I'm compiling ruby-3.2.3 and I get an error during configure:
```
checking whether LDFLAGS is valid
mold: warning: unknown command line option: -z x86-64-v2
```
my LD_FLAGS contain `-Wl,-z,x86-64-v2`, which is valid for ld.bfd. Is it a valid option for mold as well?

```
$ mold --version
mold 2.31.0 (compatible with GNU ld)
```

**Comment by rui314** [comment]
Currently, no, but we need to support them.
