### ISSUE TITLE
MSYS2/UCRT64: LINKER_TYPE 'MOLD' is unknown or not supported by this toolchain.

### ISSUE THREAD

**Issue by Tyler799** [rui314/mold#1267]
GCC Version: 14.1.0
CMAKE Version: 3.29.3
MOLD Version: 2.30.0 (mingw-w64-ucrt-x86_64-mold)

I am attempting to swap in Mold as the linker for an existing cmake project. I'm running cmake using:

`-DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold"`

(I have also tried setting CMAKE_LINKER_TYPE instead, same issue)

That causes the following error:

```
CMake Error in C:/Users/tyler.shellberg/Documents/build/myProject/CMakeFiles/CMakeScratch/TryCompile-4y8fvv/CMakeLists.txt:
  LINKER_TYPE 'MOLD' is unknown or not supported by this toolchain.
```

The minimum cmake is set to: `cmake_minimum_required(VERSION 3.16...3.29)` and the error happens the moment it hits the `project` keyword.

`mold` is in my path.

**Comment by rui314** [comment]
mold supports the ELF file format only; it does not support PE/COFF that is used by Windows. You cannot use mold for MinGW.

**Comment by rui314** [comment]
I can't speak for them, but mold can still be used to cross compile Linux binaries on Windows.

**Comment by Tyler799** [comment]
I'll go ahead and close, and look into Sold instead since it's open these days

**Comment by Alcaro** [comment]
Sold isn't very useful on windows either, it can only create mac binaries

**Comment by Tyler799** [comment]
> Sold isn't very useful on windows either, it can only create mac binaries

Weird, I thought in original discussions Windows support was a main point.

Damn, so there's nothing out there for Windows binaries?
