### ISSUE TITLE
mold: mold-wrapper.so is missing

### ISSUE THREAD

**Issue by installgentoo** [rui314/mold#127]
Basically you look for mold-wrapper in hardcoded ../../lib
On gentoo we have lib and lib64(honestly i don't know how exactly these rules work, has smth to do with 32 abi), mold goes into lib64.
Maybe similar situation exists on other distros.

Perhaps allow providing path to it in an argument?

**Comment by rui314** [comment]
If you run `make install`, mold-wrapper.so will be installed to `$PREFIX/lib`, so I guess Gentoo modifies the default Makefile so that it is installed to `lib64`. Are you using Gentoo's mold package?

**Comment by installgentoo** [comment]
Yes, it does.
"	sed -i \
		-e '/	strip/d' \
		-e '/	gzip/d' \
		-e "s:\$(DEST)/lib:\$(DEST)/$(get_libdir):" \
		Makefile || die"

Yes i do.

One thing that i got impression off, the error is confusing, only when i searched it in the sources did i realise what was happening.

**Comment by rui314** [comment]
Can you report a bug to Gentoo's package? The path to search `mold-wrapper.so` is hard-coded here  (https://github.com/rui314/mold/blob/v0.9.6/elf/subprocess.cc#L275). If you modify the Makefile, you also need that line too.

In the next release, I'll add LIBDIR variable to Makefile so that you don't have to apply a local patch to the C source file.

**Comment by installgentoo** [comment]
Already did.

**Comment by thesamesam** [comment]
Please do cross-link bugs in future if you can (the downstream bug is [here](https://bugs.gentoo.org/823653)). Thanks for the report both downstream and here. I'll fix the Gentoo package now.

**Comment by thesamesam** [comment]
I think this can be closed now. It's fixed both in Gentoo (in the earlier release and in 1.0.0 and fixed upstream in 1.0.0 too.
