### ISSUE TITLE
Very slow symbol lookup speed with gdb

### ISSUE THREAD

**Issue by user202729** [rui314/mold#1278]
To reproduce:

* assume `ld` is symlinked to `mold` somewhere
* [compile gcc](https://gcc.gnu.org/install/build.html)

	```sh
	git clone --depth 1 --single-branch git://gcc.gnu.org/git/gcc.git
	cd gcc
	mkdir build
	cd build
	../configure --enable-languages=c,c++ --disable-multilib --disable-bootstrap \
	  --disable-libstdcxx \
	  CFLAGS="-g3 -gdwarf-2 -Og" \
	  CPPFLAGS="-g3 -gdwarf-2 -Og" \
	  CXXFLAGS="-g3 -gdwarf-2 -Og"
	make
	```

* try to debug `cc1plus` as follows

	```sh
	time gdb ./gcc/cc1plus -ex 'b gimple-range-gori.cc:1510' -ex 'q'
	```

* see that it takes ≈ 9 seconds
* now unlink `ld` (it should point to GNU ld)
* recompile

	```sh
	rm ./gcc/cc1plus
	( cd gcc; time make cc1plus )
	```

	(will take 15 second to link, unlike mold which only take 1 second)

* rerun

	```sh
	time gdb ./gcc/cc1plus -ex 'b gimple-range-gori.cc:1510' -ex 'q'
	```

	now it only take 3 second

Any idea why? (could also be gdb's fault though)

Searching on gdb's bug database, there is https://sourceware.org/bugzilla/show_bug.cgi?id=30008 which talks about gdb being unable to read gdb_index generated by mold (the issue is still open).
i

**Comment by rui314** [comment]
What is your mold version? I tried that on Ubuntu 20.04 and Ubuntu 24.04 in Docker, and I couldn't see the difference (e.g. 2.287s vs. 0m2.169s.)

**Comment by user202729** [comment]
@rui314 Latest master (at the time of reporting).

Any idea how might I debug it? (I try running gdb under perf record to make a flamegraph maybe?)

**Comment by user202729** [comment]
Strangely enough, the issue is no longer reproducible for me.

Guess I'll close it for now.
