### ISSUE TITLE
Support resolving `@executable_path`

### ISSUE THREAD

**Issue by thii** [rui314/mold#128]
When linking a Mach-O binary with `-Wl,-rpath,@executable_path/some/path`, mold fails to link with the following error

```
mold: cannot open executable_path/some/path
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rui314** [comment]
Sure, I'll do that. mold for macOS is pre-alpha and isn't expected to be used by anyone at this moment. I'm implementing features one by one.

**Comment by rui314** [comment]
https://github.com/rui314/mold/issues/189
