### ISSUE TITLE
Support `libdep` plugin

### ISSUE THREAD

**Issue by haampie** [rui314/mold#1282]
Binutils 2.36 and onwards support metadata for dependencies of static libraries through a text file `__.LIBDEP`:

```shell
$ ar cr libf.a f.o "--record-libdeps=-L/foo/bar -lg"

$ ar t libf.a 
f.o
__.LIBDEP

$ ar x libf.a __.LIBDEP

$ cat __.LIBDEP 
-L/foo/bar -lg
```

Linkers ignore unrecognized file formats in archives, so old linkers do not choke on static libs with metadata.

It can be used like this:

```
$ gcc test.c -L. -lf -Wl,--plugin,<path to>/bfd-plugins/libdep.so
got deps for library ./libf.a: -L/foo/bar -lg
```

and effectively turns the link line into

```
$ gcc test.c -L. -lf -L/foo/bar -lg
```

which is very convenient.

It's simpler than resolving shared libraries.

Can this be supported in mold?

**Comment by rui314** [comment]
I think we should support that unless it is too difficult to do so. Let me take a look.

**Comment by haampie** [comment]
It looks like binutils supports basic quoting:

https://github.com/bminor/binutils-gdb/blob/master/ld/libdep_plugin.c#L136-L212

So `-L "/hello 'world'"` and `-L '/hello "world"'` are parsed as a flag and an argument.

Escaping with `\` looks broken to me :thinking:  https://github.com/bminor/binutils-gdb/blob/6a4f078b5b8b442f474a8af804c316783d216a4e/ld/libdep_plugin.c#L165-L169

**Comment by haampie** [comment]
Ok, maybe nobody ever uses `libdep` cause I struggle to make the `-L` flag work.

Here's a simple example where `libg.a` cannot be located, even though `libf.a` specifies the correct `-L` flag:

```makefile
LDFLAGS := -Wl,--plugin,/usr/lib/x86_64-linux-gnu/bfd-plugins/libdep.so

.PHONY: all clean

all: exe

f/f.o:
	mkdir -p f
	printf 'extern int g(); int f(){ return g(); }' | $(CC) -c -xc - -o $@

f/libf.a: f/f.o g/libg.a
	$(AR) crl '-L$(CURDIR)/g -lg' $@ $<

g/g.o:
	mkdir -p g
	printf 'int g(){ return 4; }' | $(CC) -c -xc - -o $@

g/libg.a: g/g.o
	$(AR) cr $@ $<

exe: f/libf.a
	printf 'extern int f(); int main() { return f(); }' | $(CC) $(LDFLAGS) -xc - -o $@ -Lf -lf

clean:
	rm -f exe f/f.o f/libf.a g/g.o g/libg.a
```

```
$ make
mkdir -p f
printf 'extern int g(); int f(){ return g(); }' | cc -c -xc - -o f/f.o
mkdir -p g
printf 'int g(){ return 4; }' | cc -c -xc - -o g/g.o
ar cr g/libg.a g/g.o
ar crl '-L/tmp/tmp.iR9g9xEukO/g -lg' f/libf.a f/f.o
printf 'extern int f(); int main() { return f(); }' | cc -Wl,--plugin,/usr/lib/x86_64-linux-gnu/bfd-plugins/libdep.so -xc - -o exe -Lf -lf
got deps for library f/libf.a: -L/tmp/tmp.iR9g9xEukO/g -lg
/usr/bin/ld: f/libf.a(f.o): in function `f':
<stdin>:(.text+0xe): undefined reference to `g'
```

If I set `-Lg/` in the LDFLAGS it works... so, looks like the plugin fails to register the search path.

```
make LDFLAGS='-Wl,--plugin,/usr/lib/x86_64-linux-gnu/bfd-plugins/libdep.so -Lg'
```

**Comment by rui314** [comment]
If no one uses it and bfd's implementation is broken, we don't want to support it. I wonder why it is supported via the plugin mechanism -- bfd could have supported as a native feature.

**Comment by haampie** [comment]
I've submitted a fix for the parser here https://sourceware.org/pipermail/binutils/2024-June/134936.html. Never contributed to binutils before, do you know anyone who could review that?

Will look into the bfd issue later when I have time.

**Comment by haampie** [comment]
I'm closing this for now. In my opinion the libdep.so plugin is poorly designed and not worth implementing in mold until it has improved.

I still wish there was a way to make static linking resolve dependencies like in dynamic linking though. But the way binutils is doing it is far from optimal.

I suggested in their mailing list to:

1. Change the API of `ar` from `ar --record-libdeps="-Lfoo -lbar"` to `ar --libdep-arg=-Lfoo --libdep-arg=lbar` or similar, so that users don't have to worry about double quoting (once for the shell, then for the linker). The arguments could've been stored as consecutive C-strings in the archive metadata member. No parsing needed.
2. Make `-L` search paths registered in the static library scoped to the library only, like runpath (or maybe inherited like rpath). The plugin handler of bfd registers *global* search paths in at *lowest* priority. So I could not get it to work previously cause some system directory had a `libg.a`, which came before my specified `-L` path among deps. And even worse, dependency -L flags for libf.a could influence search behavior of the next `-lg` specified on the command line.

Let's see if anything useful comes out of https://sourceware.org/pipermail/binutils/2024-June/134962.html

**Comment by rui314** [comment]
`-L` looks odd to me in the first place because, if you know the path in which a library exists when you create an archive file, you can specify the library as a full or a relative path instead of just `-lfoo`. I.e. `/path/to/libfoo.so`. So I think the `-L` should not present in the `__.LIBDEP`.

**Comment by haampie** [comment]
I agree to some extent, but potentially -L and -l separated could make the linker still attempt to link the relevant deps even if the library moved to a different system where paths are different (and users would have to put -L on the link line regardless).
