### ISSUE TITLE
The resulting binary fails to start after linking

### ISSUE THREAD

**Issue by drdzyk** [rui314/mold#129]
Hello, I try to use mold for linking [kphp](https://github.com/VKCOM/kphp) - a php compiler project. Build kphp succeeds, but resulting binary stuck at startup, somewhere prior main function execution. I'm failed to find a problem with help of gdb and dynamic linker. Could you please advise me what I can do with it? Thanks in advance.

Tested on ubuntu 20.04 with gcc 9.3.0 and clang 12.0.1, both with mold 0.9.6 and master. Build commands for gcc:
`cmake -Bbuild -DKPHP_TESTS=OFF -DCMAKE_BUILD_TYPE=DEBUG && make -Cbuild -j$(nproc)`
and for clang:
`cmake -Bbuild -DKPHP_TESTS=OFF -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=clang++-12  && make -Cbuild -j$(nproc)`

Having the steps below, you can reproduce the bug yourself for debugging :)
1) `git clone https://github.com/VKCOM/kphp`
2) `cd kphp`
3) patch kphp with mold:
`echo "add_link_options(--ld-path=/path/to/mold/binary)" >> cmake/init-compilation-flags.cmake`
4) build with clang for example:
 `cmake -Bbuild -DKPHP_TESTS=OFF -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=clang++-12  && make -Cbuild -j$(nproc)`
5) now binary is ready, and after run it will stuck forever:
`./objs/bin/kphp2cpp`

**Comment by rui314** [comment]
Thank you for reporting the issue. I built kphp myself and confirmed that it hangs on startup. I don't know what is wrong, but I'll take a look.

**Comment by rui314** [comment]
It was a bug in mold, which should have been fixed in the above commit. Please try it now or wait for the next release to confirm the fix. Thanks!
