### ISSUE TITLE
question about support relaxation of loongarch

### ISSUE THREAD

**Issue by ywgrit** [rui314/mold#1307]
Hi, Rui.
I'm trying to support relaxation for loongarch, but there are a few problems and I'd like to hear your opinion on it.
The relaxation needs to be done before the relocation starts, and from the current code, it seems that non-architecture related files/code need to be modified, such as adding an apply_relocate member function for OutputSection in elf.output-chunks.cc. I'm not sure if this is appropriate. Because except for riscv and a few other instruction sets that are similar to the loongarch instruction set, the rest don't need to do relax.
I'd like to hear your opinion on this.
Thanks!

**Comment by rui314** [comment]
Could you share more details about your problem? What are the relocations you are trying to handle?

**Comment by ywgrit** [comment]
> Could you share more details about your problem? What are the relocations you are trying to handle?
Sure.
I'd like to replace the original call to InputSection::apply_reloc_[no]alloc with InputSection::apply_relax. Where apply_relax is a new member function added to the InputSection class that handles **relaxation** including pcalau12i/addi -> pcaddi.
The copy_chunks (where the relaxation occurs) is followed by apply_relocate(new routine), which invokes OutputSection::apply_relocate to relocate all InputSections.

In the current hypothesis, the calling relationship is as follows
```
copy_chunks->chunk.copy_buf->OutputSection::write_to->InputSection::write_to->InputSection::apply_relax

apply_relocate->OutputSection::apply_relocate->InputSection::apply_reloc_[no[alloc 
```
All of these changes are made so that all InputSections have been relocated before relaxation.

**Comment by rui314** [comment]
Have you read https://github.com/rui314/mold/blob/main/elf/arch-riscv.cc? I believe LoongArch's relaxation is modeled after the RISC-V psABI's, so maybe you can do the same as RISC-V?

**Comment by ywgrit** [comment]
> Have you read https://github.com/rui314/mold/blob/main/elf/arch-riscv.cc? I believe LoongArch's relaxation is modeled after the RISC-V psABI's, so maybe you can do the same as RISC-V?

Thanks.
I've searched for this file before based on "arg.relax", but there is only one case processed in riscv and that case doesn't delete the instruction bytes, so that case doesn't cause the symval to change. But for the case of relaxation that deletes instructions(i.e., pcalau12i/addi -> pcaddi in loongarch), it may cause some of the symbol values to be changed. If relocation is done where the symbols are used before these relaxations are applied, then after the relaxation is applied, the value of the symbols are changed and the relocation is invalidated. That's why maybe we need to do the relaxation before the relocation.

**Comment by rui314** [comment]
We do support the RISC-V relaxations that remove bytes. Please take a look at `riscv_resize_sections` in that file.

**Comment by ywgrit** [comment]
> We do support the RISC-V relaxations that remove bytes. Please take a look at `riscv_resize_sections` in that file.

Sorry for my omission. Thank you, Rui.
