### ISSUE TITLE
x86_64-as-needed-weak (Failed)

### ISSUE THREAD

**Issue by siegLoesch** [rui314/mold#1312]
[ctest.zip](https://github.com/user-attachments/files/16315111/ctest.zip)
[log2.zip](https://github.com/user-attachments/files/16315129/log2.zip)
Latest build of mold (version: 2.32.1) succeeded without error. My operating system is _debian bookworm_. I did not use the system _gcc_ compiler but self build _gcc/g++ version 13.3.0_.

Running the unit tests yields one error:
**x86_64-as-needed-weak (Failed)**
I attached the output of `ctest -R x86_64-as-needed-weak --output-on-failure` : _ctest.zip_.

On a first view this seems to be caused from the command
`! grep -Fq 'Shared library: [libfoo.so]' $t/log2 || false` in the script file: _as-needed-weak.sh_ which yields `[ctest.zip](https://github.com/user-attachments/files/16315093/ctest.zip)` because the string "Shared library: [libfoo.so]" is contained in _log2_. See atached _log2.zip_ file.

Please let me know something is wrong on my side.

Thank you
Siegfried

**Comment by rui314** [comment]
Can you zip the entire `out/test/elf/x86_64/as-needed-weak/` directory and share it with me?

**Comment by siegLoesch** [comment]
Thank you for answering!
Find requested data dir attached:

Siegfried
[as-needed-weak.zip](https://github.com/user-attachments/files/16319505/as-needed-weak.zip)

**Comment by rui314** [comment]
It looks like the issue is no longer reproducible with git head. Please try again with git head.

**Comment by siegLoesch** [comment]
100% tests passed using git head - thanks for support!
