### ISSUE TITLE
Undefined reference when linking shared libraries not raised

### ISSUE THREAD

**Issue by mattparks** [rui314/mold#1313]
I have an example where two shared libraries (A and B) don't link with `-z defs`; and where C does build with `-z defs` and links both libraries.
This example includes an mistake where B attempts to use a local from A (`helper_a()`). When linking with `ld` an undefined reference error is raised. This does not occur with Mold with the same linker flags, transforming this mistake into a runtime error.

If `helper_a()` were not defined in A at all, there is still no error raised with Mold, I don't think symbol visibility matters in this example.

I tested with mold 2.32.1, attached is the described example project:
[mold_vs_ld_undefined_symbols.zip](https://github.com/user-attachments/files/16322368/mold_vs_ld_undefined_symbols.zip)

**Comment by rui314** [comment]
Please try again with the above change.
