### ISSUE TITLE
unknown command line option: -dynamic-list-data

### ISSUE THREAD

**Issue by siegLoesch** [rui314/mold#1320]
During build of _openucc_ an error was reported from mold:

```
mold: fatal: unknown command line option: -dynamic-list-data
collect2: error: ld returned 1 exit status
```

**OS: debian bookworm
gcc: 13.3.0**

After that the same build succeeded using _gnu ld (which is in fact: bfd)_ without any issue.

Is it true that _mold_ does not know about those specific option or might it be that I did anything wrong?

Best regards
Siegfried

**Comment by rui314** [comment]
mold does not support that flag while GNU ld does. We may want to support it for the sake of compatibility. Let me see.
