### ISSUE TITLE
Fails to build ninja with mold linker on gcc15

### ISSUE THREAD

**Issue by blackteahamburger** [rui314/mold#1336]
[build.log](https://github.com/user-attachments/files/16824485/build.log)
[emerge-info-output.log](https://github.com/user-attachments/files/16791648/emerge-info-output.log)
Ref: https://bugs.gentoo.org/938659

Without `-fuse-ld=mold` build succeeds.

Edit: [gdb.txt](https://github.com/user-attachments/files/16824487/gdb.txt)

**Comment by rui314** [comment]
Thank you for your report. GCC 15 is not released yet, no? If that's the case, it might be a bug that is in the development branch. You may want to report it to GCC.

**Comment by jwakely** [comment]
The build.log seems to show that the python configure.py step fails, but the logs don't show any information about why, except that ninja trapped.

There is nothing useful here that can be reported as a GCC bug, and a gentoo toolchain dev is unable to reproduce this.

Please rebuild with `-g3`, `ulimit -c unlimited`, and check `coredumpctl`

**Comment by blackteahamburger** [comment]
I recompiled it using gcc-14 but it still failed. It never failed before. My gcc-14 and mold are built on gcc-15.

**Comment by rui314** [comment]
Is there any possibility that gcc 15 miscompiled mold? Overall, it looks more like an issue with the gcc dev branch rather than a mold issue.

**Comment by blackteahamburger** [comment]
It seems that gcc 15 has broken too many things. I don't want to move further because I have reinstalled my system.

**Comment by thesamesam** [comment]
I suspect your issue was actually https://github.com/rui314/mold/issues/1361.

**Comment by rui314** [comment]
Ah, it can be. @blackteahamburger What is your Linux kernel version? You can check it with `uname -r`.

**Comment by thesamesam** [comment]
Their `emerge --info` attachment has `6.11.0-rc5-tkg-bore`. I also test GCC 15 extensively so it makes sense that it wouldn't be that.

**Comment by rui314** [comment]
Then it's very likely be the case.
