### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by just-an-engineer** [rui314/mold#1339]
When I run `cmake --build build -j$(nproc)`, it gets to linking the `CXX executable mold`, but gives me the attached error
[ERROR.txt](https://github.com/user-attachments/files/16873801/ERROR.txt)
os-release
```
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
```
On x86_64

```
> clang --version
Ubuntu clang version 20.0.0 (++20240828064146+c43190f99445-1~exp1~20240828184310.1138)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-20/bin
```

I did `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang -B build`
I updated my clang, I updated libstdc++ and libc++ to the latest versions. Each time rerunning, and still error-ing out at the exact same place. I followed the installation instructions up to that point.

**Comment by rui314** [comment]
You want to pass `-DCMAKE_CXX_COMPILER=clang++` instead of `-DCMAKE_CXX_COMPILER=clang`. The former is a C++ compiler command while the latter is C.

**Comment by just-an-engineer** [comment]
Darn, that was it. Woops. Thank you!
