### ISSUE TITLE
riscv64-absolute-symbols fails with GCC 14

### ISSUE THREAD

**Issue by marxin** [rui314/mold#1340]
It started to fail on around August 31, though it might have been caused by a change in the GCC 14 compiler. The binary does not produce any output:

```
[ 5308s] + out/test/riscv64/absolute-symbols/exe
[ 5308s] + out/test/riscv64/absolute-symbols/exe
[ 5308s] + grep -q '^ip=0x80000.$'
```
[absolute-symbols.gz](https://github.com/user-attachments/files/16885784/absolute-symbols.gz)

**Comment by rui314** [comment]
When I ran your executable in a `riscv64/ubuntu` docker image, it printed out `ip=0x800008`. So it looks like it's system-dependent?

**Comment by marxin** [comment]
Maybe. @andreas-schwab can help us, I guess?

**Comment by andreas-schwab** [comment]
It's a qemu bug.

**Comment by rui314** [comment]
Did you have a link to the qemu bug?

**Comment by andreas-schwab** [comment]
No.

**Comment by rui314** [comment]
How did you know it was a qemu bug?

**Comment by andreas-schwab** [comment]
$ qemu-riscv64 ./exe
mmap stack: Cannot allocate memory

**Comment by marxin** [comment]
@andreas-schwab  Can you file an issue so that upstream knows about it?

**Comment by andreas-schwab** [comment]
0x7ee000           0x866000    0x78000        0x0  rw-p   [heap]
