### ISSUE TITLE
`error: undefined symbol: std::__ndk1::basic_string<...>::assign(...)` when linking Firefox for Android with mold

### ISSUE THREAD

**Issue by theres-waldo** [rui314/mold#1342]
I've previously had success using mold as the linker for building Firefox for various platforms on a Linux host.

However, when trying to build **Firefox for Android** from a recent trunk of the [mozilla-central](hg.mozilla.org/mozilla-central/) repository, I'm getting the following error:

> mold: error: undefined symbol: std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::assign(char const*, unsigned long)

The full output of the build command can be seen [here](https://bug1917723.bmoattachments.org/attachment.cgi?id=9423701).

I originally reported the error in the Mozilla bug tracker at https://bugzilla.mozilla.org/show_bug.cgi?id=1917723, and I've been advised to report it here. The build succeeds when not using mold.

My mold version is 2.31.0.

Please let me know if there is any other information I can provide.

**Comment by rui314** [comment]
Thank you for the report. This is a subtle symbol resolution issue, but I think I managed to fix it in the above commit. Please try again with the git head.

**Comment by theres-waldo** [comment]
Thank you for the quick fix! I can confirm that with git head Firefox for Android links successfully.
