### ISSUE TITLE
rustc -Clinker-plugin-lto , mold fatal

### ISSUE THREAD

**Issue by user7z** [rui314/mold#1343]
mold: fatal: /var/tmp/portage/dev-util/bindgen-0.70.1/work/rust-bindgen-0.70.1/target/x86_64-unknown-linux-gnu/release/deps/bindgen-46fd42290229b24f.bindgen.15e13fc049958349-cgu.00.rcgu.o: not claimed by the LTO plugin; please make sure you are using the same compiler of the same version for all object files
          collect2: error: ld returned 1 exit status
here are my flags on a regular gcc profile  : 

COMMON_FLAGS="-march=native -O3 -pipe -flto=auto ${WARNING_FLAGS} -fno-semantic-interposition"
LDFLAGS="${LDFLAGS} -fuse-ld=mold -Wl,--thread-count=12"
RUSTFLAGS="-Ctarget-cpu=native -Copt-level=3 -Clinker-plugin-lto"

cant mold be used with -Clinker-plugin-lto ? , even -Clink-arg=$LDFLAGS or -fuse-ld=mold , give the same probleme.
one other question is it true mold has a --lto-O3 flag or any lto related one. 
can i consider mold for a better lto ?

**Comment by rui314** [comment]
Chances are, as the error message said, you are using two different compilers, maybe gcc and clang. Please make sure you are using only one compiler to compile and link your program.
