### ISSUE TITLE
mold on gentoo llvm profiles

### ISSUE THREAD

**Issue by user7z** [rui314/mold#1344]
the default LDFAGS in llvm profiles in bouth glibc & musl are : 
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,--as-needed"
i make use of mold by : 
LDFLAGS="$LDFLAGS -fuse-ld=mold"
but the compiler dont work , i think its a syntax issue , normally thise works under gcc based profiles, what could be the probleme here , can i use mold instead of lld ?

**Comment by rui314** [comment]
I'm not a Gentoo user, so I cannot answer to your question as to how to pass compiler options as you desire. You may want to ask at a Gentoo forum.
