### ISSUE TITLE
`mold 2.33.0` produced illformed shared object with `--retain-symbols-file`

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1346]
Using mold for linking `vlc` (aarch64/linux) resulted in a couple of plugins (although most appear to be fine) to be illformed as reported by `strip`:
```
$ strip libtaglib_plugin.so 
strip: warning: libtaglib_plugin.so has a section extending past end of file
strip: libtaglib_plugin.so: file format not recognized
```
Appears to be caused by use of `--retain-symbols-file` or at least dropping it produces correct shared object. Attached sample file for which symbol file has 3 entries:
```
vlc_entry__3_0_0f
vlc_entry_copyright__3_0_0f
vlc_entry_license__3_0_0f
```
[plugin.zip](https://github.com/user-attachments/files/17081381/plugin.zip)

**Comment by rui314** [comment]
Does the above change work?

**Comment by jpalus** [comment]
`vlc` linked fine, stripped fine and works fine so looks like it's fixed. Thanks!

**Comment by rui314** [comment]
Thank you for confirming!
