### ISSUE TITLE
Runs Mold on *BSD ?

### ISSUE THREAD

**Issue by mustafacco7** [rui314/mold#1349]
#/### Discussed in https://github.com/rui314/mold/discussions/1302

<div type='discussions-op-text'>

<sup>Originally posted by **theuserbl** July 13, 2024</sup>
It runs on Linux, but currently not on macOS and Windows.
But runs it on *BSD (FreeBSD, NetBSD, OpenBSD, ...) ?

I wonder, that it is a lesser problem to add additional hardware-support (different CPUs)  and that it is a bigger problem to add support of different operating systems.
I understand, that adding linking of Windows programs is hard, because Windows have the PE-format and the object files can be different. gcc on Windows created different object files then VC++.
But Linux, *BSD and I think also macOS are all using the ELF-format. Where is there the difference for the linker for the different operating systems?
That the libraries which are linked are on different places and that the libraries are different can not be the reason. Or I am wrong?
</div>

**Comment by rui314** [comment]
Each BSD is different, but at least mold works on FreeBSD. I even set up a CI to test mold on FreeBSD for each commit. If you find that mold lacks a feature for other BSDs, please file a bug for each issue. Thanks!
