### ISSUE TITLE
mold generates larger binaries than gold: is this expected/acceptable?

### ISSUE THREAD

**Issue by madscientist** [rui314/mold#1350]
I'm comparing GCC 14.2 using gold from binutils 2.43.1 on X86_64 (GNU/Linux), with the identical compiler using mold 2.34.0.

This is a moderately large and complex C++20 program.  With gold the link on my system takes about 5s and generates a binary that is 368M (most things are statically linked, including the STL: only libc is not statically linked).  Also this is built with optimization (-O2) and embedded debugging (-ggdb3, not using debug files) and not stripped.  No LTO.

mold takes only about 0.45s (wow!), and the binary it produces is 387M: 19M larger, which is about a 5% increase in size.

The README discusses link time but doesn't discuss binary sizes.  If this seems on par with expected behavior feel free to close this issue.  If you'd like me to gather more info using objdump or whatever, let me know what you'd like me to look at.

Thanks!

**Comment by rui314** [comment]
Can you compare them after running the `strip` command on them? If the sizes are still different, please share the output of `readelf -WS <executable1> <executable2>`.

**Comment by madscientist** [comment]
Thank you for that suggestion.  After stripping the result is that the mold binary is about 50K smaller than the gold binary (e.g., they are almost identical).  We don't ship stripped binaries since we want to debug cores etc. on user systems, in our environment.  However a 5% difference in size is not that significant.

**Comment by rui314** [comment]
If the size difference came from debug info, you don't need to worry about it too much. If you want to reduce the size of debug sections for whatever reason (to reduce the transfer size or save disk space, etc.), you may want to link your binary with `-Wl,--compress-debug-sections=zlib` to compress debug info sections.

**Comment by madscientist** [comment]
I indeed did add compression yesterday and it reduces the binary size from 387M down to 163M, very nice.

Thanks for checking this.  I don't know if it's worth a note in the readme regarding binary sizes.  Although I'm well aware debug info doesn't matter at runtime, it does make a difference when distributing software so we do at least think about it.
