### ISSUE TITLE
Use readelf to verify compress-debug-sections

### ISSUE THREAD

**Issue by praetorian20** [rui314/mold#1352]
Hi @rui314, I'm trying to build mold on RHEL 8.7. The compress-debug-sections test is failing because the version of `dwarfdump` I have available, 2018-01-29, doesn't seem to recognize the `SHF_COMPRESSED` flag.

I modified the test to use `readelf` instead using this patch

```patch
diff --git a/test/compress-debug-sections.sh b/test/compress-debug-sections.sh
index 4a658a02..9877e639 100755
--- a/test/compress-debug-sections.sh
+++ b/test/compress-debug-sections.sh
@@ -1,8 +1,6 @@
 #!/bin/bash
 . $(dirname $0)/common.inc
 
-command -v dwarfdump >& /dev/null || skip
-
 cat <<EOF | $CC -c -g -o $t/a.o -xc -
 #include <stdio.h>
 
@@ -13,6 +11,6 @@ int main() {
 EOF
 
 $CC -B. -o $t/exe $t/a.o -Wl,--compress-debug-sections=zlib
-dwarfdump $t/exe > $t/log
-grep -Fq '.debug_info SHF_COMPRESSED' $t/log
-grep -Fq '.debug_str SHF_COMPRESSED' $t/log
+readelf -tW $t/exe > $t/log
+grep -F -A2 '.debug_info' $t/log | tr '\n' ' ' | grep -qw 'COMPRESSED'
+grep -F -A2 '.debug_str' $t/log | tr '\n' ' ' | grep -qw 'COMPRESSED'
-- 
```

Does this look like an alternative you'd be interested in merging? I'll make a PR if it looks good to you. Or if you have a different method you'd like me to try, please let me know.

**Comment by rui314** [comment]
Yeah, please send me a PR if this works for you. Thanks.
