### ISSUE TITLE
Plans of supporting Blackberry QNX?

### ISSUE THREAD

**Issue by Vegeshp** [rui314/mold#1359]
Do we have plans of supporting Blackberry QNX? By using mold, the linking time can be 30 times faster on the machine with 32 workers!

**Comment by rui314** [comment]
What is the processor of Blackberry QNX?

**Comment by Vegeshp** [comment]
cortex-a75 I think.

**Comment by rui314** [comment]
We do support both ARM32 and ARM64, so it's supported I guess?

**Comment by Vegeshp** [comment]
Then it may be the "black" magic of Blackberry... I think I may have to look for more help from Blackberry. Thanks for your help!
