### ISSUE TITLE
Assertion fails when compiling Rust

### ISSUE THREAD

**Issue by Sl1mb0** [rui314/mold#1365]
I am using `mold` to compile a Rust app. I'm using the latest unstable version of mold from the debian repository, which is: `2.34.1`. This is the error I am seeing:
```
mold: ./src/../lib/common.h:637: std::pair<T*, bool> mold::ConcurrentMap<T>::insert(std::string_view, mold::u32, const T&) [with T = mold::SectionFragment<mold::X86_64>; std::string_view = std::basic_string_view<char>; mold::u32 = unsigned int]: Assertion `false && "ConcurrentMap is full"' failed.
```

**Comment by rui314** [comment]
What program are you trying to build with mold?

**Comment by Sl1mb0** [comment]
It's an internal product; not sure how much more information I can give at the moment.

If there is specific info that would help though I'd be happy to see if I can share it.

**Comment by rui314** [comment]
Can you build mold with the following patch and share the new error message?

```
diff --git a/lib/common.h b/lib/common.h
index ac2b0c5c..7d679aa1 100644
--- a/lib/common.h
+++ b/lib/common.h
@@ -615,6 +615,7 @@ public:
       // If we successfully claimed the ownership of the slot,
       // copy values to it.
       if (claimed) {
+        nused++;
         new (&ent.value) T(val);
         ent.keylen = key.size();
         ent.key.store(key.data(), std::memory_order_release);
@@ -633,8 +634,11 @@ public:
         return {&ent.value, false};
     }

-    assert(false && "ConcurrentMap is full");
-    return {nullptr, false};
+    std::cerr << "ConcurrentMap is full: capacity=" << nbuckets
+              << " nused=" << nused
+              << " key=" << key
+              << "\n";
+    abort();
   }

   i64 get_idx(T *value) const {
@@ -698,6 +702,7 @@ public:

   Entry *entries = nullptr;
   i64 nbuckets = 0;
+  Atomic<i64> nused = 0;
 };

 //
```

**Comment by Sl1mb0** [comment]
Managed to build & run with the above patch:
```
  = note: ConcurrentMap is full: capacity=2097152 nused=1242771 key=_ZN4core4iter6traits8iterator8Iterator8for_each4call28_$u7b$$u7b$closure$u7d$$u7d$17h3536458bda9eba6eE␀
          clang: error: unable to execute command: Aborted (core dumped)
          clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by rui314** [comment]
Thank you for testing with the patch. The error is mysterious -- the concurrent hashmap that is reported as full is only 60% full. The error is raised if 128 consecutive hash table slots are occupied, but with 60% usage, it is extremely unlikely to occur. There are a few possible explanations:

- Our hash function is low quality and causes too many collisions in the hash table (but it's unlikely because we are using XXHash),
- The symbol names of your programs causes XXHash to cause collisions (it's very unlikely too), or
- There's a bug in our concurrent hash map.

I don't know which is the case. 

I made a small change to the concurrent hashmap. Can you test again with the git head?

Does this occur without multi-threading? Please try again with `--no-threads` linker option.

I really want to fix this issue.

**Comment by Sl1mb0** [comment]
Just pulled & built the latest `mold`. Looks like the small change eliminated the bug!

**Comment by rui314** [comment]
Ahh, that's nice, but I cannot explain why that could fix the issue. If you have time, can you rebuild mold without that commit (i.e. build at 85be067813952409878ddd7d507855c2a017841d) to see if the problem occurs right before the last commit? I want to make sure that the problem was really fixed.

**Comment by Sl1mb0** [comment]
Looks like building & running with that commit causes a segmentation fault:
```
  = note: clang: error: unable to execute command: Segmentation fault (core dumped)
          clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by rui314** [comment]
It's interesting. So it looks like my last commit actually fixed your issue, but I still cannot explain why. If you have time, can you revert my last commit one line at at time to see which line of change fixed the issue. If not, feel free to close the bug.

**Comment by Sl1mb0** [comment]
Okay so this is getting interesting.

I've created my own local branch for playing around with the commits; and these are the commits I currently have:
```
commit 4028f310cbc9238ade9999138903fae7ea563231 (HEAD -> tm/insertion-bug-check)
Author: Timothy Maloney <tmaloney@influxdata.com>
Date:   Tue Nov 5 08:45:32 2024 -0800

    refactor: use u64

commit 62a899985535787b8427511675f68a1993bf86a5
Author: Timothy Maloney <tmaloney@influxdata.com>
Date:   Tue Nov 5 08:29:07 2024 -0800

    refactor: use u32 instead of u64

commit baf4f76f53155d021d19560db0f97ca60bba682f (origin/main, origin/HEAD, main)
Author: Rui Ueyama <ruiu@cs.stanford.edu>
Date:   Sat Nov 2 16:40:50 2024 +0900

    Report an error even without NDEBUG=1 if a ConcurrentMap becomes full
```

### commit `4028f310`

The current commit `4028f310` is no different than what's currently in main:

```
sl1mb0@cheetah:~/Developer/mold$ git diff baf4f76f53155d021d19560db0f97ca60bba682f
sl1mb0@cheetah:~/Developer/mold$
```
Now, the bug _did_ occur in `4028f310`:
![image](https://github.com/user-attachments/assets/9d110561-6b64-49d8-916a-3ef784f498c5)


 but when re-running the CI job; the bug did **NOT** occur: 
![image](https://github.com/user-attachments/assets/c8e9b986-1d27-4835-94ca-f93a166568c2)



### commit `62a89998`

The change in `62a89998` is:
```
sl1mb0@cheetah:~/Developer/mold$ git diff 62a899985535787b8427511675f68a1993bf86a5
diff --git a/lib/common.h b/lib/common.h
index f39e0c97..0a35e555 100644
--- a/lib/common.h
+++ b/lib/common.h
@@ -595,7 +595,7 @@ public:
 #endif
   }
 
-  std::pair<T *, bool> insert(std::string_view key, u32 hash, const T &val) {
+  std::pair<T *, bool> insert(std::string_view key, u64 hash, const T &val) {
```

Now, I've confirmed that the bug occurs in `62a89998`:
![image](https://github.com/user-attachments/assets/e730aa9d-cf7d-4ce3-9ec1-466e6c9e8a17)

And re-running the job does **NOT** fix the issue. I've re-ran it 3 times now.

**Comment by rui314** [comment]
Thank you for your investigation! Based on your report, it looks like my last commit did not really fix the issue, because the first attempt on CI with 
4028f310cbc9238ade9999138903fae7ea563231 should not have failed if there were no issues with the linker. It seems like this is a flaky issue.

It's very hard to debug this without reproducing it locally.

One question: is the CI machine x86 or ARM or something else?

**Comment by rui314** [comment]
How about this?

```
diff --git a/lib/common.h b/lib/common.h
index 0a35e555..5e4dda17 100644
--- a/lib/common.h
+++ b/lib/common.h
@@ -617,7 +617,7 @@ public:
       // Otherwise, use CAS to atomically claim the ownership of the slot.
       const char *ptr = nullptr;
       bool claimed = ent.key.compare_exchange_strong(ptr, (char *)-1,
-                                                     std::memory_order_acquire);
+                                                     std::memory_order_acq_rel);

       // If we successfully claimed the ownership of the slot,
       // copy values to it.
```

**Comment by Sl1mb0** [comment]
CI Machine is x86. Also looks like that commit didn't fix the bug:
```
$ git log
commit 4daa37642bb13fc90b10e28d2645e794eb487bd7 (HEAD -> tm/insertion-bug-check)
Author: Timothy Maloney <tmaloney@influxdata.com>
Date:   Wed Nov 6 07:07:44 2024 -0800

    refactor: use memory_order_acq_rel

commit 4028f310cbc9238ade9999138903fae7ea563231
Author: Timothy Maloney <tmaloney@influxdata.com>
Date:   Tue Nov 5 08:45:32 2024 -0800

    refactor: use u64

commit 62a899985535787b8427511675f68a1993bf86a5
Author: Timothy Maloney <tmaloney@influxdata.com>
Date:   Tue Nov 5 08:29:07 2024 -0800

    refactor: use u32 instead of u64

commit baf4f76f53155d021d19560db0f97ca60bba682f (origin/main, origin/HEAD, main)
Author: Rui Ueyama <ruiu@cs.stanford.edu>
Date:   Sat Nov 2 16:40:50 2024 +0900
sl1mb0@cheetah:~/Developer/mold$ git diff HEAD~1
diff --git a/lib/common.h b/lib/common.h
index 0a35e555..5e4dda17 100644
--- a/lib/common.h
+++ b/lib/common.h
@@ -617,7 +617,7 @@ public:
       // Otherwise, use CAS to atomically claim the ownership of the slot.
       const char *ptr = nullptr;
       bool claimed = ent.key.compare_exchange_strong(ptr, (char *)-1,
-                                                     std::memory_order_acquire);
+                                                     std::memory_order_acq_rel);
 
       // If we successfully claimed the ownership of the slot,
       // copy values to it.
```


![image](https://github.com/user-attachments/assets/d9973bee-e031-4c73-b673-4f8b1f76eaff)

**Comment by rui314** [comment]
We might have been looking in the wrong place; the hash table might not be faulty, especially since the issue occurs even with `--no-threads`. If that's the case, it becomes extremely difficult to debug further, as I have no idea what could be wrong other than that.

Is there any way to reproduce the issue without your proprietary software? Or could I get access to the object files of your software?

If you _need_ to make a contract with my company and pay money for it to share your object files, we are open to that option as well.

**Comment by domodwyer** [comment]
If anyone else hits this, @rui314 has provided a patch that temporarily works around the problem:

```diff
diff --git a/src/gdb-index.cc b/src/gdb-index.cc
index a87b7691..8c7b3459 100644
--- a/src/gdb-index.cc
+++ b/src/gdb-index.cc
@@ -676,7 +676,7 @@ void write_gdb_index(Context<E> &ctx) {
     estimator.merge(e);
   });

-  ConcurrentMap<MapValue> map(estimator.get_cardinality() * 3 / 2);
+  ConcurrentMap<MapValue> map(estimator.get_cardinality() * 30 / 2);

   tbb::parallel_for_each(cus, [&](Compunit &cu) {
     cu.entries.reserve(cu.nametypes.size());
diff --git a/src/output-chunks.cc b/src/output-chunks.cc
index 753f47a1..6de972d3 100644
--- a/src/output-chunks.cc
+++ b/src/output-chunks.cc
@@ -2138,7 +2138,7 @@ void MergedSection<E>::resolve(Context<E> &ctx) {
   });

   // We aim 2/3 occupation ratio
-  map.resize(estimator.get_cardinality() * 3 / 2);
+  map.resize(estimator.get_cardinality() * 30 / 2);

   tbb::parallel_for_each(members, [&](MergeableSection<E> *sec) {
     sec->resolve_contents(ctx);
```
