### ISSUE TITLE
No test on x86

### ISSUE THREAD

**Issue by bl4ckb0ne** [rui314/mold#1371]
This has been tested with the latest release (2.34.1) with the AlpineLinux CI for x86 arch, no tests are found for the arch

```
Internal ctest changing into directory: /home/buildozer/aports/community/mold/src/mold-2.34.1/build
Test project /home/buildozer/aports/community/mold/src/mold-2.34.1/build
No tests were found!!!
Errors while running CTest
>>> ERROR: mold: check failed
>>> mold: Uninstalling dependencies...
```

In the `test` CMake file [1] the arch is checked for a match against `i386` and sets `MACHINE` to `i686`, shouldn't it check for both `i686` and `i386` to enable the tests? And should `i386` test `i686`?

I made a small patch to fix the local build, I also added the `x86_64` match, somewhat our x86_64 machine was running i686 tests. Let me know if  you want me to submit it as a pull request

```
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index e64a1f0e..7ff26bb5 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -16,9 +16,9 @@ if(NOT EXIT_CODE AND ARCH MATCHES "([^-]+).*")
   set(MACHINE ${CMAKE_MATCH_1})
 endif()
 
-if(${MACHINE} MATCHES "amd64")
+if(${MACHINE} MATCHES "amd64" OR ${MACHINE} MATCHES "x86_64")
   set(MACHINE x86_64)
-elseif(${MACHINE} MATCHES "i386")
+elseif(${MACHINE} MATCHES "i?86")
   set(MACHINE i686)
 elseif(${MACHINE} MATCHES "arm.*")
   set(MACHINE arm)
```

[1]: https://github.com/rui314/mold/blob/main/test/CMakeLists.txt

**Comment by rui314** [comment]
Please send it as a PR.

**Comment by rui314** [comment]
`MATCHES` takes a regular expression, so shouldn't it be `i.86`?

**Comment by bl4ckb0ne** [comment]
I think you're right [1], I'll fix it when submitting the PR.

[1]: /pool/media/tv_series/Dune.Prophecy.2024
