### ISSUE TITLE
Design question: why centralised headers?

### ISSUE THREAD

**Issue by sicherha** [rui314/mold#1382]
I find it interesting that the project foregoes the conventional C++ structure where every module is accompanied by its own header. Instead, mold has few huge centralised headers (`lib/common.h`, `src/mold.h`) with 1000+ lines of code each.

I wonder what motivated this design choice. Is it an artefact from when the build system was based on plain `Makefile`s and dependency tracking was hard?

**Comment by rui314** [comment]
I just feel it's easier to maintain this way compared to having lots of h files in the directory.

**Comment by sicherha** [comment]
Are you open to reconsidering this design choice? (I'd be willing to help out.)
One unfortunate side effect of the current state is that every change to one of these two headers forces the recompilation of almost the entire source tree.

**Comment by rui314** [comment]
Honesty, no, I don't personally like to separate that file into small files. But how bad is the single header file for you?

**Comment by sicherha** [comment]
I'm currently toying around with clang-tidy a bit, looking at its findings and suggestions: const-correctness, argument-passing semantics, making single-argument constructors `explicit`, ... small things like these. Every tiny change I make to `lib/common.h` results in 372 build steps in CMake.

This feels a bit excessive. I'm interested in mold because I care about link times, but I do care just as much about compile times. 🙂

**Comment by rui314** [comment]
Editing a base header library like that would cause massive recompilation even if the header were split into small files. One thing you can try to reduce build time when experimenting it is to restrict the target to x86-64. That should significantly reduce the number of compiled files to ~1/10.

**Comment by sicherha** [comment]
True - I could restrict the set of targets to x86_64, but then I wouldn't notice right away if I broke another target. That's not optimal either.

If I may attempt to paraphrase your view, it's that the `lib` directory should be regarded as one monolithic module, right?

My point is that, for instance, much of the functionality declared in `lib/common.h` does not appear to be relevant for building any of the `src/arch-*.cc` files. So maybe it is at least worth considering whether that functionality might benefit from being split off into a separate module.

**Comment by rui314** [comment]
Yeah, my view is that I had no choice but to write declarations and some inline definitions in the header because C++ forced me to do so, but I don't want to be too bothered by that. Go, for example, doesn't require any header file. I can tolerate having one large header file, but having two files for each implementation (.cpp and .h pair) and manage which .cpp file should include which .h feels too much.

**Comment by sicherha** [comment]
I understand. Actually, this sounds like a good argument for trying out C++20 modules.

Maybe I'll find a bit of time over the holidays to experiment with module support.

**Comment by sicherha** [comment]
First, a list of build requirements for C++ modules - taken from [the CMake documentation](https://cmake.org/cmake/help/latest/manual/cmake-cxxmodules.7.html):
* Clang >= 16 or GCC >= 14
* CMake >= 3.28
* Ninja >= 1.11 (GNU Make is not supported)

Please yell 'stop!' if any of this is an outright deal breaker. 🙂

**Comment by rui314** [comment]
GCC >= 14 is probably too recent.

**Comment by sicherha** [comment]
Do you have a rule of thumb regarding build dependencies - something like *mold must build out of the box with the latest Ubuntu LTS*?

Ubuntu 24.04 [does ship GCC 14 as an optional package](https://packages.ubuntu.com/noble-updates/gcc-14), but [the default is still GCC 13](https://packages.ubuntu.com/noble/gcc). I guess I'll have to shelve the use of modules for the time being.

**Comment by rui314** [comment]
I don't have a hard rule, but requiring Ubuntu 24.04 is unacceptable in my opinion. I'd like to make it compile on older distributions, such as Ubuntu 20.04.

**Comment by sicherha** [comment]
Ubuntu 20.04 will only be around for another six months, but the newest compilers shipped by Ubuntu 22.04 are GCC 12 and Clang 15. So I'll put this topic on ice for now and revisit it in two years or so.
