### ISSUE TITLE
Not needed shared object linked with `--as-needed`

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#1395]
`libB.so` needs `libA.so`. `libC.so` needs `libB.so` but not `libA.so`. While linking `libC.so` with `--as-needed` both `-lB` and `-lA` are present hence it is expected `libA.so` is not linked:
```sh
$ echo 'void a() {}' | gcc -x c -shared -o libA.so -
$ echo 'void a();void b() {a();}' | gcc -x c -shared -o libB.so - -L. -lA
$ echo 'void b();void c() {b();}' | gcc -x c -shared -Wl,--as-needed -fuse-ld=mold -o libC.so - -L. -lB -lA
```
In practice both are linked:
```sh
$ readelf -a libC.so|grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libB.so]
 0x0000000000000001 (NEEDED)             Shared library: [libA.so]
```
While with `bfd`/`lld` only `libB.so` is linked:
```sh
$ echo 'void b();void c() {b();}' | gcc -x c -shared -Wl,--as-needed -fuse-ld=bfd -o libC.so - -L. -lB -lA 
$ readelf -a libC.so|grep NEEDED                                                                            
 0x0000000000000001 (NEEDED)             Shared library: [libB.so]
```

`mold 2.35.0 / Linux / aarch64`

**Comment by rui314** [comment]
libC.so is arguably needed, so I wouldn't say it is immediately a bug. Does this cause an issue for real-world programs?

**Comment by jpalus** [comment]
I guess you meant `libA.so`, however this is what man page states (and what other linkers do too):
https://github.com/rui314/mold/blob/0b8090994bbc4681df34f4aecc1d2ff282109f68/docs/mold.md?plain=1#L458-L462

`libC.so` does not use any symbol from `libA.so` (only `libB.so` does) so to my understanding actual behavior is not in line with what docs say.

**Comment by jpalus** [comment]
As for an actual issue, from a package maintainer point of view, suppose all `lib*.so` are separate pieces of software packaged independently. Now if `SONAME` of `libA.so` changes all packages depending on it need to be rebuilt, but instead of one package to rebuild (`libB.so`), there are two, even though `libC.so` does not use `libA.so` directly.

**Comment by rui314** [comment]
OK, let me take a look. One thing to note is that a symbol resolution algorithm like this isn't an exact science but is based on heuristics, and I've settled on the current behavior because it works with most programs. So I can't promise we can do something about it, but let's see.
