### ISSUE TITLE
Alpine Linux build is broken

### ISSUE THREAD

**Issue by ftphikari** [rui314/mold#142]
`PAGE_SIZE` from `macho/mold.h` is already defined in Alpine Linux in header `/usr/include/limits.h` as
```
#define PAGE_SIZE PAGESIZE
```

See a similar issue: https://github.com/manticoresoftware/manticoresearch/issues/32

### Simple solution

Rename all instances (1 declaration and 2 uses) of `PAGE_SIZE` to something more specific, like `MACHO_PAGE_SIZE`, or whatever you want.

**Comment by rui314** [comment]
Thank you for the report. I'll rename the variable.
