### ISSUE TITLE
Better support for --dynamic-list

### ISSUE THREAD

**Issue by dangelog** [rui314/mold#149]
Hi,

Trying to build Qt 6 with mold errors out with

```
mold: /home/peppe/p/src/qt5/qtbase/src/gui/QtGui.dynlist:3:      extern "C++" {
                                                                               ^ expected ';'
```

This is the file in question https://github.com/qt/qtbase/blob/dev/src/gui/QtGui.dynlist . There are also others around in Qt:

https://github.com/qt/qtbase/blob/dev/src/corelib/QtCore.dynlist
https://github.com/qt/qtbase/blob/dev/src/widgets/QtWidgets.dynlist

I'm not sure if this is supposed to be supported by mold?

**Comment by rui314** [comment]
I wasn't aware that a dynamic list can contain `extern "C++"`. I'll implement that. Thank you for reporting!

**Comment by alcroito** [comment]
Good to know that it will be implemented. 
I was under the impression the linker script support was meant to be minimal.
I'll update https://codereview.qt-project.org/c/qt/qtbase/+/386882 to not exclude those linker scripts once they're supported by mold.

**Comment by MaskRay** [comment]
In GNU ld, --dynamic-list cannot contain `local:` or `global:`.

The current dynamic list semantics looks weird as it looks more like a version script. In GNU ld/ld.lld, for -shared, non-matched symbols are non-preemptible; for -no-pie and -pie, matched defined symbols are exported.
