### ISSUE TITLE
mold erases undefined global symbols too aggressively (?) breaking environ in shared libraries on FreeBSD

### ISSUE THREAD

**Issue by unrelentingtech** [rui314/mold#152]
The `environ` symbol is (perhaps infamously) located in crt1 rather than something like the libc on FreeBSD, so linking shared libraries that use `environ` with `--no-undefined` is not possible. However without that flag everything normally works.

<details>
<summary>with warnings of course</summary>

```
 0:02.44 mold: undefined symbol: Unified_c_external_nspr_pr1.o: environ
```

LLD:

```
 0:02.48 ld: warning: undefined symbol: environ
 0:02.48 >>> referenced by uxproces.c:0 (/home/greg/src/hg.mozilla.org/mozilla-central/nsprpub/pr/src/md/unix/uxproces.c:0)
 0:02.48 >>>               Unified_c_external_nspr_pr1.o:(_MD_CreateUnixProcess)
 0:02.48 >>> referenced by prenv.c:132 (/home/greg/src/hg.mozilla.org/mozilla-central/nsprpub/pr/src/misc/prenv.c:132)
 0:02.48 >>>               Unified_c_external_nspr_pr1.o:(PR_DuplicateEnvironment)
```

</details>

However when linking Firefox with mold, there is an issue in libnspr4 — somehow touching `environ` results in a null dereference:

```
Process 4318 launched: '/home/greg/src/hg.mozilla.org/mozilla-central/obj-x86_64-unknown-freebsd14.0/dist/bin/firefox' (x86_64)
Process 4318 stopped
* thread #38, name = 'IPC Launch', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x0000243de278d256 libnspr4.so`PR_DuplicateEnvironment at prenv.c:132:19
   129  #ifdef DARWIN
   130      the_environ = *(_NSGetEnviron());
   131  #else
-> 132      the_environ = environ;
   133  #endif
   134
   135      for (end = the_environ; *end != NULL; end++)
```

This has never happened with the LLD linker.

Adding `__attribute__((__weak__))` works as a workaround:

```
--- i/nsprpub/pr/src/misc/prenv.c
+++ w/nsprpub/pr/src/misc/prenv.c
@@ -15,7 +15,7 @@
 #include <crt_externs.h>
 #endif /* HAVE_CRT_EXTERNS_H */
 #else  /* DARWIN */
-PR_IMPORT_DATA(char **) environ;
+PR_IMPORT_DATA(__attribute__((__weak__)) char **) environ;
 #endif /* DARWIN */
 #endif /* XP_UNIX */
```

But that shouldn't be necessary.

Looking at readelf, it seems that mold is just deleting it:

```
% readelf -a nspr.lld.so | rg environ
00000003bc10  003e00000006 R_X86_64_GLOB_DAT 0000000000000000 environ + 0
    62: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND environ
   636: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND environ
% readelf -a nspr.mold.bad.so | rg environ
   476: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND environ
% readelf -a nspr.mold.weak.so | rg environ
00000003a008  013600000006 R_X86_64_GLOB_DAT 0000000000000000 environ + 0
   310: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND environ
   476: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND environ
```

**Comment by rui314** [comment]
I believe it's a bug in mold, but I don't know what's wrong. Let me fire up an EC2 FreeBSD instance to build firefox to reproduce the issue.

**Comment by rui314** [comment]
Which are you using FreeBSD, 12 or 13?

**Comment by unrelentingtech** [comment]
> Which are you using FreeBSD, 12 or 13?

14-CURRENT

This issue is very likely to appear on any version – it's not like `environ` is a new thing..

**Comment by rui314** [comment]
Ah, yes, I was trying to build Firefox on FreeBSD, but it should probably be enough to just compile a small .so file referring `environ` as you said. Let me do that.

**Comment by rui314** [comment]
If I create a small shared library from an object file containing `environ` as an undefined symbol, the symbol was automatically promoted to a dynamic symbol. That's an expected behavior, because when we are creating a shared library, all undefined symbols are exported so that they will get another chance to be resolved at runtime.

It's odd that you get a warning message on `environ`. That symbol is usually silently promoted. Do you know if the final link line contains special options like `--unresolved-symbols` or `--warn-unresolved-symbols`?

**Comment by unrelentingtech** [comment]
Firefox on BSD (when built without sanitizers) actually checks for `--ignore-unresolved-symbol` support

```
configure:3080: checking for --ignore-unresolved-symbol option to ld
configure:3092: /usr/local/bin/clang13 -std=gnu99 -o conftest --target=x86_64-unknown-freebsd14.0 -march=x86-64-v3 -fPIC -isystem/usr/local/include -fno-strict-aliasing -Qunused-arguments  -pie -Wl,-z,relro -Wl,-z,now -lrt  -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,-z,now -Wl,-z,nocopyreloc -Wl,-Bsymbolic-functions -Wl,--build-id=sha1 -Wl,--ignore-unresolved-symbol,environ conftest.c  1>&5
mold: mold: unknown command line option: --ignore-unresolved-symbol
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

and… uses `-Wl,--ignore-unresolved-symbol,environ` if that succeeds, `-Wl,--warn-unresolved-symbols` if that fails (weird?)

so I guess it is the warning that results in the deletion, unlike on LLD?

**Comment by rui314** [comment]
Likely. I'll add `--ignore-unresolved-symbol` option to mold.

**Comment by rui314** [comment]
Hmm, it looks like the presence or absence of `--warn-unresolved-symbols` doesn't affect the output from the linker. That flag only controls whether the linker should emit a warning message or not. So I think it must be something else.

Can you show me the whole command line of the linker? There may be some other linker flag that affects the behavior of the linker.

**Comment by rui314** [comment]
Does the final command line contains `-z defs`?

I forgot that I wrote this comment, but according to https://github.com/rui314/mold/blob/36633895e58c9cbb089ad80c64d9208a06e2baba/elf/object-file.cc#L1010-L1013, Firefox uses weak symbols as a loophole to promote undefined symbols to dynamic symbols even if `-z defs` is given.

**Comment by unrelentingtech** [comment]
Yeah, I think it does — nspr is built with the moz.build system now, and the flags it uses are

```
    'DSO_LDOPTS': '-shared -Wl,-z,defs -Wl,--warn-unresolved-symbols',
```
