### ISSUE TITLE
Look into splice syscall for faster I/O

### ISSUE THREAD

**Issue by mre** [rui314/mold#16]
While reading through the `README.md`, I found that you were using `cat` to concatenate input object files.

If you are just interested in copying the files into another file without modification, there are ways to speed up this process on Linux with the `splice` syscall. This is what I used for [`fcat`](https://github.com/mre/fcat) (short for "fast-cat"). It resulted in a 3x speedup in my tests. There is also a [write-up on my blog](https://endler.dev/2018/fastcat) on that topic if you're interested.

For macOS there is `copyfile`, which seems to support `COPYFILE_CLONE` which will attempt to use the APFS clone capabilities for faster copies. (See e.g. mono/mono#9038.)
There is a similar API for windows. 
I wouldn't be surprised if the C++ I/O copy function already uses these optimizations under the hood already, but at least for Linux `splice` could yield some improvements.

**Comment by rui314** [comment]
We have to not only copy a lot of data from input files to an output file but also apply relocations. Relocations exist essentially everywhere, so it is not a simple copy. As such, I think mmap is a good solution for our problem.

**Comment by mre** [comment]
Ah, was afraid it wouldn't be that easy. In this case splice doesn't help; you're right. Guess we can close this then. Thanks for the quick feedback. 👍
