### ISSUE TITLE
Feature request : Add -b/--format option to specify input-format like GNU ld & lld

### ISSUE THREAD

**Issue by baskervill** [rui314/mold#164]
Description from https://man7.org/linux/man-pages/man1/ld.1.html

>        -b input-format
       --format=input-format
           ld may be configured to support more than one kind of object
           file.  If your ld is configured this way, you can use the -b
           option to specify the binary format for input object files
           that follow this option on the command line.  Even when ld is
           configured to support alternative object formats, you don't
           usually need to specify this, as ld should be configured to
           expect as a default input format the most usual format on
           each machine.  input-format is a text string, the name of a
           particular format supported by the BFD libraries.  (You can
           list the available binary formats with objdump -i.)

           You may want to use this option if you are linking files with
           an unusual binary format.  You can also use -b to switch
           formats explicitly (when linking object files of different
           formats), by including -b input-format before each group of
           object files in a particular format.

           The default format is taken from the environment variable
           "GNUTARGET".

           You can also define the input format from a script, using the
           command "TARGET";

**Comment by rui314** [comment]
What format do you want to use? `binary`?

**Comment by baskervill** [comment]
Yes

**Comment by baskervill** [comment]
> What format do you want to use? `binary`?

Yes

**Comment by rui314** [comment]
So, I guess you are trying to embed some binary file into an executable. Is this correct?

If so, you can do that using objcopy. `objcopy -I binary -O elf64-x86-64 input-file output-file.o` turns an input file into an ELF object file which you can link to any program.

**Comment by baskervill** [comment]
> So, I guess you are trying to embed some binary file into an executable. Is this correct?
> 
> If so, you can do that using objcopy. `objcopy -I binary -O elf64-x86-64 input-file output-file.o` turns an input file into an ELF object file which you can link to any program.

Thanks. The WAR works. Closing.

**Comment by baskervill** [comment]
Same as https://github.com/rui314/mold/issues/162. Maybe you can point this out somewhere.

**Comment by rui314** [comment]
Now if you pass `-b binary` to mold, you'll get the following error/hint message.

```
mold: mold does not suppor `-b binary`. If you want to convert a binary file into an object file, use `objcopy -I binary -O elf64-x86-64 <input-file> <output-file.o>` instead.
```
