### ISSUE TITLE
--thread-count=N or --threads=N

### ISSUE THREAD

**Issue by MaskRay** [rui314/mold#168]
I understand that you may not be motivated to change this:) gold calls the option `--thread-count=N` and in my experiments it nearly has no effect. In ld.lld the degree of parallelism is controlled by `--threads=N`. Having the same option name makes it slightly easier for a user to compare the two linkers.

Having `--thread-count=N` technically makes it easier to port projects using the gold specific option, but as we see, there is none.

The lld specific option name is used in a rustdoc.rs: `Clink-arg=-Wl,--threads=1` (guarded by `RUSTDOC_FUSE_LD_LLD`).

**Comment by rui314** [comment]
I'm happy to add `--threads=N`, but what about `--threads N`? Usually `--foo=bar` is equivalent to `--foo bar`, so is `--threads` a special case?

**Comment by rui314** [comment]
OK, this is where gold and lld are incompatible. gold doesn't allow an argument for `--threads` while lld requires it. mold currently behaves like gold.

For the sake of compatibility to the both linkers, I'll support `--threads` and `--threads=N` but not `--threads N`.

**Comment by MaskRay** [comment]
Ah thanks. Most GNU ld originated long options can be specified as both `--threads N` and `--threads=N`. For newer/ld.lld specific options, I think not supporting the space separated form is fine. Most people use the `=` form anyway, unless the value itself may have `=`. For `-threads`, newer options don't benefit from one-dash long options. GNU ld folks seem to accept this as well.
