### ISSUE TITLE
support `--thinlto-cache-dir`

### ISSUE THREAD

**Issue by Enhex** [rui314/mold#171]
Mold can't be used with Clang's ThinLTO cache directory option, `--thinlto-cache-dir`.

In my case `--thinlto-cache-dir` speeds up build time more than Mold, so there's no point to switch until Mold supports it.

**Comment by Trass3r** [comment]
It doesn't support LTO.
#88

**Comment by rui314** [comment]
https://github.com/rui314/mold/issues/181
