### ISSUE TITLE
Test `strip` fails using clang

### ISSUE THREAD

**Issue by Exonorid** [rui314/mold#173]
Currently, the test strip fails when using clang as the compiler, giving the output
```
Testing strip ... clang: error: unsupported argument '--keep-locals' to option 'Wa,'
```
This stems from the fact that llvm-as doesn't currently support the --keep-locals argument that gnu as does. However, gnu as supports -L as a short form, which llvm-as also has, so this problem could be fixed by replacing the long form with the short form in the compile options.

**Comment by rui314** [comment]
Thank you for your suggestion! I made a fix accordingly.
