### ISSUE TITLE
mold-1.0.0/mold.h:592:5: error: Resource leak: fp [resourceLeak]

### ISSUE THREAD

**Issue by dcb314** [rui314/mold#175]
Source code is

  bool write_to(std::string path) {
    FILE *fp = fopen(path.c_str(), "w");
    if (!fp)
      return false;
    fwrite(data, size, 1, fp);
    return true;
  }

It also looks like path should be const reference.

const std :: string & path

**Comment by rui314** [comment]
Is the `path` actually leaking? I wonder how you identify this as an issue.

**Comment by sicherha** [comment]
The original reporter is referring to two issues:
 1. `fp` is leaked because there is no `fclose()`.
 2. *(minor)* The `path` argument is accepted by value, potentially causing unnecessary copying.

**Comment by rui314** [comment]
@sicherha Ah, thanks! I indeed forgot to close `fp`. I'll fix the issue.

**Comment by rui314** [comment]
Turned out it was actually dead code, so I just removed it.
