### ISSUE TITLE
mold-1.0.0/mold.h:525:5: warning: Class 'Timer' object issues

### ISSUE THREAD

**Issue by dcb314** [rui314/mold#176]
mold-1.0.0/mold.h:525:5: warning: Class 'Timer' does not have a copy constructor which is recommended since it has dynamic memory/resource allocation(s). [noCopyConstructor]
mold-1.0.0/mold.h:525:5: warning: Class 'Timer' does not have a operator= which is recommended since it has dynamic memory/resource allocation(s). [noOperatorEq]

**Comment by rui314** [comment]
I don't understand what this warning means. Did you?

**Comment by sicherha** [comment]
This message seems to come from cppcheck.

I believe cppcheck is concerned about the fact that the `record` member variable is dynamically allocated in the constructor of `Timer`. It wonders what is supposed to happen if the `Timer` object gets copied (via copy constructor or assignment operator): should the copied `Timer` hold a pointer to the same `TimerRecord` object as the original?

**Comment by rui314** [comment]
I think this is not a resource leak, as the `new`ed object is managed by another mechanism. I'll make a commit to remove copy constructor instead to see if it can silence your warning.

**Comment by sicherha** [comment]
In my understanding it's not so much about a potential resource *leak* as it is about potentially unwanted resource *sharing*.
But if you make the `Timer` object non-copyable, the concern will go away anyway. 🙂
