### ISSUE TITLE
elf: `%t/a.o %t/c.so %t/b.a` undef in c.so does not extract b.a

### ISSUE THREAD

**Issue by MaskRay** [rui314/mold#179]
```asm
# RUN: rm -rf %t && split-file %s %t
# RUN: llvm-mc -filetype=obj -triple=x86_64 %t/a.s -o %t/a.o
# RUN: llvm-mc -filetype=obj -triple=x86_64 %t/b.s -o %t/b.o
# RUN: llvm-mc -filetype=obj -triple=x86_64 %t/c.s -o %t/c.o
# RUN: llvm-ar rc %t/b.a %t/b.o
# RUN: ld.lld -shared -soname=b %t/c.o -o %t/c.so
# RUN: ld.lld %t/a.o %t/c.so %t/b.a -o %t/out

#--- a.s
.globl _start
_start:

#--- b.s
.globl foo
foo:

#--- c.s
call foo
```

This may appear to be fairly edge case.

In GNU ld, gold, and ld.lld, the undefined symbol in c.so causes b.a to be extracted. In mold, b.a is not extracted.

If b.a has a strong definition which can override a weak definition in a.o, the current semantics will not make that happen.
The current semantics can also suppress a possible duplicate definition error.

**Comment by rui314** [comment]
I think it is very hard or almost impossible to make our symbol resolution algorithm to behave exactly the same as other linkers for this kind of edge cases. Fortunately, this slight difference in semantics doesn't cause any problem while compiling thousands of Gentoo packages using mold. And even if it does, it is probably a bad programming practice to define the same symbol in many places. So I think mold is OK as-is.

**Comment by rui314** [comment]
I made a change to our symbol resolution algorithm in ce5749ce2fdb41488f0b0608d3fcc5cb016d9683, and I believe now undefined symbols in a DSO pulls out an object from an archive file.
