### ISSUE TITLE
elf: report warning instead of error for `-z unknown` 

### ISSUE THREAD

**Issue by MaskRay** [rui314/mold#180]
GNU ld always uses a warning for `-z unknown`.
There is a trend of having more optional options (usually security hardening related) like -z cet-report=, -z bti-report=, -z force-bti.
From my observation, the doing-essential-work -z foo is much fewer than the converse.

For lld, ld.lld 14.0.0 will use a warning, in 15/16/17/... timeframe when people add new options to software, they can worry less about linker errors on older linkers.

**Comment by rui314** [comment]
Thanks, that makes sense. I made a change accordingly.
