### ISSUE TITLE
Mention that openSUSE Tumbleweed provides mold linker

### ISSUE THREAD

**Issue by marxin** [rui314/mold#183]
Please mention at the homepage, that one can install the package:
https://software.opensuse.org/package/mold

with `zypper install mold` on openSUSE Tumbleweed.

**Comment by rui314** [comment]
Maybe should I just refer https://repology.org/project/mold/versions instead?

**Comment by marxin** [comment]
Works for me. Will be the `openSUSE` listed there automatically?

**Comment by rui314** [comment]
I assume so because its coverage seems excellent. I'd just wait for a few days for that gadget to pick up the openSUSE package.
