### ISSUE TITLE
-z nodefaultlib missing

### ISSUE THREAD

**Issue by haampie** [rui314/mold#184]
```
mold: mold: unknown command line option: -z nodefaultlib
```

**Comment by rui314** [comment]
mold does not have the notion of default search paths. Library paths need to be explicitly given via `-L`. So `-z nodefaultlib` option doesn't make sense. We should just ignore the flag for the sake of compatibility.

**Comment by haampie** [comment]
`-z nodefaultlib` is not a link-time but a run-time feature. It signals to runtime linker it should not consider it's system paths or cache, only rpaths/LD_LIBRARY_PATH.

**Comment by rui314** [comment]
Hmm, OK, I might have confused it with something else. Let me reopen this issue.

**Comment by rui314** [comment]
Implemented in https://github.com/rui314/mold/commit/8c86c2849697dd2a5747b075fa818ebead6b09e1
