### ISSUE TITLE
mold produces broken i686 ELF binaries

### ISSUE THREAD

**Issue by sicherha** [rui314/mold#185]
I'm on Fedora 35 x86_64, using the current `main` branch of mold. Trying to link even a trivial 32-bit 'hello world' C program results in a broken ELF binary that segfaults on execution.

This can easily be reproduced with a small shell script:
```sh
#!/bin/sh

set -e -u -x

cat <<EOF | cc -m32 -o a.o -c -xc -
#include <stdio.h>

int main() {
  printf("Hello world\n");
  return 0;
}
EOF
clang -fuse-ld=$PWD/mold -m32 -o exe a.o
./exe
```

Output from `dmesg`:
```
[19215.224202] exe[150734]: segfault at 0 ip 00000000f7f49194 sp 00000000ffa9a8c0 error 4 in ld-linux.so.2[f7f47000+23000]
[19215.224208] Code: 00 00 00 00 66 90 8b 7e 04 83 c0 0f 83 c8 03 01 f8 83 e0 fc 01 c6 8b 85 38 fe ff ff 01 f0 39 85 40 fe ff ff 0f 86 c1 10 00 00 <8b> 06 83 f8 04 75 d5 83 7e 08 05 75 cf 81 7e 0c 47 4e 55 00 75 c6
```

I have bisected the Git history and found the following commit to be the culprit:
```
commit 1f3931fc9e5c2e84fa9d77b10fcfcfc2f371818e (HEAD, refs/bisect/bad)
Author: Rui Ueyama <ruiu@cs.stanford.edu>
Date:   Tue Jun 1 00:53:06 2021 +0900

    Do not put non-alloc NOTE section into a PT_LOAD segment
    
    This bug caused a test failure of Gentoo's dev-lang/go-1.16.4
    paackage. Specifically, `go tool dist test testshared` failed
    due to this bug.
```

**Comment by sicherha** [comment]
Note that the shell script I provided above is derived from `test/elf/i386-hello-dynamic.sh`, which also fails for me but doesn't make it sufficiently clear that a segmentation fault is occurring.

**Comment by rui314** [comment]
Thank you for reporting! Honestly, i686 isn't as tested as x86-64, so it's likely to have more bugs than x86-64.

Does the test pass if you revert 1f3931fc9e5c2e84fa9d77b10fcfcfc2f371818e?

**Comment by sicherha** [comment]
Simply reverting that one commit (which requires fixing a few merge conflicts in `test/elf/note.sh`) doesn't seem to do the trick - now mold already bails out with a failed assertion:
```
mold: elf/passes.cc:849: mold::elf::i64 mold::elf::set_osec_offsets(Context<E> &) [E = mold::elf::I386]: Assertion `!(chunk.shdr.sh_flags & SHF_ALLOC)' failed.
clang-13: error: unable to execute command: Aborted (core dumped)
clang-13: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by rui314** [comment]
I set up a Fedora 35 environment on Docker and succeeded to reproduce the issue. It was mold's bug that it created an incorrect segment entry. I fixed the bug.

Thank you for your report. If you find other issue, feel free to file another bug report.
