### ISSUE TITLE
empty output sections need __start_ symbols too

### ISSUE THREAD

**Issue by FeepingCreature** [rui314/mold#19]
D uses __start___minfo, __stop___minfo to mark module info section. Sometimes that section can be empty. (I don't fully understand when?) But even empty sections need __start and __stop segments. Something like this?

```
diff --git a/main.cc b/main.cc
index b8d2173..40d98ed 100644
--- a/main.cc
+++ b/main.cc
@@ -1259,8 +1259,7 @@ int main(int argc, char **argv) {
 
   // Add sections to the section lists
   for (OutputSection *osec : OutputSection::instances)
-    if (osec->shdr.sh_size)
-      out::chunks.push_back(osec);
+    out::chunks.push_back(osec);
```
Seems to work for me.

**Comment by rui314** [comment]
Out of curiosity, can you link D programs only with that change?

**Comment by FeepingCreature** [comment]
I mean, the one program I tried with ldc 1.24.0 only got to run with that change, but I don't know if it's a general requirement.

I just ran ldc with -v, picked up the linker line, and dropped flags until it worked. :)

**Comment by rui314** [comment]
This has been fixed. Also mold has gained support of `-push-state` and `-pop-state`.
