### ISSUE TITLE
GCC 12.x+ supports -fuse-ld=mold

### ISSUE THREAD

**Issue by marxin** [rui314/mold#205]
I've just installed patch:
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=ad964f7eaef9c03ce68a01cfdd7fde9d56524868

that support `-fuse-ld=mold` on the current master. So starting with `12.1.0`, one can invoke GCC with `-fuse-ld=mold`.
Please document the change. Thanks.

**Comment by rui314** [comment]
This is really great. Thank you for doing this! I updated README accordingly.

**Comment by marxin** [comment]
You're welcome.
