### ISSUE TITLE
--defsym support is missing

### ISSUE THREAD

**Issue by scardracs** [rui314/mold#208]
On gentoo we (at least proxy maintainers and devs) use to add `-Wl,--defsym=__gentoo_check_ldflags__=0` on LDFLAGS, this let us know if a package does not respect LDFAGS. Could you take a look into it and add that feature too? Actually running any installation with the flag enabled ends into that error `mold: mold: unknown command line option: --defsym=__gentoo_check_ldflags__=0
`

Used version of mold: 1.0.0

**Comment by rui314** [comment]
I implemented `--defsym` in the above change.

**Comment by scardracs** [comment]
Awesome, thanks! :D
