### ISSUE TITLE
Compilation on Windows with MSYS2 + mingw-64: about shared mem in MappedFile<C>::open() in mold.h

### ISSUE THREAD

**Issue by vtorri** [rui314/mold#211]
I tried to compile old on Windows with MSYS2 + mingw-w64 and gcc.

problem: mmap (mold.h). On Windows:

 * mman.h does not exist on Windows
 * shared mem is done withCreateFileMaping() + MapViewOfFile()
 * this requires windows.h and not sys/mman.h
 * it needs a HANDLE of the file, preferably returned with CreateFile() and not open() + _get_osfhandle().
 * on Windows, preferably use wchar_t instead of char for strings, but it's not a hard requirement
 * in this function to get st.mtime, i can use the HANDLE above with GetFileInformationByHandle()

I can help as I did this kind of code several time.

@rui314:
 * no problem if a do some #ifdef _WIN32 in this function to port it to Windows, and also for sys/mman.h at the top ?
 * do you think it is possible to support wchar_t * (std::wstring) easily on Windows ?

I can provide a PR if you want

thank you

**Comment by rui314** [comment]
Thank you for your suggestion, but I think it is a bit too early to start doing something for Windows. mold can't produce an Windows executable, so even if you improve mold so that it works on Windows, it will only be used for cross compilation. So I'd like to revisit this after we start working on mold for Windows.

**Comment by vtorri** [comment]
Well, i currently compile (with errors of course) natively on Windows with MSYS2. Technically, using MSYS2 is cross-compilation (Windows on Windows), but I can create native executables with it.

And use meson instead of a Makefile to avoid all the problems inherent to Windows (.dll for extension oflibraries, installation of dll in bin/ and not lib, creation of  import lib etc...)

**Comment by rui314** [comment]
mold can only produce ELF and Mach-O binaries so far. Can it produce a native executable for Windows?

**Comment by vtorri** [comment]
i was talking about producing mold.exe. I can guess that creating the linker for Windows is a difficult task, but one should start somewhere. mold.exe must exist before mold.exe creates PE files on Windows, no ?

**Comment by rui314** [comment]
Yes, but I want to make it possible just before we start working on mold for Windows.

**Comment by vtorri** [comment]
ok

**Comment by septag** [comment]
@vtorri I had to bring this up again and ask you a question. Could you describe a little bit on how you built mold.exe with msys2 ? 
I just need mold to produce android binaries on windows, but I'm fairly new to msys2 and I'm getting compile errors, so I would appreciate some pointers. Thanks

**Comment by vtorri** [comment]
@septag i have not built mold on Windows with MSYS2, i have tried to compile it and there are several compilation errors. The author (@rui314 ) does not want to support Windows right now.

**Comment by vtorri** [comment]
@septag normally you should have the same errors than me. You can paste them here between ``` and ```

**Comment by septag** [comment]
> @septag i have not built mold on Windows with MSYS2, i have tried to compile it and there are several compilation errors. The author (@rui314 ) does not want to support Windows right now.

yes I was aware of that, but like I said, I just want to the windows binary that generates android output for cross compiling. so I guess it would be technically possible with msys2 ?  

ok, I will try again and post errors here ..

**Comment by Alcaro** [comment]
Compilation errors mean not possible. If you need it, try WSL, Cygwin, or a virtual machine. Or use lld until mold is ready.

**Comment by rui314** [comment]
I'm sorry, but I don't have enough resources to make this compile on Windows. And even if you succeed to compile mold on Windows, I believe mold won't work out of the box. For example, currently we do not have any code to handle drive names (like `C:/` or `D:/`) in pathnames. Therefore, in the meantime, as @Alcaro suggested, please use WSL or something if you want to use mold, or just use lld.

**Comment by vtorri** [comment]
> I'm sorry, but I don't have enough resources to make this compile on Windows.

that's why i proposed my help :-) But I'll wait for the mac port to be finished. I hope soon

**Comment by rui314** [comment]
I mean even if you or I can make a one-time change to make mold compile on Windows, I don't think I maintain it to keep it working on Windows. That maintenance part needs resources.

**Comment by vtorri** [comment]
just fyi: I've ported to Windows and maintaining  this port, a whole toolkit, plus other libraries out there. I've written a pet tool to check mem leaks and read PE structures on Windows, I'm helping David Anderson for libdwarf (though it's mainly not the libdwarf code itself as it was already written). So I think that I can help.

**Comment by rui314** [comment]
@vtorri How large is your patch to mold?

**Comment by vtorri** [comment]
As you said you didn't want it until mac port is done, i didn't write any, I've just ask questions in my first comment.. But I can do it this week

**Comment by rui314** [comment]
I misunderstood that "this port" meant mold. Ok, unless you are very motivated, let's not port mold to Windows at this moment. Sorry for the confusion.
