### ISSUE TITLE
user experience: add mold logo for social media preview

### ISSUE THREAD

**Issue by odeke-em** [rui314/mold#215]
If we examine the GitHub docs at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview they show how to customize a logo to display on social media.

Currently it is @rui314's avatar per
![image](https://user-images.githubusercontent.com/4898263/147796148-de8b9bcf-d506-44de-9ca9-d44760e8373c.png)

But it could be the nice logo in the README

**Comment by rui314** [comment]
Thanks. I set that image as a logo.

**Comment by odeke-em** [comment]
> Thanks. I set that image as a logo.

Cool, thank you Rui!
