### ISSUE TITLE
Missing support for relocation type: R_X86_64_GOTOFF64

### ISSUE THREAD

**Issue by dcb314** [rui314/mold#224]
From current github mold, I get error message:

mold: error: build.OPENIB_FF.release.opa10/stream.o:(.text): unknown relocation: R_X86_64_GOTOFF64

**Comment by BenBE** [comment]
Do you have a minimal example test case to trigger this issue?

**Comment by dcb314** [comment]
Command line is

gcc  -Wl,-z,noexecstack -z relro -z now     -fopenmp -pie -L/home/dcb35/rpmbuild/BUILD/eth-fast-fabric-11.1.0.1/builtlibs.OPENIB_FF.release.opa10 -Xlinker -rpath-link -Xlinker /home/dcb35/rpmbuild/BUILD/eth-fast-fabric-11.1.0.1/builtlibs.OPENIB_FF.release.opa10  -o build.OPENIB_FF.release.opa10/stream build.OPENIB_FF.release.opa10/stream.o -Xlinker --start-group   -Xlinker --end-group -lpthread

I am not sure how to attach the stream.o file.

**Comment by rui314** [comment]
Thank you for your report! I implemented that relocation in the above patch.

**Comment by dcb314** [comment]
I tried it out on package eth-tools and it seemed to work. 

Thanks very much for a fast fix.
