### ISSUE TITLE
 unknown file type

### ISSUE THREAD

**Issue by dcb314** [rui314/mold#227]
I just got error message:

jgmenu.spec.out:mold: jgmenu.o: unknown file type

without any clue as to the type number. Source code in elf/main.cc is

  default:
    Fatal(ctx) << mf->name << ": unknown file type";

Suggest new code:

    Fatal(ctx) << mf->name << ": unknown file type " << get_file_type(mf);

**Comment by rui314** [comment]
If the code reach there, `get_file_type(mf)` must have returned `FileType::UNKNOWN`, so adding that result to the output wouldn't make it better.

What actually was your `jgmenu.o`? What `file` command says when you run `file jgmenu.o`?

**Comment by dcb314** [comment]
$ file ../BUILD/jgmenu-4.4.0/jgmenu.o
../BUILD/jgmenu-4.4.0/jgmenu.o: empty

**Comment by rui314** [comment]
OK, we can print out a better error message for the empty file. I'll do that.
