### ISSUE TITLE
`  = note: mold: unknown command line option: -dynamic           clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### ISSUE THREAD

**Issue by guswynn** [rui314/mold#245]
I know `mold` for macos is pre-alpha, but I was testing it out on some rust code and got this error today:
```
  = note: mold: unknown command line option: -dynamic
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I didn't see any other issues about this, so I figured i'd make an issue to track it! please close if this is too noisy!

**Comment by rui314** [comment]
As you guessed, mold for macOS is so incomplete that we don't use GitHub issues to track missing features at this moment. Please allow us a few more months to file a bug against it.

**Comment by guswynn** [comment]
@rui314 sorry for the noise!
