### ISSUE TITLE
mold sometimes see warnings about not respecting LDFLAGS even if bfd/lld do not show any error

### ISSUE THREAD

**Issue by scardracs** [rui314/mold#247]
Hi @rui314,

sometimes mold triggers an LDFLAGS QA warning (see for eg https://bugs.gentoo.org/830563) even if bfd/ld/lld do not show any warning. If possible please take a look into it.

How to reproduce:

In gentoo we use to add LDFLAGS="... -Wl,--defsym=__gentoo_check_ldflags__=0 ..." to check if LDFLAGS are respected or not.

**Comment by BenBE** [comment]
Isn't this a duplicate of #208?

**Comment by rui314** [comment]
I believe so. If not, please reopen this issue.

**Comment by scardracs** [comment]
It isn't, in the older issue I'm asking for adding --defsym functionality while now I'm saying there's something wrong with it because it spawns (false ?) QA warnings about LDFLAGS not respected

**Comment by scardracs** [comment]
I put another example, to be more clear. SystemD actually does not have any LDFLAGS issues but mold triggers them:

 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /bin/journalctl
 * /bin/networkctl
 * /bin/systemd-creds
 * /bin/systemd-inhibit
 * /bin/systemd-repart
 * /bin/systemd-sysext
 * /bin/systemd-tty-ask-password-agent
 * /bin/userdbctl
 * /lib/systemd/systemd-backlight
 * /lib/systemd/systemd-coredump
 * /lib/systemd/systemd-fsck
 * /lib/systemd/systemd-localed
 * /lib/systemd/systemd-networkd-wait-online
 * /lib/systemd/systemd-oomd
 * /lib/systemd/systemd-portabled
 * /lib/systemd/systemd-random-seed
 * /lib/systemd/systemd-shutdown
 * /lib/systemd/systemd-sleep
 * /lib/systemd/systemd-sysctl
 * /lib/systemd/systemd-timedated
 * /lib/systemd/systemd-user-runtime-dir
 * /lib/systemd/systemd-userdbd
 * /lib/systemd/systemd-userwork
 * /usr/bin/busctl
 * /usr/bin/coredumpctl
 * /usr/bin/localectl
 * /usr/bin/systemd-cgtop
 * /usr/bin/systemd-delta
 * /usr/bin/systemd-dissect
 * /usr/bin/systemd-run
 * /usr/bin/systemd-socket-activate
 * /usr/bin/systemd-stdio-bridge

**Comment by scardracs** [comment]
These are my *FLAGS, but actually I don't see anything wrong with them...

```
COMMON_FLAGS="-O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches"
CFLAGS="${COMMON_FLAGS} -ggdb"
CXXFLAGS="${COMMON_FLAGS} -ggdb"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${LDFLAGS} -fuse-ld=mold -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0"
PORTAGE_ELOG_CLASSES="${PORTAGE_ELOG_CLASSES} qa warn"
FEATURES="${FEATURES} ccache qa-unresolved-soname-deps"
```

**Comment by scardracs** [comment]
My command, for gettext, should be something like x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -ggdb -Wl,-O1 -Wl,--as-needed -fuse-ld=mold -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0

**Comment by rui314** [comment]
Could you paste the command that you executed and its entire output including the error message here?

**Comment by scardracs** [comment]
I'm sorry, I've removed mold for now because I need to make some test for my packages and need to have "common" linker. I'll try it again in few weeks.

**Comment by scardracs** [comment]
Ok, I've moved back to mold and can confirm it still show these QA warnings. I post here the full log of gettext (as we used it as example). I add the fact that I'm using -fuse-ld=mold instead of '''/usr/bin/ld''' [gettext.log](https://github.com/rui314/mold/files/7920007/gettext.log)

**Comment by scardracs** [comment]
> @scardracs I built gettext with `emerge sys-devel/gettext` with `/usr/bin/ld` being mold. I didn't notice anything interesting, and it looks it builded fine. What was your problem? Please paste your command execution log.

If I link as you suggested it works!
