### ISSUE TITLE
Mold links more than gold

### ISSUE THREAD

**Issue by rossburton** [rui314/mold#254]
I'm building [glib](https://gitlab.gnome.org/GNOME/glib) and have noticed that mold is putting more libraries into NEEDED than gold is:

With gold:
```
$ objdump -p glib-gold/image/usr/bin/gsettings | grep NEEDED
  NEEDED               libgio-2.0.so.0
  NEEDED               libglib-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libc.so.6
  NEEDED               ld-linux-aarch64.so.1
```

But with mold:
```
$ objdump -p glib-mold/image/usr/bin/gsettings | grep NEEDED
  NEEDED               libgio-2.0.so.0
  NEEDED               libgmodule-2.0.so.0
  NEEDED               libglib-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libc.so.6
  NEEDED               ld-linux-aarch64.so.1
```

The linkage to `libgmodule` should be implicit: gsettings doesn't directly use it, it gets pulled in via libgio at runtime.

**Comment by rossburton** [comment]
Some of the binaries are vastly different in size too:

```
-rwxr-xr-x 1 ross ross   11704 Jan  5 12:08 glib-gold/image/usr/lib/libgthread-2.0.so.0.7000.2
-rwxr-xr-x 1 ross ross 1051008 Jan  5 12:17 glib-mold/image/usr/lib/libgthread-2.0.so.0.7000.2
```

**Comment by rui314** [comment]
I confirmed the issue. mold indeed created bigger executables and shared objects for glib. Although I believe it doesn't directly affects correctness, creating larger binaries are undesirable. I'll take a look at it and fix it.

**Comment by rossburton** [comment]
What lead me to discover this was that our packing tools (rpmdeps) fail to read the SONAME field from the glib library headers, and I’m hoping this is related…

**Comment by rui314** [comment]
Did you remember which shared object file rpmdeps report the error for?

**Comment by rossburton** [comment]
All of the glib libraries have the problem.  The underlying tool is `elfdeps`, typically at `/usr/lib/rpm/elfdeps` if you have RPM installed.  `--provides` will list the sonames.

With gold:
```
$ /usr/lib/rpm/elfdeps glib-gold/image/usr/lib/libgio-2.0.so.0.7000.2 --provides
libgio-2.0.so.0()(64bit)
$
```
But with mold b18d488:
```
$ /usr/lib/rpm/elfdeps glib-mold/image/usr/lib/libgio-2.0.so.0.7000.2 --provides
$
```

**Comment by rui314** [comment]
The above change should fix the `elfdeps` issue.

mold-generated libgthread's size is still slightly larger, but that's perhaps due to alignment or something. mold no longer creates a one megabyte libgthread-2.0.so.

```
-rwxrwxr-x 1 ruiu ruiu 17960 Jan 12 21:15 ./bfd/gthread/libgthread-2.0.so.0.7100.0
-rwxrwxr-x 1 ruiu ruiu 55424 Jan 12 21:15 ./mold/gthread/libgthread-2.0.so.0.7100.0
```

**Comment by rossburton** [comment]
I'll file a bug with RPM about that behaviour. Thanks, I'll test this shortly.

**Comment by rui314** [comment]
FYI, here is a better way to distinguish shared object files from position-independent executables.

1. Look for `DT_FLAGS_1` dynamic section entry
2. Check if `DF_1_PIE` bit is set. If so, it's position-independent executable. Otherwise shared object file.

If `DT_FLAGS_1` entry is not present, I believe you can safely assume that that's a shared object file.

**Comment by rui314** [comment]
Please paste a URL to the RPM's bug as a cross reference if you have filed already. Thanks!

**Comment by rossburton** [comment]
Filed https://github.com/rpm-software-management/rpm/issues/1887.
