### ISSUE TITLE
mold aborts with --version-script

### ISSUE THREAD

**Issue by marxin** [rui314/mold#258]
Noticed the while linking listdc++:

```
$ echo '' | gcc -c -x c -o x.o -
$ cat x.ver
GLIBCXX_3.4 {
    extern "C++"
    {
    };
    _ZNSsC[12]EPKc*;
};

$ mold --version-script=x.ver -m elf_x86_64 x.o
Aborted (core dumped)
```

**Comment by marxin** [comment]
Note it's with the current master, `1.0.1` works fine.

**Comment by rui314** [comment]
I added a test to make sure that it's fixed.

**Comment by marxin** [comment]
Is it really fixed? I still see it crashing with 404fa1288b5094a2e5e3ed8cb6ea45eed937b187.

**Comment by rui314** [comment]
Sorry, I thought that the crash was caused by the empty `extern "C++"` clause, but it was actually caused by `[12]` in the following pattern. I fixed it in the above commit.

**Comment by marxin** [comment]
Great, it works now, thanks!
