### ISSUE TITLE
Link failure with static musl libc

### ISSUE THREAD

**Issue by bossmc** [rui314/mold#262]
Digging into the second half of https://github.com/rui314/mold/issues/216 I've reduced the problem to a minimal reproduction:

```
$ cat test.c
int main() {
  return 0;
}
$ clang -c test.c
$ musl=/path/to/musl/lib/dir
$ mold -static -o test ${musl}/crti.o ${musl}/Scrt1.o test.o ${musl}/libc.a ${musl}/crtn.o
mold: error: undefined symbol: lib/libc.a(__libc_start_main.lo): __sysinfo
mold: error: undefined symbol: lib/libc.a(__init_tls.lo): __sysinfo
```

_Note that the link command (and the associated binary) works with `lld`/`ld`/`gold`/`bfd`._

Digging into what's special about `__sysinfo`:

```
$ readelf --syms ${musl}/libc.a | grep __sysmain
File: lib/libc.a(__init_tls.lo)
    20: 0000000000000000     0 NOTYPE  GLOBAL HIDDEN   UND __sysinfo
File: lib/libc.a(__libc_start_main.lo)
    28: 0000000000000000     0 NOTYPE  GLOBAL HIDDEN   UND __sysinfo
File: lib/libc.a(defsysinfo.lo)
     8: 0000000000000008     8 OBJECT  GLOBAL HIDDEN   COM __sysinfo
```

So it seems that `mold` is unwilling to use the symbol in `defsysinfo.lo` to satisfy the holes in `__init_tls.lo` and `__libc_start_main.lo` while the other linkers are.  I initially suspected that the fact that the symbols were `HIDDEN` was why the symbol in `defsysinfo.lo` was being rejected for consideration but rebuilding musl's `libc.a` to remove the `hidden` attribute, I still see the same error from `mold`:

```
$ readelf --syms lib/libc.a | grep __sysinfo
    21: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __sysinfo
    28: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __sysinfo
     8: 0000000000000008     8 OBJECT  GLOBAL DEFAULT  COM __sysinfo
$ ../mold/mold -static -o test lib/crti.o lib/Scrt1.o test.o lib/libc.a lib/crtn.o
mold: error: undefined symbol: lib/libc.a(__init_tls.lo): __sysinfo
mold: error: undefined symbol: lib/libc.a(__libc_start_main.lo): __sysinfo
```

Tested with the master build of `mold` and against musl 1.1.24 (which is the version used by the Rust compiler for now).

**Comment by Alcaro** [comment]
That sounds quite similar to #256.

**Comment by bossmc** [comment]
Ah, maybe, does seem similar (common symbol in archive seems to be the recurring theme).  Happy to close this or keep it as another repro/example if that's useful.

**Comment by bossmc** [comment]
In fact, in that issue @rui314 asks:

> I wonder if there's a program in the wild that depends on this subtle difference.

Statically linking against the musl libc is very common in Rust codebases (using the `x86_64-unknown-linux-musl` target) and the musl `libc.a` depends on this function, so I'd hope this is a motivating example 😁

**Comment by rui314** [comment]
@bossmc Thank you for investigating. Let's keep this bug open. We need to make musl users happy, so it seems mold's behavior needs fixing.

I can't casually change the behavior, though, because changing it to fix musl's problem can cause other programs to fail to link. So it may take a while to fix this issue, but I'll do that before 1.0.2.

**Comment by bossmc** [comment]
One thing I noticed (when reading your notes in the other issue) is that Musl's `defsysinfo.c` is simply:

```
#include "libc.h"  // Doesn't introduce any symbols

size_t __sysinfo
```

So the object is builds into has only one (interesting) symbol present and thus, unless `mold` elects to use that specific symbol it won't get pulled in for any other reason.  If this symbol was in some other object then the link might work by luck since the object might be selected for one of its other symbols.

It seems to me that the handling for common symbols has to include some logic of the form "if there's any instance of symbol `X` as a common instance and there's no non-common instance of `X` and there's any reference(s) to `X` then (any) one of the objects providing the common symbol have to be included".  I'm not sure if that logic is covered by the bullets in the other issue (which seems to only kick in if the requesting object is not in the archive containing the common symbol...) but does seem to be happening when `ld`/lld` are linking the objects.

**Comment by rui314** [comment]
Besides the bug in mold, I think musl should be built with the `-fno-common` compiler flag. Common symbol in C is a workaround for old C code that doesn't add the `extern` keyword to global variable declarations in header files. These days, it is not useful and tend to rather hide a possible issue in source code.

GCC 10 defaults to `-fno-common` for that reason (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678) and so is LLVM (https://github.com/llvm/llvm-project/commit/0a9fc9233e172601e26381810d093e02ef410f65). Therefore, if you do not add neither `-fno-common` nor `-fcommon`, musl libc symbols became common or regular defined symbols depending on the build system. That's not an issue per se, but that's I think unnecessary churn.

**Comment by rui314** [comment]
I sent a patch to musl to always add the `-fno-common` flag. We need to fix this mold's issue anyway for existing musl versions though.

**Comment by rui314** [comment]
Should be fixed in https://github.com/rui314/mold/commit/27d836180fb7868bf7cd6e87917e0c09531dd945

**Comment by bossmc** [comment]
Thanks @rui314 - great work!
