### ISSUE TITLE
node-v16.13.1 (LTS) fails to work if mold-1.0.1 is used as default linker

### ISSUE THREAD

**Issue by scardracs** [rui314/mold#264]
Expected results:  
node and npm command works
  
Current result:  
error: fish: Job 1, 'node' terminated by signal SIGSEGV (Address boundary error)  

Reproducible: always

**Comment by scardracs** [comment]
If you need more infos please let me know

**Comment by rui314** [comment]
What is the command you actually ran? Just `node` or with some other arguments?

**Comment by scardracs** [comment]
> What is the command you actually ran? Just `node` or with some other arguments?

node or npm, same error here

**Comment by rui314** [comment]
I can create a working node.js binary using mold on Ubuntu 22.04. Please provide more info about how to reproduce your problem. What command did you _actually_ run on what machine? Please paste your command and its output as part of a bug report.

**Comment by scardracs** [comment]
Nevermind, it was my fault. I've resolved myself 😅 thanks for your effort on mold.

**Comment by rui314** [comment]
Good to know that it actually worked for you. If you find any other problem, feel free to file abug.
