### ISSUE TITLE
[question] what is the minimal compiler version to compile on linux?

### ISSUE THREAD

**Issue by stefson** [rui314/mold#265]
hey there, 

can you please update the README.md with the minimal versions of gcc and clang, which you support for compiling mold? 
you state that the compiler has to support C++20, but that implementation is not fully implemented into clang yet:

```
C++20 implementation status

Clang has support for some of the features of the ISO C++ 2020 standard.

[followed by a very long list of pullrequests] 
```
full list is here: https://clang.llvm.org/cxx_status.html ; please croll down a bit for details on C++20

adding confusion on my side is, that you state to use ubuntu-20.04 for your developement, which ships with gcc-9.3.0 accoding to distrowatch information. I use gcc-9.4.0, but that fails to compile mold for me. My systems llvm/clang is 11.1.0, but fails to compile mold as well for me. 

I surely am willing to upgrade the compiler, but again it will be really helpfull to know which version to install. 

thank you

**Comment by rui314** [comment]
Building mold can fail for various reasons. Can you share the output of your `make` run?

**Comment by stefson** [comment]
so the system gcc is 9.4.0, the corresponding llvm/clang-11.1.0 toolchain is installed alongside of it. 

first obvious problem is, that stock gcc-9.4.0 doesn't understand ``-std=c++20`` : 

```
armv7a-unknown-linux-musleabihf-g++ -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/lib\"" -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -fomit-frame-pointer -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions -c -o out/filepath.o filepath.cc
armv7a-unknown-linux-musleabihf-g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
make: *** [Makefile:126: out/compress.o] Error 1
make: *** Waiting for unfinished jobs....
```

patching makefile with ``-std=c++2a`` shows: 

```
armv7a-unknown-linux-musleabihf-g++ -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/lib\"" -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -fomit-frame-pointer -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++2a -fno-exceptions -c -o out/filepath.o filepath.cc
In file included from demangle.cc:1:
mold.h:12:10: fatal error: span: No such file or directory
   12 | #include <span>
      |          ^~~~~~
compilation terminated.
make: *** [Makefile:126: out/demangle.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from compress.cc:15:
mold.h:12:10: fatal error: span: No such file or directory
   12 | #include <span>
      |          ^~~~~~
compilation terminated.
In file included from filepath.cc:1:
mold.h:12:10: fatal error: span: No such file or directory
   12 | #include <span>
      |          ^~~~~~
compilation terminated.
```

missing span header indicates incomplete C++20 support in gcc-9 compiler. 

so what is the minimal gcc version? is it sufficent to upgrade to gcc-10? 

with clang-11.1.0, it is similar to the patched approach to gcc-9.4.0:

```
clang++-11 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/lib\"" -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -fomit-frame-pointer -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions -c -o out/hyperloglog.o hyperloglog.cc
In file included from compress.cc:15:
./mold.h:12:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
In file included from demangle.cc:1:
./mold.h:12:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
In file included from filepath.cc:1:
./mold.h:12:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
In file included from hyperloglog.cc:7:
./mold.h:12:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~

```

**Comment by ADKaster** [comment]
On SerenityOS we found that gcc 10.2 and clang 12.0.0 were the minimum to compile all the c++20 language features we use. According to https://en.cppreference.com/w/cpp/compiler_support#cpp20 though, `<span>` was added in libstdc++ 10 and libc++ 7. So, you'll probably need a way to have either clang use it's own shipped libc++, or grab a newer gcc + libstdc++ package from your package manager.

**Comment by rui314** [comment]
Thank @ADKaster, I added that information to README.
