### ISSUE TITLE
building on debian 10 buster

### ISSUE THREAD

**Issue by djdisodo** [rui314/mold#27]
I'm using debian 10 which has no gcc-10 or clang-10 package
so I'm using clang and libc++ from llvm apt repo
and added -stdlib=libc++
but i'm unable to build as some headers are missing like "cstdint" "atomic"

**Comment by rui314** [comment]
<cstdint> and <atomic> aren't new at all, so if your compiler can't include them, it is likely that you cannot build any C++ program on your machine. Have you tried compiling programs other than mold?

**Comment by djdisodo** [comment]
@rui314 this problem came because i used libc++ instead of libstdc++
I wasn't able to install libstdc++-10-dev on debian 10
so i had to use libc++ instead
now, i just updated my pc to debian unstable and just works

**Comment by rui314** [comment]
Glad to hear that you succeeded to build this program!
