### ISSUE TITLE
mold fails if you don't own existing output

### ISSUE THREAD

**Issue by shinh** [rui314/mold#275]
mold fails if you don't own existing output

Reproduce script:

```
#!/bin/bash
echo 'int main() {}' > main.c
gcc -c main.c
rm -f a.out
sudo ./mold main.o -o a.out
sudo chmod 777 a.out
./mold main.o -o a.out
```

mold outputs:

```
mold: fchmod failed
```

If you change `mold` to `ld.bfd`, `ld.gold`, or `ld.lld`, the script succeeds.

I believe the culprit is `rename` call here: https://github.com/rui314/mold/blob/945348842420e5ffcfcb7952ccdbdefaeb12be4b/elf/output-file.cc#L28 Removing this block fixed the issue. I guess this is an optimization for better disk cache utilization?

I'm not sure if I can claim this is a bug of mold. The situation, you don't own the output file but have write permission, is a bit odd. If we fix this issue, checking the owner of the existing destination file before `rename` would work.

**Comment by rui314** [comment]
Being a drop-in replacement of the GNU linker, I think it is better to behave just like GNU ld does. So, if chmod failed, we should handle it as if the output file weren't exist. I'll make such change.

**Comment by shinh** [comment]
Thanks for the quick fix!
