### ISSUE TITLE
mold fails to build on s390x-linux-gnu and riscv64-linux-gnu

### ISSUE THREAD

**Issue by doko42** [rui314/mold#276]
a first step at packaging:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+sourcepub/13210136/+listing-archive-extra

fails to build on s390x and riscv64

In file included from /<<PKGBUILDDIR>>/third-party/tbb/src/tbb/tools_api/ittnotify_static.c:17,
                 from /<<PKGBUILDDIR>>/third-party/tbb/src/tbb/itt_notify.cpp:43:
/<<PKGBUILDDIR>>/third-party/tbb/src/tbb/tools_api/ittnotify_config.h: In function ‘long int __itt_interlocked_increment(volatile long int*)’:
/<<PKGBUILDDIR>>/third-party/tbb/src/tbb/tools_api/ittnotify_config.h:348:12: error: ‘__TBB_machine_fetchadd4’ was not declared in this scope
  348 |     return __TBB_machine_fetchadd4(ptr, 1) + 1L;
      |            ^~~~~~~~~~~~~~~~~~~~~~~

is there a way to build with the tbb provided by the distribution?

**Comment by Alcaro** [comment]
See also: #267, #222

Yes, you can set SYSTEM_TBB=1 on the make invocation.

Looks to me like an issue in upstream TBB. We're on the latest release (2021.5), did anyone file that issue? ...does Intel even have a proper bug tracker?

**Comment by rui314** [comment]
As @Alcaro pointed out, it looks like Intel OneTBB library cannot be built on those ISAs. Please report the issue to Intel at https://github.com/oneapi-src/oneTBB.

Besides that, I want to make it clear that even if you can build mold on s390 and RISC-V, mold can't be used to build programs on those machines. Being able to run on architecture A is different from being able to produce machine code for architecture A. Only you can do would be cross compilation (from RISC-V or s390 to x86-64, i386 or ARM64). So, for now, I believe it is better to just support x86-64, i386 and ARM64 unless you have another reason to run mold on other architectures.

**Comment by rui314** [comment]
We now support riscv64 and s390x both as hosts and targets.
