### ISSUE TITLE
Whether to consider adding a third-party build system

### ISSUE THREAD

**Issue by waruqi** [rui314/mold#280]
mold is great, have you considered adding a third-party build system to provide more convenient cross-platform builds and dependency management?

I used the [xmake](https://github.com/xmake-io/xmake) build tool to make a basic port that provides builds for linux, macos and android platforms, if you are interested, I will open a pr and further improve it to support installation and add tests.

the port file: [xmake.lua](https://github.com/waruqi/mold/blob/xmake/xmake.lua)

### MacOS and Linux

```console
$ xmake
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> tbb 2021.4.0 
  -> xxhash v0.8.0 
please input: y (y/n/m)

  => install xxhash v0.8.0 .. ok                 
  => install tbb 2021.4.0 .. ok    
[  2%]: ccache compiling.release main.cc
[  2%]: ccache compiling.release elf/main.cc
[  2%]: ccache compiling.release elf/arch-arm64.cc
[  2%]: ccache compiling.release compress.cc
[  2%]: ccache compiling.release perf.cc
[  2%]: ccache compiling.release tar.cc
[  2%]: ccache compiling.release filepath.cc
...
[ 62%]: ccache compiling.release macho/dead-strip.cc
[ 65%]: ccache compiling.release macho/output-chunks.cc
[ 95%]: linking.release mold
[100%]: build ok!
```

### Android

```console
 xmake f -p android --ndk=~/files/android-ndk-r23b/
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> tbb 2021.4.0 
  -> xxhash v0.8.0 
  -> zlib 1.2.11 
  -> openssl 1.1.1l 
please input: y (y/n/m)

  => download https://github.com.cnpmjs.org/madler/zlib/archive/v1.2.11.tar.gz .. ok
  => install xxhash v0.8.0 .. ok                                      
  => install zlib 1.2.11 .. ok                                
  => install tbb 2021.4.0 .. ok                  
  => install openssl 1.1.1l .. ok  
ruki-2:mold ruki$ xmake
[  2%]: ccache compiling.release elf/arch-i386.cc
[  2%]: ccache compiling.release demangle.cc
[  2%]: ccache compiling.release hyperloglog.cc
[  2%]: ccache compiling.release main.cc
...
[ 62%]: ccache compiling.release macho/dead-strip.cc
[ 65%]: ccache compiling.release macho/output-chunks.cc
[ 95%]: linking.release mold
[100%]: build ok!
```

### Enable LTO

```console
$ xmake f --lto=y
$ xmake
```

### Build for debug

```console
$ xmake f -m debug
$ xmake
```

### Build for Asan

```console
$ xmake f -m asan
$ xmake
```

### Build for Tsan

```console
$ xmake f -m tsan
$ xmake
```

### Run 

```console
$ xmake run mold --version
mold 1.0.1 (fd6d6e8fc8c5e62df9fe553993d8a034b70cd90f; compatible with GNU ld)
```

BTW, I have added mold to the [xmake-repo](https://github.com/xmake-io/xmake-repo/blob/master/packages/m/mold/xmake.lua) repository, we can install and use it with the following command.

```console
$ xrepo install mold
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> mold 1.0.1 
please input: y (y/n/m)

  => install mold 1.0.1 .. ok   
$ xrepo env -b mold shell
[xmake] working > mold --version
mold 1.0.1 (fe209f3f4c7177b0613f8c10f38862a23d8fb8f0; compatible with GNU ld)
```

**Comment by rui314** [comment]
I want to support cross build in the future, but I have a little concern about supporting it at this moment, as I don't think I can maintain it, in particular in a build system that I'm totally unfamiliar with (I haven't heard of `xmake` before). So, I think it's a bit too early to work in this area?

**Comment by waruqi** [comment]
Thanks for your reply, I'll add cross-compilation support for you if you want, and maintain it permanently. Of course, I can also understand your concerns, it doesn't matter if you don't want to consider xmake at the moment.

**Comment by rui314** [comment]
Start supporting cross build and choosing xmake for that purpose are a kind of a commitment, and I'd think I'm not ready to make such commitment. I'm thinking of introducing CMake at some point in the future (in particular when I have to support Windows), and I'm not sure how it would interact for xmake. There are many other technical points that I want to investigate, and I simply don't have enough time to do that right now.

**Comment by waruqi** [comment]
ok, I understand.
