### ISSUE TITLE
possible type in README.md about gcc-12.1.0

### ISSUE THREAD

**Issue by stefson** [rui314/mold#282]
hey, I just read through the readme.md and found a note about gcc version 12.1.0: 

```

If you can specify an additional command line option to your compiler
driver by modifying build system's config files, add one of the
following flags to use `mold` instead of `/usr/bin/ld`:

- Clang: pass `-fuse-ld=mold`

- GCC 12.1.0 or later: pass `-fuse-ld=mold`

- GCC before 12.1.0: `-fuse-ld` does not accept `mold` as a valid
  argument, so you need to use `-B` option instead. `-B` is an option
  to tell GCC where to look for external commands such as `ld`.

```

I can only imagine its a typo or other missunderstanding, as gcc-12 is still in developement and not yet released. Can you please clearify this? Thank you

**Comment by Alcaro** [comment]
It means the gcc development branch [supports that flag](https://www.phoronix.com/scan.php?page=news_item&px=GCC-12-Mold-Linker), and once gcc-dev becomes gcc-12, it will keep supporting that flag. Sure, it's kinda rare to talk about unreleased software like that, but unless GCC skips version 12, it's correct.

**Comment by rui314** [comment]
Yes, the feature is actually coming to the next release of gcc.

**Comment by stefson** [comment]
Can you maybe clearify this in the readme.md file? Something along of: this feature will be a part of a stable gcc-12 release, and is available for testing through nightly snapshots of gcc-12 dev branch.
