### ISSUE TITLE
Absolute path for -l not supported

### ISSUE THREAD

**Issue by mrichtarsky** [rui314/mold#283]
This does not work:

```
$ mold main.cpp.o -l/s3/lib1.a -o ex2
mold: library not found: /s3/lib1.a
```

I'm assuming this is on purpose. `bfd`  and `lld` do not support it either, but `gold` does.

Still, would it do harm to support it?

**Comment by rui314** [comment]
If only gold supports it, I'd prefer to not mimic that behavior. The reference implementation here is bfd (although we don't have to support all the features exactly the same.)

**Comment by mrichtarsky** [comment]
Ok, thanks!
