### ISSUE TITLE
`mold -r` does not merge sections

### ISSUE THREAD

**Issue by rui314** [rui314/mold#289]
Currently, `mold -r` does not merge input sections at all. So the resulting object file contains as many `.text` sections as they were in input object files, for example. This slows down some systems such as GHC that use merged object files are their own dynamically-loadable object file form.

https://github.com/rui314/mold/issues/268

**Comment by rui314** [comment]
Now mold merges sections. We can't still build GHC due to a few GHC-side issues though.

**Comment by ocharles** [comment]
@rui314 Awesome! Do you know what the outstanding issues are? I'd like to subscribe to them

**Comment by rui314** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/22540
https://gitlab.haskell.org/ghc/ghc/-/issues/22527

**Comment by rui314** [comment]
Here is another issue:
https://gitlab.haskell.org/ghc/ghc/-/issues/22550
