### ISSUE TITLE
[SETUP] issue making it default linker

### ISSUE THREAD

**Issue by quadroli** [rui314/mold#29]
running ```./mold -run make``` while in the mold directory gives:
```make: Nothing to be done for 'all'.```

so i moved the mold executable to a separate directory and run ```../manma/mold -run make```
it gave: ```ERROR: ld.so: object '/home/superman/packed/manma/mold-wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
make: Nothing to be done for 'all'.```

even having moved the shared object file to appropriate folder and rebuilt mold with make as a sub process, it doesn't seem as though it worked, resulting binaries dont seem to have used mold

system: pop!_os

**Comment by rui314** [comment]
Please try to rename mold in the same directory instead of moving to somewhere else, just like this:

```
$ make
$ mv mold mold2
$ ./mold2 -run make
```

Then, verify that your mold is built with mold by running `readelf -p mold`.

**Comment by quadroli** [comment]
well, yes, mold is successfully linked using mold:
```[     0]  GCC: (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
  [    2b]  clang version 10.0.0-4ubuntu1
  [    4b]  mold a02fc7edb64b3fe7a58360123fab1ed3069b42f3```
But by default the applications i compile are not
```[     0]  GCC: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0```

**Comment by rui314** [comment]
What is your application?

**Comment by quadroli** [comment]
Oh, just a simple hello world, one file

**Comment by quadroli** [comment]
Also, is there a way to check the invoked linker?
Because some time back i installed the debug version of ld(ld-gdb), have a feeling that may be what's being used

**Comment by rui314** [comment]
You have to tell `cc` to use mold as a linker. One way of doing it is adding `-fuse-ld=<absolute-path-to-mold>` to `cc` (if it doesn't work with your `cc`, try `clang` instead of `cc`). The other way is to run your cc as a subcommand of mold, as shown below

`path/to/mold -run cc file1 file2 -o output`

**Comment by quadroli** [comment]
Ohh, alright, sorry i got the impression that by running that 
(```/mold -run make```) it would automatically replace ld

**Comment by rui314** [comment]
I'm closing this issue as it seems to have been resolved.
