### ISSUE TITLE
RTLD_DEEPBIND doesn't exist on musl

### ISSUE THREAD

**Issue by CosmicToast** [rui314/mold#295]
I'm building a musl-based statically linked mold for distribution, but haven't been able to do this since 1.0 hit.
The core problem so far appears to be the use of RTLD_DEEPBIND, which doesn't exist there.

There are also plenty of openssl-related deprecation warnings (due to my use of openssl 3), but for now they're just warnings.

**Comment by rui314** [comment]
Looks like libtbb is using that flag. Does it work if you apply this patch?

```
diff --git a/third-party/tbb/src/tbb/dynamic_link.cpp b/third-party/tbb/src/tbb/dynamic_link.cpp
index 3f1342503..91b33639b 100644
--- a/third-party/tbb/src/tbb/dynamic_link.cpp
+++ b/third-party/tbb/src/tbb/dynamic_link.cpp
@@ -413,9 +413,6 @@ namespace r1 {
         int flags = RTLD_NOW;
         if (local_binding) {
             flags = flags | RTLD_LOCAL;
-#if __linux__ && !__ANDROID__ && !__TBB_USE_SANITIZERS
-            flags = flags | RTLD_DEEPBIND;
-#endif
         } else {
             flags = flags | RTLD_GLOBAL;
         }
```

**Comment by CosmicToast** [comment]
That fixes the RTLD issue, but errors during linking due to missing swapcontext, getcontext and makecontext (also in libtbb).

Musl doesn't have those since they're deprecated and no longer part of POSIX, though I can get around this by installing and manually linking to [libucontext](https://github.com/kaniini/libucontext) with LDFLAGS (though ideally that last part shouldn't be necessary).

**Comment by rui314** [comment]
That issue is the same as the one reported in https://github.com/rui314/mold/issues/281. The problem is that libtbb doesn't work with musl. If we want to run mold (or any program that uses libtbb) with musl, we need to fix libtbb.

**Comment by CosmicToast** [comment]
In the meanwhile, would it be possible to add a conditional `-lucontext` into the Makefile?
The above patch I can keep in the tree myself.

Also please do ping me if possible if and when this gets resolved upstream :)

**Comment by rui314** [comment]
I applied a local patch to libtbb in our source tree to disable the feature that depends on getcontext/setcontext. I also sent that patch to upstream already.

**Comment by stefson** [comment]
I think your backport diverges a bit from the upstream commit: 

https://github.com/rui314/mold/blob/main/third-party/tbb/src/tbb/dynamic_link.cpp#L416
https://github.com/oneapi-src/oneTBB/blob/master/src/tbb/dynamic_link.cpp#L416

`if __linux__ && __GLIBC__` vs `if (__linux__ && __GLIBC__)`

is that on purpose?

**Comment by rui314** [comment]
Yes. We want to define the macro if

 - not Linux, or
 - glibc (out compatible)-based Linux

For example, FreeBSD falls into the first category, and most Linux distro a fall into the second. We want to exclude only musl-based Linux.

**Comment by stefson** [comment]
I see, but the upstream commit is in exlamation marks: ` ( ) ` so is that divergence on purpose?

**Comment by rui314** [comment]
```
#if __linux__ && __GLIBC__ && !__TBB_USE_SANITIZERS
```

means exactly the same as

```
#if (__linux__ && __GLIBC__) && !__TBB_USE_SANITIZERS
```

in C professor, no?

**Comment by rui314** [comment]
My fix to upstream has been merged (https://github.com/oneapi-src/oneTBB/pull/748), so since the next release, oneTBB should compile with musl out of the box.
