### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by InfRandomness** [rui314/mold#304]
I have been testing mold with rust to link a binary from a huge game called "Veloren". I've found out that for some reason, mold is slower than lld although it has been shown that mold is seconds faster than lld on building projects like clang.

Is there a reason for this ? 
So far my tests have been revealing (across 3 tests) that mold is ~20 seconds slower than lld, I expected mold to be seconds faster..

**Comment by rui314** [comment]
Is you game open source? I wonder if I can build it myself too reproduce the issue.

**Comment by rui314** [comment]
Also, how do you run mold? `mold -run` seems to slow it down for some reason.

**Comment by InfRandomness** [comment]
> Is you game open source? I wonder if I can build it myself to reproduce the issue.

yes : https://gitlab.com/veloren/veloren
It is a big project, building it from scratch takes a long time (unless you have a high core count)
Make sure to install and initialize git lfs because there are some assets that need to be pulled to build the game


> Also, how do you run mold? `mold -run` seems to slow it down for some reason.

I use 
```
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```
In the cargo config

**Comment by rui314** [comment]
Thanks! I'm building the game now.

What exactly did you measure time for? I.e. the entire `cargo build` after `cargo clean`, or just edit some file and rebuild it with `cargo build`.

**Comment by InfRandomness** [comment]
> Thanks! I'm building the game now.
> 
> What exactly did you measure time for? I.e. the entire `cargo build` after `cargo clean`, or just edit some file and rebuild it with `cargo build`.

the entire cargo build, then ran "rm -rf target" and then again

**Comment by rui314** [comment]
For me mold is still slightly faster than lld as shown below. The top one is with mold and the second is with lld.

```
 ruiu@blue:~/veloren$ ~/hyperfine/target/debug/hyperfine -r3 'rm -rf target; cargo build'
Benchmark 1: rm -rf target; cargo build
  Time (mean ± σ):     128.677 s ±  0.354 s    [User: 2402.362 s, System: 132.751 s]
  Range (min … max):   128.287 s … 128.978 s    3 runs

ruiu@blue:~/veloren$ ~/hyperfine/target/debug/hyperfine -r3 'rm -rf target; cargo build'
Benchmark 1: rm -rf target; cargo build
  Time (mean ± σ):     130.341 s ±  0.298 s    [User: 2418.012 s, System: 148.985 s]
  Range (min … max):   130.114 s … 130.678 s    3 runs
```

Valoren is a large project but compared to other really large projects such as Clang or Chrome, Veloren's executable and shared library files aren't that big. They are <100MB. lld and other linkers are fast enough already. For that reason, I think it is hard for mold to make a difference.

Being said that, it is a little concerning that mold is slower than lld. I wonder if it is due to memory consumption. How much memory does your machine have?

**Comment by InfRandomness** [comment]
The machine I benchmarked on has 16 gigs of ram

**Comment by InfRandomness** [comment]
Here is the result of my runs on my bigger server
```
[admin@Gecko veloren]$ hyperfine -r3 'rm -rf target; cargo build'
Benchmark 1: rm -rf target; cargo build
  Time (mean ± σ):     579.286 s ± 36.924 s    [User: 8647.284 s, System: 358.149 s]
  Range (min … max):   548.264 s … 620.128 s    3 runs

[admin@Gecko veloren]$ hyperfine -r3 'rm -rf target; cargo build'
Benchmark 1: rm -rf target; cargo build
  Time (mean ± σ):     583.148 s ± 24.170 s    [User: 8567.153 s, System: 366.526 s]
  Range (min … max):   558.239 s … 606.505 s    3 runs
```

**Comment by rui314** [comment]
Compiler dominates in your test and linker can make a little difference, as it's already fast anyways.

That said, this is a test case of a clean build. And in clean build, compiler usually dominates. mold is most useful when you are in rapid debug-edit-build cycles. Imagine that you are doing a printf debugging and can save a few seconds every time you rebuild your project by using mold. That's the situation we most care about.

**Comment by InfRandomness** [comment]
it appears as if the results that came out of my benchmark were actually false : 
I did not catch the fact that there was a custom cargo configuration in .cargo/config, therefore, the wrong linker was used all along

**Comment by InfRandomness** [comment]
It also sounds like my computer does not contain enough memory to successfully link this with mold, mold ends up taking about 10gb of ram off of my system which ends up in the OOM killer kicking in and killing processes
