### ISSUE TITLE
doc: mold with rust not working as documented ("linker clang not found")

### ISSUE THREAD

**Issue by shoffmeister** [rui314/mold#316]
The instructions for using mold with rust at https://github.com/rui314/mold#how-to-use are not sufficient to get things working.

I am on Fedora 35, 
* using the brand new, official distro package of mold 1.0.2 (thanks to @sicherha!)
* have rust (latest stable) installed via rustup as my local user
* printing "hello world"

I was able to compile / link / run before adding config.toml as suggested by the mold docs; after applying the configuration change, I get
```
wombat on  master [?] is 📦 v0.1.0 via 🦀 v1.58.1 
❯ cargo build
   Compiling wombat v0.1.0 ( ... rust/wombat)
error: linker `clang` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `wombat` due to previous error
```

The root cause of the error message is somewhat obvious: I don't have the `clang` package installed. And, indeed, after installing the `clang`package (on Fedora 35: dnf install clang), `cargo build` works.

It seems as if the documentation perhaps could be enriched to mention that the clang linker actually has to be _installed_ for the steps to work ("linker" in the config.toml apparently is not a linker template, but really refers to the linker binary's name)

**Comment by shoffmeister** [comment]
Surprisingly, I have not found any issue within the Rust organization that asks for "native" mold support (in cargo, their build tool).

**Comment by rui314** [comment]
Thanks. I'll update the doc.

Linker is not supposed to be invoked directly by any program, so it's normal not to support it "natively". Using `cc` (or `gcc` or `clang`) to invoke `ld` is the correct usage.

**Comment by rui314** [comment]
Fixed in https://github.com/rui314/mold/commit/1de4874478ae83312d2618acb60bf23b32216a58
