### ISSUE TITLE
complex build works with GCC but not Clang

### ISSUE THREAD

**Issue by PhilipDeegan** [rui314/mold#324]
Hi there,

We have a pretty complicated and template heavy code over at https://github.com/PHAREHUB/PHARE/
I've noticed that our tests are failing with strange errors when I use mold with Clang, but not mold with GCC.

Happy to help in the investigation.

**Comment by rui314** [comment]
Is it easy to build? If so, I'll do that myself to reproduce your issue locally.

What are your clang and gcc versions?

**Comment by PhilipDeegan** [comment]
> Is it easy to build? 

With the dockerfiles we have it is more so, as there are a few prerequisites (MPI/HDF5/etc)
base: https://github.com/PHARCHIVE/phare-teamcity-agent
src dependencies: https://github.com/PHARCHIVE/phare-teamcity-agent_dep
run "build_image.sh 34" for both, to build Fedora 34 images

in docker container:

```
git clone https://github.com/nicolasaunai/PHARE --depth 1 --recursive phare; cd phare; mkdir build; cd build
#export CC=clang CXX=clang++ # fine without this, not fine with this
cmake .. -G Ninja
mold --run ninja
ctest -j10
```

GCC: 10.2
Clang: 11.0.1-2

**Comment by rui314** [comment]
It was an ABI incompatibility issue between GCC and Clang. I think mold can now handle it. Please rebuild mold with the above commit and try again.

**Comment by PhilipDeegan** [comment]
awesome

**Comment by rui314** [comment]
No hurry, but please close this bug when you verify my fix to confirm that my fix was correct.
