### ISSUE TITLE
Error for undefined protected/hidden symbol

### ISSUE THREAD

**Issue by MaskRay** [rui314/mold#329]
```sh
>a.s cat <<e
.global _start
_start:
.quad foo
.hidden foo  # protected is similar
e
>b.s cat <<e
.global foo
foo:
e
cc -c a.s
cc -shared b.s -o b.so
```

```
% ld.bfd a.o b.so              
ld.bfd: a.o: in function `_start':
(.text+0x0): undefined reference to `foo'
ld.bfd: a.out: hidden symbol `foo' isn't defined
ld.bfd: final link failed: bad value
% ld.lld a.o b.so
ld.lld: error: undefined hidden symbol: foo
>>> referenced by a.o:(.text+0x0)
% mold a.o b.so # no diagnostic
```

Swap the order:
```
% ld.lld b.so a.o
ld.lld: error: undefined hidden symbol: foo
>>> referenced by a.o:(.text+0x0)
% mold b.so a.o # no diagnostic
```

**Comment by rui314** [comment]
Ah, this is a tricky case, and I don't even know what is the correct behavior. But maybe we can just report an error if a hidden/protected symbol is resolved to an imported symbol. I can think of many edge cases such as what if the symbol is hidden and weak undef... But as long as a user supply a definition of the symbol in a .o, mold already behaves as expected, so reporting an error in an unusual use case is probably fine.
