### ISSUE TITLE
Can not cross-compile rust program (Linux->Windows) in release mode.

### ISSUE THREAD

**Issue by s0lst1ce** [rui314/mold#338]
I have a rust program I cross-compile from linux (arch) to windows using the [`cross`](https://github.com/cross-rs/cross) tool. This works fine if I don't use mold but then I do I can only make `debug` builds (unoptimized, as opposed to `release` builds).
This is done using the `x86_64-w64-mingw32-gcc` toolchain that depends on the `mingw-w64-gcc`arch package.
The short error I get is: `= note: mold: unknown -m argument: i386pep`. If needed I can provide the full error.

**Comment by rui314** [comment]
Currently mold can't create Windows executables. So, even though you can cross compile Linux programs on Windows, you can't do the other way. Please wait until we add Windows support.

**Comment by rui314** [comment]
https://github.com/rui314/mold/issues/190
