### ISSUE TITLE
[release] publish compiled binary file in release

### ISSUE THREAD

**Issue by ClSlaid** [rui314/mold#351]
I've been trying to use `mold` as the default linker in GitHub actions, but `mold` is not in the package list of `ubuntu-latest` (actually `ubuntu-20.04`) so I have to use other Github actions like [`setup-mold`](https://github.com/Warchant/setup-mold).
Building `mold` from source is time costing and will mostly cover those saved by replacing the linker. If I can download trustable binary files from this repository directly, using `mold` as the default linker in projects will be a worthy deal.

**Comment by rui314** [comment]
I understand there's a need for it. It's just a matter of time and effort that I can spend on making a release. But let me think about that. It may not be too hard to build pre-compiled binaries for a few major distributions because we can use Docker.

**Comment by rui314** [comment]
I made several changes to our script files and settled down with a single script file `dist.sh`. If you run this script, it should create a tar file containing a mold executable which should run on most Linux systems (as long as they have some essential libraries such as libc, libm, libz or librt). If you need a binary distribution of mold right now, please create by yourself. I'll start distributing tar files created by this script from the next release.
