### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by sajcho** [rui314/mold#353]
Hi.

gcc 12.0.1
mold git version of 2022.02.19
build cflags with -fuse-ld = mold -flto

build coreutils:
FORCE_UNSAFE_CONFIGURE=1
./configure --prefix=/usr --libexecdir=/usr/lib --disable-nls --disable-assert --enable-no-install-program=uptime,kill,chcon,runcon,groups

- - `gcc   -O2 -m64 -march=x86-64 -mtune=generic -fuse-ld=mold -flto -fexceptions -fstack-clash-protection -fcf-protection -D_FORTIFY_SOURCE=2 -Wno-psabi -Wl,--as-needed  -o src/cat src/cat.o src/libver.a lib/libcoreutils.a  lib/libcoreutils.a 
- - gcc   -O2 -m64 -march=x86-64 -mtune=generic -fuse-ld=mold -flto -fexceptions -fstack-clash-protection -fcf-protection -D_FORTIFY_SOURCE=2 -Wno-psabi -Wl,--as-needed  -o src/chgrp src/chgrp.o src/chown-core.o src/libver.a lib/libcoreutils.a  lib/libcoreutils.a 
- - terminate called after throwing an instance of 'std::runtime_error'
- -   what():  pthread_create has failed: Resource temporarily unavailable
- - collect2: fatal error: ld terminated with signal 6 [Aborted]
- - compilation terminated.
- - make[2]: *** [Makefile:9382: src/chgrp] Error 1
- - make[2]: *** Waiting for unfinished jobs....`
 
- build openssl v.3
openssl-3.0.1
perl ./Configure linux-x86_64 --prefix=/usr --libdir=lib --openssldir=/etc/ssl shared enable-rfc3779 enable-cms enable-md2 enable-ktls enable-ec_nistp_64_gcc_128 no-async no-comp no-ec2m no-idea no-mdc2 no-rc5 no-seed no-sm2 no-sm4 no-ssl3 no-weak-ssl-ciphers no-zlib
Configuring OpenSSL version 3.0.1 for target linux-x86_64
 
- - `{LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -O2 -m64 -march=x86-64 -mtune=generic -fuse-ld=mold -flto -fexceptions -fstack-clash-protection -fcf-protection -D_FORTIFY_SOURCE=2 -Wno-psabi   \
- 	-o test/curve448_internal_test \
- 	test/curve448_internal_test-bin-curve448_internal_test.o \
- 	test/libtestutil.a libcrypto.a -ldl -pthread 
- terminate called after throwing an instance of 'std::runtime_error'
-   what():  pthread_create has failed: Resource temporarily unavailable
- collect2: fatal error: ld terminated with signal 6 [Aborted]
- compilation terminated.
- make[1]: *** [Makefile:23837: test/curve448_internal_test] Error 1
- - make[1]: *** Waiting for unfinished jobs....`
```

**Comment by rui314** [comment]
It looks like something has stopped because resource is not available. Isn't it actually the case? LTO needs lots of memory.

**Comment by sajcho** [comment]
$ free -h
                      total        used        free      shared  buff/cache   available
Mem:            62Gi       847Mi        60Gi        35Mi       1,0Gi        61Gi
Swap:          2,9Gi          0B       2,9Gi

when i change -fuse-ld=mold to bfd compilation passes

**Comment by sajcho** [comment]
When I leave the mold and turn off the lto - it passes
I suspect it will be something with gcc12.0.1.
I don't have a stable version of gcc. I can't compare.
There may be an error in the above packages.

**Comment by rui314** [comment]
I got an internal compiler error with gcc 12. gcc 9, 10 and 11 seem to work fine; they can build LLVM with gcc+mold. So it's likely that there's something wrong with gcc 12.

**Comment by sajcho** [comment]
I have the same opinion. I think we can close this problem.

**Comment by sajcho** [comment]
The problem has a simple solution.
I compiled with make -j8.
I reduced it to -j4 and it worked.
Maybe it will help someone.
