### ISSUE TITLE
RFE/Question: Support targetting multiple archs

### ISSUE THREAD

**Issue by Keruspe** [rui314/mold#354]
Is there a plan to support targetting multiple archs with a single binary?

Something like `mold -target x86_64-unknown-linux-gnu`, `mold -target i386-unknown-pc-linux-gnu` etc?

(Or even better, detecting when called as e.g. `x86_64-unknown-linux-gnu-mold`)

**Comment by rui314** [comment]
It needs a runtime support, no? Apple did this thrice, for m68k/PowerPC, PowerPC/x86 and x86/ARM. They defined a new binary format called the Fat binary to make it possible which essentially just a bundle of two executables. You build for each target and then use an Apple-provided tool to combine them to create a fat binary.

**Comment by Alcaro** [comment]
I think OP is requesting that a single mold can (cross) compile for multiple architectures, not that a mold-generated binary (or mold itself) can run on multiple architectures.

As far as I know, mold already supports that. Except output format detection is done by checking what object files it's given, not via -target or argv[0].

**Comment by rui314** [comment]
Ah, yeah, I misunderstood the question. And what @Alcaro said is correct. It looks for `-m` if exists and then falls back to the first object file to deduct the output arch.

**Comment by Keruspe** [comment]
Oh right, my bad, my testing was wrong, it works fine indeed, thanks!
