### ISSUE TITLE
Different sizes for kodi's debug-builds with ld.gold / mold

### ISSUE THREAD

**Issue by howie-f** [rui314/mold#373]
hello @rui314 ! thanks for response.
honestly i noticed the size differences by coincidence while i was playing with @wsnipex ' pullrequest.
i'm sure not the expert of compilers/linkers etc., but since the difference seems quite significant, i'm just curious what can be done with the larger binaries, that may not be work with the smaller ones. :)
possibly, in terms of debugging, there's no difference.

for sure it's much more convenient to open the smaller files in the debugger.

so in case you're in the mood or would like to try to improve the filesize for mold linked debug-binaries, i've uploaded the ldgold- and mold-versions here https://drive.google.com/drive/folders/1oiTuVoJkM-C8b_RqrSxAhdErEpukuPO-

please let me know if you have further questions. thanks

**Comment by rui314** [comment]
Let me take a look. I'll build kodi myself with gold and mold to compare the results.

**Comment by rui314** [comment]
It looks like mold-generated `.debug_info` is ~500 MiB larger than the one created by gold.

Let me build Kodi myself to see if I can reproduce the issue on my machine. Did you pass any special options or anything when you build it? Can I just build it by checking out https://github.com/xbmc/xbmc and follow the build instruction?

**Comment by rui314** [comment]
Building kodi isn't easy as it has a lot of build dependencies.

Can you re-link the final kodi executable with the `-Wl,--repro` option? That option tells the mold linker to create a tar file containing all input object files. If your output file is `kodi`, the linker creates `kodi.tar` in the same directory. Can you share the tar file with me so that I can re-run the final link with the exact same input as you?

**Comment by wsnipex** [comment]
`-DLD_FLAGS="-Wl,--repro"`

**Comment by howie-f** [comment]
kodi-x11.repro.tar up

**Comment by rui314** [comment]
Thank you @howie-f for sharing that file! I rebuilt kodi with ld.lld, ld.gold and ld.mold using it.

For some reason, I got the executables of almost the same size as follows.

```
-rwxrwxr-x 1 ruiu ruiu 854M Mar  4 15:43 kodi-x11.gold
-rwxrwxr-x 1 ruiu ruiu 854M Mar  4 15:42 kodi-x11.lld
-rwxrwxr-x 1 ruiu ruiu 865M Mar  4 15:42 kodi-x11.mold
```

I wonder if the kodi's build system really passes the same command line flags to mold as it does to other linkers. It might be passing some extra flags only to mold which bloats the output file size.

**Comment by howie-f** [comment]
thanks a lot @rui314 for taking the time to look into this.

finally we / wsnipex found what is actually happening. our build system enables GNU DebugFission by default if ld.gold is used.
(which is also default on linux)
https://github.com/xbmc/xbmc/blob/3ee23533b8ba41c9580aeefd78ca3b6a86376c10/cmake/modules/LDGOLD.cmake#L16-L21

so far `DebugFission / split darwf` seems to be only implemented in ldgold.

refs. https://totalview.io/sites/totalview/files/pdfs/white-paper-totalview-saving-time-space-split-dwarf.pdf (**Debug Information Indexing**) and https://help.totalview.io/previous_releases/2018/html/index.html#page/Reference_Guides%2FUsingGNUDebugFissionSplitDWARF.html%23

latest comparison results:
```
-rwxr-xr-x 1 fhw fhw 857M Mar  4 11:57 kodi-x11-clang_gold_fission_off
-rwxr-xr-x 1 fhw fhw 399M Mar  4 12:41 kodi-x11-clang_gold_fission_on
-rwxr-xr-x 1 fhw fhw 867M Mar  4 20:37 kodi-x11-clang_mold_fission_off
-rwxr-xr-x 1 fhw fhw 987M Mar  4 20:26 kodi-x11-clang_mold_fission_on
-rwxr-xr-x 1 fhw fhw 1.2G Mar  4 18:57 kodi-x11-cpp_gold_fission_off
-rwxr-xr-x 1 fhw fhw 369M Mar  4 19:20 kodi-x11-cpp_gold_fission_on
-rwxr-xr-x 1 fhw fhw 1.3G Mar  4 18:35 kodi-x11-cpp_mold_fission_off
-rwxr-xr-x 1 fhw fhw 1.4G Mar  4 17:47 kodi-x11-cpp_mold_fission_on
```

glad a plausible explanation is there now :)
issue can be closed

**Comment by rui314** [comment]
Thank for you investigating! Glad that we could find the cause of the difference.
