### ISSUE TITLE
Building 20220305 gcc11 snapshot with gcc11 fails with LD=ld.mold, succeeds otherwise.

### ISSUE THREAD

**Issue by satmandu** [rui314/mold#386]
```
mold: error: duplicate symbol: ../src/c++17/.libs/libc++17convenience.a(cow-fs_dir.o): ../src/c++17/.libs/libc++17convenience.a(fs_dir.o): std::_Sp_make_shared_tag::_S_ti()::__tag
mold: error: duplicate symbol: ../src/c++17/.libs/libc++17convenience.a(cow-fs_path.o): ../src/c++17/.libs/libc++17convenience.a(fs_dir.o): std::_Sp_make_shared_tag::_S_ti()::__tag
mold: error: duplicate symbol: ../src/c++17/.libs/libc++17convenience.a(fs_path.o): ../src/c++17/.libs/libc++17convenience.a(fs_dir.o): std::_Sp_make_shared_tag::_S_ti()::__tag
collect2: error: ld returned 1 exit status
make[5]: *** 
[gcc11-11.2.1-20220305-x86_64.log](https://github.com/rui314/mold/files/8209803/gcc11-11.2.1-20220305-x86_64.log)
[Makefile:732: libstdc++.la] Error 1
make[5]: Leaving directory '/usr/local/tmp/crew/gcc11.20220308200101.dir/gcc-11-20220305/objdir/x86_64-cros-linux-gnu/libstdc++-v3/src'
make[4]: *** [Makefile:765: all-recursive] Error 1
make[4]: Leaving directory '/usr/local/tmp/crew/gcc11.20220308200101.dir/gcc-11-20220305/objdir/x86_64-cros-linux-gnu/libstdc++-v3/src'
make[3]: *** [Makefile:568: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/gcc11.20220308200101.dir/gcc-11-20220305/objdir/x86_64-cros-linux-gnu/libstdc++-v3'
make[2]: *** [Makefile:493: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/gcc11.20220308200101.dir/gcc-11-20220305/objdir/x86_64-cros-linux-gnu/libstdc++-v3'
make[1]: *** [Makefile:11851: all-target-libstdc++-v3] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/gcc11.20220308200101.dir/gcc-11-20220305/objdir'
make: *** [Makefile:962: all] Error 2
```
```
mold --version
mold 1.1.1 (c1af9c97e763a1d521889191a83b27bd6c43b351; compatible with GNU ld)
```

building with `-fPIC -pipe --with-arch-64=x86-64 --enable-languages=c,c++,jit,objc,fortran` and `LD=ld.mold NM=gcc-nm AR=gcc-ar RANLIB=gcc-ranlib`

Build Log file attached.
[gcc11-11.2.1-20220305-x86_64.log](https://github.com/rui314/mold/files/8209810/gcc11-11.2.1-20220305-x86_64.log)

**Comment by rui314** [comment]
The direct cause of the failure is that gcc is using the GNU-unique mechanism instead of the COMDAT mechanism to de-duplicate template instances and inline functions. GNU-unique predates COMDAT and is not being in active use for 10+ years now.

I believe the problem is GCC 11's configure script does not recognize `ld.mold` at all and therefore falls back to the (probably a bit-rotted) code path. Traditionally, old GNU tools assumes very little as the baseline, so sometimes they even recognize mold as a linker which does not support dynamic linking (from '80s).

I wonder if pass `--enable-comdat` to `configure` could fix the issue.

**Comment by marxin** [comment]
> I believe the problem is GCC 11's configure script does not recognize `ld.mold` at all and therefore falls back to the (probably a bit-rotted) code path. Traditionally, old GNU tools assumes very little as the baseline, so sometimes they even recognize mold as a linker which does not support dynamic linking (from '80s).

Yes, that's something I fixed for the upcoming GCC 12 compiler.

**Comment by rui314** [comment]
It's more like a GCC's issue than a mold's issue, and I don't think there's a way to fix it other than applying a local patch to GCC 11's configure script.
