### ISSUE TITLE
mold produces corrupted compressed debug sections for aarch64

### ISSUE THREAD

**Issue by sicherha** [rui314/mold#387]
Found while building mold 1.1.1 for Fedora on aarch64. The `compressed-debug-info` test case doesn't report a failure, but the output of `readelf` clearly indicates that something is awry:
```
Testing compressed-debug-info ... readelf: out/test/elf/compressed-debug-info/exe: Warning: Debug info is corrupted, abbrev offset (80000000) is larger than abbrev section size (72)
readelf: out/test/elf/compressed-debug-info/exe: Warning: Debug info is corrupted, abbrev offset (80000038) is larger than abbrev section size (72)
readelf: out/test/elf/compressed-debug-info/exe: Warning: DIE at offset 0xc refers to abbreviation number 1 which does not exist
 OK
```
The whole thing feels pretty familiar: in #361 I reported a similar issue concerning i386.

**Comment by rui314** [comment]
It's not only for compressed debug info but it looks like mold creates a corrupted debug info. I could reproduce the issue without `--compress-debug-sections=zlib`.
