### ISSUE TITLE
mold: fatal: unknown -m argument: armelf_linux_eabi

### ISSUE THREAD

**Issue by satmandu** [rui314/mold#389]
This happens when building the current version of freetype (2.11.1), with GCC patched to support `-fuse-ld=mold` as per https://github.com/skycocker/chromebrew/pull/6839
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ gcc -dumpmachine
armv7l-cros-linux-gnueabihf
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ mold --version
mold 1.1.1 (c1af9c97e763a1d521889191a83b27bd6c43b351; compatible with GNU ld)
```

```
meson.build:26:0: ERROR: Unable to detect linker for compiler "cc -Wl,--version -O2 -fuse-ld=mold"
stdout:
stderr: collect2 version 11.2.1 20220305
/usr/local/bin/ld.mold -plugin /usr/local/libexec/gcc/armv7l-cros-linux-gnueabihf/11/liblto_plugin.so -plugin-opt=/usr/local/libexec/gcc/armv7l-cros-linux-gnueabihf/11/lto-wrapper -plugin-opt=-fresolution=/usr/local/tmp/ccEVcbqi.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X -m armelf_linux_eabi -pie /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/../../../Scrt1.o /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/../../../crti.o /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/crtbeginS.o -L/usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11 -L/usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/crtendS.o /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/11/../../../crtn.o
mold: fatal: unknown -m argument: armelf_linux_eabi
collect2: error: ld returned 1 exit status
```
Happy to provide an armv7l docker container to replicate this if you want. (It runs fastest on a current Raspberry Pi 4B device running Ubuntu since that does the armv7l natively.)

**Comment by satmandu** [comment]
(Build works fine on `x86_64` and `i686`)

**Comment by sicherha** [comment]
You're trying to link a 32-bit ARM binary. Unfortunately, that target architecture is not (yet?) supported by mold.

Right now, mold supports the following target architectures:
* aarch64
* i686
* riscv64
* x86_64

**Comment by satmandu** [comment]
What do we need to do to get `armv7l` supported? The userspace on all arm ChromeOS machines is 32-bit `armv7l` `gnueabihf`.

I'd love to get `mold` to be the default linker for [Chromebrew](https://github.com/skycocker/chromebrew), but that would be easiest done if `armv7l` was supported as well. (Armv7l is also perhaps still one of the most used architectures, since it is used by default on the debian-based Raspberry PI OS).

**Comment by sicherha** [comment]
To support `armv7l`, one would need to create and fill in a new architecture file `elf/arch-arm32.cc`, analogous to [elf/arch-arm64.cc](https://github.com/rui314/mold/blob/main/elf/arch-arm64.cc). That's somewhere between 500 and 900 lines of code.
The new architecture description could then be instantiated and referenced in [elf/main.cc](https://github.com/rui314/mold/blob/main/elf/main.cc).

**Comment by rui314** [comment]
I'm happy to add ARM32 support to mold if there's enough number of users. @satmandu Do you want all Chromebrew users to use mold by default? If so, I'll raise the priority of ARM32 support.

**Comment by satmandu** [comment]
@rui314 We try to stay cutting edge. We're using GCC 11 & LLVM 13 as our default compilers, and we use gold as our default linker. As you can see at https://github.com/skycocker/chromebrew/pull/6839 I am testing mold. But mold not supporting `armv7l` means a lot more work on the backend since now we have to modify packages to use `mold` or something else if mold isn't supported. (And that makes creating upstream issue more difficult too since we don't have commonality in our packages across architectures.)

If `mold` was available for `armv7l`, we would seriously consider it as the default.  (Indeed that's why I did all this work over the last several days - to try to make that possible.)

Would you please put a list of supported architectures in the main Readme file? :)

**Comment by rui314** [comment]
@satmandu Thanks for the explanation. Let me raise the priority of ARM32 support. It usually takes a week or so for me to add a new architecture, so it's not very hard. It's not very easy though, as what the linker does is essentially binary patching object files to combine them. If something is wrong, we need to dig into the machine code level.

By the way, the main readme file already contains the description as the supported architecture as follows:

> mold currently supports x86-64, i386, ARM64 and 64-bit RISC-V.

**Comment by rui314** [comment]
I believe you can now link most ARM32 programs just fine using mold. Can you try to rebuild your programs?

**Comment by satmandu** [comment]
Curiously enough, I have an error of building top of tree on `x86_64` but not armv7l or i686...
[mold-615a24d1dde2e7d0756a53897ed7f46842f0c3a1-x86_64.log](https://github.com/rui314/mold/files/8404899/mold-615a24d1dde2e7d0756a53897ed7f46842f0c3a1-x86_64.log)

**Comment by rui314** [comment]
Are you using mold to build mold?

**Comment by satmandu** [comment]
Yes.

**Comment by rui314** [comment]
Can you try building mold using the default ld? If that fixes the problem, it means we are mis-linking mold probably only on ChromeOS for some reason.

**Comment by satmandu** [comment]
looking more carefully, we aren't passing any LD options to the build, so it must be using gold linker...

**Comment by rui314** [comment]
That means mold simply cannot be built on ChromeOS for some reason, no? I'd try to rebuild without LTO to see if it is an LTO issue.

**Comment by satmandu** [comment]
I got it to builds on `x86_64` by passing `CFLAGS='-fuse-ld=gold'` before the make command.... so gold linker does work to build it.

**Comment by rui314** [comment]
So, did it break only when mold was built using mold?

**Comment by satmandu** [comment]
Curiously building with `system "CXXFLAGS='-fuse-ld=mold' CFLAGS='-fuse-ld=mold' make LTO=1"` appeared to work, so maybe there was something screwed up about the build container...

**Comment by rui314** [comment]
I'm closing this bug as the original issue has been resolved. Feel free to file another bug if you have other issue.

**Comment by LegendL3n** [comment]
Could you provide an ARM 32-bit build? The current release supports it, but the assets don't include that build.

**Comment by rui314** [comment]
So you want to run mold natively on ARM32? I'm curious what is your environment.

My current build script can't do a cross build, but I cannot immediately do this, but that's of course doable.

**Comment by LegendL3n** [comment]
If it's too much effort then don't bother.

It was more of a best to have since compiling on that arch takes too much time, but I'll try cross-compiling with QEMU

**Comment by rui314** [comment]
I filed it as a separate bug.

**Comment by LegendL3n** [comment]
Thanks 👍
