### ISSUE TITLE
Linking rust code results in `library not found: gcc`

### ISSUE THREAD

**Issue by expenses** [rui314/mold#39]
Hello! I'm trying to use mold to link some rust code.

I tried the following in my `~/.cargo/config`:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker-flavor=ld",
]
linker = "mold"

```
This runs the following `mold` command (censored a bit, hope that isn't a problem):

`
  = note: "mold" "--eh-frame-hdr" "-L" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.0.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.1.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.2.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.3.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.4.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.5.rcgu.o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.<my project>.49v4udum-cgu.6.rcgu.o" "-o" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915" "<my dir>/<my project>/target/debug/deps/<my project>-53526ca339f51915.bup2hku2a0i3608.rcgu.o" "--gc-sections" "-pie" "-zrelro" "-znow" "-L" "<my dir>/<my project>/target/debug/deps" "-L" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--start-group" "-Bstatic" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0a9489cf400f65e4.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ff5dc44c66f8c479.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-3317c66a83501f9c.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-5d8dec11fc25537d.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-3af2a9328550e2a6.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3092e2ecef0f49f1.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-29b776c021389465.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e8873bd287db0d28.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-1171b49d77e47426.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c29894d22dc88b51.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-796a7750df3d8218.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-ff7772d803d3e0de.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-dae3eac9cfa44200.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-0fa02f580e987af5.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-7f7254233be843ed.rlib" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1395c6db3d116086.rlib" "--end-group" "<my dir>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b4bd87926720b651.rlib" "-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
`

This fails with:
```
  = note: mold: library not found: gcc_s
```

We need to link with `/usr/lib/libgcc_s.so`, so that can be done with:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker-flavor=ld",
    "-C", "link-arg=-L/usr/lib",
]
linker = "mold"
```
And then the linking fails with:
```
  = note: mold: library not found: gcc
```

**Comment by rui314** [comment]
Could you try setting `linker` to just `ld`?

```
linker = "ld"
```

I believe the above configuration won't work as well, because `linker` should be set to a compiler driver (e.g. `gcc` or `clang`) instead of a linker command itself (e.g. `ld` or `mold`).

If you undo your changes to use mold and instead run `cargo build` as `mold -run cargo build`, does that work? If a build command is run as `mold -run <command>`, all invocations of /usr/bin/ld, /usr/bin/ld.gold or /usr/bin/ld.lld are replaced with mold.

**Comment by expenses** [comment]
Hmm, with
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-L/usr/lib",
]
linker = "ld"
```
and running `mold -run cargo run` I get the same 
```
  = note: mold: library not found: gcc
```
error.
The `ld`/`mold` command that's run seems to be the same.

**Comment by rui314** [comment]
Please remove `rustflags` and `linker` from `~cargo/config` and run `mold -run cargo run`. In other words, you don't have to edit your cargo config file to use mold. Just run `mold -run cargo run` without changing any config file.

Generally, `linker` in a cargo config file is expected to set to `gcc` or `clang`. If you set it to `ld`, `lld` or anything else, that will fail.

**Comment by expenses** [comment]
That works! Thanks!
