### ISSUE TITLE
regression: mold-1.1 produces "illegal hardware instruction" on an open-source project

### ISSUE THREAD

**Issue by daquexian** [rui314/mold#405]
The project is [oneflow](https://github.com/Oneflow-Inc/oneflow) (WARNING: this project is large and takes ~20 minutes to build on a 48 cpu core machine). My compile command is

```bash
# NOTE: "75" here is the cuda architecture of my device.
# If this value is mismatch to the current cuda device, there will be a runtime error 
# (but not compile/link error) when trying to access gpu.
#
# ccache and ninja are needed, 
# and other dependencies: https://github.com/Oneflow-Inc/oneflow#option-3-build-on-bare-metal
cmake -C ../cmake/caches/cn/fast/cuda-75.cmake -DCMAKE_BUILD_TYPE=Debug ..
ninja oneflow_py
```

Downgrading mold to 1.0.0 fixes this problem.

This problem also doesn't exist when building a pure cpu version.

**Comment by daquexian** [comment]
Add `add_link_options(-Wl,--no-relax)` in cmake (following https://github.com/rui314/mold/issues/154) fixes (a.k.a. bypasses) this problem.

**Comment by rui314** [comment]
Thank you for the report. I'll take a look at the issue.

**Comment by daquexian** [comment]
> Thank you for the report. I'll take a look at the issue.

Thanks!

Update: no-relax doesn't always fix the issue. Sometimes I edited the source code of oneflow and then got "segfault" when I started the program.

**Comment by rui314** [comment]
After building it with `ninja oneflow_py`, what command should I run to see the failure?

**Comment by rui314** [comment]
I follow the instructions in README to build your program, but I still cannot run it. I'm using your docker image for building.

Here is the error I got when I try to run it after `ninja oneflow_py`.

```
[root@2c2a97d51e8a build]# python3 -m oneflow --doctor
bash: python3: command not found

[root@2c2a97d51e8a build]# python3.10 -m oneflow --doctor
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.10.2/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/_internal/cpython-3.10.2/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/_internal/cpython-3.10.2/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/oneflow/python/oneflow/__init__.py", line 21, in <module>
    import oneflow._oneflow_internal
ImportError: libprotobuf.so.3.9.2.0: cannot open shared object file: No such file or directory
```

**Comment by daquexian** [comment]
Sorry for the late response. It is strange. Could you please try building oneflow in docker container following https://github.com/Oneflow-Inc/oneflow#option-2-build-in-docker-container-recommended ? Thanks!

**Comment by jackalcooper** [comment]
@rui314 may I ask what was your cmake configure command?

**Comment by rui314** [comment]
My commands are the same as the one @daquexian's first post.

```
cmake -C ../cmake/caches/cn/fast/cuda-75.cmake -DCMAKE_BUILD_TYPE=Debug ..
ninja oneflow_py
```

**Comment by daquexian** [comment]
@rui314 Sorry for the late response. I published a docker image for easier reproduce.

In the image, /usr/bin/ld is mold-v1.1.1. Please pull the image by `docker pull daquexian/mold-reproduce`, and clone oneflow, then run

```bash
mkdir build
cd build
cmake -C ../cmake/caches/cn/fast/cuda-75.cmake -DCMAKE_BUILD_TYPE=Debug ..
ninja oneflow_py
source source.sh
python3 -m oneflow --doctor
```

to reproduce the issue.

FYI, here is the dockerfile:

```dockerfile
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
MAINTAINER daquexian

ENV DEBIAN_FRONTEND=noninteractive 

# Comment it if you are not in China
RUN sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# Add common tools and oneflow dependencies available in apt repository.
RUN apt update && \
    apt -o Acquire::http::proxy=false install -y apt-utils software-properties-common && \
    apt update && \
    apt -o Acquire::http::proxy=false install -y man pkg-config git locales sed ack-grep htop python3 python3-dev build-essential autoconf automake libtool make gcc g++ curl wget tar libevent-dev libncurses-dev unzip libcurl4-openssl-dev gdb zip tree sudo libxxhash-dev zlib1g-dev ccache fuse libopenblas-dev nasm && \
    apt clean

RUN locale-gen "en_US.UTF-8"

# Install Ninja
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip && unzip ninja-linux.zip -d ninja && cp ninja/ninja /usr/bin && rm -rf ninja

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py | python3

RUN python3 -m pip install cmake
RUN echo "export PATH=$HOME/.local/bin:$PATH" >> .bashrc

# Install mold-1.1.1
RUN wget https://github.com/rui314/mold/releases/download/v1.1.1/mold-1.1.1-x86_64-linux.tar.gz && \
    tar xvf mold-1.1.1-x86_64-linux.tar.gz && \
    cp mold-1.1.1-x86_64-linux/bin/mold /usr/bin/ld && \
    rm -r mold*
```

**Comment by rui314** [comment]
`python3 -m oneflow --doctor` segfaulted even without using mold. Is it expected?

My machine doesn't have an Nvidia card, so I omitted `--runtime=nvidia` from the command line. Does this matter?

**Comment by rui314** [comment]
If you can find the location where the illegal instruction is executed and can find the object file where the function containing that illegal function, you might want to share it with me, so that I can take a look.

**Comment by daquexian** [comment]
> `python3 -m oneflow --doctor` segfaulted even without using mold. Is it expected?
> 
> My machine doesn't have an Nvidia card, so I omitted `--runtime=nvidia` from the command line. Does this matter?

It is not expected. Did you build oneflow in `daquexian/mold-reproduce` container? In this container /usr/bin/ld is already mold. 

I just had a try. In the container, building with mold-1.1.1 leads to segfault, but building with mold-1.0 is successful.

**Comment by rui314** [comment]
> In this container /usr/bin/ld is already mold.

That's what I wasn't aware of. I'll try again with your docker image.

**Comment by rui314** [comment]
I found an issue with section layout and fixed it in the above commit. Can you rebuild mold and try again?

It turned out it wasn't actually a regression. It happens in some probability if your input file contains a section with a large alignment requirement. Nvidia-provided object files tend to have such section, so the bug occurs in your environment.

Thank you for finding and reporting the issue to me! If you find any, please let me know so that I can fix it.

**Comment by daquexian** [comment]
Thanks for your fantastic work! I'll have a try now

**Comment by daquexian** [comment]
@rui314 It works, thanks again!

**Comment by rui314** [comment]
Great! Thank you for confirming.

**Comment by daquexian** [comment]
@rui314 😂 There is a new issue: Several hours ago I only tried deleting and re-generating liboneflow.so and ../python/oneflow/_oneflow_internal.cpython-38-x86_64-linux-gnu.so, and latest mold works on these two libraries. But I just found it fails on generating libof_pyext_obj.so. The error is:

```
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
```

You can try reproducing it in the docker container.

**Comment by daquexian** [comment]
@rui314 Do you have any time to solve this issue? I can help if needed :)

**Comment by rui314** [comment]
Sorry, I'll take a look before releasing 1.2.1.

**Comment by daquexian** [comment]
> Sorry, I'll take a look before releasing 1.2.1.

Thanks!

**Comment by rui314** [comment]
I fixed the crash bug in the above commit. Please rebuild mold and try again. Thanks!

**Comment by daquexian** [comment]
> I fixed the crash bug in the above commit. Please rebuild mold and try again. Thanks!

The latest mold builds oneflow successfully! Mold is extremely useful and saves a lot of link time. Thanks for your fantastic work!
