### ISSUE TITLE
RISC-V: Testing as-needed ... collect2: fatal error

### ISSUE THREAD

**Issue by advancedwebdeveloper** [rui314/mold#406]
Hi.

Got this:

> $ make test
> make -C test -f Makefile.linux --no-print-directory --output-sync
> Testing z-nodump ... OK
> Testing as-needed ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
> compilation terminated.
> make[1]: *** [Makefile.linux:6: elf/as-needed.sh] Error 1
> make: *** [Makefile:162: test] Error 2

**Comment by advancedwebdeveloper** [comment]
Please inform which information should be shared, regarding my build environment.

**Comment by rui314** [comment]
What is your machine and distro? I'm using a SiFive Unmatched board with Ubuntu.

**Comment by advancedwebdeveloper** [comment]
You can reproduce via
> $ qemu-system-riscv64 -machine virt -nographic -m 2048 -smp 4 -bios /usr/lib/riscv64-linux-gnu/opensbi/generic/fw_jump.elf -kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf -device virtio-net-device,netdev=eth0 -netdev user,id=eth0 -drive file=ubuntu.img,format=raw,if=virtio -netdev user,id=usernet,hostfwd=tcp::22222-:22 

[Compressed vhdd image, for Qemu](https://drive.google.com/file/d/1xgF3AqR0iXBGV5N1oGTGuuuzJVJnrhFt/view?usp=sharing)
**Host** machine uses 

> $ qemu-system-riscv64 --version
> QEMU emulator version 6.0.0 (Debian 1:6.0+dfsg-2expubuntu1.2)

> $ apt info u-boot-qemu
> Package: u-boot-qemu
> Version: 2021.07+dfsg-0ubuntu8
> Priority: optional
> Section: admin
> Source: u-boot
> Origin: Ubuntu

> $ apt info opensbi
> Package: opensbi
> Version: 0.9-2ubuntu2
> Priority: optional
> Section: misc
> Origin: Ubuntu


Within the RISC-V **guest**:
I am seeing that the kernel is of version **Ubuntu 20.04.4 LTS 5.11.0-1031-generic**

> 
> $ cmake --version
> cmake version 3.16.3
> $ ninja --version
> 1.10.0
> $ gcc --version
> gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> $ ld --version
> GNU ld (GNU Binutils for Ubuntu) 2.34

**Mold's** version is:

> $ mold --version
> mold 1.1.1 (c1af9c97e763a1d521889191a83b27bd6c43b351; compatible with GNU ld)
Guest machine does not allow SSH access, from the host's side, cause of wrong configuration.
Also check Qemu's configuration.

There is an option to perform automated builds, run test suites within the guest machine (scripts).
Also remote access, via an SSH, could allow some CI integration to be done (against's Qemu's RISC-V guest environment).

**Comment by advancedwebdeveloper** [comment]
@rui314 , where you able to reproduce?

**Comment by rui314** [comment]
Yes, and I think these problems have been fixed. Please sync to git head and try again.
