### ISSUE TITLE
Support preloading without changing command line arguments

### ISSUE THREAD

**Issue by nitsky** [rui314/mold#41]
According to the README:

> if you run mold with `-preload` flag along with other command line flags, it becomes a daemon and halts after parsing input files. Then, if you invoke mold with the same command line options (except -preload flag), it tells the daemon to reload only updated files and proceed.

I am using mold with my rust project to improve incremental link times, and the rust compiler does not provide a way to change the linker flags depending on whether this is the first build or a subsequent build. Because of this, I am unable to take advantage of preloading.

Would you consider changing this behavior so that you do not have to omit the `-preload` flag on the second run? This means the behavior with the `-preload` flag would be:

> if you run mold with `-preload` flag along with other command line flags, it becomes a daemon and halts after parsing input files. Then, if you invoke mold with the same command line options (*including* -preload flag), it tells the daemon to reload only updated files and proceed.

**Comment by rui314** [comment]
Thank you for your suggestion, but I think there are a few practical issues with that approach:

 - Preloading is supposed to be used in preload object files, compile, link cycles. So, in a single build (e.g. a single invocation of `make` or `cargo`), you are supposed to first run mold with -reload, compile source, and then invoke mold again without -preload. Can you make a change to cargo config to do this in the first place?
 - If we allow the exact same command line flags, every number of mold run does preload, and every odd number of mold run creates an output. I think it can easily be out of sync and confuses build systems and users.

**Comment by nitsky** [comment]
@rui314 thanks for the explanation, I clearly misunderstood how preloading is implemented in mold. This will not work with cargo because cargo does not allow the user to access the list of object files prior to linking.

Ideally, mold would have a feature like this:

If I run `mold -daemon -o output a.o b.o c.o`, mold detects that no daemon is running, starts one up, and performs the first link.
Now, I can run `mold -daemon -o output a.o b.o c.o` any number of times, and each time mold detects that the daemon is running and the arguments are the same, so it reuses work from the first invocation.

Is this possible? I am not an expert on linking, so I don't know what the limitations are.

Thank you!

**Comment by rui314** [comment]
The preloading feature can make mold faster, but mold is already pretty fast. Could you share a little bit more about why you wanted to use the preloading feature? How long does your build takes for the linking step?

**Comment by vi** [comment]
> why you wanted to use the preloading feature?

To move from "1.69s" in "mold" column in README to "0.79s" in "mold w/ preloading"?

**Comment by gilescope** [comment]
If you're using `mold --run` then that would know when it had started for the first time and could do the --preload and then subsequent mold calls could make use of that for the lifetime that the mold --run is running. I.e. it could act as a short-term daemon. (That said maybe I too have misunderstood)

**Comment by rui314** [comment]
When mold started as `mold run make`, it doesn't know the actual linker command. It only gets `make` as an argument. But we need a list of object files and other command line parameters to start preloading. So it is not feasible.

**Comment by gilescope** [comment]
Can’t preload but once the first child mold process runs you have enough
knowledge to speed up subsequent invocations.

**Comment by rui314** [comment]
Object file preloading doesn't seem to get traction, and it looks to me that making that feature trickier/more implicit isn't a good idea, so I'll close this issue as working-as-intended.
