### ISSUE TITLE
invalid relocation for non-allocated sections: R_ARM_TLS_LDO32

### ISSUE THREAD

**Issue by iulian3144** [rui314/mold#417]
```
$ mold --version
mold 1.1.1 (006b13aec1506ac141de951d3c419f84d40e9766; compatible with GNU ld)
```
Error:
```
mold: fatal: <snip>/fp_os.lib:(.debug_loc): invalid relocation for non-allocated sections: R_ARM_TLS_LDO32
```
Probably not a real issue but I have no idea why I'm getting this error. I have no experience with linkers (or ARM architecture).

Probably, the naive approach would be to add a switch case in `elf/arch-arm32.cc@InputSection<E>::apply_reloc_nonalloc` (which I did).

<details>
  <summary>dummy patch (click to expand)</summary>

  ```diff
  diff --git a/elf/arch-arm32.cc b/elf/arch-arm32.cc
  index 508f97bb..c75dc019 100644
  --- a/elf/arch-arm32.cc
  +++ b/elf/arch-arm32.cc
  @@ -341,6 +341,9 @@ void InputSection<E>::apply_reloc_nonalloc(Context<E> &ctx, u8 *base) {
      case R_ARM_ABS32:
        *(u32 *)loc = S + A;
        break;
  +    case R_ARM_TLS_LDO32:
  +      *(u32 *)loc = S + A - ctx.tls_begin;
  +      break;
      default:
        Fatal(ctx) << *this << ": invalid relocation for non-allocated sections: "
                    << rel;
  ```
</details>
This makes the error go away but I doubt that it does the correct things.

At least, I would like to have your confirmation if this is expected behavior or not.
If you need more information, please let me know.

Also, thanks a lot for dedicating your time to this awesome project.

**Comment by rui314** [comment]
Your patch seems correct, but I didn't expect that TLS relocations appear in non-memory-allocated sections. What was your program?

**Comment by iulian3144** [comment]
That was quick. Thanks a lot for your answer, Rui.

An application for an embedded Linux target (managed switch). It is proprietary (Hirschmann Operating System - HiOS) so it won't be possible for you to test/build if this is what you're interested in.
```
$ file */fp_os.lib */switchdrvr
*/fp_os.lib:  ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), with debug_info, not stripped
*/switchdrvr: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=6e8e0f43ec99fcc3ca44441f4a60f384adb309c4, for GNU/Linux 2.6.32, with debug_info, not stripped
```
`switchdrvr` is the output program.

_Just for reference:_
`fp_os.lib` is a [FASTPATH](https://www.broadcom.com/products/ethernet-connectivity/software/fastpath) library.

If you were looking for some other specific information, please let me know and I'll try to pass that on to you if possible.
