### ISSUE TITLE
Add --oformat,binary support

### ISSUE THREAD

**Issue by X547** [rui314/mold#418]
Need for building boot loaders.

```
[29/900] BuildMBR objects/haiku/x86_64/release/bin/writembr/mbr.bin 
mold: fatal: unknown command line option: --oformat
collect2: error: ld returned 1 exit status
```
```
/Haiku/data/packages/haiku2/generated.x86_64/cross-tools-x86_64/bin/x86_64-unknown-haiku-gcc -B /Haiku/data/packages/mold -fno-strict-aliasing -fno-delete-null-pointer-checks -fno-builtin-fork -fno-builtin-vfork -Xlinker --no-undefined -Xlinker --Bsymbolic \
../src/bin/writembr/mbr.S -o objects/haiku/x86_64/release/bin/writembr/mbr.bin  -nostdlib -m32 -Wl,--oformat,binary -Wl,-z,notext \
-Xlinker -S -Xlinker -N -Xlinker --entry=start -Xlinker -Ttext=0x600
```

**Comment by rui314** [comment]
I don't think we can build a bootloader with mold if we only support --oformat=binary, because bootloaders generally use a linker script to fix file layout in some specific way.

**Comment by X547** [comment]
For Haiku needs following requirements are enough:

1. Ability to set image base address (0x80000000 for RISC-V boot loader).
2. Ability to put startup code at image beginning (put object file first when linking?).
3. Know image size (to reserve memory range), BSS section begin/end (to run zeroing code), constructor functions array. Linker symbols _edata, _end, __init_array_start etc. are needed.

It should be not hard to add raw output to linker.

**Comment by rui314** [comment]
Thank you for the input. I implemented the flag in the above commit.
