### ISSUE TITLE
Add support for "old" dynamic tags with --disable-new-dtags

### ISSUE THREAD

**Issue by mheimlich** [rui314/mold#420]
In many of our applications we rely on the propagation of `RPATH` of the executable to the library search path for loaded shared libraries (plugins). The newer replacement `RUNPATH` does not have this effect. Mold currently ignores the  `--disable-new-dtags` flags that works with `ld`.

I'm well aware that RPATH is deprecated, so feel free to disregard this feature request, but it solves our issues with distributing our application just fine. Also I don't now which other tags are affected by this command line flag.

**Comment by rui314** [comment]
Supporting `--disable-new-dtags` is fine, but the problem is that I don't know the exact effects of that flag, so let me take a look.

**Comment by rui314** [comment]
I added the `--disable-new-dtags` flag to mold in the above commit.

**Comment by andrewkcorcoran** [comment]
clang++ doesn't have this option so it errors out instead of passing the option down to mold. Would it be possible to enable this option using an environment variable? e.g. `MOLD_OPTIONS` if defined is a list of default mold options?

**Comment by rui314** [comment]
You can pass that option by passing `-Wl,--disable-new-dtags` to clang++, no?

**Comment by andrewkcorcoran** [comment]
Ah I wasn't aware of that option, cheers that's works!

**Comment by mheimlich** [comment]
Thanks a lot for implementing this! I'm currently on vacation, so I can't test it for now, but surely will upon my return!
