### ISSUE TITLE
error when building mesa

### ISSUE THREAD

**Issue by zmike** [rui314/mold#421]
When trying to build mesa using mold, I get lots of errors like:

`mold: error: undefined symbol: src/amd/vulkan/libvulkan_radeon.so.p/radv_llvm_helper.cpp.o: _TLS_MODULE_BASE_`

from various drivers. Only happens with release or debugoptimized build types. Any tips?

**Comment by rui314** [comment]
Thank you for your report. That is a bug in mold which I fixed in the above commit. Does this fix work for you?

**Comment by zmike** [comment]
It fixes the compile issue, but attempting to run anything (e.g., glxgears) on the mesa build crashes.

**Comment by rui314** [comment]
I submitted another fix. With that, at least mesa's tests now pass. They were previously failing indeed.
