### ISSUE TITLE
Creating executable `.so` files with Mold doesn't work

### ISSUE THREAD

**Issue by Kestrer** [rui314/mold#422]
For this contents of `example.c`:

```c
#include <stdlib.h>

const char interp[] __attribute__((section(".interp"))) = "/lib64/ld-linux-x86-64.so.2";

void _start() {
	exit(0);
}
```

Gold works:

```
$ clang -shared example.c -o example.so -fuse-ld=gold && ./example.so; echo $?
0
$ gcc -shared example.c -o example.so -fuse-ld=gold && ./example.so; echo $?
0
```

LLD works:

```
$ clang -shared example.c -o example.so -fuse-ld=lld && ./example.so; echo $?
0
$ gcc -shared example.c -o example.so -fuse-ld=lld && ./example.so; echo $?
0
```

but Mold causes a segfault:

```
$ clang -shared example.c -o example.so -fuse-ld=mold && ./example.so; echo $?
Segmentation fault
139
```

I know it's something to do with the `.interp` section, because if I specify the interpreter manually Mold's version _does_ work:

```
$ clang -shared example.c -o example.so -fuse-ld=mold && /lib64/ld-linux-x86-64.so.2 ./example.so; echo $?
0
```

When looking at `objdump`, all three produce a similar output though:

```
$ objdump -s --section=.interp example.so

example.so:     file format elf64-x86-64

Contents of section .interp:
 0540 2f6c6962 36342f6c 642d6c69 6e75782d  /lib64/ld-linux-
 0550 7838362d 36342e73 6f2e3200           x86-64.so.2.
```

So I'm really not sure what's going on here.

**Comment by rui314** [comment]
Thank you for your report!

The dynamic linker doesn't use the section header at all. Instead, it uses the program header to find an interpreter name. It looks like other linkers sets `.interp` section's address to the program header if the section is supplied by the user, but I don't think that's a very obscure way to do that. The more common way to do that is to pass `-Wl,--dynamic-linker=<dynamic-linker-path>`.

Please rebuild mold and try again with `--dynamic-linker`, just like

`$ clang -shared example.c -o example.so -fuse-ld=mold -Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2 && /lib64/ld-linux-x86-64.so.2 ./example.so; echo $?

?

**Comment by Kestrer** [comment]
Indeed it works, thank you!

```
$ cat example.c
#include <stdlib.h>
#include <stdio.h>
void _start() {
	exit(0);
}
$ clang -shared example.c -o example.so -Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2 -fuse-ld=mold && ./example.so; echo $?
0
```

However, the unforuntate thing is that it now fails with LLD (but not Gold) 😅 (this is why I assumed `interp` is the correct way to do it initially):

```
$ clang -shared example.c -o example.so -Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2 -fuse-ld=lld && ./example.so; echo $?
zsh: segmentation fault  ./example.so
139
```

But if I re-add the `interp` static _and_ use the command-line arg it seems to work with all three, so I guess I'll do that.

**Comment by Alcaro** [comment]
I've had some success creating an executable .so by replacing -shared with -rdynamic. Feels cleaner, less platform conditionals. (May need -fpic.)

But I didn't test very thoroughly, so I may have missed something.
