### ISSUE TITLE
alpine mold package not found

### ISSUE THREAD

**Issue by gitmalong** [rui314/mold#428]
```
> [builder  3/18] RUN apk add mold --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing:                                     
#8 0.210 fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/aarch64/APKINDEX.tar.gz                                                
#8 0.843 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
#8 6.116 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
#8 7.728 ERROR: unable to select packages:
#8 7.749   mold (no such package):
#8 7.749     required by: world[mold]
------
executor failed running [/bin/sh -c apk add mold --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing]: exit code: 1
```

Executed within `rust:alpine3.15`

**Comment by rui314** [comment]
I'm not using Alpine and not a maintainer of the package, so I don't think I can help you on this matter. Please file a bug to Alpine.

**Comment by gitmalong** [comment]
I thought you are providing the binaries and might know the cause of the error.

**Comment by rui314** [comment]
I indeed provide binaries in the .tar.gz format on the release pages (e.g. https://github.com/rui314/mold/releases/tag/v1.1.1), but that's different from Linux distos' binary packages. Just like Alpine's package maintainer wouldn't know anything about the binary .tar.gz I distribute on that page, I know nothing about Alpine's packages.

**Comment by gitmalong** [comment]
Might the issue be that I am running my Docker image on a MacBook with M1 (ARM) procesor while the package is only available for x86_64? If yes I'm not sure who would be responsibility for that.

**Comment by rui314** [comment]
It's likely that Alpine provides only the x86-64 package for mold. If that's the case, someone in the Alpine project need to build their mold package on an ARM machine and distribute it to make mold usable on Alpine/ARM.
