### ISSUE TITLE
Release tag should match version in name of artifacts

### ISSUE THREAD

**Issue by Hofer-Julian** [rui314/mold#435]
The tag of the latest release is `v1.2`, but the name of the artifact is `mold-1.2.0-x86_64-linux.tar.gz`.
Most [release monitors](https://release-monitoring.org/project/241732/) would expect the artifact to be called `mold-1.2-x86_64-linux.tar.gz` in the style of the other releases.

**Comment by rui314** [comment]
Thank you for pointing it out. I'll re-tag that commit as `v1.2.0`.

**Comment by rui314** [comment]
Mold version number is in its `Makefile`, and the version number is `1.2.0` there. I made a mistake to tag it as `1.2`, but it looks like it's too late to change the tag name, as it also changes the release note's URL. I'll be careful when I make a release next time.

**Comment by Hofer-Julian** [comment]
Thank you!
