### ISSUE TITLE
Mold 1.2.0 fails to build on ARMv7 on Ubuntu Focal based Armbian

### ISSUE THREAD

**Issue by turkerali** [rui314/mold#437]
When I try to build Mold 1.2.0 on ARMv7 based Odroid HC1 board with gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1),
the build fails with the following error:

static_cast<size_type>(        )
elf/../filetype.h:44:35: error: non-constant-expression cannot be narrowed from type 'unsigned long long' to 'std::span::size_type' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]

                                  sec.sh_size / sizeof(ElfSym<E>)};
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

elf/../filetype.h:85:13:` note: in instantiation of function template specialization 'mold::is_gcc_lto_obj<mold:: elf ::X86_64, mold:: elf ::Context<mold:: elf ::ARM64> >' requested here
        if (is_gcc_lto_obj<elf::X86_64>(mf))
            ^
elf/main.cc:75:19: note: in instantiation of function template specialization 'mold::get_file_type<mold:: elf ::Context<mold:: elf ::ARM64> >' requested here
  FileType type = get_file_type(mf);
                  ^
elf/../filetype.h:44:35: note: insert an explicit cast to silence this issue
                                  sec.sh_size / sizeof(ElfSym<E>)};
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  static_cast<size_type>(        )

Kernel version:
`Linux odroidxu4 5.4.181-odroidxu4 #22.02.1 SMP PREEMPT Sun Feb 27 08:55:42 UTC 2022 armv7l armv7l armv7l GNU/Linux`

**Comment by rui314** [comment]
If you add `-Wno-c++11-narrowing` to `MOLD_CXXFLAGS`, does it compile?

**Comment by turkerali** [comment]
Thanks for the quick reply. Adding `-Wno-c++11-narrowing` to `MOLD_CXXFLAGS,` solves the issue, and mold builds fine.

Btw, there is another warning I noticed, which you may want to address:

`CMake Warning at CMakeLists.txt:114 (message):
  You are building oneTBB as a static library.  This is highly discouraged
  and such configuration is not supported.  Consider building a dynamic
  library to avoid unforeseen issues.`

**Comment by rui314** [comment]
It is not recommended by oneTBB, but we deliberately static-link oneTBB, so even though the warning is real, that warning message is expected.
