### ISSUE TITLE
--gdb-index causes "unknown DWARF version 2"

### ISSUE THREAD

**Issue by llunak** [rui314/mold#439]
Current git version of mold fails to link even a trivial program on openSUSE 15.3 if --gdb-index is used. This is possibly the same problem mentioned by the last comment in #396 .

$ cat a.cpp
int main() { return 0; }
$ clang++ -Wall -g -ggnu-pubnames a.cpp -fuse-ld=mold
[no output, i.e. no problem]

$ clang++ -Wall -g -ggnu-pubnames a.cpp -fuse-ld=mold -Wl,--gdb-index
mold: fatal: /usr/lib64/crt1.o: --gdb-index: unknown DWARF version 2
mold: fatal: /usr/lib64/crtn.o: --gdb-index: unknown DWARF version 2
clang-11.0: error: linker command failed with exit code 1 (use -v to see invocation)

$ mold --version
mold 1.2.0 (7ebd071273691a5cc095203f6542b2b13ec6642c; compatible with GNU ld)
$ rpm -qf /usr/lib64/crt1.o
glibc-devel-2.31-150300.20.7.x86_64
[This is the normal latest glibc-devel package for openSUSE 15.3.]

$ llvm-dwarfdump --all /usr/lib64/crt1.o
/usr/lib64/crt1.o:      file format elf64-x86-64

.debug_abbrev contents:
Abbrev table for offset: 0x00000000
[1] DW_TAG_compile_unit DW_CHILDREN_no
        DW_AT_stmt_list DW_FORM_data4
        DW_AT_low_pc    DW_FORM_addr
        DW_AT_high_pc   DW_FORM_addr
        DW_AT_name      DW_FORM_strp
        DW_AT_comp_dir  DW_FORM_strp
        DW_AT_producer  DW_FORM_strp
        DW_AT_language  DW_FORM_data2

Abbrev table for offset: 0x00000014
[1] DW_TAG_compile_unit DW_CHILDREN_yes
        DW_AT_producer  DW_FORM_strp
        DW_AT_language  DW_FORM_data1
        DW_AT_name      DW_FORM_strp
        DW_AT_comp_dir  DW_FORM_strp
        DW_AT_stmt_list DW_FORM_sec_offset

[2] DW_TAG_variable     DW_CHILDREN_no
        DW_AT_name      DW_FORM_strp
        DW_AT_decl_file DW_FORM_data1
        DW_AT_decl_line DW_FORM_data1
        DW_AT_type      DW_FORM_ref4
        DW_AT_external  DW_FORM_flag_present
        DW_AT_location  DW_FORM_exprloc

[3] DW_TAG_base_type    DW_CHILDREN_no
        DW_AT_byte_size DW_FORM_data1
        DW_AT_encoding  DW_FORM_data1
        DW_AT_name      DW_FORM_string

[4] DW_TAG_const_type   DW_CHILDREN_no
        DW_AT_type      DW_FORM_ref4

.debug_info contents:
0x00000000: Compile Unit: length = 0x0000002a, format = DWARF32, version = 0x0002, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000002e)

0x0000000b: DW_TAG_compile_unit
              DW_AT_stmt_list   (0x00000000)
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_high_pc     (0x000000000000002b)
              DW_AT_name        ("../sysdeps/x86_64/start.S")
              DW_AT_comp_dir    ("/home/abuild/rpmbuild/BUILD/glibc-2.31/csu")
              DW_AT_producer    ("GNU AS 2.37")
              DW_AT_language    (DW_LANG_Mips_Assembler)
0x0000002e: Compile Unit: length = 0x0000003b, format = DWARF32, version = 0x0004, abbr_offset = 0x0014, addr_size = 0x08 (next unit at 0x0000006d)

0x00000039: DW_TAG_compile_unit
              DW_AT_producer    ("GNU C11 7.5.0 -mtune=generic -march=x86-64 -g -g -O2 -std=gnu11 -fgnu89-inline -fmessage-length=0 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fpatchable-function-entry=16,14 -fmerge-all-constants -frounding-math -fstack-protector-strong -fmath-errno -fno-stack-protector -ftls-model=initial-exec -fPIE")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name        ("init.c")
              DW_AT_comp_dir    ("/home/abuild/rpmbuild/BUILD/glibc-2.31/csu")
              DW_AT_stmt_list   (0x0000005c)

0x0000004b:   DW_TAG_variable
                DW_AT_name      ("_IO_stdin_used")
                DW_AT_decl_file ("/home/abuild/rpmbuild/BUILD/glibc-2.31/csu/init.c")
                DW_AT_decl_line (23)
                DW_AT_type      (0x00000067 "const int")
                DW_AT_external  (true)
                DW_AT_location  (DW_OP_addr 0x0)

0x00000060:   DW_TAG_base_type
                DW_AT_byte_size (0x04)
                DW_AT_encoding  (DW_ATE_signed)
                DW_AT_name      ("int")

0x00000067:   DW_TAG_const_type
                DW_AT_type      (0x00000060 "int")

0x0000006c:   NULL

.eh_frame contents:

00000000 00000014 00000000 CIE
  Format:                DWARF32
  Version:               1
  Augmentation:          "zR"
  Code alignment factor: 1
  Data alignment factor: -8
  Return address column: 16
  Augmentation data:     1B

  DW_CFA_def_cfa: reg7 +8
  DW_CFA_offset: reg16 -8
  DW_CFA_undefined: reg16

00000018 00000010 0000001c FDE cie=00000000 pc=00000000...0000002b
  Format:       DWARF32
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:

.debug_aranges contents:
Address Range Header: length = 0x0000002c, format = DWARF32, version = 0x0002, cu_offset = 0x00000000, addr_size = 0x08, seg_size = 0x00
[0x0000000000000000,  0x000000000000002b)
Address Range Header: length = 0x0000001c, format = DWARF32, version = 0x0002, cu_offset = 0x00000000, addr_size = 0x08, seg_size = 0x00

.debug_line contents:
debug_line[0x00000000]
Line table prologue:
    total_length: 0x00000058
          format: DWARF32
         version: 3
 prologue_length: 0x00000030
 min_inst_length: 1
 default_is_stmt: 1
       line_base: -5
      line_range: 14
     opcode_base: 13
standard_opcode_lengths[DW_LNS_copy] = 0
standard_opcode_lengths[DW_LNS_advance_pc] = 1
standard_opcode_lengths[DW_LNS_advance_line] = 1
standard_opcode_lengths[DW_LNS_set_file] = 1
standard_opcode_lengths[DW_LNS_set_column] = 1
standard_opcode_lengths[DW_LNS_negate_stmt] = 0
standard_opcode_lengths[DW_LNS_set_basic_block] = 0
standard_opcode_lengths[DW_LNS_const_add_pc] = 0
standard_opcode_lengths[DW_LNS_fixed_advance_pc] = 1
standard_opcode_lengths[DW_LNS_set_prologue_end] = 0
standard_opcode_lengths[DW_LNS_set_epilogue_begin] = 0
standard_opcode_lengths[DW_LNS_set_isa] = 1
include_directories[  1] = "../sysdeps/x86_64"
file_names[  1]:
           name: "start.S"
      dir_index: 1
       mod_time: 0x00000000
         length: 0x00000000

Address            Line   Column File   ISA Discriminator Flags
------------------ ------ ------ ------ --- ------------- -------------
0x0000000000000000     63      0      1   0             0  is_stmt
0x0000000000000002     79      0      1   0             0  is_stmt
0x0000000000000005     85      0      1   0             0  is_stmt
0x0000000000000006     88      0      1   0             0  is_stmt
0x0000000000000009     90      0      1   0             0  is_stmt
0x000000000000000d     93      0      1   0             0  is_stmt
0x000000000000000e     97      0      1   0             0  is_stmt
0x000000000000000f    101      0      1   0             0  is_stmt
0x0000000000000016    102      0      1   0             0  is_stmt
0x000000000000001d    104      0      1   0             0  is_stmt
0x0000000000000024    120      0      1   0             0  is_stmt
0x000000000000002a    122      0      1   0             0  is_stmt
0x000000000000002b    122      0      1   0             0  is_stmt end_sequence

debug_line[0x0000005c]
Line table prologue:
    total_length: 0x00000023
          format: DWARF32
         version: 3
 prologue_length: 0x0000001d
 min_inst_length: 1
 default_is_stmt: 1
       line_base: -5
      line_range: 14
     opcode_base: 13
standard_opcode_lengths[DW_LNS_copy] = 0
standard_opcode_lengths[DW_LNS_advance_pc] = 1
standard_opcode_lengths[DW_LNS_advance_line] = 1
standard_opcode_lengths[DW_LNS_set_file] = 1
standard_opcode_lengths[DW_LNS_set_column] = 1
standard_opcode_lengths[DW_LNS_negate_stmt] = 0
standard_opcode_lengths[DW_LNS_set_basic_block] = 0
standard_opcode_lengths[DW_LNS_const_add_pc] = 0
standard_opcode_lengths[DW_LNS_fixed_advance_pc] = 1
standard_opcode_lengths[DW_LNS_set_prologue_end] = 0
standard_opcode_lengths[DW_LNS_set_epilogue_begin] = 0
standard_opcode_lengths[DW_LNS_set_isa] = 1
file_names[  1]:
           name: "init.c"
      dir_index: 0
       mod_time: 0x00000000
         length: 0x00000000

.debug_str contents:
0x00000000: "../sysdeps/x86_64/start.S"
0x0000001a: "/home/abuild/rpmbuild/BUILD/glibc-2.31/csu"
0x00000045: "GNU AS 2.37"
0x00000051: "/home/abuild/rpmbuild/BUILD/glibc-2.31/csu"
0x0000007c: "init.c"
0x00000083: "GNU C11 7.5.0 -mtune=generic -march=x86-64 -g -g -O2 -std=gnu11 -fgnu89-inline -fmessage-length=0 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fpatchable-function-entry=16,14 -fmerge-all-constants -frounding-math -fstack-protector-strong -fmath-errno -fno-stack-protector -ftls-model=initial-exec -fPIE"
0x000001cc: "_IO_stdin_used"
0x000001db: "/home/abuild/rpmbuild/BUILD/glibc-2.31/csu"
0x00000206: "GNU C11 7.5.0 -mtune=generic -march=x86-64 -g -g -O2 -std=gnu11 -fgnu89-inline -fmessage-length=0 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fpatchable-function-entry=16,14 -fmerge-all-constants -frounding-math -fstack-protector-strong -fmath-errno -fno-stack-protector -ftls-model=initial-exec -fPIE"
0x0000034f: "static-reloc.c"

**Comment by rui314** [comment]
Can you try again after rebuilding mold? Now, mold doesn't read `.debug_info` contents, so it doesn't matter what version the debug info is.

**Comment by llunak** [comment]
Yes, the current git avoids the abort, but see #444 .

**Comment by llunak** [comment]
In case you decide to bring back the .debug_info reading, this one is actually simple: https://gist.github.com/llunak/40072018c1085cbf398b5c69a00a8882

**Comment by rui314** [comment]
This is fixed in ec062f72418d821fca368d5e871a0a359a1948be
