### ISSUE TITLE
--gdb-index causes "unknown DWARF version 29531" with compressed debug sections

### ISSUE THREAD

**Issue by llunak** [rui314/mold#440]
Current git version of mold fails to link even a trivial binary if compressed debug sections are generated by the linker.

$ cat a.cpp
int test() { return 0; }
$ clang++ -shared a.cpp -g -gz=zlib -ggnu-pubnames -fPIC -Wl,--gdb-index -Wl,--compress-debug-sections=zlib
[no output, i.e. no problem]
$ clang++ -shared a.cpp -g -gz=zlib -ggnu-pubnames -fPIC -Wl,--gdb-index -Wl,--compress-debug-sections=zlib -fuse-ld=mold
mold: fatal: /tmp/a-ce2402.o: --gdb-index: unknown DWARF version 29531
clang-11.0: error: linker command failed with exit code 1 (use -v to see invocation)
$ mold --version
mold 1.2.0 (7ebd071273691a5cc095203f6542b2b13ec6642c; compatible with GNU ld)

This seems to be caused by --compress-debug-sections=zlib (which IIRC is implied by -gz=zlib if Clang 14+ is used, with older it needs to be specified explicitly).

**Comment by rui314** [comment]
I hope d4cc0ed3fb5f1d595cdc2e4747f46aa7944791d0 fixed the issue. Can you try again? Thanks!

**Comment by llunak** [comment]
Yes, the current git avoids the abort, but see #444 .

**Comment by llunak** [comment]
Note: On repeated runs this complains about different files, even /usr/lib64/crtn.o (which is obviously not compressed), so this looks like a race condition somewhere.

**Comment by rui314** [comment]
Should be fixed now.
