### ISSUE TITLE
testsuite: failures on i586

### ISSUE THREAD

**Issue by marxin** [rui314/mold#441]
Using the latest master (21e1a80cec70152bbe7c1bc8648aaa468a3f1e7a), I see the following failures:

```
Testing hello-static-pie ... make[1]: *** [Makefile.linux:6: elf/hello-static-pie.sh] Error 1
...
Testing ifunc-static-pie ... make[1]: *** [Makefile.linux:6: elf/ifunc-static-pie.sh] Error 1
...
Testing lto-archive ... mold: fatal: out/test/elf/lto-archive/d.o: not claimed by the LTO plugin
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.linux:6: elf/lto-archive.sh] Error 1
Testing lto-dso ... mold: fatal: out/test/elf/lto-dso/a.o: not claimed by the LTO plugin
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.linux:6: elf/lto-dso.sh] Error 1
Testing lto-gcc ... mold: fatal: out/test/elf/lto-gcc/a.o: not claimed by the LTO plugin
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.linux:6: elf/lto-gcc.sh] Error 1
Testing lto-llvm ... clang-13.0: error: unable to execute command: Segmentation fault (core dumped)
clang-13.0: error: linker command failed due to signal (use -v to see invocation)
make[1]: *** [Makefile.linux:6: elf/lto-llvm.sh] Error 254
Testing lto-version-script ... mold: fatal: out/test/elf/lto-version-script/a.o: not claimed by the LTO plugin
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.linux:6: elf/lto-version-script.sh] Error 1
```

**Comment by rui314** [comment]
How important are 32-bit hosts? mold supports i586 and ARM32 as targets, but I think it is not as important as that to support them as hosts.

**Comment by marxin** [comment]
Sure, fully agree. What about printing a sorry message that the target in unsupported?

**Comment by marxin** [comment]
I noticed you claim the following targets are supported:
`mold currently supports x86-64, i386, ARM32, ARM64 and 64-bit RISC-V.`

**Comment by rui314** [comment]
They are supported as targets, but I didn't test them as hosts.

**Comment by sicherha** [comment]
Is this issue still relevant? For what it's worth, the test suite for mold 1.4.0 is running fine on an i686 Fedora build machine:
https://kojipkgs.fedoraproject.org//packages/mold/1.4.0/1.fc36/data/logs/i686/build.log
A few test cases are skipped because they have an architecture-related precondition check, but all others are green.

**Comment by marxin** [comment]
I can confirm the same, it's fine on openSUSE Tumbleweed.

**Comment by sicherha** [comment]
I suggest we close this issue then.

**Comment by marxin** [comment]
Works for me.
