### ISSUE TITLE
testsuite: linker-script3 test fails

### ISSUE THREAD

**Issue by marxin** [rui314/mold#445]
The test fails on `x86_64-linux-gnu` with the following result:

```
$ ./test/elf/linker-script3.sh
Testing linker-script3 ... /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/crt1.o: in function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.35/csu/../sysdeps/x86_64/start.S:103: undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by rui314** [comment]
I pulled `opensuse/tumbleweed` from Docker Hub, built mold inside it and run tests, and all tests passed. Can you debug that script a little bit to see why it is failing?

**Comment by marxin** [comment]
Whoops, sorry for the noice. Apparently I had an object `$root/a.o` that was selected by the linker script when I run tests from root directory ;)

**Comment by rui314** [comment]
Great, thank you for investigating!
