### ISSUE TITLE
Wrong code when using TLS global variable in common section

### ISSUE THREAD

**Issue by marxin** [rui314/mold#447]
The following crashes:
```
$ cat ~/Programming/testcases/emutls-3.c
__thread int i __attribute__((common));

int main (int ac, char *av[])
{
  i++;
}

$ gcc-11 ~/Programming/testcases/emutls-3.c -B. && ./a.out
Segmentation fault (core dumped)
```

**Comment by marxin** [comment]
However, it works with clang.

**Comment by rui314** [comment]
I didn't know it's doable to create a common TLS symbol. mold works if an uninitialized TLS variable is in `.tbss` (which is common (I mean more usual)), and that's what clang does. I'll fix mold anyway.
