### ISSUE TITLE
mold + gdc + -flto + partial static linking causes duplicated DSO

### ISSUE THREAD

**Issue by baryluk** [rui314/mold#479]
This might be a GCC issue, but it doesn't happen with `gold` or ld.bfd linker

`example.d`:

```d
int main(string[] args) {
  return 0;
}
```

```
gdc-12 -flto -frelease -static-libphobos -fuse-ld=mold example.d -o example
```

```
$ ./example
Aborting from ../../../../src/libphobos/libdruntime/gcc/sections/elf.d(727) DSO already registered.Aborted
```

Linux, Debian unstable, amd64

`gcc version 12.0.1 20220319 (experimental) [master r12-7719-g8ca61ad148f] (Debian 12-20220319-1) `

`mold 1.2.0 (compatible with GNU ld)`

`libgphobos-12-dev:amd64                                     12-20220319-1`

Same with gcc 11.2.0-20.

**Comment by baryluk** [comment]
Attaching produced binary if this is of any help

[issue-479.tar.gz](https://github.com/rui314/mold/files/8578627/issue-479.tar.gz)

(compiled with `gdc-12 -flto -Os -march=native -frelease -fdata-sections -ffunction-sections -fno-weak-templates -static-libphobos -fuse-ld=mold -Wl,-O12 -Wl,--gc-sections example.d -o example` )

**Comment by rui314** [comment]
I can reproduce the issue on a Ubuntu 22.04 machine with `gdc` that I just installed using apt. Looking...

**Comment by rui314** [comment]
I knew almost nothing about the D language and its compiler `gdc`, but I believe I somehow managed to fix this error. Can you recompile mold and try again? Thanks!

**Comment by baryluk** [comment]
> I knew almost nothing about the D language and its compiler `gdc`, but I believe I somehow managed to fix this error. Can you recompile mold and try again? Thanks!

Thanks for the quick identification and a fix. I will try in few hours on my machine and less trivial programs.

**Comment by baryluk** [comment]
Compiled and tested briefly. Looks to be working perfectly.
