### ISSUE TITLE
mold: fatal: -auxiliary may not be used without -shared

### ISSUE THREAD

**Issue by sajcho** [rui314/mold#482]
Build gcc-12 use mold.

+ CFLAGS+=' -fuse-ld=mold'
+ CXXFLAGS+=' -fuse-ld=mold'
+ export 'LDFLAGS=-Wl,-z,relro -Wl,-z,now -fuse-ld=mold'
+ LDFLAGS='-Wl,-z,relro -Wl,-z,now -fuse-ld=mold'
+ ../configure --prefix=/usr --libexecdir=/usr/lib --enable-languages=c,c++,fortran,lto --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-linker-build-id --enable-initfini-array --enable-link-serialization=1 --enable-gnu-indirect-function --enable-libstdcxx-backtrace=yes --enable-plugin --enable-bootstrap --disable-nls --disable-multilib --disable-sjlj-exceptions --with-system-zlib --with-isl
 --with-linker-hash-style=gnu --with-build-config=bootstrap-lto --with-pkgversion=SAUX-x86_64 --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu ac_cv_prog_LD=x86_64-unknown-linux-gnu-mold ac_cv_prog_LD_FOR_TARGET=x86_64-unknown-linux-gnu-mold

+ make -O 'BOOT_CFLAGS=-O2 -m64 -march=x86-64 -mtune=generic -Wno-psabi -fuse-ld=mold' 'BOOT_LDFLAGS=-Wl,-z,relro -Wl,-z,now -fuse-ld=mold' 'LDFLAGS_FOR_TARGET=-Wl,-z,relro -Wl,-z,now -fuse-ld=mold' 'STAGE1_CFLAGS=-O2 -m64 -march=x86-64 -mtune=generic -Wno-psabi -fuse-ld=mold' 'STAGE2_CFLAGS=-O2 -m64 -march=x86-64 -mtune=generic -Wno-psabi -fuse-ld=mold' 'STAGE3_CFLAGS=-O2 -m64 -march=x86-64 -mtune=generic -Wno-psabi -fuse-ld=mold' 'STAGE4_CFLAGS=-O2 -m64 -march=x86-64
-mtune=generic -Wno-psabi -fuse-ld=mold' profiledbootstrap

Error: 
/home/devel/building/work/src/build/x86_64-unknown-linux-gnu/libgomp/config.log

configure:3912: checking whether the C compiler works
configure:3934: /home/devel/building/work/src/build/./gcc/xgcc -B/home/devel/building/work/src/build/./gcc/ -B/usr/x86_64-unknown-linux-gnu/bin/ -B/usr/x86_64-unknown-linux-gnu/lib/ -isystem /usr/x86_64-unknown-linux-gnu/include -isystem /usr/x86_64-unknown-linux-gnu/sys-include   -fno-checking -g -O2 -m64 -march=x86-64 -mtune=generic -Wno-psabi -fuse-ld=mold  -Wl,-z,relro -Wl,-z,now -fuse-ld=mold conftest.c  >&5
mold: fatal: -auxiliary may not be used without -shared
collect2: error: ld returned 1 exit status

**Comment by rui314** [comment]
It worked for me too. Can you try again after rebuilding mold?

**Comment by sajcho** [comment]
I apologize for the delay.

With this configuration:
Use gcc-12-20220424

../configure --prefix=/usr --libexecdir=/usr/lib --enable-languages=c,c++,fortran,lto \--enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-linker-build-id --enable-initfini-array --enable-link-serialization=1 --enable-gnu-indirect-function --enable-libstdcxx-backtrace=yes --enable-plugin --disable-nls --disable-werror --disable-libssp --disable-multilib --disable-libstdcxx-pch --disable-sjlj-exceptions --with-system-zlib --with-isl --with-ld=/usr/bin/mold --with-linker-hash-style=gnu --with-build-config=bootstrap-lto --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu

and rebuild mold use latest commit

make -j 8 bootstrap # nproc=8
result:
build/genconfig.o build/rtl.o build/read-rtl.o build/ggc-none.o build/vec.o build/min-insn-modes.o build/gensupport.o build/print-rtl.o build/hash-table.o build/sort.o build/read-md.o build/errors.o .././libiberty/libiberty.a
/home/devel/building/work/src/gcc-12-20220424/build/./prev-gcc/xg++ -B/home/devel/building/work/src/gcc-12-20220424/build/./prev-gcc/ -B/usr/x86_64-unknown-linux-gnu/bin/ -nostdinc++ -B/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -B/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs  -I/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu  -I/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include  -I/home/devel/building/work/src/gcc-12-20220424/libstdc++-v3/libsupc++ -L/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -L/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs   -g -O2 -fchecking=1 -flto=jobserver -frandom-seed=1 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H  -DGENERATOR_FILE -static-libstdc++ -static-libgcc  -o build/gentarget-def \
    build/gentarget-def.o build/rtl.o build/read-rtl.o build/ggc-none.o build/vec.o build/min-insn-modes.o build/gensupport.o build/print-rtl.o build/hash-table.o build/sort.o build/read-md.o build/errors.o .././libiberty/libiberty.a
terminate called after throwing an instance of 'std::runtime_error'
  what():  pthread_create has failed: Resource temporarily unavailable
collect2: fatal error: ld terminated with signal 6 [Aborted]
compilation terminated.
make[3]: *** [Makefile:3015: build/genconfig] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gfdl.pod gcc.pod gfortran.pod gcov-dump.pod gcov-tool.pod fsf-funding.pod gpl.pod cpp.pod gcov.pod lto-dump.pod
make[3]: Leaving directory '/home/devel/building/work/src/gcc-12-20220424/build/gcc'
make[2]: *** [Makefile:5045: all-stage3-gcc] Error 2
make[2]: Leaving directory '/home/devel/building/work/src/gcc-12-20220424/build'
make[1]: *** [Makefile:25516: stage3-bubble] Error 2
make[1]: Leaving directory '/home/devel/building/work/src/gcc-12-20220424/build'
make: *** [Makefile:25580: bootstrap] Error 2
=======> ERROR: Building '/home/devel/packages/gcc#12.0.1-3.x86_64.pkg.tar.zst' failed.

RAM=64G

######

make -j 6 bootstrap # result OK

Control:
readelf -p .comment /usr/bin/gcc

String dump of section '.comment':
  [     0]  mold 1.2.1 (d0fc8fb005eb721b6df52f4ea66034ae98308eb5; compatible with GNU ld)
  [    4f]  GCC: (SAUX-x86_64) 12.0.1 20220424 (experimental)
######

Why I can't use all the kernels is a mystery to me.

Why I can't use all the cores is a mystery to me.
I will be happy for any solution.

**Comment by rui314** [comment]
It looks like the same issue as https://github.com/rui314/mold/issues/410. We need to fix this or at least how to workaround the issue by increasing a resource usage limit.

**Comment by sajcho** [comment]
Only with experimental settings:
MAKEFLAGS = $ (expr $ (nproc) \ * 2)
The compilation has passed.

$ lscpu
Architecture: x86_64
  CPU op-mode (s): 32-bit, 64-bit
  Address sizes: 39 bits physical, 48 bits virtual
  Byte Order: Little Endian
CPU (s): 8
  On-line CPU (s) list: 0-7
Vendor ID: GenuineIntel
  Model name: Intel (R) Core (TM) i7-9700K CPU @ 3.60GHz
    CPU family: 6
    Model: 158
    Thread (s) per core: 1
    Core (s) per socket: 8
    Socket (s): 1
    Stepping: 12
    CPU (s) scaling MHz: 94%
    CPU max MHz: 4900,0000
    CPU min MHz: 800.0000
    BogoMIPS: 7200.00
    Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebop nop_ rep_
                         nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avxfn
                         prefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt_
                         xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d arch_capabilities
Virtualization features:
  Virtualization: VT-x
Caches (sum of all):
  L1d: 256 KiB (8 instances)
  L1i: 256 KiB (8 instances)
  L2: 2 MiB (8 instances)
  L3: 12 MiB (1 instance)
NUMA:
  NUMA node (s): 1
  NUMA node0 CPU (s): 0-7
Vulnerabilities:
  Itlb multihit: KVM: Mitigation: VMX disabled
  L1tf: Not affected
  Mds: Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
  Meltdown: Not affected
  Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
  Specter v1: Mitigation; usercopy / swapgs barriers and __user pointer sanitization
  Specter v2: Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
  Srbds: Vulnerable: No microcode
  Tsx async abort: Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled

I try:
MAKEFLAGS = $ (expr $ (nproc) + 1)

The classic says - something is rotten in the state ....

**Comment by sajcho** [comment]
MAKEFLAGS=$(expr $(nproc) + 1)

/home/devel/building/work/src/gcc-12-20220424/build/./prev-gcc/xg++ -B/home/devel/building/work/src/gcc-12-20220424/build/./prev-gcc/ -B/usr/x86_64-unknown-linux-gnu/bin/ -nostdinc++ -B/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -B/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs  -I/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu  -I/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include  -I/home/devel/building/work/src/gcc-12-20220424/libstdc++-v3/libsupc++ -L/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -L/home/devel/building/work/src/gcc-12-20220424/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs   -g -O2 -fprofile-use -fprofile-reproducible=parallel-runs -flto=jobserver -frandom-seed=1 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H  -DGENERATOR_FILE -static-libstdc++ -static-libgcc  -o build/genattr \
    build/genattr.o build/rtl.o build/read-rtl.o build/ggc-none.o build/vec.o build/min-insn-modes.o build/gensupport.o build/print-rtl.o build/hash-table.o build/sort.o build/read-md.o build/errors.o .././libiberty/libiberty.a
terminate called after throwing an instance of 'std::runtime_error'
  what():  pthread_create has failed: Resource temporarily unavailable
collect2: fatal error: ld terminated with signal 6 [Aborted]
compilation terminated.

**Comment by rui314** [comment]
@sajcho

I committed d8a8877875d96d0efdb727b4ba600ee3910a333f to workaround this issue. Can you rebuild mold and try again?

**Comment by sajcho** [comment]
@rui314

I'm working on it. I will announce the result.

**Comment by sajcho** [comment]
Result:

../configure --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-languages=c,c++,fortran,lto --enable-plugin --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-initfini-array --enable-linker-build-id --enable-checking=release --enable-link-serialization=1 --enable-gnu-indirect-function --enable-libstdcxx-backtrace=yes --disable-nls --disable-multilib --disable-libunwind-exceptions --with-isl --with-ld=/usr/bin/x86_64-unknown-linux-gnu-ld.mold --with-system-zlib --with-linker-hash-style=gnu --with-build-config=bootstrap-lto --with-pkgversion=SAUX-x86_64 --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu

make 'BOOT_CFLAGS=-O2 -Wall -Wformat-security -Wp,-D_GLIBCXX_ASSERTIONS -mtune=generic' LDFLAGS_FOR_TARGET=-Wl,-z,relro,-z,now profiledbootstrap

All compile OK.

 readelf -p .comment /usr/bin/gcc

String dump of section '.comment':
  [     0]  mold 1.2.1 (d8a8877875d96d0efdb727b4ba600ee3910a333f; compatible with GNU ld)
  [    4e]  GCC: (SAUX-x86_64) 12.1.0

**Comment by rui314** [comment]
Great, thank you for testing!
