### ISSUE TITLE
Fails to get current executable path on OSX.

### ISSUE THREAD

**Issue by gelfand** [rui314/mold#488]
Fails to get current executable path on OSX.

```sh
◆ akula git:(master) ✗ ❯❯❯ mold -run cargo build --all
libc++abi: terminating with uncaught exception of type std::__1::__fs::filesystem::filesystem_error: filesystem error: in read_symlink: No such file or directory ["/proc/self/exe"]
fish: Job 1, 'mold -run cargo build --all' terminated by signal SIGABRT (Abort)
```

**Comment by rui314** [comment]
I think that even if you fix this issue, `mold -run` won't work on macOS. It depends on the `LD_PRELOAD` mechanism, but that works only on the traditional Unix-like systems. macOS uses two-level namespaces for shared libraries, so we can't interrupt `exec`-family functions using `LD_PRELOAD`.

**Comment by bjorn3** [comment]
I believe you can use `DYLD_FORCE_FLAT_NAMESPACE` to force usage of a traditional flat namespace even if two-level namespaces would otherwise be used.
