### ISSUE TITLE
Use BLAKE3 instead of SHA256?

### ISSUE THREAD

**Issue by rui314** [rui314/mold#492]
I learned from https://llvmweekly.org/issue/430 that LLVM lld now uses BLAKE3 to create a `.note.gnu.build_id` section instead of SHA256 because BLAKE3 is faster. We may want to evaluate BLAKE3 and switch to it as well if the difference is noticeable.

**Comment by llunak** [comment]
FWIW I've tried this, just with xxhash (it's faster, and AFAICT the hash doesn't need to be crypto). And with my setup I couldn't measure any difference that would be worth it. I don't link as huge binaries as Chrome/Firefox/whatever though, the larger binary I have is ~130MiB, so maybe it'd be different there. https://gist.github.com/llunak/83391267a204ed1bd69d0f68c2ddd0d5 if you want to try.

As I remember it, the key points were: Although xxhash is faster, doing sha256 in threads hides that difference, and xxhash is so fast that there's no point in using threads. The only way I could make it faster, and I'm not entirely certain whether xxhash actually made a difference in that case, was when I commented out the munmap hack. YMMV.

**Comment by rui314** [comment]
How many cores did your machine have? I wonder if a relative low-core machine (say, 6 cores) can saturate the memory bandwidth when computing a SHA256 build-id.

**Comment by llunak** [comment]
https://www.amd.com/en/products/apu/amd-ryzen-5-2500u

**Comment by rui314** [comment]
Thanks, so it's 4-core mobile CPU. If we can't observe a difference on that CPU, it's very unlikely that BLAKE3 can make a difference. Therefore, I'm closing this issue.43hj

**Comment by firasuke** [comment]
Would you reconsider opening this as having `xxhash` and `BLAKE3` as options for `build-id` would make `mold` even faster?

I understand that the `build-id` does not have to be cryptographic, but having `sha256` seems unnecessary?

**Comment by infogulch** [comment]
The contention seems to be that it's *not* faster, at least not measurably, in the situation discussed above. Can you demonstrate a situation where xxhash or BLAKE3 is faster?

Personally I think BLAKE3 is awesome. I like it's speed and parallelizability and I think it's design is intelligent, etc. But if it doesn't help in the use case then it doesn't make much sense for a maintainer to spend their time switching to it.

**Comment by firasuke** [comment]
Not that it's _not_ measurable, @llunak mentioned that `xxhash` is faster and that they did not try it on bigger projects like FireFox, Chrome or Clang.

Perhaps we can compare `XXH3_128bits` against current `build-id`s and see if there's really a measurable difference?

**Comment by rui314** [comment]
We have switched to BLAKE3 because it was slightly faster than SHA256. I don't want to switch to a non-cryptographic hash function because guaranteeing uniqueness of build id is important.

**Comment by infogulch** [comment]
Oh cool, I didn't realize. Thanks!

**Comment by firasuke** [comment]
> We have switched to BLAKE3 because it was slightly faster than SHA256. I don't want to switch to a non-cryptographic hash function because guaranteeing uniqueness of build id is important.

This is awesome news! What version of `mold` supports `BLAKE3`? Perhaps update documentation to show that `BLAKE3` is supported?

**Comment by rui314** [comment]
The choice of cryptographic hash function is not visible to users. Even if you calculate a BLAKE3 hash of an executable, the hash will differ from the one in the build-ID section. We just guarantee that the build-id is unique for each distinctive output file. That's why we don't want to say that we use blake3.

**Comment by firasuke** [comment]
So the default build-id is BLAKE3 or SHA-1?

**Comment by rui314** [comment]
It's always blake3 but it doesn't matter to users.

**Comment by firasuke** [comment]
> It's always blake3 but it doesn't matter to users.

Running `file` on an executable linked with `mold` shows `BuildID[sha1]`, this is not `b3sum` or `BLAKE3`?

**Comment by rui314** [comment]
Again, the choice of cryptographic hash function doesn't mean anything to users, so just ignore what you tool said about it. I believe it display "sha1" because the hash size is truncated to 128 bits, and the tool assumes that 128 bit hash is always sha1.

**Comment by Alcaro** [comment]
That is a very strange behavior, because sha1 is 160 bits.

**Comment by firasuke** [comment]
It is indeed a strange behavior, I am using the `file` utility version `5.45`.

**Comment by rui314** [comment]
Oh, sorry, that's just typo. I mean 160 bits.
