### ISSUE TITLE
Debugging facilities for the linking process

### ISSUE THREAD

**Issue by deliciouslytyped** [rui314/mold#5]
(Possibly related to https://github.com/rui314/mold/issues/4)

Linking issues seem generally to be hard to debug?

I don't have a lot in terms of concrete proposals here but for starters, getting more information out of a linker, about what it's doing, would be a start? Ideally perhaps even machine readable information which could be consumed by analysis frontends.
There seems to be a lot of space for improvement here?

If I have a linker problem, I can't seem to do anything right now other than poke around in the object files with objdump and nm.

**Comment by deliciouslytyped** [comment]
Assuming something like the configuration staging in #4 were to be implemented, at the least this would allow deeper inspection of the linker configuration state?

I suppose that's largely unrelated but you've already mentioned pre-caching other files.

**Comment by rui314** [comment]
Debugging a linker is indeed hard, and I don't have a good idea to improve it significantly. In the early stage of development of mold, I added --print-map option to dump the layout of an output file, which was helpful sometimes. But most of the cases, buts are in a subtle feature or a lack thereof, and it often surfaces as a mysterious crash before the control reaches `main`. I don't know how to debug that kind of issues efficiently.

**Comment by deliciouslytyped** [comment]
As a sidenote. in the meantime, at least on NixOS, generally during packaging work, most of my linking issues are system integration related, and running `ld` in verbose mode
  - dumps the linker script currently being run,
  - lists the paths searched for libraries
latter of this is usually what

**Comment by rui314** [comment]
I think this item is not actionable, so closing this issue.
