### ISSUE TITLE
Support nix by not calling `git clone` during build

### ISSUE THREAD

**Issue by nitsky** [rui314/mold#50]
Hi, I would like to build mold with the nix package manager, but nix does not support network access while building, so the `git clone` of mimalloc in the Makefile fails.

I suggest moving the build of mimalloc out of the Makefile, like you did for TBB, to give the user control over how mimalloc is built and how to link to it. By default, the Makefile can link to mimalloc dynamically with `-lmimalloc`. The `build-static.sh` script can then clone mimalloc, build it, and pass in the appropriate `EXTRA_CPPFLAGS` and `EXTRA_LDFLAGS` like it does for TBB.

I don't know why you chose to always statically link mimalloc, but I assume it is either because mimalloc is not packaged in ubuntu or because static linking may have better performance.

If you approve of this approach, I can submit a PR.

**Comment by rui314** [comment]
mold is statically-linked to mimalloc because as you guessed Ubuntu doesn't have a package of mimalloc. I want mold to use mimalloc as the default malloc as it is measurably faster than even TBBMalloc. We could provide several options to users as to how to build mold -- using mimalloc in /usr/lib, using mimalloc as a static library, or use TBBMalloc as a last resort. However, that might be a little too complicated.

How about adding mimalloc as a git submodule to the project just like I did before? This way, `make` doesn't require any network access, and only you have to do is to add `--recursive` option to the initial `git clone`. Does that work with nix?

**Comment by nitsky** [comment]
Submodules will work fine with nix. Would you like to implement the change yourself, or get a PR?

**Comment by rui314** [comment]
Sounds good. Since adding a submodule is easy, I'll do that for you.

**Comment by nitsky** [comment]
@rui314 I was successful building mold with nix, but only after applying a patch to remove the `git submodule update --init --recursive` in the Makefile. Git operations like this are not allowed in nix's sandboxed builds. Would you consider updating the Makefile to eliminate that command or make it optional?

**Comment by rui314** [comment]
If you run the first clone command as `git clone --recursive`, didn't it create `mimalloc/CMakeLists.txt` from the beginning? That `git submodule update --init --recursive` runs only when `mimalloc/CMakeLists.txt` is missing. So, I thought that as long as you run the initial cloning with `--recursive`, that make rule wouldn't be triggered.

**Comment by nitsky** [comment]
You are right, I made a mistake in my nix configuration, sorry for the trouble. I am now able to package mold with nix. You can close this issue.

**Comment by piegamesde** [comment]
@nitsky Mind sharing your code? See also https://github.com/NixOS/nixpkgs/issues/128706

**Comment by nitsky** [comment]
@piegamesde I'll submit a PR to nixpkgs.

**Comment by rui314** [comment]
@nitsky I made a last-minute change for 0.9 so that mimalloc is no longer a submodule but just a subdirectory. i.e. mold now contains a copy of mimalloc in its subdirectory. mold's makefile no longer tries to do `git submodule update`. This should make your life easier.

**Comment by nitsky** [comment]
@piegamesde I submitted a nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/128889.
