### ISSUE TITLE
Testsuite failures on riscv64

### ISSUE THREAD

**Issue by andreas-schwab** [rui314/mold#503]
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:RISCV/mold/standard/riscv64

Testing gdb-index-compress-output ... make[1]: *** [Makefile.linux:6: elf/gdb-index-compress-output.sh] Error 1
Testing gdb-index-dwarf2 ... make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf2.sh] Error 1
Testing gdb-index-dwarf3 ... make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf3.sh] Error 1
Testing gdb-index-dwarf4 ... make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf4.sh] Error 1
Testing gdb-index-dwarf5 ... make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf5.sh] Error 1
Testing lto-archive ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
compilation terminated.
make[1]: *** [Makefile.linux:6: elf/lto-archive.sh] Error 1

**Comment by rui314** [comment]
It works on my Ubuntu 22.04 RISC-V machine.

Do you have an access to the artifact of this builder? If so, please copy files under `out/test/elf/gdb-index-dwarf[2345]` and share them with me.

**Comment by andreas-schwab** [comment]
No, I don't.

**Comment by andreas-schwab** [comment]
The gdb-index tests fail because of missing ptrace.

**Comment by marxin** [comment]
I can extract the files, working on that right now.

**Comment by marxin** [comment]
```
$ cat out/test/elf/gdb-index-dwarf5/log
Breakpoint 1 at 0x1104: file <stdin>, line 4.
warning: Could not trace the inferior process.
warning: ptrace: Function not implemented
During startup program exited with code 127.
Function "trap" not defined.
Make breakpoint pending on future shared library load? (y or [n]) [answered N; input not from terminal]
The program is not being run.
No stack.
```

**Comment by rui314** [comment]
OK, so it looks like some kernel feature hasn't been implemented yet. Maybe the only thing we can do is to disable these tests on RISC-V. I'll do that.

**Comment by marxin** [comment]
Are we convinced `lto-archive` is the same story that ptrace is missing?

**Comment by andreas-schwab** [comment]
That has really nothing to do with RISC-V, but only with qemu.
