### ISSUE TITLE
Re-linking a shared library makes running processes that use it crash

### ISSUE THREAD

**Issue by llunak** [rui314/mold#517]
If the resulting binary file already exists, mold reuses it and truncates it. This may cause any running process that uses that shared library to SIGSEGV. While a somewhat rare scenario, it's possible that one would want to re-link a library while still wanting a process to keep running (as has happened to me).

On Linux the open() call fails with ETXTBUSY only for executables, but not for shared libraries (https://lwn.net/Articles/866493/), which I find rather lame, but it is what it is. I'm not aware of any other way to detect that the shared library is in use (that wouldn't be expensive). I wonder if using fallocate() wouldn't avoid the need to reuse the file. Otherwise, could there be some other way to prevent the problem (getenv flag maybe)?

**Comment by ishitatsuyuki** [comment]
#188 is a relevant issue if not an exact duplicate.

**Comment by llunak** [comment]
Yes, this is a dupe of #188, let's close this one.
