### ISSUE TITLE
Support --fix-cortex-a53-835769

### ISSUE THREAD

**Issue by zmike** [rui314/mold#519]
I'm trying to use mold on a chromebook, but it seems `--fix-cortex-a53-835769` is not supported, so nothing works. Is it possible to support this flag?

**Comment by rui314** [comment]
Cortex A53 835769 is a processor bug found and fixed in 2014, so I think we can ignore that flag instead of actually implementing a workaround for that hardware bug.

**Comment by rui314** [comment]
The flag is already ignored here: https://github.com/rui314/mold/blob/main/elf/cmdline.cc#L952

Can you paste an error log here so that I can see what's actually wrong?

**Comment by zmike** [comment]
Hm maybe I don't have a new enough version? I'm on 1.0.1, so let me try a git build before any further time is wasted.

**Comment by rui314** [comment]
1.0.1 is pretty old, it must be a reason why it was failing.

**Comment by zmike** [comment]
Yup, it was. My fault for not checking what version I was using first. Thanks for looking!
