### ISSUE TITLE
Any plans for PE/COFF support?

### ISSUE THREAD

**Issue by santagada** [rui314/mold#52]
Hi,

Is there any plans to support linking on windows? I'll would be interested in helping as we right now mantain our own patches for objcopy and lld to make it a little faster. I think on DWARF there's no need to produce one global symbol table like there is on PDB, So I'm guessing mold for windows will look quite different than it looks now, was there any thought put on it already?

Things like ghashes for coff:
http://blog.llvm.org/2018/01/improving-link-time-on-windows-with.html

**Comment by rui314** [comment]
I hope to add a PE/COFF support to mold, but to be honest there's currently no concrete plan to do that. I strongly believe that I can make a significantly faster linker for Windows just like I did for Unix with lld and mold, but that's going to be another one-person-year project, so I can't promise to do that now.

**Comment by rui314** [comment]
I landed a preliminary AArch64 support. mold is now able to link a "hello world" program for AArch64. There are a lot to do to fully support AArch64, but I hope that by mold 1.0 mold can link most user-land programs for AArch64.

**Comment by rui314** [comment]
@bencz I know how hard or easy it is to write a linker for Windows from scratch because I did that before. I'm the creator of the LLVM lld linker for Windows. It's not too difficult to write a linker that works 95% of the time, but making a linker that can be used for production isn't an easy task.

**Comment by rui314** [comment]
https://github.com/rui314/mold/issues/190
