### ISSUE TITLE
Double install `git` in install-build-deps.sh

### ISSUE THREAD

**Issue by chill0r** [rui314/mold#525]
I don't think it's intentional but in the `install-build-deps.sh` script git is inserted twice for the ubuntu distributions in the `apt install` steps.
This won't throw an error or warning but can be ommited.

(As a sidenote: You could add debian11 (bullseye) to the ubuntu20.04 so it's supported by the script too. It has the same dependencies)

**Comment by rui314** [comment]
Thanks, fixed.
