### ISSUE TITLE
Feature request: --export-dynamic-symbol for gold & lld compatibility

### ISSUE THREAD

**Issue by kinke** [rui314/mold#532]
To selectively export some symbols directly in the cmdline, e.g.: `--export-dynamic-symbol=sym1 --export-dynamic-symbol=sym2`.

**Comment by rui314** [comment]
Yes, we need to support that option as well as `--export-dynamic-symbol-list` for compatibility with other linkers.

**Comment by ishitatsuyuki** [comment]
I'd like to look into this.

**Comment by rui314** [comment]
Thanks. Please go ahead. I believe you can use our `MultiGlob` class for glob pattern matching.

**Comment by ishitatsuyuki** [comment]
@rui314 I have a question on how dynamic and version lists are handled currently.

The `--dynamic-list` and `--version-script` arg are handled in `read_input_files`:

https://github.com/rui314/mold/blob/990b0ac4cd78081b57231a3658f34f8957797576/elf/main.cc#L217-L221

... which implies their behavior depends on argument order. But I couldn't figure out what kind of options can change their behavior. Do you have an example where this becomes order dependent, or in case it's order independent could we handle it in `parse_nonpositional_args` instead?

**Comment by rui314** [comment]
I don't remember why I wanted to handle these options in `read_input_files`. You can probably move them to `parse_nonpositional_args` safely.
