### ISSUE TITLE
Firefox segfaults on ARM64 if built with mold

### ISSUE THREAD

**Issue by sajcho** [rui314/mold#541]
triplet aarch64-unknown-linux-gnu
clang version 14.0.3
rust version 1.61.0
mold version 1.2.1 - commit 8f02509ba6528354cfe6660bb56512af38a80f87

firefox 101.0.1
Compilation okay.
Setup firefox => segmentation fault.

relevant part of configure
cd firefox-101.0.1
\# https://phabricator.services.mozilla.com/D134330
patch -p1 -i $SRC/add-support-enable-linker-mold.patch

cat <<- EOF > .mozconfig
		mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/objdir
		unset MOZ_TELEMETRY_REPORTING
		#
		ac_add_options --prefix=/usr
		ac_add_options --disable-debug
		ac_add_options --disable-debug-symbols
		#
		ac_add_options --disable-crashreporter
		ac_add_options --disable-install-strip
		ac_add_options --disable-jemalloc
		ac_add_options --disable-profiling
		ac_add_options --disable-strip
		ac_add_options --disable-tests
		ac_add_options --disable-updater
		ac_add_options --disable-necko-wifi
		ac_add_options --disable-jack
		ac_add_options --disable-smoosh
		ac_add_options --disable-bootstrap
		ac_add_options --disable-elf-hack
		#
		ac_add_options --enable-release
		ac_add_options --enable-application=browser
		ac_add_options --enable-official-branding
		ac_add_options --enable-default-toolkit=cairo-gtk3-wayland
		ac_add_options --enable-pulseaudio
		ac_add_options --enable-alsa
		ac_add_options --enable-dbus
		ac_add_options --enable-av1
		ac_add_options --enable-ffmpeg
		ac_add_options --enable-webrtc
		ac_add_options --enable-hardening
		ac_add_options --enable-rust-simd
		ac_add_options --enable-optimize="-O2"
                #######################
                # setup firefox - okay
		#ac_add_options --enable-linker=bfd
                # setup firefox - segmentation fault
                ac_add_options --enable-linker=mold
                #######################
		ac_add_options --enable-system-ffi
		ac_add_options --enable-system-pixman
		#
		ac_add_options --with-system-ffi
		ac_add_options --with-system-icu
		ac_add_options --with-system-jpeg
		ac_add_options --with-system-libevent
		ac_add_options --with-system-libvpx
		ac_add_options --with-system-nspr
		ac_add_options --with-system-nss
		ac_add_options --with-system-pixman
		ac_add_options --with-system-png
		ac_add_options --with-system-webp
		ac_add_options --with-system-zlib
		ac_add_options --without-wasm-sandboxed-libraries
EOF
./mach build
I also tried mold -run ./mach build but it's the same

attachment - patch
[add-support-enable-linker-mold.patch.txt](https://github.com/rui314/mold/files/8900092/add-support-enable-linker-mold.patch.txt)
attachment - strace firefox output 
[strace-firefox-output.txt](https://github.com/rui314/mold/files/8900026/strace-firefox-output.txt)

Please be patient in case of proposed changes and subsequent assembly.
Compilation takes about three hours on my computer.

**Comment by ishitatsuyuki** [comment]
Firefox works fine with mold on amd64, so can you update the title to mention AArch64?

**Comment by sajcho** [comment]
I compile in the native environment on a Jetson TX2 machine.

$ lscpu | head
Architecture: aarch64
CPU op-mode (s): 32-bit, 64-bit
Byte Order: Little Endian
CPU (s): 6
On-line CPU (s) list: 0-5
Vendor ID: ARM
Model name: Cortex-A57

**Comment by ptr1337** [comment]
Actually I did today a try with a firefox based browser i maintain and faced the same on amd64.
clang 14.0.5
rust 1.61.0
latest mold commit; 8f02509ba6528354cfe6660bb56512af38a80f87

PKGBUILD can be found here:
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/cachyos-browser/PKGBUILD

**Comment by ishitatsuyuki** [comment]
Can you put `--disable-elf-hack` in your mozconfig ac_add_options line and try again?

**Comment by ishitatsuyuki** [comment]
So yeah, @ptr1337 what you're encounting is #494 which is a completely different issue. Just put the flag there and it will work fine.

**Comment by ptr1337** [comment]
Sorry did not saw this issue. After using --disable-elfhack faced Stil into issues. But I will write that in the other issue.

**Comment by ishitatsuyuki** [comment]
FWIW, I routinely build Firefox dev branch and **103.0a1 (2022-06-14)** is running fine for me.

**Comment by ptr1337** [comment]
> FWIW, I routinely build Firefox dev branch and **103.0a1 (2022-06-14)** is running fine for me.

Can also confirm that it worked with firefox 101.0.1 on x86

**Comment by sajcho** [comment]
When I remove the ld symbolic link that points to ld.bfd I get an error:

clang-14: error: unable to execute command: Executable "ld" doesn't exist!
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make [4]: *** [/home/devel/building/work/src/firefox-102.0/config/rules.mk:433: nsinstall_real] Error 1
make [3]: *** [/home/devel/building/work/src/firefox-102.0/config/recurse.mk:72: config / host] Error 2
make [3]: *** Waiting for unfinished jobs ....

My computer:
System two linker ld.bfd and mold.
Rename ld.bfd ld.bfd.inactive

System only linker mold
Edit symlink ld: ld -> mold
Symlink ld points to mold

Change configure parameters
ac_add_options --enable-release -> ac_add_options --disable-release
ac_add_options --enable-hardening -> ac_add_options --disable-hardening
ac_add_options --enable-optimize="-O2" -> ac_add_options --disable-optimize

The same configuration is used for both architectures.
Arch: x86_64
Used version firefox 102.0b8
Working fine.

Arch: aarch64
Used version firefox 102.0b8
Segmentation fault

**Comment by sajcho** [comment]
I'm sorry for the late reply. This issue is resolved.

export CC="clang"
export CXX="clang++"
ac_add_options --enable-linker=mold

This configuration works fine.
$ readelf -p .comment /usr/bin/firefox
String dump of section '.comment':
   [ 0] (SAUX-Aarch64) clang version 15.0.5
   [ 24] mold 1.7.1 (compatible with GNU ld)
   [ 49] GCC: (SAUX-Arch64) 12.2.0

Time and development seems to have solved this problem.
