### ISSUE TITLE
Support for Aarch64 and more architectures?

### ISSUE THREAD

**Issue by syrusakbary** [rui314/mold#55]
Hi @rui314 , first great work on the linker! The numbers are impressive, and it's much more lightweight than other alternatives (namely LLVM's lld).

We are researching embedding a linker in [Wasmer](https://wasmer.io) as part of our dynamic library engine.

I was wondering what is the timeline for supporting more architectures, namely Aarch64 (but also curious about other architectures)

**Comment by rui314** [comment]
In the upcoming mold 0.9 release, I will have fixed almost all compatibility issues. AArch64 support will be added after that. I don't have an ARM machine in hand, so I need to set up a ARM machine in a cloud to start working on it.

In terms of timeline, I'll probably finish it by the end of this year, but I can't make a promise. If you are really interested in using mold for your business and need an AArch64 support ASAP, I can make a contract with you to give it a higher priority.

**Comment by Logarithmus** [comment]
@rui314 does `mold` support cross-linking? E.g. running `mold` on `aarch64`, but linking `x86_64` object files, or vice versa.

**Comment by rui314** [comment]
mold's behavior only depends on its command-line arguments, so it should naturally behave as a cross-compiler if you give the exact command line options and input files as a target platform. That being said, currently only x86 and x86-64 targets are supported, so it can act as a cross-compiler from AArch64 to x86-64 for example, but can't do the opposite (can't create an AArch64 executable yet).

**Comment by Logarithmus** [comment]
@rui314 and what options should I pass to `mold` to specify target architecture? Or does it somehow auto detect the target from the object files themselves?

**Comment by rui314** [comment]
It's `-m`, but even a native compiler driver always pass that option to a linker.

**Comment by syrusakbary** [comment]
> In terms of timeline, I'll probably finish it by the end of this year, but I can't make a promise. If you are really interested in using mold for your business and need an AArch64 support ASAP, I can make a contract with you to give it a higher priority.

Thanks for the proposal!
Right now we are in the evaluation phase, but if the time comes where this becomes more critical for us I'll ping you again!

**Comment by rui314** [comment]
ARM64 support has been implemented.
