### ISSUE TITLE
Even the "hello world" Rust program segfaults on ARMV7 when built with mold.

### ISSUE THREAD

**Issue by turkerali** [rui314/mold#550]
Hi again.
I reopened this issue as requested. Steps to reproduce segfault:
- Install rust on armv7 via "curl https://sh.rustup.rs -sSf | sh" 
- cargo new mold_test
- Edit .cargo/config.toml and add:
[target.armv7-unknown-linux-gnueabihf]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
- Cargo run
- And the result is:
Compiling mold_test v0.1.0 (/root/aet_rust/mold_test)
    Finished dev [unoptimized + debuginfo] target(s) in 22.73s
     Running `target/debug/mold_test`
Segmentation fault

Hope this helps to debug this issue.

**Comment by jpalus** [comment]
Can confirm issue happens for me as well both on armv6 and armv7. Segfaulting binary: [mold_test.zip](https://github.com/rui314/mold/files/8938755/mold_test.zip). Works fine on aarch64 though.
