### ISSUE TITLE
Enabling IPO seems to limit mold to a single thread

### ISSUE THREAD

**Issue by vkoskiv** [rui314/mold#556]
When enabling IPO, in my case with CMake like this:

`set_property(TARGET c-ray PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)`

Mold takes just as long, if not somewhat longer than the default system `ld` to link the final binary, and seems to be limited to a single thread while doing so.
I don't know enough about linkers to know if this is just a fundamental limitation of IPO, or if it's a possible issue on my end or in mold.
Would love to hear more about this!

If you want a quick repro, you can clone [c-ray](https://github.com/vkoskiv/c-ray) and enable mold by adding the right flag to `CMAKE_C_FLAGS`
It enables IPO by default, so just enabling mold should show the behaviour I'm seeing.

**Comment by rui314** [comment]
I believe it enables the `-flto` flag which enables link-time optimization. If LTO is enabled, mold is not faster than the other linkers, because optimization pass (which belongs to not the linker but the compiler backend) takes a very long time. That's not a bug.

**Comment by vkoskiv** [comment]
Yeah, I figured this was the case. Thanks for clarifying!

**Comment by vkoskiv** [comment]
Mold is plenty fast on my ARM laptop if I just disable LTO! 

mold:
```
vkoskiv@reform:~/c-ray$ time make -j$(nproc)
Consolidate compiler generated dependencies of target c-ray
[  1%] Linking C executable bin/c-ray
[100%] Built target c-ray

real	0m0.690s
user	0m0.438s
sys	0m0.206s
```

ld:
```
vkoskiv@reform:~/c-ray$ time make -j$(nproc)
[  1%] Linking C executable bin/c-ray
[100%] Built target c-ray

real	0m17.210s
user	0m1.084s
sys	0m0.275s
```

**Comment by rui314** [comment]
Nice! 0.69s is almost instantaneous.
