### ISSUE TITLE
Wrong symlink out/tbb/libs when building mold

### ISSUE THREAD

**Issue by Jacfger** [rui314/mold#558]
I'm building mold v1.3.0 and using clang++-14/clang++-12. (I tried both)

During compilation, I encountered error saying out/tbb/libs/libtbb.a not found. But I did noticed in previous steps, it's linked.

After somewhile I found that the out/tbb/libs is symlink to a wrong folder. To be more exact, clang_14.0_cxx11_64_release/ is the real folder that libtbb.a is in and libs is not linking to the right one (libs was a broken link). 

I have very little understanding of this project (I simply follow my friend scripts to install this), so please tell me if I need to provide any more details.

**Comment by rui314** [comment]
Can you run `git pull` and then try again?

**Comment by Jacfger** [comment]
Yup. It's fixed for me!
