### ISSUE TITLE
Linked program hangs at startup when AddressSanitizer is used.

### ISSUE THREAD

**Issue by hejllukas** [rui314/mold#562]
Hi, I use mold for linking PrusaSlicer, and mold is really fast in linking. But I discovered an issue that the application hung at startup when I used mold linker and AddressSanitizer.
I have this issue with mold 1.3.0 on Ubuntu 22.04 with GCC 10.2.0 and also with Clang 14.0.0. Previously I tried Ubuntu 20.04 and a different version of GCC, Clang, and I still had the same issue.

This issue only happened when I used mold linker, and the program was compiled with enabled AddressSanitizer. I don't have this issue with other linkers.

I tried to find out where the issue was happening to create a minimal case. I found that even a simple program hangs after calling gtk_init_check. So just the following code compiled with AddressSanitizer is needed to reproduce it:
```
#include <gtk/gtk.h>

int main(int argc, char **argv)
{
    gtk_init_check(&argc, &argv);
    return 0;
}
```
I also attached the ZIP that includes the code above, CMakeLists.txt (for compilation with GTK3 and with AddressSanitizer) and Dockerfile, for easier reproduction.
[Hangs_at_startup.zip](https://github.com/rui314/mold/files/9011835/Hangs_at_startup.zip)

Could you please take a look at it?

**Comment by rui314** [comment]
Please rebuild mold and try again. Thanks!

**Comment by hejllukas** [comment]
Thank you very much for fixing it. I just tried it, and now it is working.
I really appreciate that you fixed this issue so quickly! :+1:
