### ISSUE TITLE
test preinit-array.sh fails on 1.3.1 (musl)

### ISSUE THREAD

**Issue by nekopsykose** [rui314/mold#565]
added in https://github.com/rui314/mold/commit/3b753987860fc6b26385be56db802000c9217fea  

musl libc does not actually support .preinit_array - a reference i can find to this (aside from it being missing, of course) is https://www.openwall.com/lists/musl/2015/11/29/7 , where it was intentionally left out.  

the commit adding the support claims that it's needed for address sanitizer- but i can confirm that at least for me asan from compiler-rt sanitizers works with musl and mold 1.3.0 (and 1.3.1).

i don't think the preinit support breaks anything in any case, but i'm just asking to confirm if skipping the test is fine :)

**Comment by nekopsykose** [comment]
ah, i missed that the first time.  

adding set -x:  

```
+ CC=cc
+ CXX=c++
+ GCC=gcc
+ GXX=g++
+ OBJDUMP=objdump
++ uname -m
+ MACHINE=x86_64
++ basename ./elf/preinit-array.sh .sh
+ testname=preinit-array
+ echo -n 'Testing preinit-array ... '
Testing preinit-array ... ++ dirname ./elf/preinit-array.sh
+ cd ./elf/../..
+ t=out/test/elf/preinit-array
+ mkdir -p out/test/elf/preinit-array
+ echo 'int main() {}'
+ cc -o out/test/elf/preinit-array/exe -xc -
+ readelf --dynamic out/test/elf/preinit-array/exe
+ grep -q ld-musl
+ '[' x86_64 = x86_64 ']'
+ cc -c -o out/test/elf/preinit-array/a.o -x assembler -
+ cat
+ cc -c -o out/test/elf/preinit-array/b.o -xc -
+ cat
+ cc -B. -o out/test/elf/preinit-array/exe out/test/elf/preinit-array/a.o out/test/elf/preinit-array/b.o
+ grep -q 'preinit init fini'
+ out/test/elf/preinit-array/exe
```

it seems the grep of `readelf --dynamic $t/exe | grep -q ld-musl` is incorrect, the actual name found in the executable is something like: 
```
 0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x86_64.so.1]
```

**Comment by nekopsykose** [comment]
actually, this seems to be alpine linux specific, as on gentoo there is only a ld-musl, but on alpine there is both:  

```
< l /lib/ | grep musl
.rwxr-xr-x 591Ki root 2022-06-29 08:34 ld-musl-x86_64.so.1
lrwxrwxrwx    19 root 2022-06-29 20:04 libc.musl-x86_64.so.1 -> ld-musl-x86_64.so.1
```

and things link to the latter

**Comment by nekopsykose** [comment]
and on gentoo (via gentoo/stage3:musl) things seem to have a NEEDED of `libc.so` only, actually..  

the easiest way is probably:  

```
< ldd
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```

the musl ldd says musl in it, probably consistent always, but not sure

**Comment by rui314** [comment]
Thanks for the info. Let me use `ldd` to identify musl libc.

**Comment by nekopsykose** [comment]
small fyi: ifunc-static-pie also needs this check (was missing)

**Comment by rui314** [comment]
Thanks, fixed.
