### ISSUE TITLE
relocatable.sh test failure on i686

### ISSUE THREAD

**Issue by wangp** [rui314/mold#579]
The relocatable.sh test fails on Void Linux i686/glibc using gcc version 10.2.1 20201203 (GCC). The test executable crashes with
```
# ./relocatable.sh 
Testing relocatable ... ./relocatable.sh: line 67:   486 Illegal instruction     $t/exe
```
(I commented out the `grep` part of the command to see the error message.)

The test case passes when using clang version 12.0.1.
```
# TEST_CXX=clang++ ./relocatable.sh 
Testing relocatable ... OK
```

I see that the test case is skipped when $MACHINE = i386, to avoid a gcc bug.
On this setup, uname -m returns i686. Should the test be skipped for $MACHINE = i686 as well?

**Comment by rui314** [comment]
Yes, we should skip for i686 as well. Thank you for pointing that out!
