### ISSUE TITLE
Question: Mold latest usable in Ubuntu 22.04?

### ISSUE THREAD

**Issue by joshcangit** [rui314/mold#580]
Can latest release of Mold be backported to Ubuntu 22.04?

If not, I wonder how to use Mold but exclusively from `kinetic` release in Ubuntu 22.04?

**Comment by rui314** [comment]
According to https://repology.org/project/mold/versions, it looks like the latest version of mold is available as a package.

**Comment by joshcangit** [comment]
Yes, the latest version of mold is on Ubuntu 22.10.
I have installed it manually in 22.04 and it works.

But 22.04 mainly uses the outdated `jammy` release.
I am trying to **pin** `apt` so that only the `mold` package is sourced from `kinetic` instead of `jammy`?

Any tips?

**Comment by rui314** [comment]
You can build mold yourself or download the pre-built binary from https://github.com/rui314/mold/releases/tag/v1.3.1.
