### ISSUE TITLE
mold: error: unknown relocation: R_ARM_V4BX

### ISSUE THREAD

**Issue by lrusak** [rui314/mold#582]
Hello! Thanks for the great project!

I'm adding support for using MOLD with LibreELEC (see: https://github.com/LibreELEC/LibreELEC.tv/pull/6665)

I found a few packages that won't seem to compile for 32bit arm. I'm currently using MOLD 1.3.0 (I plan to test with master soon).

example linker command:
```
armv8a-libreelec-linux-gnueabihf-gcc -march=armv8-a+crc -mtune=cortex-a53 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-fp-armv8 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -fPIC -DPIC -DDUMMYOPT -march=armv8-a+crc -mtune=cortex-a53 -Wl,--as-needed -B/home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/toolchain/libexec/mold
```

ffmpeg: (full log: http://lrusak.libreelec.tv/public/mold-logs/ffmpeg.log.txt)
```
mold: error: libavutil/arm/float_dsp_neon.o:(.text): unknown relocation: R_ARM_V4BX
...
```

libjpeg-turbo: (full log: http://lrusak.libreelec.tv/public/mold-logs/libjpeg-turbo.log.txt)
```
mold: error: libjpeg.a(jsimd_neon.S.o):(.text): unknown relocation: R_ARM_V4BX
...
```

----

I was also going to report an issue about `R_ARM_PREL31` but it looks like it may be fixed by https://github.com/rui314/mold/commit/52943009b7dce4a0ebb5943092d47e6e33625401 so I'll have to retest

mesa:
```
mold: error: src/compiler/glsl/libglsl.a(src/compiler/glsl/libglsl.a.p/ir_array_refcount.cpp.o):(.ARM.extab.text._ZN25ir_array_refcount_visitorD2Ev): R_ARM_PREL31 relocation at offset 0x0 against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC
```

**Comment by rui314** [comment]
I should be fixed now. Please try again with main.
