### ISSUE TITLE
symbol export issues

### ISSUE THREAD

**Issue by zmike** [rui314/mold#592]
We're evaluating mold for use in Mesa CI, but there's some issues with unit tests related to symbol exports failing with the latest version. See also comments here https://gitlab.freedesktop.org/mesa/mesa/-/issues/6877#note_1487555

**Comment by rui314** [comment]
Thank you for your report. Let me take a look. What was the command you used to build Mesa?

**Comment by zmike** [comment]
I think something like `meson . build -Dgallium-drivers=swrast -Dbuild-tests=true` should be enough to have the unit tests built? I imagine if you comment on that ticket then people will rapidly reply to help get you whatever info you need.

**Comment by ishitatsuyuki** [comment]
The symbols are specified through a version script (using AMD Vulkan as an example):

https://github.com/mesa3d/mesa/blob/ae2947fbc5a7ad3879090777c829e44b7c339eb3/src/amd/vulkan/meson.build#L152-L155

For my setup (clang + ThinLTO), it looks like I get a few redundant symbols related to splitstack (only redundant one noted below):
```
  3623: 0000000000000000   184 TLS     GLOBAL DEFAULT   21 __morestack_initial_sp
  3625: 00000000000000b8     8 TLS     GLOBAL DEFAULT   21 __morestack_current_segment
  3626: 00000000000000c0     8 TLS     GLOBAL DEFAULT   21 __morestack_segments
  3633: 000000000005e590   356 FUNC    GLOBAL DEFAULT   13 __splitstack_find
  3634: 000000000005e700    98 FUNC    GLOBAL DEFAULT   13 __splitstack_block_signals
  3635: 000000000005e770   163 FUNC    GLOBAL DEFAULT   13 __splitstack_getcontext
  3636: 000000000005e820   116 FUNC    GLOBAL DEFAULT   13 __splitstack_setcontext
  3637: 000000000005e8a0   409 FUNC    GLOBAL DEFAULT   13 __splitstack_makecontext
  3638: 000000000005ea40   112 FUNC    GLOBAL DEFAULT   13 __splitstack_resetcontext
  3639: 000000000005eab0    14 FUNC    GLOBAL DEFAULT   13 __splitstack_releasecontext
  3640: 000000000005eac0    40 FUNC    GLOBAL DEFAULT   13 __splitstack_block_signals_context
  3641: 000000000005eaf0    88 FUNC    GLOBAL DEFAULT   13 __splitstack_find_context
```

**Comment by ishitatsuyuki** [comment]
In addition to that, the check-symbols tool appears to complain about symbols that are HIDDEN but set to GLOBAL (they are LOCAL in other linkers). An example is `wsi_create_buffer_image_mem`.

**Comment by rui314** [comment]
> In addition to that, the check-symbols tool appears to complain about symbols that are HIDDEN but set to GLOBAL (they are LOCAL in other linkers). An example is wsi_create_buffer_image_mem.

If that's the case, it's a bug of Mesa's unit tests rather than ours.

**Comment by ishitatsuyuki** [comment]
It looks like a STV_HIDDEN symbol should always be converted to STB_LOCAL though? Not sure why we're not doing that.

https://docs.oracle.com/cd/E19683-01/816-1386/chapter6-79797/index.html

> A hidden symbol contained in a relocatable object is either removed or converted to STB_LOCAL binding by the link-editor when the relocatable object is included in an executable file or shared object.

**Comment by rui314** [comment]
Hm, maybe you are right. If we can convert it to a local symbol, we probably should do that.

**Comment by ishitatsuyuki** [comment]
Looking more into this, we're actually handling all of this for `.dynsym` correctly but not for `.symtab`. For `.symtab` we inherit st_bind from the input file, ignoring all the handling we have done with `is_imported` etc: https://github.com/rui314/mold/blob/a8559be1b194ed63114747e7648287e9ea741200/elf/input-files.cc#L1245

(Also while on this, I found the `write_symtab` naming a bit confusing. I confused it as if it was writing to the input file itself initially. I thought about calling it `populate_symtab`, but the name might not be much better)

**Comment by rui314** [comment]
Do you want to take this? If so, feel free to rename functions as a part of your fix.

**Comment by ishitatsuyuki** [comment]
OK, will get a patch sorted in the weekend.
