### ISSUE TITLE
[Question] Can mold be used during crosscompilation? 

### ISSUE THREAD

**Issue by ericriff** [rui314/mold#595]
This may be a silly question, sorry if that's the case.

I'm working on a project that requires crosscompilation from `Linux:x86_64` to `Linux:aarch64` and `Linux:arm32`. Can I use `mold` in this scenario?

Thanks!

**Comment by rui314** [comment]
Yes, you can. Just like GNU ld, you need to pass `-m aarch64linux` and `-m armelf_linux_eabi` for arm64 and arm32, respectively.
