### ISSUE TITLE
An option for randomizing linkage order

### ISSUE THREAD

**Issue by Archivist062** [rui314/mold#598]
I would like to implement an option to randomize the linkage, the goal being to get better data during automated benchmarking of applications.

I am ready to do the implementation myself, but I am ignorant about the codebase and do not know where to start (which shall change after a few days in the code).

I am looking for recommendations if you have any.

**Comment by rui314** [comment]
We already have one: `--shuffle-sections`. You can also specify a seed with `--shuffle-sections=SEED` (e.g. `--shuffle-sections=12345`.)

**Comment by Archivist062** [comment]
Take. My. Money.
