### ISSUE TITLE
test/elf/lto-version-script.sh: fails with `pthread_create has failed: Resource temporarily unavailable`

### ISSUE THREAD

**Issue by sylvestre** [rui314/mold#600]
In a debian chroot (works fine outside), the test fails with:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  pthread_create has failed: Resource temporarily unavailable
collect2: fatal error: ld terminated with signal 6 [Aborted]

```

On:
`$CC -B. -shared -o $t/c.so -flto $t/a.o -Wl,-version-script=$t/b.script`

Trying to package 1.4.0 in Debian/Ubuntu

**Comment by rui314** [comment]
You probably need to build mold with the bundled TBB or apply [this patch](https://github.com/oneapi-src/oneTBB/pull/824) to your TBB library and rebuild your TBB package.

**Comment by rui314** [comment]
Can you ask the libtbb maintainer to cherry-pick my patch to https://salsa.debian.org/science-team/tbb/-/tree/master/debian/patches?

**Comment by sylvestre** [comment]
sure, will do!

**Comment by rui314** [comment]
Please close this bug if my patch could fix your issue.

**Comment by sergiud** [comment]
> The problem is that for some reason Intel devs have stopped merging PRs since like three months ago.

This is related to the war in Ukraine: most if not all Intel TBB devs are based in [Nizhny Novgorod](https://www.intel.com/pressroom/archive/releases/2000/aw062300.htm), Russia where Intel suspended its operations [in April](https://www.datacenterdynamics.com/en/news/intel-suspends-all-operations-in-russia/).

**Comment by rui314** [comment]
Ahh, it certainly explains it.

**Comment by marxin** [comment]
Note the patch was taken by `openSUSE` and will be available in `Tumbleweed` soon.

**Comment by rui314** [comment]
Let me close this issue. If the issue still persists, feel free to reopen.
