### ISSUE TITLE
Termux: Error: no overloaded variable '+='

### ISSUE THREAD

**Issue by joshcangit** [rui314/mold#603]
I got some error when building on Termux.
```
macho/main.cc:444:11: error: no viable overloaded '+='
  counter += std::erase_if(osec.members, [](Subsection<E> *subsec) {
  ~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
macho/main.cc:455:7: note: in instantiation of function template specialization 'mold::macho::uniquify_cstrings<mold::macho::X86_64>' requested here
      uniquify_cstrings(ctx, *(OutputSection<E> *)chunk);
      ^
macho/main.cc:1041:3: note: in instantiation of function template specialization 'mold::macho::merge_cstring_sections<mold::macho::X86_64>' requested here
  merge_cstring_sections(ctx);
  ^
macho/main.cc:987:14: note: in instantiation of function template specialization 'mold::macho::do_main<mold::macho::X86_64>' requested here
      return do_main<X86_64>(argc, argv);
             ^
macho/main.cc:1119:10: note: in instantiation of function template specialization 'mold::macho::do_main<mold::macho::ARM64>' requested here
  return do_main<ARM64>(argc, argv);
         ^
macho/../mold.h:621:12: note: candidate function not viable: cannot convert argument of incomplete type 'void' to 'int' for 1st argument
  Counter &operator+=(int delta) {
           ^
macho/main.cc:444:11: error: no viable overloaded '+='
  counter += std::erase_if(osec.members, [](Subsection<E> *subsec) {
  ~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
macho/main.cc:455:7: note: in instantiation of function template specialization 'mold::macho::uniquify_cstrings<mold::macho::ARM64>' requested here
      uniquify_cstrings(ctx, *(OutputSection<E> *)chunk);
      ^
macho/main.cc:1041:3: note: in instantiation of function template specialization 'mold::macho::merge_cstring_sections<mold::macho::ARM64>' requested here
  merge_cstring_sections(ctx);
  ^
macho/main.cc:1119:10: note: in instantiation of function template specialization 'mold::macho::do_main<mold::macho::ARM64>' requested here
  return do_main<ARM64>(argc, argv);
         ^
macho/../mold.h:621:12: note: candidate function not viable: cannot convert argument of incomplete type 'void' to 'int' for 1st argument
  Counter &operator+=(int delta) {
           ^
2 errors generated.
make: *** [Makefile:145: out/macho/main.o] Error 1
```

**Comment by Alcaro** [comment]
mold requires that std::erase_if(std::vector<>, ...) returns size_t, not void. From what I can gather (which admittedly is kinda spotty), this is implemented starting from libc++ version 11; Termux should offer libc++ version 12.

Are you behind on your updates, or otherwise on a weird configuration? If no, you may have to compile your own newer Clang and/or libc++.

**Comment by joshcangit** [comment]
Well, `clang` on Termux is `14.0.6-1`.
I don't know which version of `libc++` on Termux is `23c`.

**Comment by Alcaro** [comment]
23c is somewhere in libc++ version 12, according to https://old.reddit.com/r/termux/comments/uve9jc/about_clang14/ and https://github.com/android/ndk/wiki/Changelog-r23#r23c.

Which should be new enough. Weird. Then I have no idea what Termux is doing.

**Comment by rui314** [comment]
If this is the last error for Termux, I could fix it for you. Otherwise, I'll wait for them to catch up with the latest C++ standard correctly.

**Comment by truboxl** [comment]
This is NDK issue, https://github.com/termux/termux-packages/issues/11470

**Comment by truboxl** [comment]
@rui314
I like to know what's your stance on supporting mold to run on Android at this time. Since its likely if after fixing this, we may hit another libc++ outdated issue in the future and need fixing again.

**Comment by rui314** [comment]
mold is written in C++20, so I expect a toolchain that is used to build mold supports C++20 well. If Android's toolchain has too many issues in C++20 support, I'd like to wait for them to catch up.

**Comment by joshcangit** [comment]
I don't think this is due to `libc++`.
It's `25-1` now but I still get the same errors.

I think the issue is with the compiler.
Clang is still `14.0.6-1` because that is the latest stable version.
Maybe Termux should have used the latest qualification version instead?

**Comment by rui314** [comment]
I doubt it's a compiler thing. What the compiler is complaining is that `std::erase_if` is defined as returning `void` instead of something that can be applied to `+=`. `std::erase_if` is a part of the C++ standard library.

**Comment by joshcangit** [comment]
I think the build on Termux work now.

**Comment by rui314** [comment]
That's odd because I didn't do anything to fix this issue. That's a good news though.

**Comment by joshcangit** [comment]
> mold is written in C++20, so I expect a toolchain that is used to build mold supports C++20 well. If Android's toolchain has too many issues in C++20 support, I'd like to wait for them to catch up.

Well, you did say you'll wait. You were right about that.
Termux did fixed it on their end.
