### ISSUE TITLE
Symbols hidden with version script remain visible if used by shared library

### ISSUE THREAD

**Issue by brechtvl** [rui314/mold#606]
### Description

Context: for the Blender executable we statically link many libraries, and hide nearly all symbols. This makes it able to run on many Linux distributions and avoids conflicts with graphics/compute drivers and plug-ins.

The problem we encounter with mold is that when linking to a shared library, symbols used by that library are made visible despite being hidden with a version script. This behavior differs from other linkers such as `ld.gold` and `ld.lld`.

Tested using version: `mold 1.4.0 (b2c6206aa9ee2a5cc334e8f26f846a5e49fb6aa8; compatible with GNU ld)`

### Steps to Reproduce

test.cpp
```
#include <zlib.h>

int main(int argc, char **argv)
{
  compress2(NULL, NULL, NULL, 0, 0);
  return 0;
}
```

lib.cpp
```
#include <zlib.h>

void dummy()
{
  compress2(NULL, NULL, NULL, 0, 0);
}
```

symbols.map
```
{
global:
  _bss_start;
  __end;
  _fini;
  _init;
local:
  *;
};
```
Run:
```
clang++ lib.cpp -fPIC -lz -shared -o lib.so
clang++ test.cpp /usr/lib/x86_64-linux-gnu/libz.a lib.so -Wl,--version-script='symbols.map' -fuse-ld=/path/to/mold -o test
nm -gD ./test
```
The `compress2` symbol will be visible.

**Comment by rui314** [comment]
Thank you for your report! It's indeed odd that `compress2` is exported. Let me take a look.

**Comment by rui314** [comment]
This issue should have been fixed with the above commit. Do you mind if I ask you to verify?

**Comment by brechtvl** [comment]
I can confirm the fix, also for the real world case.

Thanks for the quick fix and mold development in general.
