### ISSUE TITLE
man page only exists for mold, not ld.mold

### ISSUE THREAD

**Issue by TerrorJack** [rui314/mold#607]
After installing `mold-1.4.0` from the x86_64-linux release tarball and having `mold` in `PATH`, `man mold` is able to open the man page, but `man ld.mold` shows `No manual entry for ld.mold`. This behavior slightly differs with other linkers, since `man ld.bfd`/`man ld.gold`/`man ld.lld` can all open man pages for the corresponding linkers.

**Comment by rui314** [comment]
Good point. I'll create `ld.mold.1` as an alias to `mold.1` manpage.
