### ISSUE TITLE
mariadb-connector-c doesn't compile with mold

### ISSUE THREAD

**Issue by dante-robinson** [rui314/mold#610]
I currently am running clang/musl gentoo mold has been working great for me setup as the default linker the only package I seem to have run into an issue with is mariadb-connector-c. I get the error 

mold: fatal: /var/tmp/portage/dev-db/mariadb-connector-c-3.2.5/work/mariadb-connector-c-3.2.5-src_build-abi_x86_64.amd64/libmariadb/mariadbclient.def:130: "mysql_affected_rows@libmariadbclient_18" = mysql_affected_rows;
                                                                                                                                                    ^ unknown linker script token
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

When switching from mold to lld no more issues. 

Here is a copy of my emerge --info in case that helps solve the issue

System uname: Linux-5.18.16-gentoo-dist-hardened-x86_64-AMD_Ryzen_9_5950X_16-Core_Processor-with-libc
KiB Mem:    32779452 total,   9799988 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Thu, 11 Aug 2022 11:30:01 +0000
Head commit of repository gentoo: 1766729b8d5ca7dd5541387eb8e3fc808efe143f
Head commit of repository 12101111-overlay: 5be8491265f106423392c6478780a01087dbef96

Head commit of repository clang-musl: e76a290fbcebc4f303cfe7b5542ce31dc19dae7f

sh bash 5.1_p16-r1
ld LLD 14.0.6 (compatible with GNU linkers)
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r1::gentoo
dev-lang/perl:             5.36.0::gentoo
dev-lang/python:           3.10.6::gentoo, 3.11.0_rc1::gentoo
dev-lang/rust:             1.62.1::clang-musl
dev-util/cmake:            3.24.0::gentoo
dev-util/meson:            0.63.0::gentoo
sys-apps/baselayout:       2.8-r2::gentoo
sys-apps/openrc:           0.45.2::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r2::gentoo, 2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.38-r2::12101111-overlay
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           14.0.6-r1::gentoo
sys-devel/libtool:         2.4.7::gentoo
sys-devel/lld:             14.0.6::gentoo
sys-devel/llvm:            14.0.6-r2::12101111-overlay
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.19::gentoo (virtual/os-headers)
sys-libs/musl:             1.2.3::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1

12101111-overlay
    location: /var/db/repos/12101111-overlay
    sync-type: git
    sync-uri: https://github.com/12101111/overlay.git
    masters: gentoo

clang-musl
    location: /var/db/repos/clang-musl
    sync-type: git
    sync-uri: https://github.com/clang-musl-overlay/clang-musl-overlay.git
    masters: gentoo

bitcoin
    location: /var/lib/layman/bitcoin
    masters: gentoo
    priority: 50

guru
    location: /var/lib/layman/guru
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    masters: gentoo mv
    priority: 50

monero
    location: /var/lib/layman/monero
    masters: gentoo
    priority: 50

musl
    location: /var/lib/layman/musl
    masters: gentoo
    priority: 50

musl-clang
    location: /var/lib/layman/musl-clang
    masters: musl gentoo
    priority: 50

mv
    location: /var/lib/layman/mv
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-gentoo-linux-musl"
CC="x86_64-gentoo-linux-musl-clang"
CFLAGS="-march=znver3 -mtune=znver3 -O3 -pipe"
CHOST="x86_64-gentoo-linux-musl"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo"
CPP="x86_64-gentoo-linux-musl-clang-cpp"
CXX="x86_64-gentoo-linux-musl-clang++"
CXXFLAGS="-march=znver3 -mtune=znver3 -O3 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=znver3 -mtune=znver3 -O3 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=znver3 -mtune=znver3 -O3 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
INSTALL_MASK="charset.alias /usr/share/locale/locale.alias"
LANG="C.UTF8"
LDFLAGS="-march=znver3 -mtune=znver3 -fuse-ld=mold -Wl,-O3,--as-needed,-zrelro,-znow"
MAKEOPTS="-j32 -l32"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X acl amd64 bzip2 clang compiler-rt crypt custom-cflags default-compiler-rt default-libcxx default-lld elogind hardened iconv ipv6 libcxx libcxxabi libedit libglvnd libtirpc lld llvm-libunwind minimal ncurses nls nptl openmp pam pie seccomp split-usr ssl ssp unicode vulkan wayland xattr xml xtpax zlib" ABI_X86="64" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="musl" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LLVM_TARGETS="X86 AMDGPU WebAssembly" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" RUBY_TARGETS="ruby27" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CCLD, CONFIG_SHELL, CPPFLAGS, CTARGET, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

=================================================================
                        Package Settings
=================================================================

dev-db/mariadb-connector-c-3.2.5::gentoo was built with the following:
USE="curl ssl -gnutls -kerberos -static-libs -test"
FEATURES="unmerge-logs strict fixlafiles sandbox binpkg-dostrip assume-digests protect-owned ebuild-locks pid-sandbox network-sandbox buildpkg-live merge-sync news ipc-sandbox distlocks sfperms config-protect-if-modified parallel-fetch qa-unresolved-soname-deps binpkg-docompress userpriv usersandbox binpkg-logs preserve-libs xattr userfetch unmerge-orphans usersync unknown-features-warn binpkg-multi-instance"
LDFLAGS="-march=znver3 -mtune=znver3 -fuse-ld=lld -Wl,-O3,--as-needed,-zrelro,-znow"

**Comment by rui314** [comment]
This error occurs because mariadb-connector-c uses linker script to define symbol aliases. They can use `--defsym` linker option instead. I'll send a patch to mariadb to get rid of the usage of linker script.

**Comment by rui314** [comment]
I decided to implement a feature to support this usage. mold should be able to build mariadb-connector-c with the above commit.
