### ISSUE TITLE
about commit ee68d1f2ff2ea5f2bb563fc9f1c00b3efaf691e1

### ISSUE THREAD

**Issue by vtorri** [rui314/mold#611]
* openssl can be compiled on Windows
* with meson, you could have used the wrap feature (see https://mesonbuild.com/Using-the-WrapDB.html and https://github.com/mesonbuild/wrapdb/tree/master/subprojects)
* also see https://docs.microsoft.com/en-us/windows/win32/seccng/creating-a-hash-with-cng

**Comment by rui314** [comment]
It was a temporary measure to just make it compile on Windows, and it's likely to be removed by https://github.com/rui314/mold/pull/608.
