### ISSUE TITLE
macOS: Mold 1.4.0 segfaults while runinng clippy on `rust-decimal`

### ISSUE THREAD

**Issue by cr0sh** [rui314/mold#621]
# Steps to Reproduce

1. `brew install mold`
2. `git clone https://github.com/paupino/rust-decimal && cd rust-decimal`
3. `cargo clippy --workspace --all-targets`

```
error: could not compile `rust_decimal_macros`

Caused by:
  process didn't exit successfully: `/Users/namjh/.rustup/toolchains/stable-aarch64-apple-darwin/bin/clippy-driver rustc --crate-name macro_tests --edition=2021 macros/tests/macro_tests.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,metadata -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --test --cfg 'feature="default"' -C metadata=67f5d57048d7219b -C extra-filename=-67f5d57048d7219b --out-dir /Users/namjh/dev/personal/rust-decimal/target/debug/deps -C linker=/usr/bin/clang -C incremental=/Users/namjh/dev/personal/rust-decimal/target/debug/incremental -L dependency=/Users/namjh/dev/personal/rust-decimal/target/debug/deps --extern quote=/Users/namjh/dev/personal/rust-decimal/target/debug/deps/libquote-dcc787d52e12b839.rmeta --extern rust_decimal=/Users/namjh/dev/personal/rust-decimal/target/debug/deps/librust_decimal-f5450e9a8d14931b.rmeta --extern rust_decimal_macros=/Users/namjh/dev/personal/rust-decimal/target/debug/deps/librust_decimal_macros-8b36c48ca1c0850f.dylib --extern trybuild=/Users/namjh/dev/personal/rust-decimal/target/debug/deps/libtrybuild-7893ca0464c2c778.rmeta -C link-arg=--ld-path=/opt/homebrew/bin/ld64.mold` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
```

```
$ mold --version
mold 1.4.0 (compatible with GNU ld)
```

`cargo.toml` configuration:

```
[target.aarch64-apple-darwin]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/opt/homebrew/bin/ld64.mold"]
```

Roughly guessing, it crashed while linting so proc-macros would be the problem.

**Comment by rui314** [comment]
Thank you for your report! I just tried to reproduce the issue, but it just succeeded. Could you try again with rebuilding mold from git head?

**Comment by cr0sh** [comment]
It works, thanks!

Side note and question about building on macOS (If a separate issue would be more appropriate, please tell me):

- Tried to build 6b27a7e9b3f213b98ddf408f276091cf5a2c800a on aarch64 macOS 12.5, which succeeded but unfortunately `make install` failed:
  - Followed the instructions on README and got
  ```
  /Library/Developer/CommandLineTools/usr/bin/strip: error: symbols referenced by indirect symbol table entries that can't be stripped in: /usr/local/lib/mold/mold-wrapper.so
  # FYI: xcode-select --version returns xcode-select version 2395.
  ```
  - I'm not familiar about C++ and CMake, so I briefly googled the error message but got no clue.
  - As a workaround, I commented out strip command on `make install` job: `$(STRIP) $D$(LIBDIR)/mold/mold-wrapper.so`
- Removed the previous installation of `mold` with `brew uninstall mold` then `ld64.mold` have been deleted but `mold` command remained alive. Is this a bug or separate command from another package(or from Apple)?

**Comment by cr0sh** [comment]
Oops, didn't mean to close right now so reopening. Close if you want!

**Comment by rui314** [comment]
`mold` command is available on macOS to allow you to build Linux executables on macOS.
