### ISSUE TITLE
[macOS] mold fails to link when passing a runtime path

### ISSUE THREAD

**Issue by BalestraPatrick** [rui314/mold#623]
I'm trying out mold for macOS and ran into an issue:
```
mold: fatal: cannot open executable_path/Frameworks: No such file or directory
```

The issue is easily reproducible in the example projects for the Bazel Apple rules: https://github.com/bazelbuild/rules_apple/
You can run `bazelisk build //examples/ios/HelloWorld --linkopt="-fuse-ld=$(which mold)"` and you'll notice the error. It seems like `mold` doesn't yet understand the runtime path in this format.

**Comment by rui314** [comment]
I think you need to pass `--linkopt="-fuse-ld=$(which ld64.mold)"` instead of `--linkopt="-fuse-ld=$(which mold)"`. ld64 is the macOS-compatible linker, and mold/ld.mold are the Unix-compatible one.

**Comment by rui314** [comment]
Actually, if you already have `ld64.mold` in your `$PATH`, you can just specify `--linkopt="-fuse-ld=mold"`. This way, clang will automatically tries to find `ld.mold` for you.

**Comment by BalestraPatrick** [comment]
Is there a pre-built distribution of `ld64.mold` already? `brew install mold` only installs `mold`. I was able to build it from source locally and pass the absolute path to ld64 (`--linkopt="-fuse-ld=path/to/mold/repo/ld64"`) and found another issue. I will open a separate issue for it then.

**Comment by rui314** [comment]
Oh really? `brew install mold` installed `/opt/homebrew/bin/ld64.mold` for me. Can you double check what files were installed to your system by running `brew install mold`?

**Comment by BalestraPatrick** [comment]
Interesting. `ld64.mold` definitely didn't exist before. I reinstalled the package via homebrew and now I have `/opt/homebrew/bin/ld64.mold`. Maybe this was added recently and I was on an older version? Anyway, I can close this issue then. It would be nice to document this at some point since I've seen other issues related to this confusion when invoking `mold` vs `ld64.mold`.

**Comment by carlocab** [comment]
> `ld64.mold` definitely didn't exist before.

No, it definitely did. The first build for mold was added in https://github.com/Homebrew/homebrew-core/commit/c7462131550aec2c7a7e9ecdc651325680662567.

You can download one of the builds with (for example):
```
curl -L -H 'Authorization: Bearer QQ==' \
  https://ghcr.io/v2/homebrew/core/mold/blobs/sha256:34632011c7a7ce08462a21076cf08692f38ca87a8d908de5df6c26370415a52e \
  -o mold.tar.gz
```
and then examine the contents of `mold.tar.gz` to find `bin/ld64.mold` there.

You can replace the checksum in the URL after `sha256:` with any of the other checksums listed in the commit given above.
