### ISSUE TITLE
Mold 1.4.1 cmake build issue: mold: fatal: aes_cbc.o: not claimed by the LTO plugin

### ISSUE THREAD

**Issue by satmandu** [rui314/mold#638]
This is on Chromebrew/x86_64
Build log attached:
[mold-1.4.1-x86_64.log](https://github.com/rui314/mold/files/9374551/mold-1.4.1-x86_64.log)

These are the essential commands being used:
```
mkdir builddir && cd builddir
cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
-DCMAKE_LIBRARY_PATH=/usr/local/lib64 \
-DCMAKE_C_FLAGS='-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold ' \
-DCMAKE_CXX_FLAGS='-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold ' \
-DCMAKE_EXE_LINKER_FLAGS='-flto ' -DCMAKE_SHARED_LINKER_FLAGS='-flto ' \
-DCMAKE_STATIC_LINKER_FLAGS='-flto ' -DCMAKE_MODULE_LINKER_FLAGS='-flto ' \
-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_TESTING=OFF \
        -DMOLD_USE_MOLD=ON \
        -DMOLD_MOSTLY_STATIC=ON \
        -DMOLD_LTO=ON \
        -Wno-dev \
        ../ -G Ninja
cd ..
samu -C builddir
```

**Comment by satmandu** [comment]
Same issue on armv7l.
[mold-1.4.1-armv7l.log](https://github.com/rui314/mold/files/9374588/mold-1.4.1-armv7l.log)

**Comment by rui314** [comment]
Could you attach `aes_cbc.o` to this repo?

**Comment by satmandu** [comment]
Where would that file be? I don't see it anywhere.

**Comment by satmandu** [comment]
Are we talking about `libcrypto.a`? That's the only place I think this might be found. Unless we're talking about the other OpenSSL libraries?

Those are available in our default build in /usr/local/lib64 - In the container here:

```
docker pull satmandu/crewbuild:nocturne-x86_64.m90
docker run --platform linux/amd64 --rm -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-x86_64 -it satmandu/crewbuild:nocturne-x86_6
```

**Comment by satmandu** [comment]
Hmm... this build might be getting further if I exclude `-DMOLD_MOSTLY_STATIC=ON`...

**Comment by rui314** [comment]
On your system, `/usr/local/lib64/libcrypto.a` contains LLVM bitcode files as shown below.

```
45ca4c7b4657 /home/chronos/user # ar x /usr/local/lib64/libcrypto.a aes_cbc.o
45ca4c7b4657 /home/chronos/user # file aes_cbc.o
aes_cbc.o: LLVM IR bitcode
```

I guess you are using gcc to build mold, right? You can't mix GCC and LLVM when doing an LTO build.

**Comment by rui314** [comment]
In general, you don't want to install LTO object files to `/usr/local`, as they are not compatible with anything other than the exact same version of compiler that was used to build the LTO object files.

I believe your `libcrypto.a` was built with LTO because you wanted to build `libcrypto.so` with LTO. But I think you need to build libcrypto twice -- to build `libcrypto.so` with LTO and to build `libcrypto.a` without LTO.

**Comment by satmandu** [comment]
Ah! Yes this is then entirely our problem in how we built OpenSSL with clang to work around a binutils issue for armv7l!

I will try rebuilding OpenSSL with GCC to see if that avoids this issue.

(FYI the build succeeded without the MOSTLY_STATIC flag.)
