### ISSUE TITLE
[macOS Apple Silicon] Rust compilation of futures-core fails with "unknown command line option: -dynamic"

### ISSUE THREAD

**Issue by nsabovic** [rui314/mold#642]
With mold 1.4.1, compiling a rust 1.63.0 project fails with:
```
= note: mold: fatal: unknown command line option: -dynamic
```

Attached is the full clang command line that failed.
[compile_log.txt](https://github.com/rui314/mold/files/9383455/compile_log.txt)

Shouldn't -dynamic just be ignored? Apple ld says it's the default.

**Comment by rui314** [comment]
On macOS, you are supposed to use `ld64.mold` instead of `mold` or `ld.mold`. Please replace your flag with`-fuse-ld=/opt/homebrew/bin/ld64.mold`.

**Comment by nsabovic** [comment]
Makes sense, thank you. Fwiw, I compiled a non-trivial project with 500 dependencies that include a 3d gaming engine, GRPC clients and server, computational physics, opencv and a bunch of UI and everything seems to work perfectly. I found breakage in another project, I'll open another ticket.

**Comment by devillove084** [comment]
With mold 1.9, compiling a rust nightly project fails with the same problem. I tried to use ld64.mold, but there is no ld64.mold in my home-brew path, it just mold and ld.mold

**Comment by Alcaro** [comment]
[It was removed in mold v1.8.0.](https://github.com/rui314/mold/releases/tag/v1.8.0)
