### ISSUE TITLE
Throwing c++ exception causes crash on arm 32-bit

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#646]
Noticed the issue after building latest `mpd` (https://github.com/MusicPlayerDaemon/MPD) with `mold 1.4.1` on both armv6 and armv7 (linux). Fortunately there's a simple reproducer:
```cpp
#include <iostream>
#include <stdexcept>
class PluginUnavailable : public std::runtime_error {
  public:
    using std::runtime_error::runtime_error;
};

static void init() {
  throw PluginUnavailable("exception");
}
int main() {
  try {
    init();
  } catch (const PluginUnavailable &e) {
    auto ce = std::current_exception();
    std::cout << "error:" << e.what() << std::endl;
  }

}
```
When linked with `bfd` program behaves as expected and `error: exception` is logged. With `mold` however exception does not seem to be caught and program crashes.

Works fine on arm64 though.

**Comment by rui314** [comment]
Thank you for reporting! I can confirm that it indeed crashes on QEMU/ARM32. Will investigate.

**Comment by rui314** [comment]
So there was a bug in code that sorts contents of `.ARM.exidx`. I fixed that issue in the above commit.

**Comment by jpalus** [comment]
That was quick! Confirmed it works fine. Thanks!
