### ISSUE TITLE
Please cut a new release to simplify packaging

### ISSUE THREAD

**Issue by Logarithmus** [rui314/mold#65]
My #62, #64 PRs has been accepted, but they didn't end up in any release.
Most distros have a policy about using the most recent release, and not `master`/`main`.
So please make a new release 0.9.2.

**Comment by rui314** [comment]
Sure. I need to build Gentoo packages to make sure that there's no regression. Please allow me a day or two.

**Comment by rui314** [comment]
I created a new branch for 0.9.2 and cherrypick only changes that matters to you. Could you confirm that the following branch contains all changes that you need? If it looks OK, I'll tag it as v0.9.2.

https://github.com/rui314/mold/commits/release/0.9.2

**Comment by Logarithmus** [comment]
@rui314 yesterday I've discovered that multiple tests fail (about 10). So today I'd like to take a record of specific tests which fail and 'll create a PR trying to fix those tests. The package can't be accepted with failing tests.
So please don't create a tag yet.

**Comment by rui314** [comment]
Got it. For me all tests pass and so do on GitHub Actions, so I wonder what these tests are.

**Comment by Logarithmus** [comment]
An issue to track failing tests: https://github.com/rui314/mold/issues/67

**Comment by Logarithmus** [comment]
> I created a new branch for 0.9.2 and cherrypick only changes that matters to you. Could you confirm that the following branch contains all changes that you need? If it looks OK, I'll tag it as v0.9.2.
> 
> https://github.com/rui314/mold/commits/release/0.9.2

Please, include test fixes for Void into `mold/0.9.2` and tag it.

**Comment by Logarithmus** [comment]
@rui314 **UPD** 3 tests still fail on my machine, namely:
- `copyrel-protected`
- `ifunc-dso`
- `run`
I'd like to investigate them before you make a release.

**Comment by rui314** [comment]
I updated https://github.com/rui314/mold/tree/release/0.9.2 branch.

Could you run each test command with `bash -x` and share its output?

**Comment by Logarithmus** [comment]
@rui314 
```
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/copyrel-protected.sh 
+ set -e
++ dirname fails/copyrel-protected.sh
+ cd fails
++ basename -s .sh fails/copyrel-protected.sh
+ echo -n 'Testing copyrel-protected ... '
Testing copyrel-protected ... ++ pwd
++ basename -s .sh fails/copyrel-protected.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/copyrel-protected
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected
+ cat
+ cc -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/a.o -c -xc -fno-PIE -
+ cat
+ cc -shared -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/b.so -xc -
++ pwd
+ clang -fuse-ld=/home/artur/Programming/C++/mold/fails/../mold /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/a.o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/b.so -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/exe
+ false
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/ifunc-dso.sh        
+ set -e
++ dirname fails/ifunc-dso.sh
+ cd fails
++ basename -s .sh fails/ifunc-dso.sh
+ echo -n 'Testing ifunc-dso ... '
Testing ifunc-dso ... ++ pwd
++ basename -s .sh fails/ifunc-dso.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/ifunc-dso
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso
+ cat
+ cc -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/a.o -c -x assembler -
+ cat
+ cc -shared -fPIC -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/b.so -x assembler -
++ pwd
+ clang -fuse-ld=/home/artur/Programming/C++/mold/fails/../mold -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/exe /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/a.o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/b.so
+ /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/exe
+ grep -q 'Hello world'
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/run.sh      
+ set -e
++ dirname fails/run.sh
+ cd fails
++ basename -s .sh fails/run.sh
+ echo -n 'Testing run ... '
Testing run ... ++ pwd
++ basename -s .sh fails/run.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/run
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/run
+ cat
+ cc -xc -c -o /home/artur/Programming/C++/mold/fails/tmp/run/a.o -
+ gcc -o /home/artur/Programming/C++/mold/fails/tmp/run/exe /home/artur/Programming/C++/mold/fails/tmp/run/a.o
+ readelf -p .comment /home/artur/Programming/C++/mold/fails/tmp/run/exe
+ grep -q mold /home/artur/Programming/C++/mold/fails/tmp/run/log
+ false
```

**Comment by rui314** [comment]
@Logarithmus Do you mind if I ask you to create a patch to fix issues you found? I can make a change myself but can't confirm that my change would fix the issue.

**Comment by Logarithmus** [comment]
@rui314, yeah, I'm currently working on it. I've installed Debian 11 inside `lxd` container. The idea is to compare generated binaries/logs between my system & the container.

**Comment by Logarithmus** [comment]
See #67 for follow-up on tests.

**Comment by rui314** [comment]
I cherrypicked bugfixes to https://github.com/rui314/mold/tree/release/0.9.2. Can you double-check that all tests pass now? If everything is fine, I'll tag it as v0.9.2.

**Comment by rui314** [comment]
@Logarithmus Are you ready for 0.9.2?

**Comment by Logarithmus** [comment]
@rui314 I'm checking right now

**Comment by Logarithmus** [comment]
@rui314 2 small fixes needed:
1) #87
2) Bump version in `Makefile` (it's still `0.9.1` there).

**Comment by rui314** [comment]
@Logarithmus Thank you very much for testing! I cherry picked your change and bumped up the version number to 0.9.2. I'm tagging v0.9.2.

**Comment by rui314** [comment]
0.9.2 has been tagged.

**Comment by Logarithmus** [comment]
Thank you.
