### ISSUE TITLE
mold doesn't set ELFOSABI_GNU for IFUNC nor STB_GNU_UNIQUE

### ISSUE THREAD

**Issue by rawoul** [rui314/mold#651]
Similar to https://sourceware.org/bugzilla/show_bug.cgi?id=17735 (which is actually fixed).

mold always sets the ELF OSABI header value to 0, even when using GNU extensions like IFUNC or STB_GNU_UNIQUE. I'm not sure if SHF_GNU_RETAIN should also trigger setting the GNU OSABI.

This can be seen in readelf output:

- IFUNC:
```
$ mold -shared ifunc.o -o ifunc.so
$ readelf -h --dyn-syms ifunc.so | grep '\(\<sd_get_seats\>\|OS/ABI\)'
  OS/ABI:                            UNIX - System V
     2: 0000000000001000    17 <OS specific>: 10 GLOBAL DEFAULT    7 sd_get_seats
```
```
$ ld.bfd -shared ifunc.o -o ifunc.so
$ readelf -h --dyn-syms ifunc.so | grep '\(\<sd_get_seats\>\|OS/ABI\)'
  OS/ABI:                            UNIX - GNU
     2: 0000000000001000    17 IFUNC   GLOBAL DEFAULT    6 sd_get_seats
```

- STB_GNU_UNIQUE:
```
$ mold -shared unique.o -o unique.so
$ readelf -h --dyn-syms unique.so | grep '\(\<unique_global\>\|OS/ABI\)'
  OS/ABI:                            UNIX - System V
     1: 0000000000003018     1 OBJECT  <OS specific>: 10 DEFAULT   10 unique_global
```
```
$ ld.bfd -shared unique.o -o unique.so
$ readelf -h --dyn-syms unique.so | grep '\(\<unique_global\>\|OS/ABI\)'
  OS/ABI:                            UNIX - GNU
     1: 0000000000002000     1 OBJECT  UNIQUE DEFAULT    7 unique_global
```

**Comment by rui314** [comment]
I don't think it makes much sense to set ELFOSABI to GNU if GNU feature is used because the runtime doesn't really care about it. If `readelf` cares it, we probably should make a change to `readelf` so that it can pretty print the magic number 10.

**Comment by rawoul** [comment]
Well, there are only 3 possible OS specific values (10 to 12), so I guess if another OS/ABI wants to add a flag, its value will also be 10 and thus it makes sense to pretty print those values depending on the actual OS/ABI. This is probably the answer I'll get from the readelf maintainers ?

**Comment by rui314** [comment]
I don't think that's a real concern, as runtime doesn't actually look at OSABI at the moment. You need to use a value other than 10 or 12 if you really want to extend ELF. "Doing the right thing" doesn't always doing the right thing if there are multiple players in the field and you want to make your work compatible with them, just like browsers abandoned `-moz-` and `-webkit-` CSS prefixes.

**Comment by rawoul** [comment]
FYI glibc does check that OSABI == SYSV (with ABIVERSION=0) or GNU and chokes otherwise when loading a library. I'm fine with handling the `<OS specific>` string in my scripts parsing readelf output, so feel free to close the issue. Thanks for the quick response !

**Comment by rui314** [comment]
I think that ELFOSABI is not a good idea in the first place. What we actually want to do is to annotate a binary with "this binary needs extension X" and make it possible for the loader to detect when it doesn't support extension feature X. ELFOSABI doesn't do that, but instead it just says its "GNU" though there are many different GNU extensions. It's just like detecting a web browsers name from JavaScript instead of testing whether it actually support some JavaScript API or not.
