### ISSUE TITLE
sorry, unimplemented: Thumb-1 'hard-float' VFP ABI for armv6l

### ISSUE THREAD

**Issue by marxin** [rui314/mold#655]
The following test fails on `armv6l`:

```
[ 1174s] Testing arm32-thumb-interwork ... <stdin>: In function 'foo':
[ 1174s] <stdin>:3:1: sorry, unimplemented: Thumb-1 'hard-float' VFP ABI
[ 1174s] make[1]: *** [Makefile:207: test/elf/arm32-thumb-interwork.sh] Error 1
```

**Comment by rui314** [comment]
Is this the line that failed in your environment?

```
cat <<EOF | $CC -o $t/a.o -c -xc - -mthumb
```

If you pass an empty string as an input to the compiler, does it compile or fail?

**Comment by marxin** [comment]
> Is this the line that failed in your environment?
> 
> ```
> cat <<EOF | $CC -o $t/a.o -c -xc - -mthumb
> ```

Yes.

> 
> If you pass an empty string as an input to the compiler, does it compile or fail?

It's going to fail as the `sorry` message comes from option parsing that we run even for an empty input file.

**Comment by rui314** [comment]
Thanks! Then I think the above fix should work.
