### ISSUE TITLE
[macOS] static inline variable exception handling behavior different with other linkers

### ISSUE THREAD

**Issue by niyue** [rui314/mold#657]
I have a `static inline` variable defined like this:

```
namespace {
  static inline auto logger = LogFactory::get_msg_logger("static_logger");
}
```

Internally, this `get_msg_logger` calls some third party API to parse a toml file to get some logging configuration and creates a logger. The third party API throws some exception internally but for some reason, the program linked by `mold` crashed with exception uncaught, while the same code linked by other linkers such as Apple default `ld` and `zld` won't behave like this.

Here is a program I created for reproducing this issue. I am not entirely sure if this is completely `mold`'s issue, probably the third party API ([spdlog-setup](https://github.com/guangie88/spdlog_setup)) has some issue as well, but at least `mold`'s behavior is different with other linkers.

[mold_test_2.zip](https://github.com/rui314/mold/files/9394935/mold_test_2.zip)

Additionally, in my test, if the static initialization code indeed throws some uncaught exception, other linker can report the exact error like below while `mold` doesn't report anything, and this  error message is very useful for troubleshooting, and it will be great if `mold` can produce such error message as well.

```
// mold
libc++abi: terminating with uncaught exception of type spdlog_setup::setup_error

// other linkers like Apple's `ld` and `zld`
libc++abi: terminating with uncaught exception of type spdlog_setup::setup_error: Error reading file at 'logging.toml'
```

Env:
1) macOS 12.5, ld `❯ ld -v @(#)PROGRAM:ld  PROJECT:ld64-764 BUILD 11:22:50 Apr 28 2022`
2) mold version 7bd86d9c489e801dbd9dedfa862cc16d40093620

**Comment by niyue** [comment]
Oops, github somehow failed to uploading my file, and I cannot upload new file to this issue (probably because the previous uploading never finishes)

**Comment by rui314** [comment]
I have a trouble building spdlog-setup. I got the following error. Do you have any idea as to why?

```
ruiu@studio:/tmp/spdlog_setup/build$ cmake ..
CMake Error at CMakeLists.txt:54 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" (requested
  version 1.0.0) with any of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by niyue** [comment]
I think this is because spdlog-setup depends on `spdlog`, which is a popular C++ logging library (https://github.com/gabime/spdlog). I installed both of them via vcpkg (but I use a custom port of spdlog_setup since it is not available via vcpkg official ports). Do you use vcpkg? Here is a portfile for spdlog-setup, which you can use with vcpkg to get it up and running quickly.

[spdlog-setup.zip](https://github.com/rui314/mold/files/9403614/spdlog-setup.zip)

Additionally, I think both spdlog_setup and spdlog can be used as a header only library, which only requires copy the header files into your source directory.

**Comment by rui314** [comment]
Thanks. I can now reduce the issue down to this piece of code.

```c++
#include <exception>

class Error : public std::exception {
public:
  const char *what() const noexcept override {
    return "*****THIS IS AN ERROR STRING*****";
  }
};

static int foo() {
  throw Error();
  return 1;
}

static inline int bar = foo();

int main() {}
```

```
$ c++ --ld-path=/Users/ruiu/mold/build/ld64 -o test -std=c++20 test.cc && ./test
libc++abi: terminating with uncaught exception of type Error
Abort trap: 6

$ c++ -o test -std=c++20 test.cc && ./test
libc++abi: terminating with uncaught exception of type Error: *****THIS IS AN ERROR STRING*****
Abort trap: 6
```

I'll investigate why the error message isn't displayed properly when using mold.

**Comment by rui314** [comment]
This is a tough one, but I think I fixed the issue in the above commit. Thank you for finding and reporting it!

**Comment by niyue** [comment]
@rui314 Thanks for addressing it! I tries the latest build and the program did pass the linking and can be launched now.
