### ISSUE TITLE
Consider linking tbb statically

### ISSUE THREAD

**Issue by nehaljwani** [rui314/mold#66]
At the moment, mold is compatible with tbb v2019 & v2020 but incompatible with tbb v2021. Similar to mimalloc, can it also be added as a sub-tree and linked in statically?

This is how I [build the static libs](https://stackoverflow.com/a/44359961/1005215) currently (for v2020.3):
```bash
cd /path/to/oneTBB
make extra_inc=big_iron.inc tbb_build_prefix=$PWD/install
```

And then use the following while building mold:
```bash
make EXTRA_CPPFLAGS="-I/path/to/oneTBB/include" EXTRA_LDFLAGS="-L/path/to/oneTBB/build/install_release" ...
```

When mold moves to tbb v2021, one can follow https://github.com/oneapi-src/oneTBB/issues/297

**Comment by gjimye** [comment]
>Maybe we could go away without tbb altogether? https://news.ycombinator.com/item?id=26246849
`gcc` and `clang`'s stdlib parallel STL implementation uses `tbb` as a backing (it was donate by Intel), and you need `-ltbb` to get parallel execution...

**Comment by rui314** [comment]
And C++ standard library doesn't provide parallel containers such as concurrent_hash_map, so even if we use STL for parallel for loop, we still need TBB.

**Comment by rui314** [comment]
Statically linking TBB makes sense in most cases, and subtree-ing the TBB repo may be a good idea. TBB comes with different versions, and it is not very likely that a system already has a required version of TBB.

We need an escape hatch to use system-wide TBB library for distros that don't want to link TBB statically, though.

**Comment by rui314** [comment]
I made a change to static-link oneTBB by default. Let's see how it works.
