### ISSUE TITLE
Some tests fail on my machine & on Void Linux CI

### ISSUE THREAD

**Issue by Logarithmus** [rui314/mold#67]
The failing tests (on Void Linux) (WIP):
 - `copyrel-protected.sh`
expected:
 `cannot make copy relocation for protected symbol`
found:
 nothing

 - `copyrel-relro.sh`
expected:
 `[21] .dynbss.rel.ro`
found:
 `[20] .dynbss.rel.ro`
Log: https://gist.github.com/Logarithmus/502ffb024f5cc8205894c2eb0d18e640#file-copyrel-relro-log

 - `dt_init.sh`
expected: 
 `(INIT) 0x201010`
found:
 `(INIT) 0x20100c`
Log: https://gist.github.com/Logarithmus/502ffb024f5cc8205894c2eb0d18e640#file-dt_init-log

 - `dynamic.sh`
 - `hello-dynamic.sh`
 `mold: cannot open /usr/lib/x86_64-linux-gnu/crt1.o`

 - `i386-*.sh`
 `fatal error: gnu/stubs-32.h: No such file or directory`
 this should be fixed by installing `glibc-devel-32bit` package

 TODO:

 - `ifunc-dso.sh`

 - `image-base.sh`

 - `incompatible-libs.sh`

 - `init-array.sh`

 - `library-path-static.sh`

 - `note-property.sh`

 - `run.sh`

 - `shared.sh`

I'll create a PR later and try to gradually fix all the tests.

**Comment by rui314** [comment]
Thank you for the report. Since tests are not completely self-contained (it uses an external compiler, libc and CRT objects), generated files may be slightly different. I believe that causes errors in non-Ubuntu-20 machines.

**Comment by Logarithmus** [comment]
@rui314 can you upload full logs for all the tests mentioned in this issue?

**Comment by rui314** [comment]
These tests have no feature to dump logs. I can fix these tests for you by running Void Linux in Docker. What packages did you have to install to build mold? I've never used that distro, so I appreciate if you can share the exact commands.

**Comment by Logarithmus** [comment]
@rui314 `sudo xbps-install base-devel openssl-devel xxHash-devel zlib-devel libdwarf clang tar`

**Comment by Logarithmus** [comment]
@rui314 did it work for you? If you have any Void-related questions, feel free to ask.

**Comment by nehaljwani** [comment]
I've opened up a PR at https://github.com/rui314/mold/pull/71 to build mold with GCC 11 in CI and added a small change to `test/Makefile` to become verbose on failure.

**Comment by rui314** [comment]
All tests pass now on a Void Linux in my docker environment. Please double-check.

**Comment by Logarithmus** [comment]
@rui314 thank you so much for doing this work!

**Comment by Logarithmus** [comment]
@rui314 

```
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/copyrel-protected.sh 
+ set -e
++ dirname fails/copyrel-protected.sh
+ cd fails
++ basename -s .sh fails/copyrel-protected.sh
+ echo -n 'Testing copyrel-protected ... '
Testing copyrel-protected ... ++ pwd
++ basename -s .sh fails/copyrel-protected.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/copyrel-protected
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected
+ cat
+ cc -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/a.o -c -xc -fno-PIE -
+ cat
+ cc -shared -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/b.so -xc -
++ pwd
+ clang -fuse-ld=/home/artur/Programming/C++/mold/fails/../mold /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/a.o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/b.so -o /home/artur/Programming/C++/mold/fails/tmp/copyrel-protected/exe
+ false
```

The resulting executable in `ifunc-dso` outputs nothing instead of `Hello world`.
```
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/ifunc-dso.sh        
+ set -e
++ dirname fails/ifunc-dso.sh
+ cd fails
++ basename -s .sh fails/ifunc-dso.sh
+ echo -n 'Testing ifunc-dso ... '
Testing ifunc-dso ... ++ pwd
++ basename -s .sh fails/ifunc-dso.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/ifunc-dso
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso
+ cat
+ cc -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/a.o -c -x assembler -
+ cat
+ cc -shared -fPIC -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/b.so -x assembler -
++ pwd
+ clang -fuse-ld=/home/artur/Programming/C++/mold/fails/../mold -o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/exe /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/a.o /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/b.so
+ /home/artur/Programming/C++/mold/fails/tmp/ifunc-dso/exe
+ grep -q 'Hello world'
```

This can be caused by my `/usr/bin/ld` being a symlink to `/usr/bin/mold`
**UPD** confirmed that passing `-fuse-ld=bfd` to `gcc` & `clang` in this test fixes it.
```
~/Programming/C++/mold fix-tests-again !5 ?1 ❯ bash -x fails/run.sh      
+ set -e
++ dirname fails/run.sh
+ cd fails
++ basename -s .sh fails/run.sh
+ echo -n 'Testing run ... '
Testing run ... ++ pwd
++ basename -s .sh fails/run.sh
+ t=/home/artur/Programming/C++/mold/fails/tmp/run
+ mkdir -p /home/artur/Programming/C++/mold/fails/tmp/run
+ cat
+ cc -xc -c -o /home/artur/Programming/C++/mold/fails/tmp/run/a.o -
+ gcc -o /home/artur/Programming/C++/mold/fails/tmp/run/exe /home/artur/Programming/C++/mold/fails/tmp/run/a.o
+ readelf -p .comment /home/artur/Programming/C++/mold/fails/tmp/run/exe
+ grep -q mold /home/artur/Programming/C++/mold/fails/tmp/run/log
+ false
```

**Comment by Logarithmus** [comment]
@rui314 please, reopen this issue, I think it's more logical to discuss test issues here.

**Comment by Logarithmus** [comment]
Everything works now
