### ISSUE TITLE
Run mold with qemu-riscv32

### ISSUE THREAD

**Issue by ksco** [rui314/mold#677]
I have successfully compiled mold to an RV32 binary using cross-compilation under an x86 Ubuntu machine.

```
# file mold
mold: ELF 32-bit LSB executable, UCB RISC-V, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-riscv32-ilp32d.so.1, for GNU/Linux 5.4.0, with debug_info, not stripped
```

But when I try to run it with qemu the error shows as below and I don't know why for now.
```
# qemu-riscv32 -L /opt/riscv/sysroot/ ./mold
The futex facility returned an unexpected error code.
Aborted
# echo $?
134
```

**Comment by ksco** [comment]
With QEMU_STRACE=1, outputs ended with a writev syscall:
```
# QEMU_STRACE=1 qemu-riscv32 -D log.txt -L /opt/riscv/sysroot/ ./mold
[...] skipped
19982 read(4,0xffffe640,32) = 2
19982 close(4) = 0
19982 Unknown syscall 403
19982 getrandom(-6624,32,1,392795177,0,1) = 32
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 faccessat(AT_FDCWD,"/sys/devices/system/node/node1",R_OK,0xfbad8001) = -1 errno=2 (No such file or directory)
19982 mmap2(NULL,4194304,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE,-1,0) = 0xfeda8000
19982 munmap(0xfeda8000,4194304) = 0
19982 mmap2(NULL,8388608,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE,-1,0) = 0xfe9a8000
19982 munmap(0xfe9a8000,2457600) = 0
19982 munmap(0xff000000,1736704) = 0
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 Unknown syscall 403
19982 Unknown syscall 422
19982 writev(2,0xffffe450,0x1)The futex facility returned an unexpected error code.
 = 54
19982 mmap2(NULL,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) = 0xfe9a8000
19982 rt_sigprocmask(SIG_UNBLOCK,0xffffe334,NULL) = 0
19982 rt_sigprocmask(SIG_BLOCK,0xffffe2b0,0xffffe230) = 0
19982 getpid() = 19982
19982 gettid() = 19982
19982 tgkill(19982,19982,SIGABRT) = 0
19982 rt_sigprocmask(SIG_SETMASK,0xffffe230,NULL) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=19982, si_uid=0} ---
Aborted
```
Seems like I've gone down a rabbit hole...

**Comment by rui314** [comment]
You may want to debug it using gdb. Run qemu-riscv32 with `-g 1234` like this

```
$ qemu-riscv32 -g 1234 -L /opt/riscv/sysroot/ ./mold
```

run `gdb-multiarch` and attach to the qemu-riscv32 process with `target remote localhost:1234`.

**Comment by ksco** [comment]
I've tried gdb, but it seems to have a problem with the length of flen.

```
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
bfd requires flen 8, but target has flen 4
(gdb)
```

But the good news is, I tried to compile all mold source files with `make CXX=riscv32-linux-gnu-g++ CC=riscv32-linux-gnu-gcc`, and then link'em together with mold-x86, and it successfully generated the binary.

**Comment by rui314** [comment]
Did your cross-compiled mold binary work on RV32?

**Comment by ksco** [comment]
I haven't run it successfully yet, as mentioned above, qemu-riscv32 can't do it for some reason. If there is any new progress, I will post it here.

**Comment by rui314** [comment]
I see. Debugging is the most difficult part of linker development, but I believe it's fixable. Good luck!

**Comment by rui314** [comment]
You may want to verify that mold cross-compiled for RV64 works first. I tested it before, but it might have regressed since then.

**Comment by ksco** [comment]
Ah, turns out the error `The futex facility returned an unexpected error code.` is a QEMU bug. I just rebuild qemu-riscv32 from [qemu/master](https://github.com/qemu/qemu), and the error is gone.

```
# ~/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot ./mold
mold: fatal: -m option is missing
```

Now I can move on to further testing ;)

**Comment by ksco** [comment]
RV32 mold is self-hosted! In case anyone wants to reproduce the result, here are some logs.

First, compile the x86 version of `mold`.

```
make -j$(nproc) CXX=g++-10
```

Then we rename the generated `mold` binary to `mold-x86`.

```
mv mold mold-x86
ln -sf mold-x86 ld
ln -sf mold-x86 ld64
```

Then we modify the `Makefile` to use our x86 mold linker, instead of GNU ld.

```diff
-  MOLD_LDFLAGS := -pthread -lz -lm -ldl
+  MOLD_LDFLAGS := -B. -pthread -lz -lm -ldl
```

Then we recompile `mold` using riscv32 gcc.

```
make clean
make CXX=riscv32-linux-gnu-g++ CC=riscv32-linux-gnu-gcc -j$(nproc)
```

Notice there are errors raised.

```
riscv32-unknown-linux-gnu-g++: error: unrecognized command-line option '-mrtm'
riscv32-unknown-linux-gnu-g++: error: unrecognized command-line option '-mwaitpkg'
```

We need to update `third-party/tbb/cmake/compilers/GNU.cmake`.

```diff
- if (CMAKE_SYSTEM_PROCESSOR MATCHES "(x86|AMD64|amd64|i.86)")
-     set(TBB_COMMON_COMPILE_FLAGS ${TBB_COMMON_COMPILE_FLAGS} -mrtm $<$<AND:$<NOT:$<CXX_COMPILER_ID:Intel>>,$<NOT:$<VERSION_LESS:${CMAKE_CXX_COMPILER_VERSION},11.0>>>:-mwaitpkg>)
- endif()
+ # if (CMAKE_SYSTEM_PROCESSOR MATCHES "(x86|AMD64|amd64|i.86)")
+ #     set(TBB_COMMON_COMPILE_FLAGS ${TBB_COMMON_COMPILE_FLAGS} -mrtm $<$<AND:$<NOT:$<CXX_COMPILER_ID:Intel>>,$<NOT:$<VERSION_LESS:${CMAKE_CXX_COMPILER_VERSION},11.0>>>:-mwaitpkg>)
+ # endif()
```

After this change, we can now rebuild everything without issues. Just rerun:

```
make CXX=riscv32-linux-gnu-g++ CC=riscv32-linux-gnu-gcc -j$(nproc)
```

Now, we have RV32 `mold`, which is linked by x86 `mold`.

```
mv mold mold-riscv32
rm ld ld64
echo '/root/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot /mold/mold-riscv32 "$@"' > ld
chmod 755 ld
```

Now, let's build a simple C program.

```
echo 'int main() { return 0; }' > /tmp/a.c
riscv32-linux-gnu-gcc -c -o /tmp/a.o -fPIC /tmp/a.c
riscv32-linux-gnu-gcc -B. -o /tmp/exe /tmp/a.o -static
```

And run it.

```
/root/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot /tmp/exe
echo $?
```

We get 0, perfect!

Now let's run the tests. First, we must ensure that we use the latest qemu-riscv32 instead of the one installed by `apt`, or many strange things will happen. So we change `Makefile` again:

```diff
- 	QEMU="qemu-${MACHINE} -L /usr/${TRIPLE}" \
+ 	QEMU="/root/qemu/build/qemu-${MACHINE} -L /usr/${TRIPLE}" \
```

And then we start testing.

```
echo '/root/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot /mold/mold-riscv32 "$@"' > mold
chmod 755 mold
make test-arch TRIPLE=riscv32-linux-gnu MACHINE=riscv32
```

Then we encountered an error.

```
Testing lto-version-script ... mold: fatal: could not open plugin file: /opt/riscv/libexec/gcc/riscv32-unknown-linux-gnu/12.1.0/liblto_plugin.so: wrong ELF class: ELFCLASS64
```

We `file` it, and get:

```
# file /opt/riscv/libexec/gcc/riscv32-unknown-linux-gnu/12.1.0/liblto_plugin.so
/opt/riscv/libexec/gcc/riscv32-unknown-linux-gnu/12.1.0/liblto_plugin.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f55fc81749fc97e3ebd26652b4b51aec0ef0ccb6, with debug_info, not stripped
```

This is because `liblto_plugin.so` is a host shared library. Anyway, let's just skip this one and continue.

> 1. We also skipped lto-gcc, and lto-dso for the same reason.
> 2. We skip the test by adding `echo OK; exit` at the beginning of the test file.

Another error:

```
Testing mold-wrapper2 ... 	not a dynamic executable
nm: mold: file format not recognized
```

Hmmm, we skip this one too. And then, all of the tests are passed, yay! 

Next, we want to link `mold` itself using `mold-riscv32`.

```
rm mold
make CXX=riscv32-linux-gnu-g++ CC=riscv32-linux-gnu-gcc
```

Done.

Now we want to use `mold-riscv32-stage2` to run tests.

```
mv mold mold-riscv32-stage2
rm ld ld64
echo '/root/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot /mold/mold-riscv32-stage2 "$@"' > ld
chmod 755 ld
echo '/root/qemu/build/qemu-riscv32 -L /opt/riscv/sysroot /mold/mold-riscv32-stage2 "$@"' > mold
chmod 755 mold
make test-arch TRIPLE=riscv32-linux-gnu MACHINE=riscv32
```

And again, all of the tests are passed.

**Comment by rui314** [comment]
Woohoo! Great job @ksco!
