### ISSUE TITLE
mold 1.4.1 linking fails with mold: fatal: symbol referring .eh_frame is not supported: .eh_frame_seg /opt/oracle/product/12.2.0.3.150/lib/libclntst19.a(ipc1_ipclw_emu.o)

### ISSUE THREAD

**Issue by PhilippeWaroquiers** [rui314/mold#685]
linking the application fails, the following errors are reported:

mold: fatal: symbol referring .eh_frame is not supported: .eh_frame_seg /opt/oracle/product/12.2.0.3.150/lib/libclntst19.a(ipc1_ipclw_emu.o)
mold: fatal: symbol referring .eh_frame is not supported: .eh_frame_seg /opt/oracle/product/12.2.0.3.150/lib/libclntst19.a(generic19_skgvm.o)

Note that this seems quite similar to:
" symbol referring .eh_frame is not supported for clang_rt.crtbegin-x86_64.o #112 "

but as I understand, this last issue is solved in 1.4.1
So, this problem is likely a similar but different issue.

I can try a patch if you that can helps to validate a fix.
Thanks for the work, hoping we can soon benefit from a faster linking time using mold.

**Comment by PhilippeWaroquiers** [comment]
I have looked more in depth at the problem and implemented a bypass/fix for the problem.
Details are:

In the library causing problems, we have some references to .eh_frame such as:
0000000000000000 l    d  .eh_frame	0000000000000000 .eh_frame
0000000000000000 l     O .eh_frame	0000000000000000 __EH_FRAME_BEGIN__
(this is in a file called nolib_crtbegin.o).

Most other references are in "normal" .o files that have one single reference
to .eh_frame:
0000000000000000 l    d  .eh_frame	0000000000000000 .eh_frame

A few files have 2 references to .eh_frame:
0000000000000000 l    d  .eh_frame	0000000000000000 .eh_frame
0000000000000000 l       .eh_frame	0000000000000000 .eh_frame_seg
Note that these .eh_frame_seg are not located in a CRT file but in "normal" .o files.

The linking problem is solved by the following patch:
*** mold.h.orig	Thu Aug 18 08:27:51 2022
--- mold.h	Mon Sep 12 17:33:44 2022
***************
*** 2334,2339 ****
--- 2334,2340 ----
          // section doesn't make much sense. However, CRT files contain
          // symbols pointing to the very beginning and ending of the section.
          if (name() == "__EH_FRAME_BEGIN__" || name() == "__EH_FRAME_LIST__" ||
+             name() == ".eh_frame_seg" ||
              esym().st_type == STT_SECTION)
            return ctx.eh_frame->shdr.sh_addr;



The resulting executable is starting properly and on a few tests, behaves properly.

**Comment by rui314** [comment]
I somehow missed this one. I'm sorry for the belated response.

I wonder what compiler has created that particular object file. What is you build environment?

Could you share the object file with me?

**Comment by PhilippeWaroquiers** [comment]
The problem happens when linking with a library provided by Oracle. We do not compile this library ourselves.
Looking at the note inside one of the .o files that have this .eh_frame_seg, this is likely compiled by:
  Intel(R) C Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.2.174 Build 20170213
Note however that many files compiled by this compiler do not have the .eh_frame_seg.
Thanks

[generic19_slrac.o.gz](https://github.com/rui314/mold/files/9590395/generic19_slrac.o.gz)

**Comment by rui314** [comment]
Thank you for the object file. It looks like `.eh_frame_seg` symbol is a local symbol and not being used in that object file. So it is odd that it causes an error, because as long as no one refers it, it shouldn't cause the trouble.

Do you mind if I ask you to rebuild mold with debug info and run it under gdb or something to get a stack trace?

You can get the list of command line arguments passed to the linker by appending `-###` to your compiler driver. E.g.

```
$ gcc foo.o -o foo -###
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/11/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/11/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-o' 'foo' '-mtune=generic' '-march=x86-64' '-dumpdir' 'foo.'
 /usr/lib/gcc/x86_64-linux-gnu/11/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so "-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper" "-plugin-opt=-fresolution=/tmp/ccnQ8J5f.res" "-plugin-opt=-pass-through=-lgcc" "-plugin-opt=-pass-through=-lgcc_s" "-plugin-opt=-pass-through=-lc" "-plugin-opt=-pass-through=-lgcc" "-plugin-opt=-pass-through=-lgcc_s" --build-id --eh-frame-hdr -m elf_x86_64 "--hash-style=gnu" --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o foo /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. foo.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crtn.o
COLLECT_GCC_OPTIONS='-o' 'foo' '-mtune=generic' '-march=x86-64' '-dumpdir' 'foo.'
```

The second last line is the linker command line arguments.

Since mold forks itself on startup, please add `--no-fork` to the command line.

**Comment by PhilippeWaroquiers** [comment]
I will find sometime next week to do the above (I might need to dig into our build scripts as the compiler and linker commands 
are launched very deep in a pile of shell scripts).
When I put mold --no-fork in the gdb, I guess I need to put a breakpoint where it produces the error message about .eh_frame_seg ?

**Comment by rui314** [comment]
Perhaps an easiest way to insert a breakpoint is to add the following piece of code and then run under gdb.

```
if (name() == ".eh_frame_seg")
  __builtin_trap();
```

**Comment by rui314** [comment]
I added code to handle `.eh_frame_seg` symbol as you suggested in the above commit, so this issue should be fixed now.
