### ISSUE TITLE
tests: protected test emits a warning

### ISSUE THREAD

**Issue by marxin** [rui314/mold#689]
It's a warning from dynamic linker:

```
$ out/test/elf/x86_64/protected/exe
warning: direct reference to protected function `baz' in `out/test/elf/x86_64/protected/b.so' may break pointer equality
3 4 0
```

Do you want to silent it, or?

**Comment by rui314** [comment]
Do you know where that message came from? I couldn't find that string in the glibc's source tree.

**Comment by marxin** [comment]
Comes from the following file: `sysdeps/generic/dl-protected.h: "warning: direct reference to "`

**Comment by Alcaro** [comment]
https://github.com/bminor/glibc/blob/master/sysdeps/generic/dl-protected.h

The string doesn't exist until glibc 2.36, and the entire file was added in 2.35. I suspect that's why we couldn't find it.

**Comment by rui314** [comment]
Thank you guys for giving me the pointer. Was the message printed out to stderr? I believe the following change should suffice, but I'm not sure if it prints out the warning to STDERR_FILENO.

```
diff --git a/test/elf/protected.sh b/test/elf/protected.sh
index 462cfe056..8654267d5 100755
--- a/test/elf/protected.sh
+++ b/test/elf/protected.sh
@@ -48,6 +48,6 @@ int main() {
 EOF

 $CC -B. -no-pie -o $t/exe $t/c.o $t/b.so
-$QEMU $t/exe | grep -q '3 4 0'
+$QEMU $t/exe 2> /dev/null | grep -q '3 4 0'

 echo OK
```

**Comment by marxin** [comment]
Yes, the error message goes to `stderr`:

```
out/test/elf/x86_64/protected/exe 2>/dev/null
3 4 0
```

**Comment by rui314** [comment]
Thank you for confirming! I added `2> /dev/null` in the above commit.
