### ISSUE TITLE
Alternatives to using Jemalloc.

### ISSUE THREAD

**Issue by lazerl0rd** [rui314/mold#7]
I'd like to ask if you've considered using TCMalloc and or mimalloc over Jemalloc, since you're focus on this project is speed.

The former two are generally faster than Jemalloc when threads are created and destroyed [1], with mimalloc being the shining star in all benchmarks except Redis [2].

[1] : https://stackoverflow.com/questions/7852731/c-memory-allocation-mechanism-performance-comparison-tcmalloc-vs-jemalloc#7853060
[2] : https://github.com/microsoft/mimalloc#on-24-core-amd-epyc

**Comment by rui314** [comment]
Ah, thank you for your advice! I tried mimalloc, and it is indeed slightly better than jemalloc. mold runs a few percent faster with mimalloc.

I wanted to give tcmalloc a shot, but it looks like it can't be built with make or cmake, so I'll leave it alone for now.

**Comment by pepsiman** [comment]
The gperftools version of tcmalloc builds with cmake. https://github.com/gperftools/gperftools

**Comment by lazerl0rd** [comment]
> Ah, thank you for your advice! I tried mimalloc, and it is indeed slightly better than jemalloc. mold runs a few percent faster with mimalloc.
> 
> I wanted to give tcmalloc a shot, but it looks like it can't be built with make or cmake, so I'll leave it alone for now.

As @pepsiman mentioned above, you can build TCMalloc with cmake from the gperftools repository. However, if Microsoft's benchmarks (as well as my preliminary benchmarks) are anything to go by then mimalloc should outperform TCMalloc.

I'm sure you'll compare them both to be sure anyways, and hopefully mold will end up even faster (it's already pretty darn fast).

**Comment by rui314** [comment]
I tried tcmalloc, and it looks like tcmalloc is the slowest among tcmalloc, tbbmalloc, jemalloc and mimalloc. Here is the chromium link time:

mimalloc: 1.83s
jemalloc: 1.89s
tbbmalloc: 1.96s
tcmalloc: 2.13s
glibc malloc: 3.10s

It is very interesting to see that swapping malloc makes such a huge performance difference.

**Comment by lazerl0rd** [comment]
> I tried tcmalloc, and it looks like tcmalloc is the slowest among tcmalloc, tbbmalloc, jemalloc and mimalloc. Here is the chromium link time:
> 
> mimalloc: 1.83s
> jemalloc: 1.89s
> tbbmalloc: 1.96s
> tcmalloc: 2.13s
> glibc malloc: 3.10s
> 
> It is very interesting to see that swapping malloc makes such a huge performance difference.

It is interesting to see TCMalloc lag behind so much, but also great to see mimalloc do quite well. Thanks for testing them all.

**Comment by rui314** [comment]
@marxin Please build mold with `make USE_MIMALLOC=0`
