### ISSUE TITLE
Support for --compress-debug-sections=zstd

### ISSUE THREAD

**Issue by ADKaster** [rui314/mold#700]
MaskRay recently pushed a proposal through the SysV gABI group to add a new ch_type value for ELFCOMPRESS_ZSTD (as the value 2) https://groups.google.com/g/generic-abi/c/satyPkuMisk/m/KwTF_U8rBAAJ

Have you been tracking this proposal? :D

It looks like the implementation in ld.lld is in progress  (https://reviews.llvm.org/D133548), and some of the underlying support has landed already (https://github.com/llvm/llvm-project/commit/a41977dd0f4fd7aaad5ec380d50782296a690b47).

I started to look into how it can be added to mold, starting with the CMake changes:

```cmake
# Setup zstd
find_package(zstd QUIET)
if (ZSTD_FOUND)
  target_link_libraries(mold PRIVATE zstd::libzstd_static)
else()
  set(ZSTD_BUILD_PROGRAMS OFF)
  set(ZSTD_BUILD_TESTS OFF)
  add_subdirectory(third-party/zstd/build/cmake EXCLUDE_FROM_ALL)
  target_link_libraries(mold PRIVATE libzstd_static)
endif()
```

But I quickly realized I don't know how to call into zstd to parallelize the compression via shards like the Gzip and Zlib compressor implementations in compress.cc do.

It also looks like, from a cursory look at the source of zstd, that they do some internal threading that might not behave nicely with a naive tbb::parallel_for approach. (https://github.com/facebook/zstd/blob/v1.5.2/lib/common/pool.c)

**Comment by rui314** [comment]
I knew about the proposal but I didn't track the progress. Thank you for the heads-up.

I wonder if you can't really concatenate zstd-compressed streams. [This note](https://pkg.go.dev/github.com/klauspost/compress/zstd#section-readme:~:text=Also%20note%2C%20that%20the%20cgo%20decompressor%20currently%20does%20not%20report%20all%20errors%20on%20invalid%20input%2C%20omits%20error%20checks%2C%20ignores%20checksums%20and%20seems%20to%20ignore%20concatenated%20streams%2C%20even%20though%20it%20is%20part%20of%20the%20spec.) in the Go's zstd package implies that it's doable (though the very package doesn't support concatenated streams.)

**Comment by ishitatsuyuki** [comment]
You should be able to concatenate zstd streams. That's what [pzstd](https://github.com/facebook/zstd/tree/dev/contrib/pzstd) basically do. It comes with a slight hit to compression ratio.

**Comment by MaskRay** [comment]
It seems that pzstd was contribute earlier than `zstd -T#`.

There are two parts: (a) input debug sections (b) output debug sections. They are implemented in ld.lld and I am trying to parallelize (b) for ld.lld: https://github.com/llvm/llvm-project/issues/57685 . I tagged the maintainers and hope that they can demystrify pzstd :)
