### ISSUE TITLE
Cmake won't build

### ISSUE THREAD

**Issue by immolo** [rui314/mold#718]
First off, this seems like an interesting project that I decided to test it in Gentoo to see what issues will crop for a user trying it out, so thank you for the fun I'll have testing this.

Now, I've looked at the other issues raised however I couldn't see one with cmake itself being compiled with mold. So currently compiling it will report that compiler doesn't support C++11std yet filtering out mold allows it to build without failing the test.

[cmake-3.42.2-build.log](https://github.com/rui314/mold/files/9595119/cmake-3.42.2-build.log)
[CMakeOutput.log](https://github.com/rui314/mold/files/9595124/CMakeOutput.log)
[CMakeError.log](https://github.com/rui314/mold/files/9595126/CMakeError.log)

I did get it build successfully with mold by patching out the test in cmake for the standard but I haven't had chance to see how poorly that idea will turn out in a live system.

 [disable-check.patch.txt](https://github.com/rui314/mold/files/9595130/disable-check.patch.txt)

Any ideas what the best way is to precede here? As I'd like to submit the fix with issue when I add this to Gentoo's mold tracker.

**Comment by rui314** [comment]
mimalloc (Microsoft's faster malloc library) seems to be complaining about something. It looks like your system is based on musl, right? Is that ARM64 or x86-64? I want to make sure that mimalloc is compatible to your system first.

**Comment by immolo** [comment]
This is a x85_64 system.

**Comment by rui314** [comment]
With musl?

**Comment by immolo** [comment]
Yes with MUS, I'll set up a quick glibc environment just to compare out of interest.

**Comment by rui314** [comment]
If there's a gentoo stage3 musl docker image, I can pull it and try to build mold myself.

**Comment by immolo** [comment]
I'm not a docker user myself however this site might be able to help you: https://github.com/gentoo/gentoo-docker-images

**Comment by rui314** [comment]
I don't know what's wrong, but `docker pull gentoo/stage3-amd64-musl` failed because the image is missing.

**Comment by immolo** [comment]
I'm getting the same, I'll check on #gentoo-containers to see what is going on.

**Comment by immolo** [comment]
'docker pull gentoo/stage3:musl-20220919' 

Just noticed my copy paste skills were failing me  :)

**Comment by rui314** [comment]
Oh, okay, unless you know that exact name, you can't pull that image. 😀

I'm pulling the image. Will try to build mold on it.

**Comment by rui314** [comment]
I built mold inside the docker image, installed it to /usr/local/bin, ran `ln -sf /usr/local/bin/mold /usr/bin/ld` and then `emerge cmake`. The last emerge just succeeded.

Could you share me the details as to how to reproduce the issue?

**Comment by immolo** [comment]
I've just had an issue with something else so I think my chroot is pulling information from the host and causing the negative integer issue.

Let me run this on bare metal to confirm.

**Comment by rui314** [comment]
It looks like mimalloc caused a runtime error. Please rebuild mold and try again.

**Comment by immolo** [comment]
> It looks like mimalloc caused a runtime error. Please rebuild mold and try again.

I've tried this with no luck with 1.4.2, is there anything in the git version that's makes this worth testing next?

**Comment by immolo** [comment]
Just seen your commit now :)

**Comment by rui314** [comment]
Yeah, sorry, please run `git pull` and then rebuild.

**Comment by immolo** [comment]
No drama, I replied to this precoffee originally.

I'm back in a few days so I'll do a full test on this then.

Thanks for your help and fix!

**Comment by immolo** [comment]
Just a quick update for you, I was having issues with the git version originally but since 1.5.1 everything seems fine now so I have push a commit to Gentoo to get x86 added to the ebuild to hopefully get some more users interested in this linker and help improve it.

https://github.com/gentoo/gentoo/pull/27642
