### ISSUE TITLE
Procps - mold: fatal: library not found: elogind

### ISSUE THREAD

**Issue by immolo** [rui314/mold#719]
When building procps with --with-elogind then mold errors with 'mold: fatal: library not found: elogind'

Works find when mold is disabled though so mold must be looking in an incorrect place.
[procps-3.3.17-build.log](https://github.com/rui314/mold/files/9595461/procps-3.3.17-build.log)

**Comment by rui314** [comment]
mimalloc is printing out lots of warning messages. I think we need to fix it first because it could be a reason why it is unstable on your system.

**Comment by rui314** [comment]
It's like a duplicate of https://github.com/rui314/mold/issues/718
