### ISSUE TITLE
Document supported CMake build options

### ISSUE THREAD

**Issue by marxin** [rui314/mold#734]
Right now, I'm using `make` with the following settings:
`USE_MIMALLOC=0 STRIP=true SYSTEM_TBB=1 SYSTEM_XXHASH=1 SYSTEM_ZSTD=1`. Can you please document the corresponding `CMake` options I'm supposed to use?

**Comment by grawlinson** [comment]
It should be in `CMakeLists.txt`, there's no option to use system xxhash or strip the binaries when using cmake though.

Here's a loose parallel:

```sh
# Ensure system has relevant dependencies installed: zstd, tbb, etc

# change into mold's repository
cd $MOLD_SRC_DIR

cmake \
  -S . \
  -B build \
  -DMOLD_USE_MIMALLOC=OFF \
  -DMOLD_USE_SYSTEM_TBB=ON

cmake --build build
```

**Comment by rui314** [comment]
I'll document common options.

I believe if you build it as a debug build with `-DCMAKE_BUILD_TYPE=Debug`, the result won't be stripped.

I wonder why you disabled mimalloc. Is there any reason to do that?

**Comment by rui314** [comment]
I don't know how to make cmake to not automatically strip binaries in Release build. Maybe you just want to build it with `RelWithDebInfo` instead?

**Comment by marxin** [comment]
> I don't know how to make cmake to not automatically strip binaries in Release build. Maybe you just want to build it with `RelWithDebInfo` instead?

Yep, that's the correct configuration.

**Comment by marxin** [comment]
> I wonder why you disabled mimalloc. Is there any reason to do that?

Just a quick note about `mimaloc`, for Clang-16 linked on `AMD EPYC 7543 32-Core Processor` I see the following numbers:
- mold w/o mimalloc (using glibc `2.36`) `1.44s`
- mold w mimalloc (statically linked) `1.3s`
- ld.bfd `68.2s`

So `mimalloc` makes the linking about ~10% faster.

**Comment by marxin** [comment]
> I'll document common options.

May I please remind this?

**Comment by rui314** [comment]
Thank you for the remainder. I'll do this before the next release.

**Comment by marxin** [comment]
Thanks for it. I noticed you unconditionally use:

```
#define XXH_INLINE_ALL 1
#include "third-party/xxhash/xxhash.h"
```

Well, I might be interested in system's xxhash that maps to a certain release (make used to support `SYSTEM_XXHASH=1`).

**Comment by rui314** [comment]
xxhash functions are inlined for the performance reason, so there's no runtime dependency to libxxhash in either way. In other words, we are using xxhash as a header-only library.

**Comment by marxin** [comment]
I know it uses only the header file, but one might want to use the one provided by a system package. But that's a minor issue, please ignore it.
