### ISSUE TITLE
Usage of mold on macOS unclear

### ISSUE THREAD

**Issue by tfar** [rui314/mold#746]
I'm trying to use mold on macOS.
I've been trying with XCode's clang++ and a hello world c++ file.

```
clang++ -fuse-ld=ld64.mold -o test test.cpp                                                                                                                                                                                            
clang-15: error: invalid linker name in argument '-fuse-ld=ld64.mold'
```

Am I using it wrongly? From the README.md file I got the impression that `-fuse-ld=ld64.mold` is the right flag to use. I've installed mold via homebrew.

**Comment by sicherha** [comment]
The correct way to invoke it is by passing `-fuse-ld=mold`. The `ld64.` prefix gets added implicitly.

**Comment by tfar** [comment]
Thanks. Maybe I've misread the instructions. :)
