### ISSUE TITLE
-Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000 is not honored

### ISSUE THREAD

**Issue by ms178** [rui314/mold#757]
Hey Rui,

a day or two after https://github.com/rui314/mold/issues/732#issuecomment-1262811744, I noticed that specifying  -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000 seems not to be honored any longer. But I am deducing my conclusion solely from the significantly lower binary size of the compiled projects which now matches the one for the standard page size.

I've reproduced the behavior with 6ea03e6433e172f57f1efdbe703da28656b2f731.

**Comment by rui314** [comment]
That's a feature and not a bug. That flag should be honored, but mold-produced binaries with a large `-z max-page-size` are now on par in terms of size with the ones linked with the default `-z max-page-size`.
