### ISSUE TITLE
CMake build on Linux wrongly handles absolute `CMAKE_INSTALL_LIBEXEC`

### ISSUE THREAD

**Issue by akien-mga** [rui314/mold#762]
Building mold 1.5.1 on Mageia Linux using our packaging `%cmake` macro, which defines standard install paths with absolute paths
```
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
        -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/libexec \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DCMAKE_INSTALL_RUNSTATEDIR:PATH=/run \
        -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
```

This is a valid usage according to https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html, i.e. the `CMAKE_INSTALL_FULL_LIBEXECDIR`, etc. would only get `CMAKE_INSTALL_PREFIX` prepended if it's not already part of the path.

However this produces unexpected results for mold's CMake script that generates the `${CMAKE_INSTALL_FULL_LIBEXECDIR}/mold/ld` symlink:
https://github.com/rui314/mold/blob/6bbf82f3b01c64eb952fb5fcce901d892e17bad1/CMakeLists.txt#L290-L307

I get the following folder structure:
```
$ find | grep -v src | grep -v debug
.
./usr
./usr/bin
./usr/bin/mold
./usr/bin/ld64.mold
./usr/bin/ld.mold
./usr/usr
./usr/usr/libexec
./usr/usr/libexec/mold
./usr/usr/libexec/mold/ld
./usr/lib
./usr/share
./usr/share/licenses
./usr/share/licenses/mold
./usr/share/licenses/mold/LICENSE
./usr/share/man
./usr/share/man/man1
./usr/share/man/man1/mold.1.xz
./usr/share/man/man1/ld.mold.1.xz
./usr/share/doc
./usr/share/doc/mold
./usr/share/doc/mold/LICENSE
./usr/share/doc/mold/README.md
./usr/lib64
./usr/lib64/mold
./usr/lib64/mold/mold-wrapper.so
```

I don't see right away what the issue could be, as printing `CMAKE_INSTALL_FULL_LIBEXECDIR` confirms that it's `/usr/libexec` and the other symlinks like `/usr/bin/ld.mold` are properly generated.

**Comment by akien-mga** [comment]
Here's how the `cmake_install.cmake` looks like:
```
if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  
    file(RELATIVE_PATH RELPATH
       //usr/libexec/mold //usr/bin/mold)
    execute_process(COMMAND /usr/bin/cmake -E make_directory
      $ENV{DESTDIR}//usr/libexec/mold)
    execute_process(COMMAND /usr/bin/cmake -E create_symlink ${RELPATH}
      $ENV{DESTDIR}//usr/libexec/mold/ld)
    execute_process(COMMAND /usr/bin/cmake -E create_symlink mold
      $ENV{DESTDIR}//usr/bin/ld.mold)
    execute_process(COMMAND /usr/bin/cmake -E create_symlink mold
      $ENV{DESTDIR}//usr/bin/ld64.mold)
    execute_process(COMMAND /usr/bin/cmake -E create_symlink mold.1
      $ENV{DESTDIR}//usr/share/man/man1/ld.mold.1)
endif()
```

I suspect the syntax used might be fine for `create_symlink` but not for `make_directory` which might wrong prepend the prefix again.

**Comment by rui314** [comment]
Cool! I'm happy to hear that that fix works for you.

**Comment by rui314** [comment]
@jpalus Thank you for making that change. I'm closing this bug.
