### ISSUE TITLE
unknown relocation: R_ARM_THM_JUMP19 on armv7l with neon

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#774]
Building `ffmpeg 4.4.3` for `armv7` with neon extensions fails with (`mold 1.5.1`):
```
mold: error: libavresample/arm/audio_convert_neon.o:(.text): unknown relocation: R_ARM_THM_JUMP19
```
Builds for `armv6` as well as `aarch64` work fine so is build for `armv7` with `bfd`.

Object file (if needed I can attach all object files):
[audio_convert_neon.zip](https://github.com/rui314/mold/files/9742701/audio_convert_neon.zip)

**Comment by rui314** [comment]
It looks like compilers don't generally create `R_ARM_THM_JUMP19` for function calls. The ffmpeg code was written in assembly by hand (https://github.com/FFmpeg/FFmpeg/blob/master/libswresample/arm/audio_convert_neon.S#L139). It is probably better to fix ffmpeg than working it around on our side. I'll send a patch to ffmpeg.

**Comment by rui314** [comment]
I decided to just implement it instead. I can't verify this fix though. Does this work for you?

**Comment by jpalus** [comment]
@rui314 links fine and programs using `ffmpeg` work fine too. Likely I won't ever hit this particular code path so can't comment if it works ok but that's good enough for me. Thanks!
