### ISSUE TITLE
qtwebengine fails linking on aarch64

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#779]
`qtwebengine` build fails with `mold 1.5.1`:
```
mold: error: undefined symbol: QtWebEngineCore::JavaScriptDialogController::defaultPrompt() const
>>> referenced by qquickwebenginedialogrequests.cpp
>>>               .obj/qquickwebenginedialogrequests.o:(QQuickWebEngineJavaScriptDialogRequest::QQuickWebEngineJavaScriptDialogRequest(QSharedPointer<QtWebEngineCore::JavaScriptDialogController>, QObject*))>>> referenced by ui_delegates_manager.cpp
>>>               .obj/ui_delegates_manager.o:(QtWebEngineCore::UIDelegatesManager::showDialog(QSharedPointer<QtWebEngineCore::JavaScriptDialogController>))
mold: error: undefined symbol: QtWebEngineCore::JavaScriptDialogController::type() const
>>> referenced by ui_delegates_manager.cpp
>>>               .obj/ui_delegates_manager.o:(QtWebEngineCore::UIDelegatesManager::showDialog(QSharedPointer<QtWebEngineCore::JavaScriptDialogController>))>>> referenced by qquickwebenginedialogrequests.cpp
>>>               .obj/qquickwebenginedialogrequests.o:(QQuickWebEngineJavaScriptDialogRequest::QQuickWebEngineJavaScriptDialogRequest(QSharedPointer<QtWebEngineCore::JavaScriptDialogController>, QObject*))>>> referenced by ui_delegates_manager.cpp
>>>               .obj/ui_delegates_manager.o:(QtWebEngineCore::UIDelegatesManager::showDialog(QSharedPointer<QtWebEngineCore::JavaScriptDialogController>))>>> referenced 1 more times
```

Links to sources for `JavaScriptDialogController`:
https://code.qt.io/cgit/qt/qtwebengine.git/tree/src/core/javascript_dialog_controller.cpp?h=v5.15.11-lts
https://code.qt.io/cgit/qt/qtwebengine.git/tree/src/core/javascript_dialog_controller.h?h=v5.15.11-lts
https://code.qt.io/cgit/qt/qtwebengine.git/tree/src/core/javascript_dialog_controller_p.h?h=v5.15.11-lts

Links to source for `UIDelegatesManager` using above:
https://code.qt.io/cgit/qt/qtwebengine.git/tree/src/webengine/ui_delegates_manager.cpp?h=v5.15.11-lts

Binary files (if needed I can provide all of them):
* object file `javascript_dialog_controller.o` 
* shared library `libQt5WebEngineCore.so` `javascript_dialog_controller` was linked into
* object file `ui_delegates_manager.o` that should form `libQt5WebEngine.so` and linked against `libQt5WebEngineCore.so`

http://jpalus.fastmail.com/mold-qtwebengine.zip

**Comment by ishitatsuyuki** [comment]
Do you by any chance know if this is specific to ARMv8?

**Comment by jpalus** [comment]
@ishitatsuyuki links fine on x86_64 so possibly specific to ARMv8. I can't test on any other platform though.

**Comment by ishitatsuyuki** [comment]
I see, I'll test the binaries you provided first, but if it doesn't work, I guess I'll rent a Graviton instance.

**Comment by jpalus** [comment]
`libQt5WebEngineCore.so` is wrong as those symbols are already undefined there even though they should be. It appears that flag used for linking `Wl,--icf=all`` is somehow involved as dropping it produces shared library with those symbols defined. Cannot reproduce it with just this single object file though. I will try to narrow down object file subset that produces wrong shared library though it may take a while since there are nearly 6k object files linked.

**Comment by jpalus** [comment]
Ok got it:
```
$ g++ file_picker_controller.o javascript_dialog_controller.o -fuse-ld=mold -shared -o libsome.so
$ nm -D libsome.so|grep default
0000000000010d30 T _ZNK15QtWebEngineCore20FilePickerController15defaultFileNameEv
0000000000014910 T _ZNK15QtWebEngineCore26JavaScriptDialogController13defaultPromptEv
```
That's all fine. Now try with `-Wl,--icf=all`:
```
$ g++ file_picker_controller.o javascript_dialog_controller.o -fuse-ld=mold -Wl,--icf=all -shared -o libsome.so
$ nm -D libsome.so|grep default
0000000000010d30 T _ZNK15QtWebEngineCore20FilePickerController15defaultFileNameEv
                 U _ZNK15QtWebEngineCore26JavaScriptDialogController13defaultPromptEv
```
`defaultPrompt` is undefined now. But it's even more interesting, let's swap order of object files:
```
$ g++ javascript_dialog_controller.o file_picker_controller.o -fuse-ld=mold -Wl,--icf=all -shared -o libsome.so
$ nm -D libsome.so|grep default                                                                                
                 U _ZNK15QtWebEngineCore20FilePickerController15defaultFileNameEv
0000000000010c60 T _ZNK15QtWebEngineCore26JavaScriptDialogController13defaultPromptEv
```
It's the `defaultFileName` that's undefined now, while `defaultPrompt` is fine.
[object-files.zip](https://github.com/rui314/mold/files/9766963/object-files.zip)

**Comment by jpalus** [comment]
Seems like behavior is the same on x86_64 so either:
- it's not the culprit (perhaps eliminated functions appear as undefined symbols?)
- my check on x86_64 was not accurate

**Comment by ishitatsuyuki** [comment]
Sorry for the delay, and thanks, it reproduces on amd64 with `-m aarch64linux` indeed.

It's indeed strange that ICF emits undefined symbols; normally they should be merged to point to the same location. I'll investigate why this is happening.

**Comment by ishitatsuyuki** [comment]
Hi @jpalus, would you mind try building #782 and see if it fixes the issue for you?

**Comment by jpalus** [comment]
@ishitatsuyuki links fine and resulting binary works correctly. Thanks!

**Comment by ishitatsuyuki** [comment]
Great. Thanks for confirming!
