### ISSUE TITLE
`--as-needed` does not work as expected

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#786]
Just noticed that `mold 1.5.1` does link libraries even though they are not used by object files while `--as-needed` was passed to linker. It seems that `mold` incorrectly checks symbols of other linked libraries so if `libbar` needs and is linked to `libfoo` and `exe` needs only `libbar` but linking has both `-lbar` and `-lfoo` then `exe` will end up with both `libbar` and `libfoo` even though `--as-needed` should have eliminated `libfoo`:

`libfoo.c`:
```c
int foo() {
  return 0;
}
```
`libbar.c`:
```c
int foo();

int bar() {
  return foo();
}
```
`exe.c`:
```c
int bar();
int main() {
  return bar();
}
```
Build:
```
gcc -shared libfoo.c -fuse-ld=mold -o libfoo.so
gcc -shared libbar.c -fuse-ld=mold -L. -o libbar.so -lfoo 
gcc exe.c -L. -Wl,--as-needed -fuse-ld=mold -o exe -lbar -lfoo
```
Check `exe` dependencies:
```
$ readelf -d exe|grep NEEDED      
 0x00000001 (NEEDED)                     Shared library: [libbar.so]
 0x00000001 (NEEDED)                     Shared library: [libfoo.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
```
`libfoo` is there. Try with `bfd`:
```
$ gcc exe.c -L. -Wl,--as-needed -fuse-ld=bfd -o exe -lbar -lfoo 
$ readelf -d exe|grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libbar.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
```
`libfoo` is eliminated correctly. Not sure how important it is but compared to `mold` `ld-linux-armhf.so.3` is also not here.

Note that if third lib is used not used by any of linked objects then it is eliminated correctly.

**Comment by rui314** [comment]
Thank you for your bug report. It looks like it's a real issue, though it's not very clear what is the desired result.

Currently, we scan symbols in DSOs and keep referred object files/DSOs. But maybe we should stop scanning undefined symbols in DSOs. Let me take a closer look.

**Comment by jpalus** [comment]
Some random thoughts regarding scanning DSOs:
- man page does not mention it, only object files:
>  However, shared libraries after --as-needed are added to the list only when at least one symbol is actually used by an object file.  In other words, shared libraries after --as-needed are not added to the list of needed libraries if they are not needed by a program.
-  if some library has undefined symbols I would actually preferred `mold` not to cover the issue even if it means my binary breaking because of linking issues in some foreign library (I can always disable `--as-needed` then)
- `lld` behaves same as `bfd`

**Comment by rui314** [comment]
I made a change so that DSO cannot mark other DSO as "needed". I'm not 100% sure it'll work correctly in all cases, but let's see how it works.
