### ISSUE TITLE
Mold don't work, what would be the reasons?

### ISSUE THREAD

**Issue by Smith-Cruise** [rui314/mold#796]
I'm using GCC 10.3, and I found that in the link phase, mold still uses one core, it's too slow.
And I check the elf header, I'm sure it's using Mold for linking.

**Comment by rui314** [comment]
I need more information. How did you know mold used only one core?

**Comment by Smith-Cruise** [comment]
I use `htop` to see it, in linking phase, only one core is working.

**Comment by rui314** [comment]
- How did you verify that your binary was built with mold?
- How did you measure that the linking phase is slow?
- Are you running it on a VM?

**Comment by Smith-Cruise** [comment]
1:
```bash
String dump of section '.comment':
  [     0]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
  [    2d]  GCC: (GNU) 10.4.0
  [    3f]  GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
  [    74]  mold 1.2.0 (8073a92614fb59f59570031badab5dd4bc3b4f7f; compatible with GNU ld)
```
2: The linking phase speed is the same as `ld`.
3: I'm running in AliCloud ECS.

**Comment by ishitatsuyuki** [comment]
Are you using `-flto`? f you are using `-flto` (and not `-flto=thin`) then the bulk of time is spent inside the compiler code doing single-threaded Link-Time Optimization. mold cannot make this magically fast. For parallel LTO, look for [ThinLTO](https://clang.llvm.org/docs/ThinLTO.html).

**Comment by rui314** [comment]
I'll close this bug as it doesn't look like a bug. It's more like a usage error. If the problem persists, please reopen with more information.
