### ISSUE TITLE
Reduction of opened files

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#797]
Today `mold` failed to link `qtwebengine` from Qt6 due to too many opened files. Linking consists of more than `8400` object files, while my limit at the time was set to `8192`. So it appears `mold` keeps descriptors to all object files at some point. Is it possible to reduce that like close descriptor after processing?

**Comment by rui314** [comment]
We close a file as soon as we `mmap(2)` it. IIUC, mmaped files are not counted as opened files. My ulimit shows that the maximum number of open files for me is 1024, but mold seems to be working fine for large programs. So I guess it's not a simple ulimit error. Can you run the linker with `strace` to watch what system call is failing?

**Comment by jpalus** [comment]
@rui314 you're absolutely right, `mold` seems to do everything correctly. Looks like it's issue with my particular setup. Raised https://github.com/containers/fuse-overlayfs/issues/378 for this.
