### ISSUE TITLE
mold 1.6.0 produced armv7 binary which crashes binutils' strip

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#801]
Running `strip` from `binutils` against attached `bindfs` binary results in segfault (elfutils strip works fine). Note that binary linked with `mold 1.5.1` strips fine.
[bindfs.zip](https://github.com/rui314/mold/files/9834039/bindfs.zip)

**Comment by rui314** [comment]
Can you try again with the above commit?

**Comment by jpalus** [comment]
@rui314 Confirmed that it fixes the issue. Thanks!

**Comment by rui314** [comment]
Cool! Thank you for confirming.
