### ISSUE TITLE
Will you support MINGW on Windows?

### ISSUE THREAD

**Issue by 3oheicrw** [rui314/mold#811]
Like the title. It will really help. See: https://github.com/brechtsanders/winlibs_mingw/issues/118

**Comment by rui314** [comment]
Maybe, but it's too early to talk about mingw. We need to support Windows first.

**Comment by rui314** [comment]
Since it's not actionable, I'll close this bug. We'll bring it up after mold/Windows is available.

**Comment by shuiweng** [comment]
Very good if it supports Windows, GNU ld sucks on Windows.
