### ISSUE TITLE
Symbol resolution optimization ideas

### ISSUE THREAD

**Issue by ishitatsuyuki** [rui314/mold#813]
While working on #810 I've looked for some (low-level) opportunities to undo the performance regression so I'll put the ideas here.

**`clear_symbols` take a redundant lock.**
This lock is *mostly* unnecessary:
https://github.com/rui314/mold/blob/61f28d270c3c6b9b88392c4c07d54c3362d9762a/elf/input-files.cc#L55
Perf changes from 69ms to 51ms. WTF.

The caveat is that plain assignments don't enjoy as much guarantees as `atomic` with `mo_relaxed`, and notably the spec allows observing *tearing* writes. On practical platforms the atomicity is guaranteed in hardware at no cost. Boehm did a [proposal](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4013.html) before for a standard compliant way to do this but it seems the progress is stalled.

Using plain atomics have poor ergonomics, because the operators on them defaults to seq_cst and we need to manually call the `<atomic>` member functions with `mo_relaxed` to get the zero-cost relaxed ordering. Compilers tend to treat relaxed atomic operations as a blackbox which also leads to them being optimized poorly.

On the other hand if we decide to just not care about compliance we can just disable TSan for the block. It's more pragmatic but puts more assumption against the architecture. That said, typically it's safe up to pointer size (which means the only unsafe thing is 64bit stores on 32bit archs).

**Experimenting with multi-pass resolution**
"Multi-pass resolution" isn't a descriptive name, but what I want to do here is to do two pass: 1. Determine the min cost and 2. Once the min cost is determined, actually assign the content. Pass 2 can be done without locking and pass 1 can be done with atomic instructions, which is an improvement from mutexes. A similar idea is used inside COMDAT elimination.

Right now we take a mutex which adds to wait time.
https://github.com/rui314/mold/blob/61f28d270c3c6b9b88392c4c07d54c3362d9762a/elf/input-files.cc#L905

---

There are a few more usages of `sym.mu`. Would be cool if we can get rid of all of them.

**Comment by ishitatsuyuki** [comment]
I tried iterating across the ctx symbol map, but it was over 10 times slower despite having better theoretical complexity. TBB’s concurrent hashmap is probably to blame.

If we don’t have a better option here, I think the easier way here would be to add an `atomic<T>` wrapper that turns reads and assignments into relaxed.

**Comment by rui314** [comment]
Is it considered a data race if multiple threads write the same value to a struct member without taking a lock? I'm just not familiar with the definition of data race in C++. If we clear all symbols, we don't need to check the current value of the `file` member but we can just set to `nullptr` unconditionally.

**Comment by ishitatsuyuki** [comment]
> When an [evaluation](https://en.cppreference.com/w/cpp/language/eval_order) of an expression writes to a memory location and another evaluation reads or modifies the same memory location, the expressions are said to conflict.

https://en.cppreference.com/w/cpp/language/memory_model

Looks like it’s technically data race and UB, unfortunately.

**Comment by rui314** [comment]
I think I'm inclined to write unsafe code here and silence TSAN, as I don't think it can cause a practical issue in reality.

**Comment by rui314** [comment]
The other radical idea is to stop using onetbb's hashmap and replace it with our own ConcurrentMap implemented at  https://github.com/rui314/mold/blob/main/mold.h#L370. It's just an idea though.

**Comment by ishitatsuyuki** [comment]
While TBB is way too slow here and likely is doing something really wrong, hashmaps have the intrinsic issue of having an iteration cost of O(slots) instead of O(items). This can give us a somewhat large constant factor of penalty when combined with the HLL predictor, for example.

**Comment by rui314** [comment]
OK, here is another idea: let a fairly large number of threads (e.g. 16 or 32) to visit all files' all symbols in a doubly nested loop. Each thread clears a symbol if the (symbol address % alignof(Symbol) == _i_ where _j_, 0 < _i_ < thread-count is a thread id.

**Comment by ishitatsuyuki** [comment]
I think that's a bit too far since 1. It makes assumption on the allocator behavior and 2. It has an even worse complexity.

I still think either making a relaxed_atomic wrapper or just straight disabling TSan is better.

**Comment by ishitatsuyuki** [comment]
With all the changes in symbol resolution has got fast enough that we can shift focus to other things. It's even a bit faster than before the COMDAT change so we don't need to worry about release-to-release perf regression.
