### ISSUE TITLE
make test: please pass -jN to `ctest`

### ISSUE THREAD

**Issue by marxin** [rui314/mold#817]
Please allow running tests in parallel by adding `-j` arguments to `ctest`.

**Comment by rui314** [comment]
I deleted our Makefile a few days ago, and even before our Makefile didn't use ctest. So I wonder which file you are talking about.

**Comment by marxin** [comment]
I use `cmake` and it emits the following Make rules:

```
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test
```

and so I'm talking about this `ctest` command invocation.

**Comment by rui314** [comment]
I don't know how to add `-j$(nproc)` there. I usually directly run `ctest -j$(nproc)`, which seems to be the official way to run tests with cmake.

**Comment by marxin** [comment]
I see. The following works for me:
```
$ ARGS="-j 16" make test
$ make test ARGS="-j 16"
```
