### ISSUE TITLE
`.note.gnu.property` not propagated to the output file

### ISSUE THREAD

**Issue by marxin** [rui314/mold#824]
I noticed that:

```
$ cat a.c
#include <string.h>

int main(int argc, char **argv)
{
  return strcmp (argv[0], "pes") == 0;
}
$ gcc-12 -c a.c
$ readelf -n a.o

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000020	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA used: 
	x86 feature used: x86
$ gcc-12 a.o -B ~/Programming/mold/objdir
$ readelf -n a.out

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 66687aadf862bd776c8fc18b8e9f8e2008971485

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0
```

So the note is lost in final executable. Note `ld` and `ld.gold` and `lld` preserve it:

```
$ gcc-12 a.o
$ readelf -n a.out

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000030	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline
	x86 feature used: x86
	x86 ISA used: 

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: a9db34a5862eb2791e30343626acd07ba4eeda4a

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0
$ gcc-12 a.o -fuse-ld=gold
$ readelf -n a.out

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000020	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline
	x86 feature used: x86

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 73066803db6d77cc0512b546d02f1da06f7f62ab

Displaying notes found in: .note.gnu.gold-version
  Owner                Data size 	Description
  GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
    Version: gold 1.16
```

Do I miss something?

**Comment by rui314** [comment]
It is because `.note.gnu.property` doesn't contain any interesting value. If for example your input object file's `.note.gnu.property` has `GNU_PROPERTY_X86_FEATURE_1_IBT`, it'll be propagated to the output.

**Comment by marxin** [comment]
Ok, but the same happens also with:

```
$ gcc a.c -mneeded -march=znver3
$ gcc-12 a.c -mneeded -march=znver3 -B ~/Programming/mold/objdir
$ readelf -n a.out

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 66687aadf862bd776c8fc18b8e9f8e2008971485

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0
```

while `ld` emits:
```
Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000030	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline, x86-64-v2, x86-64-v3
```

**Comment by marxin** [comment]
And one more comment, apparently `ld.bfd` (not `lld` nor `gold`) has the following option:
` -z x86-64-{baseline|v[234]} Mark x86-64-{baseline|v[234]} ISA level as needed`.

Is it something interesting for `mold`?

**Comment by rui314** [comment]
I don't know if we need to support `-z x86-64-{baseline|v[234]}` options, as I haven't got any bug report. It shouldn't be too hard to support them, though.

**Comment by marxin** [comment]
> while `ld` emits:
> 
> ```
> Displaying notes found in: .note.gnu.property
>   Owner                Data size 	Description
>   GNU                  0x00000030	NT_GNU_PROPERTY_TYPE_0
>       Properties: x86 ISA needed: x86-64-baseline, x86-64-v2, x86-64-v3
> ```

Hope this one is an interesting value, or am I wrong?

**Comment by marxin** [comment]
May I please ping this?

**Comment by rui314** [comment]
We'll take a look. @ishitatsuyuki If you have a bandwidth, please take this. Otherwise, let me know so that I can handle.

**Comment by ishitatsuyuki** [comment]
OK, I’ll take a look this afternoon. Sorry for the delay!

**Comment by rui314** [comment]
Thanks!

**Comment by ishitatsuyuki** [comment]
It looks like the issue is about `GNU_PROPERTY_X86_ISA_1_[USED|NEEDED]`, or more generally, the "OR" class of properties, and not the `.note.gnu.property` itself (which contains IBT and SHSTK and is already supported by mold). FWIW, lld doesn't support it either right now (property handling in lld was written by Rui and the logic in mold is roughly the same).

There's a concern here however due to the weird quirks these properties have: If any of the input files does not contain the respective property, gold [removes](https://github.com/bminor/binutils-gdb/blob/a715464cd2e25c8bf46190cc8bde9267c9ab6ac0/gold/x86_64.cc#L1654) it from the output.

The only documentation I could find, however, specifies it in the more naive way:

> A bit in the output pr_data field is set if it is set in any relocatable input pr_data fields. If all bits in the the output pr_data field are zero, this property should be removed from output.
> 
> If the bit is 1, some input relocatables have the feature.  If the bit is 0 or the property is missing, the info is unknown.

Could we have some more context on what is this ISA property used for, to determine if we should inherit the logic from gold or go for a more simplified one?

**Comment by rui314** [comment]
IIUC, these attributes are proposed and added to the x86 psABI by H.J. Lu who is the long time maintainer of the psABI and working for Intel. Unfortunately I don't know much about the rationale of these flags.

**Comment by ishitatsuyuki** [comment]
OK. On second thought I guess implementing the quirk isn't that hard after all (just need to default to `~0` in case of absent) so I'll go ahead with that way.
