### ISSUE TITLE
Memory access fault with v1.6.0_93_g28598c77

### ISSUE THREAD

**Issue by ms178** [rui314/mold#839]
Compiling mold with GCC 12.2.1 and the flags from below, I now see a memory access fault when compiling mold-git three times. While the first two compilations went fine, the third showed that error:

```
[ 12%] Built target git_hash
[ 13%] Building CXX object third-party/tbb/src/tbb/CMakeFiles/tbb.dir/rtm_rw_mutex.cpp.o
[ 14%] Linking C shared library mold-wrapper.so
collect2: schwerwiegender Fehler: ld mit Signal 11 [Speicherzugriffsfehler] beendet
Kompilierung beendet.
make[2]: *** [CMakeFiles/mold-wrapper.dir/build.make:97: mold-wrapper.so] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:282: CMakeFiles/mold-wrapper.dir/all] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 14%] Building CXX object third-party/tbb/src/tbb/CMakeFiles/tbb.dir/semaphore.cpp.o
[ 15%] Building CXX object third-party/tbb/src/tbb/CMakeFiles/tbb.dir/small_object_pool.cpp.o
```

GCC Flags used:

```
CFLAGS="-O3 -march=native -fno-semantic-interposition -falign-functions=32 -fipa-pta -flive-range-shrinkage -fno-math-errno -fno-trapping-math -mtls-dialect=gnu2 -feliminate-unused-debug-types -floop-nest-optimize -fgraphite-identity -fcf-protection=none -pipe -flto=auto -floop-parallelize-all -ftree-parallelize-loops=18 -fdevirtualize-at-ltrans -mharden-sls=none -funroll-loops -malign-data=cacheline -fomit-frame-pointer -mprefer-vector-width=256 -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
CXXFLAGS="$CFLAGS"
LDFLAGS="-Wl,-O3,--as-needed,-Bsymbolic-functions,-flto=auto -fopenmp -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
CCLDFLAGS="$LDFLAGS"
CXXLDFLAGS="$LDFLAGS"
ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -msse2avx -D__FMA__=1"
LTOFLAGS="-flto=auto"
```

Here is my PKGBUILD with my somewhat unusal (but still supported?) configuration:

[PKGBUILD.txt](https://github.com/rui314/mold/files/9891062/PKGBUILD.txt)

I should also add, that the binary size somewhat exploded, while it was +7 MB for the first run, it was +26 MB for the second run producing the faulty linker. All of the checks went through successfully though.

**Comment by ptr1337** [comment]
Ill get something equal, the package size just gets bigger with each compilation of mold. 
Compiling the completly same commit, with the same version of mold installed lead into a insane increase of it.
```
mold-git     v1.6.0_84_g460b4437-1  v1.6.0_84_g460b4437-1   14,18 MiB

Total Installed Size:  28,67 MiB
Net Upgrade Size:      14,18 MiB
```

Common cmake flags are used:
```
  -DCMAKE_BUILD_TYPE='None' \
  -DCMAKE_INSTALL_PREFIX='/usr' \
  -DCMAKE_INSTALL_LIBEXECDIR='lib' \
  -DMOLD_USE_SYSTEM_MIMALLOC=ON \
  -DMOLD_USE_SYSTEM_TBB=ON \
  -DMOLD_USE_MOLD=ON \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DMOLD_LTO=ON
```

**Comment by ms178** [comment]
Just tested the 84 revision, it is also broken.

**Comment by ms178** [comment]
To narrow it down further, the breaking change must come from Oct 27th, as 467b08a7829a10f1b420e71a3b69b80cbe2bea68 is fine.

**Comment by ms178** [comment]
@rui314 Good news, I found the culprit: c921959b819899d2245f8a7cc700fc9f12243673

**Comment by rui314** [comment]
OK, so it looks like it's the `strip` command who broke mold-produced executables. I'll fix the problem on mold's side.

**Comment by ptr1337** [comment]
@rui314 
 
 Issue seems still to be present. Compiling mold-got with mold 1.6.0 (stable release) is working fine. As soon mold gets compiled with latest commit, the install size is increasing from 12MB to 24MB.
 
 Should we add to the PKGBUILD:
` options=('strip')`
?

PKGBUILD used for mold-git:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mold-git

**Comment by rui314** [comment]
@ptr1337 Just to confirm, if you do strip mold-generated mold executable, its size increases from 12 MB to 24 MB, right? What is the size just after mold generates an output file?

**Comment by ptr1337** [comment]
Actually if compiling the PKGBUILD above, which uses mold to link mold following happens:

Compiling mold-git with GCC 12 + mold 1.6 stable:
14 MB package size

Compiling mold-git with GCC 12 + mold 1.6 latest git:
24 MB
(At this point mold-git does still compile correctly)

One more compile with the same as above, mold will break with the compilation of mold-git

I have just tested it, on compiling mold itself. I think a workaround would be simply to compile mold with ld or lld.

**Comment by ptr1337** [comment]
Oh, close this here again. Im sorry.
I defined a commit when I bisect the issue, latest git is working.
