### ISSUE TITLE
CMAKE_SYSTEM_PROCESSOR not adequate for toggling -latomic

### ISSUE THREAD

**Issue by glaubitz** [rui314/mold#843]
mold's build system currently uses `CMAKE_SYSTEM_PROCESSOR` to determine the host platform.

This mechanism fails when the system processor is not equal to the host system, i.e. the system mold is being built for.

For example, in Debian, `arm64` (ARMv9) machines are being used to built packages for `armel` (ARMV5TE). This means, that `CMAKE_SYSTEM_PROCESSOR` reports `arm64` and the following if-conditional is not executed and `-latomic` is not passed to the linker during build:

```cmake
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(riscv64|armv6|m68k)")
  target_link_libraries(mold PRIVATE atomic)
endif()
```

For this reason, the mold build for `armel` fails with [1]:

```
/usr/bin/ld: out/tbb/libs/libtbb.a(small_object_pool.cpp.o): undefined reference to symbol '__atomic_fetch_sub_8@@LIBATOMIC_1.0'
/usr/bin/ld: /usr/lib/arm-linux-gnueabi/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Thus, mold needs to use a different mechanism to determine the architecture of the host system, i.e. the system we are building mold for.

> [1] https://buildd.debian.org/status/fetch.php?pkg=mold&arch=armel&ver=1.6.0%2Bdfsg-1&stamp=1667201599&raw=0

**Comment by rui314** [comment]
I'm no expert of CMake, but https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html says that the variable is used for cross compilation in combination with the `CMAKE_TOOLCHAIN_FILE` variable (which I don't know much about). So I guess the use of `CMAKE_SYSTEM_PROCESSOR` itself is not wrong. Or, am I missing something?

**Comment by glaubitz** [comment]
According to https://stackoverflow.com/questions/70475665/what-are-the-possible-values-of-cmake-system-processor, `CMAKE_SYSTEM_PROCESSOR` contains the value of `uname -m` which is not really what we are looking for and only works if the build system is the same as the host system.

See also this CMake upstream discussion: https://gitlab.kitware.com/cmake/cmake/-/issues/22881

**Comment by rui314** [comment]
OK, so I think what we really should do is to determine whether a C++ program with `<atomic>` needs `-latomic` or not. It can be done with CMake.

**Comment by rui314** [comment]
Cool! I'll do the same. Thank you for sharing the links.

**Comment by glaubitz** [comment]
I think you can just use whatever atomic code you are using in mold as the test code for the `CHECK_CXX_SOURCE_COMPILES` test program. Should be relatively easy.

**Comment by rui314** [comment]
Please run `git pull` and try again. Thanks!

**Comment by glaubitz** [comment]
> Please run `git pull` and try again. Thanks!

Works as expected now. Thanks!
