### ISSUE TITLE
valgrind asserts `di->bss_svma + di->bss_size == svma`

### ISSUE THREAD

**Issue by ishitatsuyuki** [rui314/mold#847]
Reported by @marcluque (originally from #747).

Valgrind fails with the following assertion:
```
FAILED: CMakeFiles/sanitize /home/runner/work/yobemag/yobemag/CMakeFiles/sanitize 
cd /home/runner/work/yobemag/yobemag && valgrind --leak-check=yes --trace-children=yes ./yobemag_test
==3775== Memcheck, a memory error detector
==3775== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3775== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==3775== Command: ./yobemag_test
==3775== 

valgrind: m_debuginfo/readelf.c:2478 (vgModuleLocal_read_elf_debug_info): Assertion 'di->bss_svma + di->bss_size == svma' failed.
Segmentation fault (core dumped)
```

Full logs [here](https://github.com/Benzammour/yobemag/actions/runs/3373961077/jobs/5599075009).

**Comment by ishitatsuyuki** [comment]
@marcluque Could you try installing the latest version of mold via https://github.com/rui314/setup-mold and see if it still reproduces? Ubuntu 22.04 ships with 1.0.3 which is rather old.

**Comment by marcluque** [comment]
@ishitatsuyuki Thank you for opening the issue! You are right, the version is quite old. I'll give the action you linked a shot as soon as possible.

**Comment by marcluque** [comment]
Using the latest mold version fixes the issue! Thank you very much @ishitatsuyuki for the hint to use the action 👍🏼
This issue can be closed.
