### ISSUE TITLE
CMake integration

### ISSUE THREAD

**Issue by rui314** [rui314/mold#849]
Currently, each project has to add some code to their `CMakeLists.txt` to use mold. To lower the bar to start using mold, we probably should provide our own cmake module. It should be usable just by including and calling a function like this:

```
include(UseLinker)
target_use_linker(<target-name> mold)
```

We might even want to ask CMake to include such module to their distribution.

**Comment by jschueller** [comment]
the cmake way to do distribute cmake macros is to provide MoldConfig.cmake file containing with such a macro then downstream users might do:
```
find_package(Mold CONFIG)
mold_target_use_linker(...)
```
(this file should be installed in prefix/lib/cmake/mold for example, along with other mold files)

**Comment by gruenich** [comment]
CMake does not offer a built-in mechanism to change the linker. You have to set a variable for every language in use, and its value depends on the actual compiler, e.g., passing `-DCMAKE_CXX_FLAGS="-fuse-ld=mold"` to the CMake call for Clang. This problem occurs with gold or lld, too.

Someone should [file a feature request for CMake](https://gitlab.kitware.com/cmake/cmake/-/issues). If nobody is willing, I can do this.

**Comment by rui314** [comment]
@gruenich Please go ahead and file a feature request. Thanks!

**Comment by gruenich** [comment]
Done, I opened [issue 24254](https://gitlab.kitware.com/cmake/cmake/-/issues/24254). Feel free to commend and upvote!

**Comment by ADKaster** [comment]
It looks like CMake 3.29 will support a `CMAKE_LINKER_TYPE=mold` option, as the MR was just merged today. [gitlab.kitware.com/cmake/cmake/-/merge_requests/8861](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8861)

That MR closes the issue opened in https://github.com/rui314/mold/issues/849#issuecomment-1356834692

**Comment by rui314** [comment]
Great news! I think we can now mark this as "resolved".
