### ISSUE TITLE
ld.mold/ld64.mold symlinks missing from 1.6.0 release tarball

### ISSUE THREAD

**Issue by TerrorJack** [rui314/mold#852]
The `ld.mold`/`ld64.mold` symlinks were used to present in `bin/` of `1.5.1` release tarball of x86_64-linux, but they are missing in `1.6.0`. This was noticed only after `-DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold"` failed in a cmake based project.

**Comment by rui314** [comment]
It should be fixed at git head (https://github.com/rui314/mold/pull/848).
