### ISSUE TITLE
idea: design and implement export definition format for ELF linking like *.tbd files in MacOS

### ISSUE THREAD

**Issue by X547** [rui314/mold#857]
This will allow to link executables without having actual *.so libraries, allow to separate development packages from runtime packages, make SDKs with much smaller size, make cross-compilation easier.

Features needed to implement:
1. Allow linker to use export definition text files instead of compiled *.so libraries.
2. Generate export definition files from already compiled *.so libraries.
3. Generate stub *.so libraries for linkers that do not support export definition text files.

**Comment by rui314** [comment]
I can't remember right off the top of my head, but there's a tool to strip an .so file so that the .so file contains only .dynsym and other absolutely necessary sections. Such .so is not runnable anymore but still works as an input to the linker.

**Comment by X547** [comment]
Is it technically hard to add ability to read some text format when adding imported library symbols in Mold?

**Comment by rui314** [comment]
Technically it shouldn't be too hard. The question is whether a text format is better than a stripped-down .so or not. The former is human-readable but needs a change to the linker and we need to maintain the format to keep up with new ELF features. The latter is not human-readable but binary compatible with .so.

**Comment by X547** [comment]
Text export definition format can be managed by version control systems such as Git that helps ABI compatibility management for example.

**Comment by X547** [comment]
> I can't remember right off the top of my head, but there's a tool to strip an .so file

Can you give a link?

**Comment by rui314** [comment]
IIRC the name of the tool is `ifso` (short for "interface so") but I can't find a link.

**Comment by X547** [comment]
This: https://github.com/plotfi/llvm-project/commits/clang-ifso?

**Comment by rui314** [comment]
I thought so but looks like it's different.

**Comment by X547** [comment]
No longer interested in Mold because of licensing policy change.
