### ISSUE TITLE
installation bug on windows

### ISSUE THREAD

**Issue by RichardLuo0** [rui314/mold#860]
According to https://cmake.org/cmake/help/latest/envvar/DESTDIR.html, the [396 to 398](https://github.com/rui314/mold/blob/1f67ccfa203ee81cdd223501c01c8f7b9b3115f4/CMakeLists.txt#L396) should be rewritten to be compatible with windows. Otherwise, the installation will error when creating the new directory.

**Comment by ishitatsuyuki** [comment]
I wonder what would be the use case for installing on Windows right now? mold does not support PE yet, and symlinks are also kinda weird on Windows.

**Comment by RichardLuo0** [comment]
I will close the issue since there is no support for windows for now
