### ISSUE TITLE
Same build-id for different executables

### ISSUE THREAD

**Issue by simark** [rui314/mold#872]
Hi,

I'm building gdbserver on Ubuntu 22.04, x86-64, using:

    mold 1.7.0 (22f3b7ed243e7473be486064a18f7ac5a383e279; compatible with GNU ld)

For different commits of gdbserver, and therefore executables with different code sections, I get identical build-ids:

```
$ file gdbserver-*
gdbserver-2: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=38723a2e5e8a17aa7950dc008209944e898f69a7, for GNU/Linux 3.2.0, with debug_info, not stripped
gdbserver-3: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=38723a2e5e8a17aa7950dc008209944e898f69a7, for GNU/Linux 3.2.0, with debug_info, not stripped
gdbserver-4: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=38723a2e5e8a17aa7950dc008209944e898f69a7, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Not sure how to show in this bug that these files have different code in them but... they do.

```
$ readelf -S gdbserver-2 | grep text
  [21] .text             PROGBITS        0000000000136930 135930 1eeda2 00  AX  0   0 16
$ readelf -S gdbserver-3 | grep text
  [21] .text             PROGBITS        0000000000136b10 135b10 1ef0d2 00  AX  0   0 16
$ readelf -S gdbserver-4 | grep text
  [21] .text             PROGBITS        0000000000136bd0 135bd0 1ef1d2 00  AX  0   0 16
```

I can provide them if needed, they are 15M each, but it might be possible to reproduce this way:

- Clone https://sourceware.org/git/?p=binutils-gdb.git;a=summary
- Configure with `../path/to/binutils-gdb/configure LDFLAGS="-fuse-ld=mold"`
- `make all-gdbserver`
- copy the resulting `gdbserver/gdbserver` binary to `gdbserver-1`
- do the following change:
```
diff --git a/gdbserver/linux-low.cc b/gdbserver/linux-low.cc
index 0cbfeb99086a..903822cbe292 100644
--- a/gdbserver/linux-low.cc
+++ b/gdbserver/linux-low.cc
@@ -1731,9 +1731,9 @@ linux_process_target::status_pending_p_callback (thread_info *thread,
 struct lwp_info *
 find_lwp_pid (ptid_t ptid)
 {
+  int lwp = ptid.lwp () != 0 ? ptid.lwp () : ptid.pid ();
   thread_info *thread = find_thread ([&] (thread_info *thr_arg)
     {
-      int lwp = ptid.lwp () != 0 ? ptid.lwp () : ptid.pid ();
       return thr_arg->id.lwp () == lwp;
     });
```
- `make all-gdbserver`
- copy the resulting `gdbserver/gdbserver` binary to `gdbserver-2`
- compare gdbserver-1 and gdbserver-2

For me, they have the same build-id.  However, dumping `objdump -d -j .text gdbserver-N` shows very different output for both.  I'm pretty sure the build-ids should be different.

**Comment by rui314** [comment]
It's likely to have been caused by e228abfd5af19f5b6e4dfd1f6eb16642991321ae. Please run `git revert e228abfd5af19f5b6e4dfd1f6eb16642991321ae`, rebuild mold and try again. Does it fix your problem?

I looks like this is a major problem that warrants a new release.

**Comment by simark** [comment]
Doing the revert seems to fix it:

```
gdbserver-1: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4dbead6b01d005ced0be4b2a820de87bdde270eb, for GNU/Linux 3.2.0, with debug_info, not stripped
gdbserver-2: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0a662854778981cd3a9fef56e894f4f113fc7342, for GNU/Linux 3.2.0, with debug_info, not stripped
```
