### ISSUE TITLE
Mold fails to link OpenMW as of OpenMW comit 97e54c62

### ISSUE THREAD

**Issue by Ember2528** [rui314/mold#876]
As of [the latest](https://gitlab.com/OpenMW/openmw/-/commit/97e54c62943be11f98271ff6b75093f92cbb37ec) OpenMW mold fails to link the program with an error:
 `mold: fatal: library not found: collada-dom.-dp`

**Comment by ishitatsuyuki** [comment]
Could you provide information on how are you building the program and what environment are you building that from?

Alternatively having the linking command line would also help.

**Comment by Ember2528** [comment]
I'm on Arch Linux building the AUR package. After checking other linkers it looks like it is the AUR package that is currently broken and not a mold issue, my apologies.
