### ISSUE TITLE
Add support for object files built with -flto

### ISSUE THREAD

**Issue by nehaljwani** [rui314/mold#88]
The sample test case:
```cpp
$ cat a.cpp
#include <filesystem>

int main() {
  auto cwd = std::filesystem::current_path();
  return static_cast<int>(cwd.string().size());
}
```

My clang version:
```bash
$ clang++ --version
TRC clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/prefix/bin
```
My mold version:
```bash
$ /tmp/m/bin/mold --version
mold 0.9.2 (6695c49379d6d053ea37ba716bf94acb5c4767aa; compatible with GNU ld and GNU gold)
```

It doesn't compile 😭 
```bash
$ clang++ a.cpp -std=c++17 -fuse-ld=/tmp/m/bin/mold -stdlib=libc++ -lc++fs
mold: undefined symbol: /tmp/a-d457e4.o: std::__1::__fs::filesystem::__current_path(std::__1::error_code*)
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps it was using the wrong libc++fs? Try full path? 😭 
```bash
$ clang++ a.cpp -std=c++17 -fuse-ld=/tmp/m/bin/mold -stdlib=libc++ /path/to/prefix/lib/libc++fs.a
mold: undefined symbol: /tmp/a-d76e7d.o: std::__1::__fs::filesystem::__current_path(std::__1::error_code*)
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

Let's just use the object files directly! 😭 
```bash
$ ar x /path/to/prefix/lib/libc++fs.a

$ clang++ a.cpp -std=c++17 -fuse-ld=/tmp/m/bin/mold directory_iterator.cpp.o int128_builtins.cpp.o operations.cpp.o
mold: directory_iterator.cpp.o: looks like this is an LLVM bitcode, but mold does not support LTO
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps this has something to do with the fact that I build LLVM libraries with `-DLLVM_ENABLE_LTO=ON` and there is no shared library for `c++fs`.

As an addendum: Even gold and bfd error on this one, but lld is happy 😃

**Comment by rui314** [comment]
mold doesn't support LTO yet, so you can't use mold for object files or archive files built with `-flto`. mold skips archive files if it doesn't contain object files that it can understand, so I believe libc++fs.a (which contains object files for LTO) are just skipped. If you force to link against it by passing an object file to mold, it reports an error just like you saw in the last example.

This isn't an error. mold should eventually support LTO, but for now, it is just unsupported.

**Comment by nehaljwani** [comment]
Thank you for clarifying. I have one query though: Why does mold not error out instead of skipping the archive file? Is this a required behavior to be in parity with other linkers?

**Comment by rui314** [comment]
That behavior is required to be compatible with GNU linkers. Both GNU BFD and gold behave that way.

**Comment by Logarithmus** [comment]
> mold doesn't support LTO yet, so you can't use mold for object files or archive files built with `-flto`. mold skips archive files if they don't contain object files that it can understand, so I believe libc++fs.a (which contains object files for LTO) are just skipped. If you force to link against it by passing an object file to mold, it reports an error just like you saw in the last example.
> 
> This isn't an error. mold should eventually support LTO, but for now, it is just unsupported.

How much work would be to add `-flto=full` & `-flto=thin` support on the `mold` side? I believe the majority of LTO work is done by the compiler, am I wrong?

**Comment by rui314** [comment]
I'm working on supporting `-flto` (which I believe means `-flto=full`) using the linker plugin mechanism that is used by GNU linkers. It looks like it's not too hard to support it. I'm not sure what we need to do to support Thin LTO.

**Comment by C43H66N12O12S2** [comment]
Is there any progress on this? Looking forward to the day when I can replace LLD with Mold as my default linker.

**Comment by rui314** [comment]
No progress on this particular issue. I tried to use LLVM/GCC's LTO plugins, but unfortunately the linker plugin API wasn't as easy to use as I hoped. In the meantime, please use mold in usual build cycles and lld in production LTO builds.

**Comment by rui314** [comment]
https://github.com/rui314/mold/issues/181
