### ISSUE TITLE
warning: no debug symbols in executable (-arch arm64)

### ISSUE THREAD

**Issue by invrainbow** [rui314/mold#888]
I'm using mold 1.5.1 on MacOS M1, installed by `brew install mold`.

I'm using make and clang to compile. I swapped in mold with `-fuse-ld=mold`. This compiles, but at the end it prints out

```
warning: no debug symbols in executable (-arch arm64)
```

This warning appears to be accurate, as when I debug I'm no longer able to set breakpoints at certain places, etc. However, a `<binary>.dSYM` directory is still created.

Edit: I have `-g` enabled and if I swap mold back out, debug symbols are generated without any issue.

**Comment by rui314** [comment]
Yup, mold/macOS is just incomplete. We'll fix it before 2.0.

**Comment by drewcassidy** [comment]
Just spent hours trying to figure out why my rust breakpoints were never being hit before I remembered installing Mold 😅 Good to know its coming soon

**Comment by drewcassidy** [comment]
Nevermind, guess I'm done using mold for good if you're going to paywall Mac support
