### ISSUE TITLE
`strip` complains that sh_link not set for section `.ARM.exidx'

### ISSUE THREAD

**Issue by ericriff** [rui314/mold#889]
I'm trying to integrate mold to a project I'm working on which targets a couple of platforms. When I target arm32, the resulting binaries can't be stripped. I get:
```
arm-poky-linux-gnueabi-strip a.out
arm-poky-linux-gnueabi-strip: stXenxod: warning: sh_link not set for section `.ARM.exidx'
[1]    452210 segmentation fault (core dumped)   a.out
```
Unfortunately I can't share much on that since it comes from a private repo, so this might be hard to debug.
I tried to reproduce this with some public toolchain and a simple hello world and I get a segfault as well but without the `.ARM.exidx` message.
Toolchain: [arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz](https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz?rev=65520e9cdf324eca9c02f5302c904fa4&hash=8CA03541272BFFD80F8834A3D3B4CF12E9B6C61A)
Code:
```c++
#include <iostream>

int main(){
    std::cout << "Hello world" << std::endl;
    return 0;
}
```
Compiled with:
```
arm-none-linux-gnueabihf-g++ -B/usr/local/libexec/mold main.cpp -L../arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/arm-none-linux-gnueabihf/libc/
```
By the way that extra `-L` line is annoying. Is there a reason for it? Otherwise `mold` says it can't find `libc`. So far this extra line + having to remove `--no-map-whole-files` have been the only changes I had to do to make mold a drop in replacement on my codebase.
```
  ^ library not found: /lib/libc.so.6
```
If I try to strip:
```
arm-none-linux-gnueabihf-strip a.out                                                                                                                           
[1]    458228 segmentation fault (core dumped)  arm-none-linux-gnueabihf-strip a.out
```

I'm using `mold 1.6` 
```
readelf -p .comment a.out

String dump of section '.comment':
  [     0]  mold 1.6.0 (323ad30e25c2c81efdb07ab76601a119335a40c8; compatible with GNU ld)
  [    4e]  GCC: (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
```

**Comment by ericriff** [comment]
I missed this, and I did look. https://github.com/rui314/mold/issues/801
Shame on me. 
I'm going to try again with the latest release and see how it goes.

**Comment by ericriff** [comment]
Indeed the coredump is fixed on 1.7.1. The hello world I posted above with the open source toolchain works just fine. Regardless my private code continues to print that weird warning, but at least it doesn't crash.
```
 readelf -p .comment a.out

String dump of section '.comment':
  [     0]  GCC: (GNU) 11.3.0
  [    13]  mold 1.7.1 (d4bc87bfe12515ade842cb28553b974608c88adc; compatible with GNU ld)

```

```
arm-poky-linux-gnueabi-strip a.out                        
arm-poky-linux-gnueabi-strip: stn00QKE: warning: sh_link not set for section `.ARM.exidx'
```
I have no idea what this means.

**Comment by rui314** [comment]
I thought that I fxied that `strip`'s warning in 610042a8e927106cb2d852fba2a90faa0d0e050f. Does this happen with 1.7.1? If so, can you upload your executable (before and after `strip`) so that I can take a look?

**Comment by ericriff** [comment]
Yes, it does happen with 1.7.1.
[arm32App.zip](https://github.com/rui314/mold/files/10076684/arm32App.zip)

**Comment by rui314** [comment]
In my environment, `strip` doesn't complain anything.

```
$ arm-linux-gnueabihf-strip a_unstripped.out
$
```

Can you run `strip` on your `a_unstripped.out` by hand to see if it complains on the structure of the given file?

Also, what is `stn00QKE` file in the following message?

```
arm-poky-linux-gnueabi-strip: stn00QKE: warning: sh_link not set for section `.ARM.exidx'
```

**Comment by ericriff** [comment]
So when I use the open source toolchain listed above, the warning is not there. But when I use our internal toolchains (generated by `yocto` or `ABE`), then the warning shows up.
This is with an ABE-built toolchain
```
$ arm-none-linux-gnueabi-g++ main.cpp -B /usr/local/libexec/mold
$ readelf -p .comment a.out

String dump of section '.comment':
  [     1]  mold 1.7.1 (d4bc87bfe12515ade842cb28553b974608c88adc; compatible with GNU ld)
  [    4f]  GCC: (GNU) 10.2.1 20201103
$ arm-none-linux-gnueabi-strip a.out
arm-none-linux-gnueabi-strip: st776y8e: warning: sh_link not set for section `.ARM.exidx
``` 

And this is with a yocto-built toolchain:
```
$ arm-poky-linux-gnueabi-g++ -B/usr/local/libexec/mold main.cpp -L path-to-libc --sysroot=path-to-sysroot -mfpu=neon -march=armv7-a -mfloat-abi=hard -mthumb -mtune=cortex-a7
$ readelf -p .comment a.out

String dump of section '.comment':
  [     0]  GCC: (GNU) 11.3.0
  [    13]  mold 1.7.1 (d4bc87bfe12515ade842cb28553b974608c88adc; compatible with GNU ld)
arm-poky-linux-gnueabi-strip a.out
arm-poky-linux-gnueabi-strip: strW9NIG: warning: sh_link not set for section `.ARM.exidx'
```

Each toolchain targets a different arm32 platform, notable differences are that one is soft float and the other one is hard float.
I have no idea what those `st776y8e` and `strW9NIG` are. 

What do you mean by running strip by hand?

**Comment by ericriff** [comment]
These weird strings change each time.
```
arm-poky-linux-gnueabi-strip: stBoQbct: warning: sh_link not set for section `.ARM.exidx'
```

**Comment by rui314** [comment]
Isn't your internal toolchain open-source?

**Comment by ericriff** [comment]
I managed to reproduce it with the open source version we're basing our toolchain, the one I mentioned on the comment above.
https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz?revision=d0b90559-3960-4e4b-9297-7ddbc3e52783&rev=d0b9055939604e4b92977ddbc3e52783&hash=C3D4D1D828D6F933760715F509D3762118AA1D84

```
$ ../gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ main.cpp -B /usr/local/libexec/mold 
$ readelf -p .comment a.out

String dump of section '.comment':
  [     0]  GCC: (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.2.1 20201103
  [    5e]  mold 1.7.1 (d4bc87bfe12515ade842cb28553b974608c88adc; compatible with GNU ld)

$ ../gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-strip a.out 
../gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-strip: stXgoh4T: warning: sh_link not set for section `.ARM.exidx'
```

**Comment by ericriff** [comment]
Maybe something changed on binutils 2.36?
```
# No warning with this toolchain
../gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-strip --version
GNU strip (GNU Toolchain for the A-profile Architecture 10.3-2021.07 (arm-10.29)) 2.36.1.20210621

# Warning present with this toolchain
../gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ --version                           
arm-none-linux-gnueabihf-g++ (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.2.1 20201103

# Warning present with this toolchain (yocto)
arm-poky-linux-gnueabi-strip --version
GNU strip (GNU Binutils) 2.34.0.20200220
```

**Comment by rui314** [comment]
Could be. Do you mind if I ask you to build binutils 2.34 and 2.36 from source to see if your hypothesis is correct?

**Comment by ericriff** [comment]
Indeed something changed between 2.35 and 2.36. The warning is gone in 2.36.
```
./binutils/strip-new --version                        
GNU strip (GNU Binutils) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.

./binutils/strip-new ~/Documents/moldBug/a.out
./binutils/strip-new: /home/eriff/Documents/moldBug/stKV9z3E: warning: sh_link not set for section `.ARM.exidx'


./binutils/strip-new --version                        
GNU strip (GNU Binutils) 2.35
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.

./binutils/strip-new ~/Documents/moldBug/a.out
./binutils/strip-new: /home/eriff/Documents/moldBug/stR05Wd5: warning: sh_link not set for section `.ARM.exidx'

./binutils/strip-new --version                        
GNU strip (GNU Binutils) 2.36
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.

 ./binutils/strip-new ~/Documents/moldBug/a.out
```
After each strip I restored `a.out` to its unstripped stage, just in case you're wondering.

I used these tarballs 
https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.gz
https://ftp.gnu.org/gnu/binutils/binutils-2.35.tar.gz
https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.gz

And I built them with
```
./configure --target=arm-none-linux --disable-nls --disable-multilib --disable-gdb
make all -j12
```

**Comment by ericriff** [comment]
So is this something that can be addressed from the `mold` side? Or the conclusion is that mold is not fully compatible with arm32 + bintuils < 2.36 ?

**Comment by rui314** [comment]
I think that we might be able to do something on our side, I just didn't have enough time to investigate.
