### ISSUE TITLE
Support option --no-keep-memory

### ISSUE THREAD

**Issue by sajcho** [rui314/mold#894]
Hi.
You can add the --no-keep-memory option.
It will help a lot on ARM devices.

sajcho

**Comment by rui314** [comment]
So I guess you are experience an out of virtual address space error? Unfortunately, mold uses mmap'ed IO exclusively, and it is very hard to convert them to a read/write-based IO.

**Comment by sajcho** [comment]
I had no idea how hard it was.
It would help those small devices a lot.
Thanks for the information.
