### ISSUE TITLE
Add mode where object files are not copied to the executable and instead memory mapped by the executable

### ISSUE THREAD

**Issue by kytans** [rui314/mold#897]
mold is very fast, but is still limited by the fact that it needs to copy object files to the executable files, which also results in extra disk space consumption.

However, another possibility is to not copy object files to the executable and instead write relocated data to the object files themselves, write an uninitialized section/phdr to the executable and have the executable memory map the object file to the place the data would have via linker-generated startup code. This should be faster since it saves disk I/O for disk blocks without relocations and also saves disk space.

The object files themselves should be reflinked (or hardlinked if reflinks are not supported) to a separate directory and the executable should get them from there so that recompiling or removing the original object files them doesn't break the executable.

**Comment by rui314** [comment]
I don't think it's technically doable. At least on Unix, you can only create a hardlink as as whole, and you can't create a single file from other multiple files by stitching them together. In addition to that, input object files aren't always writable. For example, libc.a is almost always read-only.

**Comment by kytans** [comment]
The idea is not to create a single file, but rather compose it in memory at runtime by adding code to the executable that mmaps the object files over parts of the executable where the data would have been copied. Shared or otherwise non-writable object files would still need to be copied and obviously this is only suitable for debug builds.

**Comment by rui314** [comment]
There are a few practical issues there in that approach:

- opening lots of files and mmap'ing them are very slow, so we wouldn't want to do that on each process startup, and
- mmap works on page granularity, so we need to insert lots of paddings between code/data for each input file, which probably bloats the process size in the order of 10x.

**Comment by Alcaro** [comment]
> The idea is not to create a single file, but rather compose it in memory at runtime by adding code to the executable that mmaps the object files over parts of the executable where the data would have been copied.

That sounds like a nightmare for programs that want to inspect the executable before running it, like a debugger trying to write an int3 breakpoint to the start of main(). It also breaks if you delete the object files before running the program, or move the executable into a sandbox; I'd expect several CI systems to do exactly that.

> At least on Unix, you can only create a hardlink as as whole, and you can't create a single file from other multiple files by stitching them together.

Correct on Unix and POSIX, but the Linux-only reflink feature https://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html can do that. It's copy-on-write, so it doesn't need any particular permissions to libc.a, and it looks like a perfectly normal file to everything else, so the above problems are gone.

The drawback is it only works on some filesystems (works on XFS and btrfs, but not ext4), and it only works with object files in the same partition as the output executable. And I believe it still requires page granularity at minimum, but bloating the debug builds is fine.
