### ISSUE TITLE
Docker dist.sh failed

### ISSUE THREAD

**Issue by Rose1917** [rui314/mold#905]
I try to use your docker method to build mold. 
But when I run sudo ./dist.sh
I got the following error report.

![image](https://user-images.githubusercontent.com/49433992/205883928-488cc686-f158-449a-8e10-87c565f9ec9b.png)

Well, as for as I know, the container rui314/mold-builder should already has all the dependcies, of course includes the clang itself.
So, why it still reports clangd missing?

**Comment by ishitatsuyuki** [comment]
Can reproduce, not sure if it's the image or the script that is broken.

**Comment by rui314** [comment]
It should be fixed by the above change.
