### ISSUE TITLE
error: Installed (but unpackaged) file(s) found: /usr/bin/ld

### ISSUE THREAD

**Issue by marxin** [rui314/mold#910]
Started likely with a90e7ac782776a5737c37d25617e0a2af41bcfed where mold now installs `/usr/bin/ld` file:
[bl.txt](https://github.com/rui314/mold/files/10207709/bl.txt)

**Comment by ZhongRuoyu** [comment]
It was actually `ld.` with a dot:

```plaintext
[   61s] Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/abuild/rpmbuild/BUILDROOT/mold-1.999.999+git.20221212.998c7af-0.x86_64
[   61s] error: Installed (but unpackaged) file(s) found:
[   61s]    /usr/bin/ld.
[   61s] 
[   61s] RPM build errors:
[   61s]     Installed (but unpackaged) file(s) found:
[   61s]    /usr/bin/ld.
```

`MOLD_PRODUCT_NAME` is replaced by `MOLD_IS_SOLD`, so now `ld.${MOLD_PRODUCT_NAME}` evaluates to `ld.`. Should be fixed by #911.
