### ISSUE TITLE
Would you add OBS badge to README

### ISSUE THREAD

**Issue by marxin** [rui314/mold#922]
I'm doing Daily snapshots of mold in Open Build Service (for 8 targets) and the OBS can newly present a Badge:
[![build result](https://build.opensuse.org/projects/home:marxin:mold/packages/mold/badge.svg?type=percent)](https://build.opensuse.org/package/show/home:marxin:mold/mold)

Would you approve a PR where I'll add it to the `README.md`?

**Comment by rui314** [comment]
I think that's useful to show the badge somewhere in the README. It's green if mold builds fine and all tests pass on SuSE, right?

**Comment by marxin** [comment]
> It's green if mold builds fine and all tests pass on SuSE, right?

Yes, exactly. I've just created a PR.
