### ISSUE TITLE
missing Roadmap

### ISSUE THREAD

**Issue by theuserbl** [rui314/mold#927]
I missing the roadmap.

If there wouldn't existing one, I wouldn't ask.
But at
https://github.com/rui314/mold/issues/190
is mentioned, that support for the Windows target is planned for mold 3.0.

Currently we have 1.8.0.
Between them is 2.0.

So, what is planned for mold 2.0 ?
And what except of the Windows support is planned for mold 3.0 ?

What's the planned roadmap?

**Comment by Alcaro** [comment]
When that was posted, the lead feature for 2.0 was declaring macOS support stable and not alpha quality.

But since then, mold was split into [sold](https://github.com/bluewhalesystems/sold), and I don't know what the new plan is.

**Comment by rui314** [comment]
I'll probably bump the mold version to 2.0 when _sold_ is ready for macOS for the ease of version management, so nothing is particularly planned for 2.0 for mold. So is for 3.0.
