### ISSUE TITLE
relocation R_ARM_THM_JUMP19 out of range

### ISSUE THREAD

**Issue by jpalus** [rui314/mold#928]
Linking `ffmpeg` on `armv7` with `mold 1.8.0` fails with:
```
mold: error: libavresample/arm/audio_convert_neon.o:(.text): relocation R_ARM_THM_JUMP19 against ff_conv_fltp_to_s16_2ch_neon out of range: -1342246062 is not in [-524288, 524288)
```

**Comment by rui314** [comment]
Does applying the following patch to ffmpeg fix your issue?

```
diff --git a/libswresample/arm/audio_convert_neon.S b/libswresample/arm/audio_convert_neon.S
index 085d50aafa..cbd305e5ac 100644
--- a/libswresample/arm/audio_convert_neon.S
+++ b/libswresample/arm/audio_convert_neon.S
@@ -135,10 +135,12 @@ function swri_oldapi_conv_fltp_to_s16_nch_neon, export=1
         cmp             r3,  #2
         itt             lt
         ldrlt           r1,  [r1]
-        blt             .L_swri_oldapi_conv_flt_to_s16_neon
-        beq             .L_swri_oldapi_conv_fltp_to_s16_2ch_neon
+        bge             1f
+        blt             2f
+        b               .L_swri_oldapi_conv_fltp_to_s16_2ch_neon
+2:      b               .L_swri_oldapi_conv_flt_to_s16_neon

-        push            {r4-r8, lr}
+1:      push            {r4-r8, lr}
         cmp             r3,  #4
         lsl             r12, r3,  #1
```

**Comment by jpalus** [comment]
With above patch compilation fails since `itt lt` is expected to be followed by 2 `lt` instructions while above `ldrlt` is followed by `bge`. If I swap `bge` and `blt` so order is correct then linking still fails in the same way:
```
mold: error: libavresample/arm/audio_convert_neon.o:(.text): relocation R_ARM_THM_JUMP19 against ff_conv_fltp_to_s16_2ch_neon out of range: -1342246062 is not in [-524288, 524288)
```

**Comment by rui314** [comment]
Can you upload your libavresample/arm/audio_convert_neon.o?

**Comment by jpalus** [comment]
Sure attached:
[audio_convert_neon.zip](https://github.com/rui314/mold/files/10308296/audio_convert_neon.zip)

Though in the meantime I see I was wrong, linking does not fail anymore with the patch. It's just that there are two similar files in two similar directories. Issue was originally raised for `lib sw resample`, while after the patch it's `lib av resample` that is failing. `lib sw resample` linked fine with the fix.

**Comment by jpalus** [comment]
Confirmed that with above patch ffmpeg links fine.

**Comment by rui314** [comment]
I sent the patch to the ffmpeg-devel mailing list: http://ffmpeg.org/pipermail/ffmpeg-devel/2023-January/305424.html

**Comment by rui314** [comment]
How do you exactly build ffmpeg? Please paste the entire command line you passed to `configure`.

**Comment by rui314** [comment]
Also let me know which version of ffmpeg. Is that git head or some release version?

**Comment by rui314** [comment]
I'll retract the patch I sent to ffmpeg and close this issue as resolved, as it's been resolved in upstream.
