### ISSUE TITLE
net-misc/spice-gtk does not compile

### ISSUE THREAD

**Issue by Slaviusz** [rui314/mold#931]
net-misc/spice-gtk-0.41-r1 ends with compilation error on Gentoo. Compiling with excluded mold (/etc/portage/package.env/) works fine.

Probably add it to the list of problematic packages.

**Comment by marxin** [comment]
Can you please provide an error message you get?

**Comment by Slaviusz** [comment]
```
FAILED: src/libspice-client-glib-2.0.so.8.8.1
x86_64-pc-linux-gnu-gcc  -o src/libspice-client-glib-2.0.so.8.8.1 src/libspice-client-glib-2.0.so.8.8.1.p/meson-generated_.._spice-marshal.c.o src/libspice-client-glib-2.0.so.8.8.1.p/meson-generated_.._spice-glib-enums.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-cursor.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-inputs.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-main.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-playback.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-port.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-record.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-smartcard.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-usbredir.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-webdav.c.o src/libspice-client-glib-2.0.so.8.8.1.p/qmp-port.c.o src/libspice-client-glib-2.0.so.8.8.1.p/smartcard-manager.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-audio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-channel.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-client.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-option.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-session.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-util.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-device-manager.c.o src/libspice-client-glib-2.0.so.8.8.1.p/bio-gio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-base.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display-gst.c.o src/libspice-client-glib-2.0.so.8.8.1.p/client_sw_canvas.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-glz.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-jpeg.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-zlib.c.o src/libspice-client-glib-2.0.so.8.8.1.p/gio-coroutine.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-file-transfer-task.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-glib-main.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-gstaudio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-uri.c.o src/libspice-client-glib-2.0.so.8.8.1.p/vmcstream.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display-mjpeg.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-acl-helper.c.o src/libspice-client-glib-2.0.so.8.8.1.p/continuation.c.o src/libspice-client-glib-2.0.so.8.8.1.p/coroutine_ucontext.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usbutil.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-backend.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-device-cd.c.o src/libspice-client-glib-2.0.so.8.8.1.p/cd-scsi.c.o src/libspice-client-glib-2.0.so.8.8.1.p/cd-usb-bulk-msd.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libspice-client-glib-2.0.so.8 -O3 -march=native -pipe -fomit-frame-pointer -flto -fuse-ld=mold -Wl,-O1 -Wl,--as-needed subprojects/spice-common/common/libspice-common-client.a subprojects/spice-common/common/libspice-common.a -export-symbols /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file -lm /usr/lib64/libglib-2.0.so /usr/lib64/libpixman-1.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libopus.so /usr/lib64/libcacard.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libjpeg.so /usr/lib64/libz.so /usr/lib64/libjson-glib-1.0.so /usr/lib64/libgstreamer-1.0.so /usr/lib64/libgstbase-1.0.so /usr/lib64/libgstapp-1.0.so /usr/lib64/libgstaudio-1.0.so /usr/lib64/libgstvideo-1.0.so /usr/lib64/libusbredirparser.so /usr/lib64/libusbredirhost.so /usr/lib64/libusb-1.0.so /usr/lib64/libgirepository-1.0.so /usr/lib64/liblz4.so -Wl,--end-group
mold: fatal: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file:1: spice_audio_get
                                                                                                 ^ unknown linker script token
```

**Comment by marxin** [comment]
Can you please paste the output of `/var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file` ?

**Comment by Slaviusz** [comment]
```
spice_audio_get
spice_audio_get_type
spice_audio_new
spice_channel_connect
spice_channel_destroy
spice_channel_disconnect
spice_channel_event_get_type
spice_channel_flush_async
spice_channel_flush_finish
spice_channel_get_error
spice_channel_get_type
spice_channel_new
spice_channel_open_fd
spice_channel_set_capability
spice_channel_string_to_type
spice_channel_test_capability
spice_channel_test_common_capability
spice_channel_type_to_string
spice_client_error_quark
spice_cursor_channel_get_type
spice_cursor_shape_get_type
spice_display_change_preferred_compression
spice_display_change_preferred_video_codec_type
spice_display_channel_change_preferred_compression
spice_display_channel_change_preferred_video_codec_type
spice_display_channel_change_preferred_video_codec_types
spice_display_channel_get_gl_scanout
spice_display_channel_get_primary
spice_display_channel_get_type
spice_display_channel_gl_draw_done
spice_display_get_gl_scanout
spice_display_get_primary
spice_display_gl_draw_done
spice_file_transfer_task_cancel
spice_file_transfer_task_get_filename
spice_file_transfer_task_get_progress
spice_file_transfer_task_get_total_bytes
spice_file_transfer_task_get_transferred_bytes
spice_file_transfer_task_get_type
spice_get_option_group
spice_gl_scanout_free
spice_gl_scanout_get_type
spice_g_signal_connect_object
spice_inputs_button_press
spice_inputs_button_release
spice_inputs_channel_button_press
spice_inputs_channel_button_release
spice_inputs_channel_get_type
spice_inputs_channel_key_press
spice_inputs_channel_key_press_and_release
spice_inputs_channel_key_release
spice_inputs_channel_motion
spice_inputs_channel_position
spice_inputs_channel_set_key_locks
spice_inputs_key_press
spice_inputs_key_press_and_release
spice_inputs_key_release
spice_inputs_lock_get_type
spice_inputs_motion
spice_inputs_position
spice_inputs_set_key_locks
spice_main_agent_test_capability
spice_main_channel_agent_test_capability
spice_main_channel_clipboard_selection_grab
spice_main_channel_clipboard_selection_notify
spice_main_channel_clipboard_selection_release
spice_main_channel_clipboard_selection_request
spice_main_channel_file_copy_async
spice_main_channel_file_copy_finish
spice_main_channel_get_type
spice_main_channel_request_mouse_mode
spice_main_channel_send_monitor_config
spice_main_channel_update_display
spice_main_channel_update_display_enabled
spice_main_channel_update_display_mm
spice_main_clipboard_grab
spice_main_clipboard_notify
spice_main_clipboard_release
spice_main_clipboard_request
spice_main_clipboard_selection_grab
spice_main_clipboard_selection_notify
spice_main_clipboard_selection_release
spice_main_clipboard_selection_request
spice_main_file_copy_async
spice_main_file_copy_finish
spice_main_request_mouse_mode
spice_main_send_monitor_config
spice_main_set_display
spice_main_set_display_enabled
spice_main_update_display
spice_main_update_display_enabled
spice_playback_channel_get_type
spice_playback_channel_set_delay
spice_port_channel_event
spice_port_channel_get_type
spice_port_channel_write_async
spice_port_channel_write_finish
spice_port_event
spice_port_write_async
spice_port_write_finish
spice_qmp_port_get
spice_qmp_port_get_type
spice_qmp_port_query_status_async
spice_qmp_port_query_status_finish
spice_qmp_port_vm_action_async
spice_qmp_port_vm_action_finish
spice_qmp_status_get_type
spice_qmp_status_ref
spice_qmp_status_unref
spice_record_channel_get_type
spice_record_channel_send_data
spice_record_send_data
spice_session_connect
spice_session_disconnect
spice_session_get_channels
spice_session_get_proxy_uri
spice_session_get_read_only
spice_session_get_type
spice_session_has_channel_type
spice_session_is_for_migration
spice_session_migration_get_type
spice_session_new
spice_session_open_fd
spice_session_verify_get_type
spice_set_session_option
spice_smartcard_channel_get_type
spice_smartcard_manager_get
spice_smartcard_manager_get_readers
spice_smartcard_manager_get_type
spice_smartcard_manager_insert_card
spice_smartcard_manager_remove_card
spice_smartcard_reader_get_type
spice_smartcard_reader_insert_card
spice_smartcard_reader_is_software
spice_smartcard_reader_remove_card
spice_uri_get_hostname
spice_uri_get_password
spice_uri_get_port
spice_uri_get_scheme
spice_uri_get_type
spice_uri_get_user
spice_uri_set_hostname
spice_uri_set_password
spice_uri_set_port
spice_uri_set_scheme
spice_uri_set_user
spice_uri_to_string
spice_usb_device_get_description
spice_usb_device_get_libusb_device
spice_usb_device_get_type
spice_usb_device_manager_can_redirect_device
spice_usb_device_manager_connect_device_async
spice_usb_device_manager_connect_device_finish
spice_usb_device_manager_disconnect_device
spice_usb_device_manager_disconnect_device_async
spice_usb_device_manager_disconnect_device_finish
spice_usb_device_manager_get
spice_usb_device_manager_get_devices
spice_usb_device_manager_get_devices_with_filter
spice_usb_device_manager_get_type
spice_usb_device_manager_is_device_connected
spice_usb_device_manager_is_redirecting
spice_usb_device_manager_allocate_device_for_file_descriptor
spice_usbredir_channel_get_type
spice_util_get_debug
spice_util_get_version_string
spice_util_set_debug
spice_uuid_to_string
spice_webdav_channel_get_type
```

**Comment by marxin** [comment]
Seems to me the `-export-symbols` is a `libtool` option:

```
-export-symbols symfile
Tells the linker to export only the symbols listed in symfile. The symbol file should end in .sym and must contain the name of one symbol per line. This option has no effect on some platforms. By default all symbols are exported.
```

which should be converted by `libtool` into something like:
`... -Wl,-retain-symbols-file", "-Wl,path.sym ...`

**Comment by Slaviusz** [comment]
It seems to me then the ebuild file is to blame? Unfortunately I'm not the package maintainer.

**Comment by marxin** [comment]
Dunno. I'm not a Gentoo person, but I guess @rui314 can reproduce the ebuild build?

**Comment by rui314** [comment]
I wil try

**Comment by rui314** [comment]
It indeed failed to build, but it's not mold's fault. `-export-symbols` isn't a linker's option; no linker has such option. mold _and_ GNU ld interpret

`-export-symbols /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file`

as

the single-letter option `-e` followed by `xport-symbols`, followed by an unrelated filename `/var/tmp/...`. `-e` specifies the entry point name (which is usually `_start`), but since you are creating a shared library, it doesn't matter. So `xport-symbols` happens to not cause any failure.

GNU ld _and_ mold interprets a text file as a linker script, so the given filename is interpreted as a linker script. That command fails even with GNU ld (with `-fuse-ld=bfd`) as shown below.

```
.../spice-gtk-0.39/src/spice-glib-sym-file: file format not recognized; treating as linker script
.../spice-glib-sym-file:2: syntax error
```

So, the command line that spice-gtk constructed to build the shared library is just broken. I don't know how spice-gtk construct it, but I think it should be addressed by them rather than by me. Can you report a bug to spice-gtk?

**Comment by Slaviusz** [comment]
@rui314 Thank You very much for an extensive analysis. I will do my best to relay the information to the package maintainer. Closing for now.

**Comment by Alcaro** [comment]
Shared libraries can have entry points (for example glibc libc.so.6 - it just prints version, but it counts). -e nonexistent_symbol and/or -e not-a-valid-c-identifier should probably be an error or warning, even on them.

But I completely agree that this specific error is not a mold bug.

(Also reposting the upstream bug report, email watchers don't see edits. https://bugs.gentoo.org/888705)

**Comment by thesamesam** [comment]
This would be an issue to report to spice-gtk (or possibly meson, I haven't looked at what the issue is here), it's not a packaging issue.

**Comment by Slaviusz** [comment]
You're right. I went through spice/spice-gtk bug tracker finding no related bug and assumed it must be Gentoo's packaging doing something. I went through the Gentoo ebuild recently and although they discuss in comments hijacking the build process to enable some features they basically just use it as it is upstream at the moment.
So appropriately I created a bug directly in spice-gtk  https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/169

**Comment by eli-schwartz** [comment]
> net-misc/spice-gtk-0.41-r1 ends with compilation error on Gentoo. Compiling with excluded mold (/etc/portage/package.env/) works fine.

This bug report has no actionable information.

> Can you please provide an error message you get?


> ```
> FAILED: src/libspice-client-glib-2.0.so.8.8.1
> x86_64-pc-linux-gnu-gcc -o src/libspice-client-glib-2.0.so.8.8.1 src/libspice-client-glib-2.0.so.8.8.1.p/meson-generated_.._spice-marshal.c.o src/libspice-client-glib-2.0.so.8.8.1.p/meson-generated_.._spice-glib-enums.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-cursor.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-inputs.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-main.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-playback.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-port.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-record.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-smartcard.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-usbredir.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-webdav.c.o src/libspice-client-glib-2.0.so.8.8.1.p/qmp-port.c.o src/libspice-client-glib-2.0.so.8.8.1.p/smartcard-manager.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-audio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-channel.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-client.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-option.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-session.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-util.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-device-manager.c.o src/libspice-client-glib-2.0.so.8.8.1.p/bio-gio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-base.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display-gst.c.o src/libspice-client-glib-2.0.so.8.8.1.p/client_sw_canvas.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-glz.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-jpeg.c.o src/libspice-client-glib-2.0.so.8.8.1.p/decode-zlib.c.o src/libspice-client-glib-2.0.so.8.8.1.p/gio-coroutine.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-file-transfer-task.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-glib-main.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-gstaudio.c.o src/libspice-client-glib-2.0.so.8.8.1.p/spice-uri.c.o src/libspice-client-glib-2.0.so.8.8.1.p/vmcstream.c.o src/libspice-client-glib-2.0.so.8.8.1.p/channel-display-mjpeg.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-acl-helper.c.o src/libspice-client-glib-2.0.so.8.8.1.p/continuation.c.o src/libspice-client-glib-2.0.so.8.8.1.p/coroutine_ucontext.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usbutil.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-backend.c.o src/libspice-client-glib-2.0.so.8.8.1.p/usb-device-cd.c.o src/libspice-client-glib-2.0.so.8.8.1.p/cd-scsi.c.o src/libspice-client-glib-2.0.so.8.8.1.p/cd-usb-bulk-msd.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libspice-client-glib-2.0.so.8 -O3 -march=native -pipe -fomit-frame-pointer -flto -fuse-ld=mold -Wl,-O1 -Wl,--as-needed subprojects/spice-common/common/libspice-common-client.a subprojects/spice-common/common/libspice-common.a -export-symbols /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file -lm /usr/lib64/libglib-2.0.so /usr/lib64/libpixman-1.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libopus.so /usr/lib64/libcacard.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libjpeg.so /usr/lib64/libz.so /usr/lib64/libjson-glib-1.0.so /usr/lib64/libgstreamer-1.0.so /usr/lib64/libgstbase-1.0.so /usr/lib64/libgstapp-1.0.so /usr/lib64/libgstaudio-1.0.so /usr/lib64/libgstvideo-1.0.so /usr/lib64/libusbredirparser.so /usr/lib64/libusbredirhost.so /usr/lib64/libusb-1.0.so /usr/lib64/libgirepository-1.0.so /usr/lib64/liblz4.so -Wl,--end-group
> mold: fatal: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/spice-glib-sym-file:1: spice_audio_get
>                                                                                                  ^ unknown linker script token`
> ```

This is not hugely better -- it's still missing all the useful information which would be provided by, say, `emerge --info` as requested in the gentoo bug that is closed as NEEDINFO.

In particular, I think this is still a mold bug. spice-gtk is indeed buggy -- in the initial port to Meson, it added the nonsense argument `-export-symbols path/to/spice-glib-sym-file` which does nothing other than error out -- but spice-gtk still builds by default, when using GNU ld.

Why does it still build with GNU ld? Because this argument is only conditionally passed. It's passed when this Meson code fails:
```meson
spice_client_glib_syms = files('map-file')
spice_client_glib_syms_path = join_paths(meson.current_source_dir(), 'map-file')
spice_gtk_version_script = '-Wl,--version-script=@0@'.format(spice_client_glib_syms_path)
spice_gtk_has_version_script = compiler.has_link_argument(spice_gtk_version_script)
```

What this does is run the compiler with dummy test code, and check whether that dummy code successfully links when given the link argument: `-Wl,--version-script=path/to/spice-gtk/sources/src/map-file`

This, presumably, fails with mold, so spice-gtk attempts to use a totally broken fallback which is broken... but what you actually want is to use a GNU-compatible version script...

The question is, why does it fail? If you posted the full output of Meson, including the configure checks, it would report that this fails, and it would also log why in the debug log (`builddir/meson-logs/meson-log.txt`). As for me, it locally works with mold...

**Comment by Slaviusz** [comment]
I'm attaching meson-log.txt and also the full build.log.
[meson-log.txt](https://github.com/rui314/mold/files/10324150/meson-log.txt)
[build.log](https://github.com/rui314/mold/files/10324151/build.log)

**Comment by eli-schwartz** [comment]
Here is the relevant part of meson-log.txt

```
Command line:  x86_64-pc-linux-gnu-gcc /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41-build/meson-private/tmpfprhbrcr/testfile.c -o /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41-build/meson-private/tmpfprhbrcr/output.exe -O3 -march=native -pipe -fomit-frame-pointer -flto -D_FILE_OFFSET_BITS=64 -O0 -Wl,--fatal-warnings -Wl,--version-script=/var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file -fuse-ld=mold -Wl,-O1 -Wl,--as-needed 

Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_audio_get`: symbol not found
mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_audio_get_type`: symbol not found
mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_audio_new`: symbol not found
mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_channel_connect`: symbol not found
[...]
mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_uuid_to_string`: symbol not found
mold: error: /var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: cannot assign version `SPICEGTK_1` to symbol `spice_webdav_channel_get_type`: symbol not found
collect2: error: ld returned 1 exit status

Compiler for C supports link arguments -Wl,--version-script=/var/tmp/portage/net-misc/spice-gtk-0.41-r1/work/spice-gtk-0.41/src/map-file: NO 
```

This is why mold fails to detect the availability of -Wl,--version-script support. It doesn't fail like that on my machine, but I'm guessing that this check was added in a more recent version of mold than I have installed.

I would say that this is indeed a bug in mold, not spice-gtk and not Gentoo.

**Comment by Slaviusz** [comment]
Just for reference, I'm using `mold 1.8.0 (compatible with GNU ld)` fetched from here: http://tux.rainside.sk/gentoo/distfiles/db/mold-1.8.0.tar.gz

**Comment by eli-schwartz** [comment]
And mine is apparently 1.0, apparently the last time I installed it for comparison purposes was quite some time ago... Hmm.

**Comment by rui314** [comment]
Starting from 1.8.0, mold warns on a symbol name in a linker script that doesn't match any symbol in a program, because without it, it is very hard to find a typo in a symbol name. This is not a bug but a feature, and that doesn't make a program to fail to link, since it's just a warning but not an error.

However, since you also added `-Wl,--fatal-warnings` to the command line, that warning is promoted to an error.

So, it looks like everything is working as intended. The symbols mold warns on (`spice_audio_get`, `spice_audio_get_type`, etc) are suspicious -- are they really intended to be there in that version script? I'd remove them if they are not needed anymore.

**Comment by eli-schwartz** [comment]
> The symbols mold warns on (`spice_audio_get`, `spice_audio_get_type`, etc) are suspicious -- are they really intended to be there in that version script? I'd remove them if they are not needed anymore.

Why would you theorized that they aren't needed anymore? Seems like a strange assumption.

The log file snippet I posted very clearly states that it's trying to compile this code:
```c
int main(void) { return 0; }
```

Inside the source code file `tmpfprhbrcr/testfile.c`.

Clearly, the version script is not even remotely being used on  the actual source code that the version script is intended to apply to.

This is a configure-time system probe, it is checking to see whether the linker supports the concept of a version script.

Mold is incompatible with GNU ld here. This matter, because the *only* way to detect in a configure probe whether the linker accepts arguments such as version scripts is to try to do it and see if it errors (even when linkers don't want to error). What's your expectation of projects? Should they include a special file in the source tree with valid version script content but no symbols, just to run the check and then discard it and use the real version script later on?

**Comment by rui314** [comment]
Well, I don't have a strong opinion here. If warning on an unmatched symbol by default was a bad idea, I can change the default in the next version. Warning on it by default is compatible with LLVM lld though.

**Comment by Alcaro** [comment]
> If warning on an unmatched symbol by default was a bad idea

No, it sounds like a good idea to me. If anything here is a bad idea, I'd say it is using fatal-warnings in a configure test.

(If possible, I'd delete the version script and specify the versions using GCC attributes; it's not only harder to typo, but also harder to forget. But I didn't investigate if it is possible in this project.)

**Comment by eli-schwartz** [comment]
@rui314,

We might be able to have our cake and eat it too, if mold can detect the configure probe case by noticing that the version script doesn't target *any* of the linked object's symbols, and/or that the linked object only contains "main".

@Alcaro,

That's theoretically possible in specific cases, but terrible general advice. Version scripts include functionality of GCC attributes, but also a lot more functionality. Particularly:
```
SPICEGTK_1 {
global:
spice_audio_get;
....
```

Changing it to simple visibility attributes would be an ABI break.

In spice-gtk's case they aren't binding multiple versions nodes, but projects that do so can't switch even if they are okay with an ABI break.

What this means is that the sum total of projects that can't follow your advice is, undeniably, more than zero, and if it's more than zero then mold still has to make a decision on whether or not to support these projects.

Whether the answer is "don't support", or "support by clever detection of when a version script is used with a dummy test file" or "don't warn" or "warn but don't error", I can't say on someone else's behalf.

I do wonder how lld handles this case... If it warns like mold does, does that warning also trip up configure probes? But I can't experiment until later today...

**Comment by Slaviusz** [comment]
If you want I can run the ebuild with GNU ld and post the ebuild and meson logs.
