### ISSUE TITLE
Regression from v0.9.2 introduced in commit d8ad600b6a6a1eb18c79f035be7f1089745d51bc

### ISSUE THREAD

**Issue by matu3ba** [rui314/mold#94]
Unfortunately I cant disclose the code due to a NDA.
What essentially happens: googleTest framework breaks with a segfault, when I execute the googleTest binary.

Would some part of the `objdump` help or what information do you need?

**Comment by rui314** [comment]
Can you try again with https://github.com/rui314/mold/commit/fa543ae35098018ea69ee8eb4f6d787e90004980?

**Comment by matu3ba** [comment]
Using fa543ae35098018ea69ee8eb4f6d787e90004980 works. This was fast.

**Comment by rui314** [comment]
Great, thank you for testing! Feel free to file more bugs if you find any.

**Comment by matu3ba** [comment]
Thanks alot for the superfast fix! Will do.
