### ISSUE TITLE
[question] use mold with rust-analyzer

### ISSUE THREAD

**Issue by alexzanderr** [rui314/mold#942]
hello.

mold is great and working for me. thanks for the project.

i have linked the issue here: https://github.com/rust-lang/rust-analyzer/issues/13880

any suggestions?

thanks in advance.

**Comment by rui314** [comment]
I'm not familiar with Rust analyzer, but it looks like the problem has been resolved? It seems like all you need is to set up your cargo config so that Rust uses mold by default.

**Comment by alexzanderr** [comment]
yeah, thanks for the response
