### ISSUE TITLE
Linking fails when -fno-lto with FAT LTO objects

### ISSUE THREAD

**Issue by pic91** [rui314/mold#953]
With mold v1.8.0
If some file has been compiled with gcc -ffat-lto-objects -flto
and then linked with  gcc -fno-lto ,  linking will fail 
 _don't know how to handle this LTO object file because no -plugin option was given. Please make sure you added -flto not only for creating object files but also for creating the final executable._

It is working with ld or gold (non-LTO link)

**Comment by rui314** [comment]
It should already been fixed in 1.9.0, so please upgrade your mold binary to the latest release.
