### ISSUE TITLE
Build failed on M1 Mac

### ISSUE THREAD

**Issue by devillove084** [rui314/mold#955]
```
= note: mold: fatal: unknown command line option: -dynamic; -dynamic is a macOS linker's option. If you are trying to build a binary for an Apple platform, you need to use ld64.mold instead of mold or ld.mold.
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rui314** [comment]
It's just because mold doesn't support macOS.

**Comment by DrewRidley** [comment]
If macOS is not supported, why does the error message suggest that some ``ld.64 mold`` exists? Imo that error message is a little confusing

**Comment by DrewRidley** [comment]
Nevermind, I did some more research and understand now that I have more context.

I appreciate everything you do for making linking fast.
