### ISSUE TITLE
Unable to complete installation for sys-apps/sandbox with if --fuse=ld=mold

### ISSUE THREAD

**Issue by Cerberios** [rui314/mold#956]
Hello there!
Seems bug: in case  **--fuse-ld=mold** I getting configure error for sys-apps/sandbox under Gentoo
Portage 3.0.43 (python 3.10.9-final-0, default/linux/amd64/17.1/desktop, gcc-12, glibc-2.36-r6, 6.1.4-gentoo x86_64)
mold 1.9.0 (9f5b7e278fea7e84dbc6a0f2a71d810a09580ad2; compatible with GNU ld)
and error looks like:
**configure: error: Unable to determine LIBC PATH ()**
Once I've changed  **--fuse-ld=lld** - configuration and compilation was OK.
Error is in sandbox scripts I am sure, but please, may be need tune-up mold configs also.
Thanks!

**Comment by rui314** [comment]
It looks like that app was trying to do something tricky with a linker. It has per-linker logic here: https://gitweb.gentoo.org/proj/sandbox.git/tree/configure.ac#n354

Can you report the issue to that app's developers to fix it on their side? I don't think there's anything we can do on our side.
