### ISSUE TITLE
Add notice that you're looking for a sponsor in the readme

### ISSUE THREAD

**Issue by kirawi** [rui314/mold#96]
It seems like the notice is only in the license file. It might add more visibility if you add it to the `README.md`.

**Comment by rui314** [comment]
Thank you for your suggestion, but I think that I don't need that much visibility at least for now. In the future, I might want to add it to README, but for now I'm focusing on making the mold linker something that other people are willing to use.

**Comment by kirawi** [comment]
Noble goal :)
