### ISSUE TITLE
missing section specification for debug sections (mold 1.9.0)

### ISSUE THREAD

**Issue by leap0x7b** [rui314/mold#962]
![Screenshot_20230113-193236_Termux.png](https://user-images.githubusercontent.com/76893443/212321281-9a504989-8a50-41f6-ba93-0f968210c576.png)

**Comment by rui314** [comment]
This is not a bug, but first of all, `--section-roder` is an undocumented option which is under development and therefore you are not supposed to use unless you know what you are doing.
