### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Fyyyyyyyy** [rui314/mold#97]
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- HWLOC target HWLOC::hwloc_1_11 doesn't exist. The tbbbind target cannot be created
-- HWLOC target HWLOC::hwloc_2 doesn't exist. The tbbbind_2_0 target cannot be created
-- HWLOC target HWLOC::hwloc_2_4 doesn't exist. The tbbbind_2_4 target cannot be created

when i try to install mold with docker,it seems that some items don't work,will that affect the performance of mold?

**Comment by rui314** [comment]
I don't think that's an issue, because statically linking TBB using the docker container actually improves performance of the linker compared to dynamically linking TBB.
