### ISSUE TITLE
Building on OpenBSD

### ISSUE THREAD

**Issue by brad0** [rui314/mold#970]
Trying to build mold on OpenBSD I am currently dead in my tracks as the dependency with TBB makes it impossible at the moment. TBB seems to be (currently) dependent on an API POSIX has removed, ucontext. OpenBSD does not have said API and never will.

https://github.com/oneapi-src/oneTBB/issues/795

**Comment by rui314** [comment]
TBB isn't an optional library for mold, so it needs to be fixed on the oneTBB side.

**Comment by brad0** [comment]
I built mold CFLAGS / CXXFLAGS defining ```__TBB_RESUMABLE_TASKS_USE_THREADS``` and it built Ok.

```
humpty$ mold --version
mold 1.10.0 (compatible with GNU ld)
humpty$ uname -sr
OpenBSD 7.2
```

**Comment by rui314** [comment]
I don't even know what the resumable tasks are, but it looks like the feature is not available on several non-glibc systems, so maybe you can make this change to disable the feature on OpenBSD?

```
diff --git a/third-party/tbb/include/oneapi/tbb/detail/_config.h b/third-party/tbb/include/oneapi/tbb/detail/_config.h
index 9bc2ed50..776917a2 100644
--- a/third-party/tbb/include/oneapi/tbb/detail/_config.h
+++ b/third-party/tbb/include/oneapi/tbb/detail/_config.h
@@ -268,7 +268,7 @@
     #define __TBB_CPP20_COMPARISONS_PRESENT __TBB_CPP20_PRESENT
 #endif

-#define __TBB_RESUMABLE_TASKS                           (!__TBB_WIN8UI_SUPPORT && !__ANDROID__ && !__QNXNTO__ && (!__linux__ || __GLIBC__))
+#define __TBB_RESUMABLE_TASKS                           (!__TBB_WIN8UI_SUPPORT && !__ANDROID__ && !__QNXNTO__ && (!__linux__ || __GLIBC__) && !__OpenBSD__)

 /* This macro marks incomplete code or comments describing ideas which are considered for the future.
  * See also for plain comment with TODO and FIXME marks for small improvement opportunities.
```

**Comment by brad0** [comment]
I believe what are called co-routines.

**Comment by rui314** [comment]
Do you have any issue other than this to use mold on OpenBSD?

**Comment by nuudlman** [comment]
I built mold with the standard way and `-DCXXFLAGS="-D__TBB_RESUMABLE_TASKS_USE_THREADS"`, and when I attempt to initialize a meson project with `CC_LD=mold meson setup build` the sanity-check fails, but works correctly with system ld (lld 13).

Error and invocation:
``` 
"/usr/local/bin/ld.mold" -e __start --eh-frame-hdr -Bdynamic -dynamic-linker /usr/libexec/ld.so -o sanitycheckc.exe /usr/lib/crt0.o /usr/lib/crtbegin.o -L/usr/lib /tmp/sanitycheckc-3d3f78.o -lcompiler_rt -lc -lcompiler_rt /usr/lib/crtend.o

---
Running test binary command:  /home/isaac/Work/ece460n/build/meson-private/sanitycheckc.exe

meson.build:1:0: ERROR: Executables created by c compiler cc -v are not runnable.
```

Repro file: https://files.catbox.moe/n1wb54.tar
