### ISSUE TITLE
1.10.1 still segfaults/asserts on linking ARM binary

### ISSUE THREAD

**Issue by sieberst** [rui314/mold#974]
I already reported in https://github.com/rui314/mold/issues/934 that mold segfaults on my ARM build and when using the debug build of mold an assert is reported. Today I retried using version 1.10.1 and get the same result, only the assert location moved a few lines:

    ld: /mold/elf/mold.h:2293: mold::u64 mold::elf::InputSection<E>::get_thunk_addr(mold::i64) [with E = mold::elf::ARM32; mold::u64 = long unsigned int; mold::i64 = long int]: Assertion `ref.thunk_idx != -1' failed.

It would be great if this could be resolved.

**Comment by rui314** [comment]
Can you link your program with `-Wl,--repro`? With that option, mold creates a tar file with all input files as its contents. Then please upload that tar file so that I can reproduce the issue on my machine.

**Comment by rui314** [comment]
Can you try again with the above change?

**Comment by sieberst** [comment]
I tried the current master and can't reproduce the issue any more, so it seems the change works.
