### ISSUE TITLE
powerpc64-execute-only (Failed) on ppc64

### ISSUE THREAD

**Issue by marxin** [rui314/mold#989]
Must be a recent regression (last successful build was from ~3 days ago):

```
[  284s] ++ code=1
[  284s] ++ echo 'command failed: 15: grep -q '\''Hello world'\'''
[  284s] command failed: 15: grep -q 'Hello world'
[  284s] ++ trap - EXIT
```

**Comment by rui314** [comment]
Do you mind if I ask you to bisect? The test doesn't fail in my ppc64 qemu environment.

**Comment by marxin** [comment]
It's been there since 45bece4bd9af065234534ed2c4b51e3a04159ca1 and I get a Segmentation fault when I run `$QEMU $t/exe` in the mentioned test-case.

**Comment by marxin** [comment]
```
[  500s] + gdb -batch -ex run out/test/elf/ppc64/execute-only/exe
[  500s] [Thread debugging using libthread_db enabled]
[  500s] Using host libthread_db library "/lib64/libthread_db.so.1".
[  500s] 
[  500s] Program received signal SIGSEGV, Segmentation fault.
[  500s] 0x00000001000106bc in __glink_PLTresolve ()
```

**Comment by rui314** [comment]
Maybe that test has been broken since the beginning but hadn't been executed until the recent change to the cmakefile. Can you share the executable file with me?

Maybe we can just disable the test on ppc64 because no one probably want to use the modern `-execute-only` option on ppc64v1 though.

**Comment by marxin** [comment]
> Maybe that test has been broken since the beginning but hadn't been executed until the recent change to the cmakefile. Can you share the executable file with me?

Sure.
[ppc64.out.gz](https://github.com/rui314/mold/files/10734072/ppc64.out.gz)

**Comment by rui314** [comment]
Thanks. PPC64 .text segment contains not only code but also data, so it wasn't compatible with `-execute-only`.

**Comment by marxin** [comment]
Good, thanks for the investigation.
