### ISSUE TITLE
Build fails with v.0.9.1 branch on ubuntu 20.04

### ISSUE THREAD

**Issue by Sameeranjoshi** [rui314/mold#99]
I see too many include file errors:

```
In file included from archive_file.cc:1:
./mold.h:23:10: fatal error: 'tbb/concurrent_hash_map.h' file not found
#include <tbb/concurrent_hash_map.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from compress.cc:15:
./mold.h:23:10: fatal error: 'tbb/concurrent_hash_map.h' file not found
#include <tbb/concurrent_hash_map.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from tar.cc:1:
./mold.h:23:10: fatal error: 'tbb/concurrent_hash_map.h' file not found
#include <tbb/concurrent_hash_map.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from arch_x86_64.cc:1:
./mold.h:23:10: fatal error: 'tbb/concurrent_hash_map.h' file not found
#include <tbb/concurrent_hash_map.h>

```

Reproducing steps:
```
$ sudo apt-get install build-essential libstdc++-10-dev cmake clang libssl-dev zlib1g-dev libxxhash-dev git
$ git clone https://github.com/rui314/mold.git
$ cd mold
$ git checkout v0.9.1
$ make
```

Whereas main branch works.

**Comment by rui314** [comment]
Thank you for reporting! However, currently, we maintain only the most recent release of mold, so we won't create a fix for the 0.9.1 branch. As long as 0.9.3 works OK, we are fine with that.

**Comment by Sameeranjoshi** [comment]
Should you make changes in readme either?

**Comment by rui314** [comment]
I set up a bug template in 2d003c2546d4c53acde1397eb4174bcec8f18afc and add a note in that template.

**Comment by Alcaro** [comment]
I think Sameeranjoshi means that if you're not supposed to use 0.9.1, [it shouldn't be in the readme.](https://github.com/rui314/mold/blob/main/README.md#how-to-build)

**Comment by Sameeranjoshi** [comment]
Yes @Alcaro I meant changes in 
`git checkout v0.9.1` to `git checkout v0.9.3`
