### ISSUE TITLE
Support for ppc/ppc64 is missing for macho

### ISSUE THREAD

**Issue by barracuda156** [rui314/mold#990]
CMakeLists have:
```
list(APPEND MOLD_MACHO_TARGETS X86_64 ARM64)
```

It is desirable to add support for PPC.

**Comment by rui314** [comment]
Unlike open-source Unix-like systems that support PPC as of today, macOS has terminated the PowerPC support more than 10 years ago. Therefore, it is extremely unlikely we want to support PowerPC-based Macs. So is true for ARM32-based old iPhones that no longer get OS updates and have been declared as an unsupported system for a long term.
