### ISSUE TITLE
Add Build Optional Config

### ISSUE THREAD

**Issue by meleehao** [rui314/mold#995]
Default Build Optional No Include Ignore Architecture Set ,Many Non-Essential Build_In  To Mold From  Host Architecture ,Such Non_Cross Compiler Scenes To Be Used ,Shoud Refinemnet For Build Option .

**Comment by rui314** [comment]
So you are saying that mold doesn't provide a way to selectively enable/disable targets? If so, is intentional. I want mold to behave exactly the same however it was built for the sake of build reproducibility.
