### ISSUE TITLE
Binary segfaults when using `.symver` on CentOS 7

### ISSUE THREAD

**Issue by moncefmechri** [rui314/mold#998]
The following test program crashes (segmentation fault) when building/running on a CentOS 7 x86_64 box (with glibc 2.17, and building with gcc 12 and mold 1.10.1):

```
#include <cmath>

__asm__(".symver pow,pow@GLIBC_2.2.5");

int main(int argc, char** argv)
{
    return std::pow(10, size_t(argc));
}
```

Built with `g++ -Wall -fuse-ld=mold -o prog prog.cpp`

The binary works as expected when linking with any other linker (I tried ld.bfd, lld, and gold).

The issue disappears if I remove the `__asm__` statement.

No issue as well when building and running with mold on a Ubuntu 20.04 box.

**Comment by ksco** [comment]
Please add a `-Wl,--repro` flag to `g++`, and upload the generate `test.repro.tar` here. So we can reproduce the issue on a local machine.

**Comment by moncefmechri** [comment]
> Please add a `-Wl,--repro` flag to `g++`, and upload the generated `prog.repro.tar` here. So we can reproduce the issue on a local machine.

[test.repro.tar.zip](https://github.com/rui314/mold/files/10805443/test.repro.tar.zip)

(Had to zip it because GitHub wouldn't let me upload a tarball).

**Comment by ksco** [comment]
Could you add a `-v` and paste the linker command also?

**Comment by ksco** [comment]
I have reproduced the issue, let me take a look.

**Comment by moncefmechri** [comment]
On a side note: We use `.symver` for `pow()` and a few other C functions so that we can build our binary on Ubuntu 20.04 (which has glibc 2.31) and run on CentOS 7 (which has glibc 2.17). If you know a better way to achieve this than using `symver`, I would be very interested :)

**Comment by moncefmechri** [comment]
@ksco @rui314 we have an intern starting in a couple of weeks. We are considering having him work on fixing this bug, as it is blocking us from switching to `mold`. I have a few questions:

- Would this be a contribution you would welcome?
- Do you think this is a reasonable task for an intern not familiar with `mold` (and linkers in general)?
- If yes to both questions above: Would you be able to share some pointers to help the intern get started on this task?

**Comment by rui314** [comment]
This might be very subtle problem, so I wouldn't assign it to an intern. At least it's likely to end up with committing a very small patch, so there intern can't get the feeling of achievement. Let me take a look first.

**Comment by moncefmechri** [comment]
> This might be very subtle problem, so I wouldn't assign it to an intern. At least it's likely to end up with committing a very small patch, so there intern can't get the feeling of achievement. Let me take a look first.

Thanks for the honest feedback.

**Comment by moncefmechri** [comment]
@ksco @rui314 The issue is not present anymore in recent versions of mold.

I did a git bisect to find the commit that solved the issue, and it returned this commit:

https://github.com/rui314/mold/commit/ab126ad1d974f73722aff82df571aee3e17b2dcb

Is this expected?

**Comment by rui314** [comment]
I wasn't aware that the change would fix this issue, but yes, it is very likely that the change has fixed the problem.

**Comment by moncefmechri** [comment]
Cool! Then I guess we can close this issue. Thank you :)
